### ISSUE TITLE
asset import

### ISSUE THREAD

**Issue by Inlife** [Inlife/nexrender#1]
![nexrender](https://cloud.githubusercontent.com/assets/2182108/13123763/8215afc6-d5c6-11e5-8462-039165c84e2f.png)
![scheme](https://cloud.githubusercontent.com/assets/2182108/13123764/84efaf94-d5c6-11e5-9517-69f940bfadbc.png)

**Comment by inlife** [comment]
![image](https://user-images.githubusercontent.com/2182108/52443468-7270dd00-2b2e-11e9-8336-255349279c43.png)
