### ISSUE TITLE
Pre-render Actions support (image resizing)

### ISSUE THREAD

**Issue by tomasdms** [inlife/nexrender#101]
Thanks so much for creating this tool, I been playing around with it all weekend at i'm already loving it.

I been trying to do image cropping/resizing before I render the videos to make sure they all have the right size. I saw on the docs that you mention prerender actions but don't see any documentation for that yet. 

Is that feature not implemented yet?

Thanks again!

**Comment by inlife** [comment]
Hello,

It is implemented, at least partially. There is a short doc describing how to add custom actions:
https://github.com/inlife/nexrender#external-packages

And also other exiting actions can be used as a reference:
https://github.com/inlife/nexrender/blob/master/packages/nexrender-action-copy/index.js

**Comment by tomasdms** [comment]
Thanks inlife, I was looking at the action-copy package as a reference last night and I think that I could get this done. I will like to contribute with such a package if you will like. 

If so, are there any request or specs that this package should implement? 
and do you recommend any particular library for creating the resizing?

I've looked into this one and it looks very straightforward and efficient.
https://github.com/lovell/sharp

Thanks again!!

**Comment by inlife** [comment]
>I will like to contribute with such a package if you will like.

That would be very nice.

>If so, are there any request or specs that this package should implement?


I think from the design standpoint main concern should be an ability to easily set values that need to be changed from the json file. f.e.:
```js
{
    "module": "@nexrender/image-transform", // just a random name
    "input": "myimage.jpg", // which file we want to handle
    "operations": [ // which operations we wanna do
        { "method-name": ["arg1", "arg2"] }, // example syntax
        { "resize": [1920, 720] }
    ],
    "output": "newimage.jpg" // optionally ability to save as a different file
}
```

Also I'm not sure, whether this action shoudl be called on per-asset(image) basis, or "input" should support multiple files per operation.

And of course, a bit of documentation, wouldn't hurt.
Other than that, i think it's more up to you!

>and do you recommend any particular library for creating the resizing?

That is a good question. I believe we should aim for performance, good interface, and minimal footprint.
Library you shown looks pretty good. However as far as I understand, it has partially native (c++) implementation, and compilation might be triggered on installation, for some platforms.
And I think that might lead to some problems, especially if dep versions are not gonna be updated frequently enough.

It seems to me that in our case it would be better to look into something like: https://github.com/oliver-moran/jimp
This library fully self contained, doesn't have any dependencies, and actually has been used in previous versions of nexrender.

I think there are similar alternatives, of even more light-weight, and performant libraries.

**Comment by tomasdms** [comment]
Thanks again Inlife, This is very helpful.

I'm a junior developer and this will be my first open source contribution, but I'll do my best to accomplish the task at hand.

some notes.

I think that the resizing should be done per asset. adding the properties there, something like

resizing: true,
output_size: [x,y]

and if those properties are present, nexrender should resize the files after downloading them and replace the original downloaded files with the new ones before calling aerender.

Not sure if it should be just that or also have a prerender property where we specify more details. and give more flexibility, but this will be for all images on the comp.

Another alternative, don't know if possible is to read the size of the original image from the XML ae project file and resize to that size. In which case we don't need to add anything to each asset, just the pre-render action.

Let me know what you think!

**Comment by inlife** [comment]
>Another alternative, don't know if possible is to read the size of the original image from the XML

That is definitely impossible. And even if it would be possible, that is a bad way of doing that.

Another point that I understood from your proposition, seems like you want to add properties to asset objects? I think a much better way would be to actually add pre-render action as a separate module. Not everyone needs image resizing functionality by default. 

Take another example json I've sent you in the previous message. And here is more detailed version:

```json
// myjob.json
{
    "template": {
        "src": "http://example.com/assets/myproject.aep",
        "composition": "main"
    },
    "assets": [
        {
            "src": "http://example.com/assets/myimage.png",
            "type": "image",
            "layerName": "background.png"
        },
        {
            "src": "https://example.com/assets/image.jpg",
            "type": "image",
            "layerName": "MyNicePicture.jpg"
        },
        {
            "src": "file:///home/assets/audio.mp3",
            "type": "audio",
            "layerIndex": 15
        }
    ],
    "actions":{
        "prerender": [
            {
                "module": "@nexrender/image-transform",
                "input": "background.jpg",
                "operations": [
                    { "resize": [1920, 1080] }
                ],
                "output": "background.jpg"
            },
            {
                "module": "@nexrender/image-transform",
                "input": "MyNicePicture.jpg",
                "operations": [
                    { "rotate": [90] },
                    { "blur": [5] },
                    { "color": [[{ "apply": "red", "params": [100] }]] },
                    { "resize": [800, 600] }
                ],
                "output": "MyNicePicture.jpg"
            }
        ],
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "encoded.mp4",
                "output": "d:/mydocuments/results/myresult.mp4"
            }
        ]
    }
}
```

**Comment by tomasdms** [comment]
That works but how would NExrender know that those resized images are the
ones that neet to be used for a particular asset if we are not referencing
the asset in question in the pre-render module?

[image: Tomas De Matteis Photography] <http://www.tomasdms.com>

Tomás De Matteis
tomasdms@gmail.com / +1 682.252.1842

 [image: Twitter] <https://twitter.com/tomasdms> [image: Linkedin]
<http://es.linkedin.com/in/tomasdms>

**Comment by inlife** [comment]
that actually depends on the filename, since it's the key in this case

lets looks at the sequence:
1. download is capable of taking the source from http/ftp/file and save it under specific name to local folder, usually by `layerName`
2. image-trasnform takes image by that name, changes its side, and re-writes original
3. renderer takes that rewritten image and uses it

**Comment by tomasdms** [comment]
Oh perfect, that works. I just need to figure out how to call the asset
file and write to it again. I can see that you do it on the post-render
action but that's with the final file, not the assets.
