### ISSUE TITLE
frame rate and file size discrepancy

### ISSUE THREAD

**Issue by q-depot** [inlife/nexrender#1027]
Hi,

I just tried to use nexrender for the first time, I've managed to render the file but there seems to be a discrepancy with with frame rate and file size.

When I render from AE the frame rate is correct (29.97) but when I use nexrender the output is at 25. I'm using the same output module and settings template.

Also the filesize from nexrender is considerably smaller, for my test clip the filesize is  46Kb, compared with the 735Kb I get from AE.

any idea what's going on?

**Comment by inlife** [comment]
Hey
Feel free to use --debug to try to see the input that aerender receives and figure out what goes wrong with the settings

**Comment by q-depot** [comment]
I ran it with the debug option, the output seems fine to me, framerate is set to 29.97 and bitrate to CBR 30 Mbs. But the final render is again at 25 and the filesize is 10 times smaller compared to the output from AE render

![image](https://github.com/user-attachments/assets/54f11bc6-38a0-4805-ac3a-b24f9df4ebc1)
![image](https://github.com/user-attachments/assets/9125ae0e-86d3-4707-a2ff-921aca0a27cd)
![image](https://github.com/user-attachments/assets/4f681265-2254-46f3-a087-49f26571c845)

**Comment by q-depot** [comment]
in my json I had a postrender action to encode, I thought that was just a standard pass, but obviously it for re-encoding the video, that was causing the discrepancy. I've removed the encode action and just use action-copy, works just fine.
