### ISSUE TITLE
Whether to consider using layerId matching replacement

### ISSUE THREAD

**Issue by zhulix** [inlife/nexrender#1029]
In the project, I noticed that layerName or index is used to replace layer resources. Have you thought about using layerId for matching replacement?
I wrote some AE scripts to quickly extract layer properties and output them in a structured way, which I believe can improve efficiency for developers.

**Comment by inlife** [comment]
It could be useful for someone, but I feel like, typically, it's hard to spot a layer ID without any tooling. Unless there will be standardized tooling.
