### ISSUE TITLE
Action-fonts package on Mac will never reach installation of fontfile

### ISSUE THREAD

**Issue by lee-thornton** [inlife/nexrender#1032]
I had been playing around with trying to get fonts working using the action-fonts package (I understand it's in alpha). I noticed that the code will always skip the install as it checks the filePath rather then destination path to see if it exists on a Mac environment

```
if (fs.existsSync(fontpath)) {
        settings.logger.log(`[action-fonts] Font ${fontpath} already exists, skipping.`);
        return 0;
    }
```

I believe this issue has been fixed for the windows environment in your most recent release ? So something similar for the mac environment should fix it I think ?

```
const fontdest = path.join(fontdir, path.basename(fontpath))

if (fs.existsSync(fontdest)) {
settings.logger.log(`[action-fonts] Font ${fontdest} already exists, skipping.`);
return 0;
}

fs.copyFileSync(fontpath, fontdest)
```

**Expected behavior**
package should use fontFile downloaded from the job.assets & copy then install into the font directory on Mac.

**Screenshots**

**Comment by inlife** [comment]
Indeed. It shall be fixed in the upcoming release!
