### ISSUE TITLE
Set Nexrender Job polling timeout in settings

### ISSUE THREAD

**Issue by franeko** [inlife/nexrender#104]
Currently, the Api (@nexrender/api) emits events every 10 seconds (`@nexrender/api/src/job.js`). My app is very performance constrained - I have published a simple PR than allows changing polling delay for workers via settings param. It would be nice to have similar option for API but I don't see any easy fix for that.

**Comment by inlife** [comment]
seems to me, the best place to put it would be the object that is getting passed as an argument to the `createClient` method, and then as additional restof options object, to the https://github.com/inlife/nexrender/blob/master/packages/nexrender-api/src/index.js#L18 call

also probably the 10-second delay isn't that good as default either, probably 30-60 as a default should be more balanced?

**Comment by franeko** [comment]
For most projects 10s is probably fine, it is just a simple call so the load on the CPU is probably insignificant in most cases
