### ISSUE TITLE
aerender ERROR: No comp was found with the given name.

### ISSUE THREAD

**Issue by misaunde** [inlife/nexrender#110]
Hi, in a simple comp, when the text layer was in the main composition, I was able to replace the text inside a text layer very easily.

However, now that I've moved on to a more compex .aep file, I'm trying to just replace text on a uniquely named, nested text layer, but I keep getting this error (in the logs):
`    aerender ERROR: No comp was found with the given name.`

Here is the structure of my file:
![image](https://user-images.githubusercontent.com/10051350/53294121-d5ed4280-379d-11e9-82b7-9c4ced2c5f78.png)

The text layer is in a sub comp which is deeply nested in the main composition and folders. Should I be able to reach this?

I've tried a number of different approaches in my json, but it looks something like this:
``` 
{
    "template": {
        "src": "file:///c:/dev/nexrender-test2/assets/AE_Template.aep",
        "composition": "main"
    },
    "assets": [
        {
            "type": "data",
            "layerName": "text01",
            "property": "Source Text",
            "value": "This is test num 1",
            "composition": "text01"
        }
    ]
}
```

Any ideas?

**Comment by inlife** [comment]
hello!
theoretically, it should be possible, i cant definitely say there can't be any bugs
would you be able to send me this `aep` file?

**Comment by misaunde** [comment]
You bet, here's the file:
[AE_Template.zip](https://github.com/inlife/nexrender/files/2898299/AE_Template.zip)

More than likely I'm just doing something wrong! :)

**Comment by inlife** [comment]
wait, i just realized, seems like you haven't changed the `composition` field for the `job.template` object

**Comment by misaunde** [comment]
Haha, duh!! 

When that error is thrown, does it have the composition name? Any chance the composition name could be added to the error message? ie:
```
aerender ERROR: No comp was found with the given name: "main"
```

Lol, that whole time I incorectly assumed it was tripping up on the layer/comp I was focusing on, but it turned out to be another layer/comp entirely!

Nice catch and thanks again!

**Comment by inlife** [comment]
Unfortunately this is an error message from aerender binary itself, however, I'll see what I can do.
No problem!
