### ISSUE TITLE
aerender Error write permissions

### ISSUE THREAD

**Issue by JamesBotterill** [inlife/nexrender#116]
right now when I'm attempting to render I get this error, first it was because it's writing to a tmp dir but I specified a dir which should have all the permissions and I get the same issue. 

aerender Error: After Effects error: Error in output for render queue item 1, output module 1. Can not create a file in directory {insert dir here}. Try checking write permissions.

**Comment by inlife** [comment]
could you please show your job json, and your full output log

**Comment by JamesBotterill** [comment]
The json is as follows
`{
    "template": {
        "src": "file:///users/user/desktop/video/test.aep",
        "composition": "comp 1"
    },
    "assets": [
        {
            "src": "https://somesite.com/image1.png ",
            "type": "image",
            "layerName": "image.png"
        }
    ],
    "actions":{
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "encoded.mp4",
                "output": "/Users/user/nexrender/video.mp4"
            }
        ]
    }
}`


The output is as follows:

MacBook-3-James-B:comp_1 user$ sudo nexrender-cli --file test.json -w /Users/user/nexrender --debug
> starting nexrender-cli
using automatically determined directory of After Effects installation:
 - /Applications/Adobe After Effects CC 2019/aerender
adding default render-only-node license for After Effects at:
 - /Users/user/Documents/Adobe/ae_render_only_node.txt
checking After Effects command line renderer patch...
command line patch already is in place
[HuDB0trCGYGjfQUqWjiYh] setting up job...
[HuDB0trCGYGjfQUqWjiYh] working directory is: /Users/user/nexrender/HuDB0trCGYGjfQUqWjiYh
[HuDB0trCGYGjfQUqWjiYh] downloading assets...
[HuDB0trCGYGjfQUqWjiYh] applying prerender actions...
[HuDB0trCGYGjfQUqWjiYh] running script assemble...
[HuDB0trCGYGjfQUqWjiYh] rendering job...
[HuDB0trCGYGjfQUqWjiYh] spawning aerender process: /Applications/Adobe After Effects CC 2019/aerender -project /Users/user/nexrender/HuDB0trCGYGjfQUqWjiYh/360test.aep -comp comp 1 -output /Users/user/nexrender/HuDB0trCGYGjfQUqWjiYh/result.mov -r /Users/user/nexrender/HuDB0trCGYGjfQUqWjiYh/nexrender-HuDB0trCGYGjfQUqWjiYh-script.jsx
> job rendering failed
Running Script: /Users/user/nexrender/HuDB0trCGYGjfQUqWjiYh/nexrender-HuDB0trCGYGjfQUqWjiYh-script.jsx
PROGRESS: Adding specified comp to Render Queue
aerender Error: After Effects error: Error in output for render queue item 1, output module 1. Can not create a file in directory /Users/user/nexrender/HuDB0trCGYGjfQUqWjiYh. Try checking write permissions.
aerender version 16.0.1x48
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched

**Comment by inlife** [comment]
Well seems like after effects binary can't create a file in the directory. Have you tried removing that nexrender folder, and then launching the command without sudo?

**Comment by JamesBotterill** [comment]
I've attempted to launch without the sudo and everything seems to work correct. 

Thanks,
