### ISSUE TITLE
Can nexrender render nested compostions?

### ISSUE THREAD

**Issue by nanustyle** [inlife/nexrender#119]
Nexrender render only one compostiion?
or nexrender render nested compostiions, too?

**Comment by inlife** [comment]
Hello!

I'm actually not quite sure. Do you mean will the main targeted composition will render any subsequent compositions?

**Comment by nanustyle** [comment]
Hi,

sub composition works well.

`{
    //sample_sub_03.json:
    "template": {
        "src": "file:///C:/Users/user/Downloads/sample.aep",
        "composition": "Sub_03"
    },
    "assets": [
        {
            "src": "file:///C:/Users/user/Downloads/background.jpg",
            "type": "image",
            "layerName": "background.png"
        }
    ],
}
`
![sub](https://user-images.githubusercontent.com/8827071/53732745-324d1200-3ec2-11e9-9b56-2e53e4c4dcbf.png)

But Main composition isn't.

`{
    //sample_main.json:
    "template": {
        "src": "file:///C:/Users/user/Downloads/sample.aep",
        "composition": "Main"
    },
    "assets": [
        {
            "src": "file:///C:/Users/user/Downloads/background.jpg",
            "type": "image",
            "layerName": "background.png"
        }
    ],
}
`
![main](https://user-images.githubusercontent.com/8827071/53732855-7f30e880-3ec2-11e9-8fd4-15fa9f1cdc96.png)

Question: Nested compostions are not supported?

**Comment by inlife** [comment]
seems like this is a bug

**Comment by nanustyle** [comment]
I think it must lookup all assets of compositions, not only parent but also child.

**Comment by inlife** [comment]
yes, indeed, currently iirc it works the opposite way, however that doesn't feel right

**Comment by nanustyle** [comment]
I found the solution from https://github.com/inlife/nexrender/issues/131.
I should  setting in which composition that image asset needs to be replaced.

**Comment by mayank-sagar** [comment]
Yes like this
{
        "src": "file:///C:/Users/test/Desktop/test.mp4",
        "type": "video",
        "composition":"nestedCompositionName",
        "layerName": "LayerName"
    }

**Comment by mayank-sagar** [comment]
if composition is nested deeply the you can use '->' token.You can go to any levels by chaining them one after another. Below is the example of two level deep composition.

{
"src": "file:///C:/Users/test/Desktop/test.mp4",
"type": "video",
"composition":"nestedCompositionName->deeplyNestedCompositionName",
"layerName": "LayerName"
}

Hope it help. This all info could be found in documentation on git hub.
