### ISSUE TITLE
Incompatible with aerender version 13.8.1x38

### ISSUE THREAD

**Issue by nguyenvanduocit** [Inlife/nexrender#12]
nexrender@0.4.10
Windows 10, aerender version 13.8.1x38

`Error message: aerender version 13.8.1x38`

I open issue because you said "If you successfully (unsuccessfully) tested it on other versions, please let me know!" :)

**Comment by Inlife** [comment]
Could you also provide your Adobe After Effects version itself ?

**Comment by Inlife** [comment]
i will close the issue, due to lack of information; for now at least :P
