### ISSUE TITLE
nexrender-cli no need to specify the installation path of ae？

### ISSUE THREAD

**Issue by chinacc** [inlife/nexrender#120]
sorry，my english is   is too bad.

my question is ：

“nexrender-cli --file myjob.json”

so，nexrender-cli no need to specify the installation path of ae？

hope you can help me。

think you ，inlife！

**Comment by inlife** [comment]
hello!

yes, you do not need to specify it, both `nexrender-cli` and `nexrender-worker` will try to automatically detect your installation https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/helpers/autofind.js#L5-L34

and if it cannot do that, it will raise an error

if you wish to manually set path to the binary, you need to provide an extra agrument:

``` $ nexrender-cli --file myjob.json --binary="d:/programs/ae2019cc/aerender.exe"```

**Comment by chinacc** [comment]
> 你好！
> 
> 是的，你不需要指定它，`nexrender-cli`并且`nexrender-worker`会尝试自动检测你的安装[https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/helpers/autofind.js#L5 -L34](https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/helpers/autofind.js#L5-L34)
> 
> 如果它不能这样做，它将引发错误
> 
> 如果您希望手动设置二进制文件的路径，则需要提供额外的agrument：
> 
> ```shell
> $ nexrender-cli \
>     --file myjob.json \
>     --binary = “ d：/ programs / ae2019cc / support files / aerender.exe ”
> ```

Thank you very much

**Comment by chinacc** [comment]
think you very much
