### ISSUE TITLE
How to modify the start time of background music

### ISSUE THREAD

**Issue by chinacc** [inlife/nexrender#121]
hey，inlife！
Thank you for your help yesterday, I have solved that problem.

now，I have a new question：
use nexrender, How to modify the entry time of music，I hope that music will start playing from the 30th second！

**Comment by inlife** [comment]
well you have a few options
1. try to use expressions to achieve that (via https://github.com/inlife/nexrender#data-items)
2. try to use AE scripting to achieve that (via https://github.com/inlife/nexrender#script-items)
3. add a pre-render action that will use ffmpeg to create a clipped version of your original track (a bit overkill)

**Comment by chinacc** [comment]
> well you have a few options
> 
> 1. try to use expressions to achieve that (via https://github.com/inlife/nexrender#data-items)
> 2. try to use AE scripting to achieve that (via https://github.com/inlife/nexrender#script-items)
> 3. add a pre-render action that will use ffmpeg to create a clipped version of your original track (a bit overkill)

thank you ,I try to use experessions

`{
      "type": "data",
      "layerName": "tk.mp3",
      "property": "displayStartTime",
      "value": -350
    },`

and

`{
      "type": "data",
      "layerName": "tk.mp3",
      "property": "startTime",
      "value": -350
    },`

used "displayStartTime" and "startTime", but none of them worked as I wanted.  can you give me some hints?

**Comment by inlife** [comment]
if you wish to set expression, you need to provide `expression` instead of `value`
and also make sure those properties actually do exist in the layer

**Comment by chinacc** [comment]
> if you wish to set an expression, you need to provide `expression` instead of `value`
> and also make sure those properties actually do exist in the layer
Thank you for your reply，
Like 'Source Text', where can I see other property?

**Comment by inlife** [comment]
![image](https://user-images.githubusercontent.com/2182108/53860034-4db23d00-3fe8-11e9-91a2-a48a13c36522.png)

**Comment by chinacc** [comment]
thanks，It seems that it can't be solved by `expressions'.
