### ISSUE TITLE
Command line render: WARNING:After Effects warning: Project has missing fonts. 

### ISSUE THREAD

**Issue by sbala69gmail** [inlife/nexrender#123]
Hi ,

I have a one problem to render the AE files.  If I run command line, the font missing warning came. If I run I GUI, there is not error came. 

`WARNING:After Effects warning: Project has missing fonts.`

Please suggest to fix this issue.

**Comment by inlife** [comment]
are you running it on the same system as the one where project has been created?

**Comment by inlife** [comment]
hey @sbala69gmail, were there any changes to the issue, have you succeed with making it work properly?

**Comment by sbala69gmail** [comment]
Yes,  I figure out the code,  use ***fontlocation** to register the fonts location to AE.  

Ref: http://docs.aenhancers.com/other/textdocument/#textdocument-fontlocation

**Comment by darshakgosar** [comment]
Hi @sbala69gmail ,
So, I had one question did you make the AEP Project to point it to the correct fonts path or did you download the font using aerender command line ?
Also how did you Identify which was the font that was missing while rendering the aepx file ?

Thanks

**Comment by sbala69gmail** [comment]
Hi @darshakgosar ,

I register the font path in the command line. If new font, programmatically downloads and paste the corresponding folder and run it.

**Comment by darshakgosar** [comment]
Hi @sbala69gmail ,
Thank you so much for the response, how did you Identify the missing font, so that programmatically download it.

Thanks

**Comment by sbala69gmail** [comment]
Hi @darshakgosar ,

We predefined list of front only suggested for the designer to design the AEPX file. 

The same designers may do not follow the rules or we miss new font to update in server. 

If error occur. 
`WARNING:After Effects warning: Project has missing fonts.`

Download the fonts from driver and run again, the same error occurs again it's mail to the designer head to check this APEF file.

**Comment by darshakgosar** [comment]
Hi @sbala69gmail ,
I am sorry, I think I was not so clear while asking the above query to you. I wanted to ask how do we Identify the missing font warning programmatically on aerender cli or after effect extend script. So is there a way that we can identify this warnings programmatically ?
Thanks for the quick response.

Thanks :)

**Comment by sbala69gmail** [comment]
@darshakgosar ,

I am using "aerender cli". Check the warning in log file and take action accordingly.

**Comment by kimown** [comment]
@sbala69gmail 

I had some proble about `fontLocation`, `fontLocation` is read-only property, how can I change it?


https://buildmedia.readthedocs.org/media/pdf/after-effects-scripting-guide/latest/after-effects-scripting-guide.pdf
