### ISSUE TITLE
how to change string to text layer?

### ISSUE THREAD

**Issue by oncelot** [inlife/nexrender#126]
How to change the value of text layer?
I have an animated text with this string 'this is test' Can I change string in 'text change'?

"assets":[{
            "type": "data",
            "layerName": "Text_1",
            "property": "Text",
            "value": "'text change'"
        }],

thanks

**Comment by inlife** [comment]
Please, refer to the provided example:
https://github.com/inlife/nexrender#data-items

**Comment by oncelot** [comment]
Help me please, 
I have been feeling since this morning, for render no problem...

this is my project
![Immagine](https://user-images.githubusercontent.com/11942345/54369624-8ac8a000-4676-11e9-9587-2048f163b9eb.png)

and this the json file:


 "template": {
        "src": "file:///users/oncelot/test.aep",
        "composition": "Instagram_4"
    },
	"assets":[{
            "type": "data",
            "layerName": "prova",
			"composition":"Text_1",
			"property": "Source Text",
			"value": "new text"
        }],

**Comment by inlife** [comment]
What I still haven't tested, is whether or not property name is influenced by a different language.
Try opening up all the nested elements of the layer you shown (clicking small triangles)
![image](https://user-images.githubusercontent.com/2182108/54415887-661c0900-4706-11e9-8e8f-cde1ecc2dad5.png)

There should be "Source Text" property, however, it might be called differently in your language. Could you share that screenshot? And also could you try changing  `"property": "Source Text",` to  `"property": "YOUR LANG VALUE",`, maybe that would solve the issue?

**Comment by oncelot** [comment]
![Immagine](https://user-images.githubusercontent.com/11942345/54435242-5addd300-4730-11e9-9198-de0b704554b0.jpg)
I've change but does not solve the problem
"assets":[{
            "type": "data",
            "layerName": "prova",
			"composition":"Text_prova",
			"property": "Testo sorgente",
			"value": "new text"
        }],

**Comment by oncelot** [comment]
resolve thanks, I've rename the layerName and now change the text...
thanks

**Comment by inlife** [comment]
oh, that's great 👍

**Comment by nicohery** [comment]
In a French configuration you'll have to use 
`"property": "Texte.Texte source",`
