### ISSUE TITLE
my server crashes with error 500

### ISSUE THREAD

**Issue by shogothpl** [inlife/nexrender#128]
Hi, 
First of all I'd like to thank you for the fantastic job you've done.

I have the issue with assets files larger than 1GB - the server crashes with Internal Server Error 500. Do you know how to deal with this issue?

Thanks for help in advance.

**Comment by inlife** [comment]
Hey @shogothpl !

Could you please provide the following information:
* Which version of nexrender are you using?
* What kind of the setup do you have? (server+worker or cli)
* Are you using pre-built binaries or globally installed npm packages?
* Which kind (and version) of operating system you are running it in?
* Any additional information that might be helpful

**Comment by shogothpl** [comment]
Hi @inlife 

- The version of nexrender: 6.4.1
- My setup: CLI
- NPM package
- system: macOS Mojave v10.14.3

I've built the system that catches the rendering requests from other server (send by POST) and then the json with job is being amended and send to nexrender. Everything works perfectly fine except the situation when the assets files (f.i. mov) with file size over 1GB are generating Internal Server Error 500.

**Comment by inlife** [comment]
i assume its related to file size limitations for http requests handled by http server which is serving assets
is it being run by you? have you checked ability to download an asset directly using your browser?

P.S. i would recommend to switch to version 1.x

**Comment by shogothpl** [comment]
I think my server has the limitation. Thank you for your help.
