### ISSUE TITLE
Using DXGI: Device: "NVIDIA GeForce G100" has dedicated video RAM (MB): 231

### ISSUE THREAD

**Issue by chinacc** [inlife/nexrender#129]
in the log file, "Using DXGI: Device: "NVIDIA GeForce G100" has dedicated video RAM (MB): 231"

**Comment by inlife** [comment]
hello
I don't see the question there

**Comment by chinacc** [comment]
Thank you. I've solved this problem.
because use  ae cc 2019 for template making,  
but, use ae 2014 for rendering server
