### ISSUE TITLE
Asset type for .json or .txt?

### ISSUE THREAD

**Issue by ThisIsIgnis** [inlife/nexrender#130]
Hello there, You made awesome tool here! I wanted to ask a question is it possible to import asset in .json or .txt formats, or even .csv? Or just use type: data and put a src link for example:?

```
{
    "assets": [
        {
            "src": "https://example.com/assets/dataset.json",
            "type": "data",
            "layerName": "MyCustomDataset.json"
        },
        {
            "src": "https://example.com/assets/image.jpg",
            "type": "image",
            "layerName": "MyNicePicture.jpg"
        },
        {
            "src": "file:///home/assets/audio.mp3",
            "type": "audio",
            "layerIndex": 15
        }
    ]
}
```

more info: https://helpx.adobe.com/after-effects/using/data-driven-animations.html

**Comment by inlife** [comment]
Those types of assets (json, txt, csv) for the built-in data-driven approach are not yet supported in the nexrender.

At the moment nexrender offers a slightly different approach of making data-driven animations. (Ability to set directly set value or an expression of a particular property from the json job description itself.)
https://github.com/inlife/nexrender#data-items

**Comment by ThisIsIgnis** [comment]
Roger that. Thanks!
