### ISSUE TITLE
compostions question

### ISSUE THREAD

**Issue by chinacc** [inlife/nexrender#131]
![QQ截图20190325204649](https://user-images.githubusercontent.com/7865526/54920949-84bca400-4f3f-11e9-8754-ed1b84234cd8.png)

Only this layerName “p101.jpg”, pictures can not be replaced successfully，Because it's not in main comp

**Comment by chinacc** [comment]
like this ，https://github.com/inlife/nexrender/issues/119

**Comment by inlife** [comment]
you can try setting in which composition that image asset needs to be replaced

**Comment by chinacc** [comment]
nexrende is very good, thanks for your wisdom
