### ISSUE TITLE
Dealing with Image sequences and Postrender action-copy

### ISSUE THREAD

**Issue by stratos133t** [inlife/nexrender#132]
Dear Inlife,

I´m rendering an image sequence by using nexrender/cli. The process executes flawlessly in the temporary folder. yet I´m having trouble with the post render action. 

What Id like to do is to copy of that image sequence that is being made in the temporary folder to another location in my drive. Im assuming this is possible by setting a post render action.

Right now my .Json file looks like this:

```
{
    "template": {
        "src": "file:///C:/NODE_TEST/assets/amazing.aepx",
        "composition": "main",
        "frameStart": "0",
        "frameEnd": "1440",
        "continueOnMissing": "Boolean",
        "settingsTemplate": "Best Settings",
        "outputModule": "JPEG", (this one named after a custom module I made in after effects)
        "outputExt": "jpeg"
    },

    "actions": {
        "postrender": [
            {
                "module": "@nexrender/action-copy",
                "output": "C:/Users/Victor/Documents/NODE_TEST/results/result_[#####].jpg"
            }
        ]
    }
}
```
 
While it does the render . I get an error at the end.

![question](https://user-images.githubusercontent.com/49046329/55200477-8fd13780-51be-11e9-8789-5db536b2d382.jpg)

Wonder if you could bring some light on how to set the .json properly for this scenario.

Many thanks.

**Comment by stratos133t** [comment]
hey!,
Thx for replying. that sounds ok, *yet my program needs to locate the files in the same render folder time after time.
is there any possible solution for that?

thx for your help.

**Comment by inlife** [comment]
Well actually, you could try setting `job.output` to some path, in your case to `"C:/Users/Victor/Documents/NODE_TEST/results/result_[#####].jpg"`

nexrender should pick up this path and use it to render the output into that folder. Now, this option is not carefully tested, but might work, please try.

**Comment by johnrico2000** [comment]
Hi, has the post render action been updated to take care of image sequences in the meantime?

Thanks,
Frank

**Comment by johnrico2000** [comment]
Hi, I've been using the hack you proposed to directly render an image sequence using the `result_[#####].jpg` file name syntax into a designated folder via `job.output`. I then use ffmpeg to merged the images into a video myself.
Starting with release 1.10.0 this does not work anymore. It looks like you are now checking if an output file with that name really exists. Could you please support the above method again. I would regret to be forced to be stuck on old nexrender worker versions.

Best regards,
Frank

**Comment by inlife** [comment]
Oh yes @johnrico2000 that definitely can be fixed, going to push an udpdate
