### ISSUE TITLE
Downloading assets with a project

### ISSUE THREAD

**Issue by franeko** [inlife/nexrender#134]
So I have a composition that is connected with a couple of .psd files. I can have a JSON with Job description that link to the project file (.aep) but I cant figure out how to link to those PSD files. 

I cannot just replace the assets like with images because the AE layer name = PS layer name, not file name.

Is there any workaround for that?

**Comment by inlife** [comment]
Hello @franeko,

I'm honestly not sure, never had experience with a situation like that. However, if there is a possibility to replace a PSD file via scripting, you can try adding a custom js script that would do the job. Unfortunately, currently, I do not have time to explore that

(you can always take a look at the generated script to see how the image/audio replacement works there, to use as an reference)

Hope that helps!

**Comment by franeko** [comment]
Okay, it was worth a try

Vladyslav Hrytsenko <notifications@github.com> schrieb am Do. 4. Apr. 2019
um 08:27:
