### ISSUE TITLE
Replacing Footage items in composition

### ISSUE THREAD

**Issue by franeko** [inlife/nexrender#135]
The documentation states: 

> composition: string, composition where the layer is, useful for searching layer in pre-compositions. If none is provided, it uses the default composition set in the template. Providing "*" will result in a wildcard compostion matching, and will apply this data to every matching layer in every matching composition.

I have been trying to use "*" to match any composition. The program hangs as if there was some infinite loop in the .jsx script generated by nexrender.

**Comment by inlife** [comment]
Could you also please provide a screenshot of the project/composition structure in AE?

**Comment by franeko** [comment]
![image](https://user-images.githubusercontent.com/550687/55609954-3ea6e200-5782-11e9-9442-bba100641115.png)

Do you have any idea what might be causing the issue?

**Comment by inlife** [comment]
Thank you!

No, I'm not sure yet. This is the part where all that stuff is getting handled:
https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/assets/nexrender.jsx#L35-L80

**Comment by inlife** [comment]
yes, it is possible

**Comment by inlife** [comment]
hello guys
please try out the newest release (1.1.2), there was a fix in #140 that might have helped with the issue

**Comment by HarryLafranc** [comment]
hey,

yep it works for me ! thanks a lot to you and @stoikheia for the fix, it's a nice catch
