### ISSUE TITLE
How does nexrender work? (rendering part)

### ISSUE THREAD

**Issue by wmustafaAwad** [inlife/nexrender#137]
Hey there ! 

I am a bit interested in how nexrender performs its rendering task, and I have been trying to figure this out. Would appreciate a bit of help here. Below, I lay my conclusions and questions in subsections:

## 1.0 How the file is rendered:
That's by using the .aep file with aerender, as mentioned. A version of ffmpeg is then used to convert the .avi file into a .mp4 
All of the extra files are then deleted.

### 2.1 audio or image files:
The .aep file is copied and the files from the respective paths are copied, too. But how is that path edited in the .aep file itself ? I believe aerender does not allow this by default, so how do you do it ?

### 2.2 text
I have no clue about how you edit the text/data. 

##
So, my questions are:
- How do you change the paths to the files (if that's what happens) ?
- How do you change the text in the data layer? 

Cheers to Vlad and the team for their great work!

**Comment by inlife** [comment]
Hello, @wmustafaAwad!

First of all, thank you!

Yes, you are right about the concept of how the file is rendered.

And the rest, well, it is actually quite simple.
The major part of the rendering process itself happens in the `nexrender-core` package. And it is very small. You can check out the most important sequence right there:
https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/index.js#L81-L89

Mainly:
1. setup the needed folders and prepare everything
2. download assets (local fs/http/ftp/aws s3/etc)
3. run custom pre-render actions
4. create a custom jsx script file
5. spawn ae render process and wait for it to finish
6. run custom post-render actions
7. clean everything up

The magic related to image substitution, custom text and data is actually happening on that step 4. nexrender forms a script with instructions that are fetched from json job file, and fills the predefined template file for the script: https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/assets/nexrender.jsx

That script will be executed as aerender starts, just moments before actual rendering will begin. And that's pretty much it.

P.S. In the older version, it worked differently. It partially worked by patching the original aepx file, but that way was a bit more unstable in regards to the different AE versions and changes in project signatures and other caveats.

Also, as you might've noticed, there are a few other packages in the nexrender, some of them responsible for client/server communication (and ability to set up simple networked rendering farm), others extend the functionality by adding custom actions, like `action-encode` and `action-copy`. And they meant to be used as optional plugins.

Hope all that helps to understand it better!

**Comment by wmustafaAwad** [comment]
I guess I partially found what I am looking for in your second link, specifically this code snippet:

```
    var importOptions = new ImportOptions(file);
    //importOptions.importAs = ImportAsType.COMP; // you can do stuff like this at this point for PSDs
    var theImport = app.project.importFile(importOptions);
    layer.replaceSource(theImport, true);

    return true;
};
```

I would like if you can guide me to where I can find the implementation of this function?

**Comment by inlife** [comment]
That is something coming from After Effects scripting side. You can check out: https://blogs.adobe.com/wp-content/blogs.dir/48/files/2012/06/After-Effects-CS6-Scripting-Guide.pdf?file=2012/06/After-Effects-CS6-Scripting-Guide.pdf

Or maybe newer versions, if you will be able to find them.
