### ISSUE TITLE
German Umlauts are not render right

### ISSUE THREAD

**Issue by christianjung** [inlife/nexrender#138]
German Umlauts aren't shown correct after render.
The whole pipeline works fine but i get wrong shown Umlamuts in the final video.
If i running the Script in the AE-GUI it works fine as well, but not in the common automated commandline-way. Is there any issue known or way to fix this problem?

I'm using the nexrender server/worker 1.0.1 binarys on Windows 10 and After Effects CC 2019.
The whole pipline is UTF-8 encoded.

I need to deliver common german sentences with all chars represented.

Thanks for your help!

**Comment by adanielyan** [comment]
I have a similar issue with other non-english characters. @christianjung were you able to find a solution?

**Comment by brassel** [comment]
Maybe the font you use does not support those characters?

**Comment by inlife** [comment]
Closing issue based on inactivity, if it is still relevant, please reopen

**Comment by FinnFrotscher** [comment]
please reopen. 
When rendering in aftereffects headless mode, my umlauts come out as gibberish $@#, when opening the same `project.aet`, running `nexrender-xyx.jsx` and rendering using the interface, the umlauts come out correctly.

**Comment by inlife** [comment]
Hey @FinnFrotscher,

Please check which version is affected for you?
Also, I believe that `v1.16.0` should fix it. (it was published today)

**Comment by FinnFrotscher** [comment]
I am having issues with ffmpeg:
```
MCsc0M7y0Gx0VAi97CNuu] action-encode: output file /Users/finnfrotscher/code/cofenster/api.renderer/tmp/MCsc0M7y0Gx0VAi97CNuu/encoded.mp4
> ffmpeg binary b4.2.2 is not found
> downloading a new ffmpeg binary b4.2.2 to: /Users/finnfrotscher/code/cofenster/api.renderer/tmp/ffmpeg-b4.2.2
> ffmpeg binary b4.2.2 was successfully downloadednds





[ERROR]

"Error loading postrender module @nexrender/action-encode: Error: Error starting ffmpeg process: Error: spawn /Users/finnfrotscher/code/cofenster/api.renderer/tmp/ffmpeg-b4.2.2 EACCES"
{}

```

first off: ` /Users/finnfrotscher/code/cofenster/api.renderer/tmp/ffmpeg-b4.2.2` is not the desired location.
second: i cant run this with and without sudo. what do i do?

**Comment by FinnFrotscher** [comment]
reposted here: https://github.com/inlife/nexrender/issues/389
