### ISSUE TITLE
Example of creating personalized videos?

### ISSUE THREAD

**Issue by kylewill** [Inlife/nexrender#14]
Is there an example of the process for using nexrender to generate personalized videos with an image or text changing?

**Comment by Inlife** [comment]
End-to-end, currently – no. However, there are some examples of using api to do this (in issues).

In nearest future, (probably in one or two weeks), I'm going to create an article with demonstration of whole, end-to-end process of creating personalized video.

As soon as i'll finish the article, i will notify you in this thread. :)

**Comment by Inlife** [comment]
hey, @kylewill 

i made real example of using nexrender with personalization/changing elemnts
hope that will be helpful to you: https://github.com/Inlife/nexrender-boilerplate

😉 😄 👍
