### ISSUE TITLE
Is it possible to  starttime, inpoint, outpoint?

### ISSUE THREAD

**Issue by Killer-Awesome-Phantom** [inlife/nexrender#141]
I not sure if it possible but i would like to have some picture and video and some audio files and i want to add them to layers and the set the inpoint and outpoint of the pic lay to match the audio file length and set the start time of the videos to before the images and after.

**Comment by inlife** [comment]
you can check out the boilerplate project:
https://github.com/inlife/nexrender-boilerplate

especially look on how project file is structured, and how expressions influence it's behavior
