### ISSUE TITLE
Error invalid JSON when sending job via AJAx request

### ISSUE THREAD

**Issue by JamesBotterill** [inlife/nexrender#144]
**Describe the bug**
When attempting to send a request to the nexrender-server via request from a webform I get an error for invalid json, I take the same JSON output from the request and send to server using a CURL request and the job renders correctly. 

The error from the server is as follows:

Error: Invalid JSON
    at createError (/usr/local/lib/node_modules/@nexrender/server/node_modules/micro/lib/index.js:20:14)
    at parseJSON (/usr/local/lib/node_modules/@nexrender/server/node_modules/micro/lib/index.js:120:9)
    at exports.text.then.body (/usr/local/lib/node_modules/@nexrender/server/node_modules/micro/lib/index.js:158:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Information about environment**
* v1.1.3
* server+worker
* npm packages?
* OSX - High Sierra 

**Expected behavior**
The job from the web server should be handled correctly without issue.

**Comment by inlife** [comment]
hello @JamesBotterill 

could you provide the snippet of the code that forms the request?

**Comment by JamesBotterill** [comment]
![Screen Shot 2019-04-23 at 10 48 02](https://user-images.githubusercontent.com/9433760/56573367-d39a3f80-65b8-11e9-9e8e-3bac8f3f95dd.png)

**Comment by JamesBotterill** [comment]
doh!, 

I see the issue clear as day now

**Comment by inlife** [comment]
cheers! :D

**Comment by Kiernan-M** [comment]
Hey @JamesBotterill 

This was a little while ago but I was wondering if you could share what the issue was?

I am trying to create an ajax script to submit a job from a HTML form.
I have a php script that works but I want to be able to retrieve the job status and display it in the browser.

Thanks.
