### ISSUE TITLE
Change temp directory

### ISSUE THREAD

**Issue by Killer-Awesome-Phantom** [inlife/nexrender#145]
Is There a way to change the temp directory for the aerender output as it is currently on my main drive which is only 500gb so it keep running out of space while rendering?

Thanks in advanced.

**Comment by inlife** [comment]
sure, that directory is called `workpath`, it can be changed via options

`--workpath ` for the worker and the cli, and `{workpath: 'somepath'}` for the core

**Comment by Killer-Awesome-Phantom** [comment]
Awesome thanks for the quick reply
