### ISSUE TITLE
data.jason in assets can be read

### ISSUE THREAD

**Issue by nazemi0101** [inlife/nexrender#146]
Hello man. tank you for build nexrender.
..
on older version  nexrender we can render after effect
project by jason file included in ae. but in this update version not do can
..
I need to change the parameters of both simultaneous methods ..
..

This is a great feature that we do not need to save all parametr and long parametr in data base that need operations and can not use  script file(jsx file in myjob.js) method . in after effect  that can be change we use the method expression in the layer project aep file to read automatic the values from the jason file We will perform operations on them automatic .
...
info :in the older version i can call data type in assets code in start.js and can get src address and get name of layer then change 

look like below code
{ "type": "data",  "name": "data.json" ,    "src": `http://localhost:${port}/assets/slideshow/data.json${datascript}` }
this code add in assets in start.js old version nexrender and worked
...

![1](https://user-images.githubusercontent.com/47674802/56721098-6d98ee00-6759-11e9-979f-cced75116b00.png)
![2](https://user-images.githubusercontent.com/47674802/56721104-7093de80-6759-11e9-9bfd-ad0a94e888a8.png)
![3](https://user-images.githubusercontent.com/47674802/56721155-8b665300-6759-11e9-8c45-336d8e7e3881.png)

**Comment by inlife** [comment]
hello

the features that were introduced in the new version allow you to achieve those same results much easier, please check out this link: https://github.com/inlife/nexrender#data-items

and also, since you are coming from an older version, also check out the migration guide:https://github.com/inlife/nexrender#migrating-from-v0x
