### ISSUE TITLE
Clear nexrender-server database via cli

### ISSUE THREAD

**Issue by JamesBotterill** [inlife/nexrender#149]
**Is your feature request related to a problem? Please describe.**
The ability to reset clear the nexrender-server jobs list via a cli command 

**Describe the solution you'd like**
$ nexrender-server --DBRESET

**Describe alternatives you've considered**
Thought about just going and manually locating and deleting the json but it's a pain

**Additional context**
A lot of testing and I really like things cleaned up every now and then :)

**Comment by inlife** [comment]
I will definitely think about adding something like that in the future releases 👍 

Meanwhile, for your specific case, you can create a simple script that would send an HTTP DELETE /jobs/:uid request with a specified job uid. And the list of ids can be retrieved via HTTP GET /jobs, and filtered by conditions that you can provide.

**Comment by inlife** [comment]
Added ability to cleanup the server in https://github.com/inlife/nexrender/commit/6f6883ef1735b536ff0a7704601bc6bc00c22468

To use simply run `nexrender-server --cleanup`
