### ISSUE TITLE
Pass Render % Progress in Get api/v1/jobs/:uid response

### ISSUE THREAD

**Issue by JamesBotterill** [inlife/nexrender#150]
**Is your feature request related to a problem? Please describe.**
When I send a get request for jobs I'd like the render percentage to be returned as well as the status, this is so I can pass the progress back via the GUI

**Describe the solution you'd like**
in the response from the server I'd like to have a percent object which returns the render percentage for the job (percent: 0(queued) to 100(finished) 
 
**Describe alternatives you've considered**
None at present

**Comment by inlife** [comment]
I was thinking about adding that feature at some point, however, I'm still not sure if sending so many HTTP requests would be ok for every user. Probably that feature would require a switch of some sort.

**Comment by JamesBotterill** [comment]
I can see your point, yes making it a switch seems sensible

**Comment by inlife** [comment]
Progress passing was added from worker to server in https://github.com/inlife/nexrender/commit/8b2dc86518c2870b0c6851e375eb9ea288372189
