### ISSUE TITLE
Replace Footage Item

### ISSUE THREAD

**Issue by bblo-seso** [inlife/nexrender#151]
**Describe the bug**
When replacing the assets of a layer in a composition using 'layerName', job fails with error.
Same job works using 'layerIndex' or when 'layerName' is used to replace assets on a project level (include file extension)

**Information about environment**
* Which version of nexrender are you using?
v1.1.3
* What kind of the setup do you have? (server+worker or cli)
cli
* Are you using pre-built binaries or globally installed npm packages?
pre-built
* Which kind (and version) of operating system you are running it in?
MacOSX
* Any additional information that might be helpful

**Expected behavior**
I expected the asset defined in 'assets.src' to replace the asset used in layer [asset.layerName] of type [asset.type]

**Screenshots**

copy paste error:

job rendering failed
Running Script: /var/folders/sw/wb7bf_956fvc0ly3gk3cbmrm0000gr/T/nexrender/bLa-Lo0-sEaJOtikgVluG/nexrender-bLa-Lo0-sEaJOtikgVluG-script.jsx
aerender ERROR: Error executing script: /var/folders/sw/wb7bf_956fvc0ly3gk3cbmrm0000gr/T/nexrender/bLa-Lo0-sEaJOtikgVluG/nexrender-bLa-Lo0-sEaJOtikgVluG-script.jsx
Error: After Effects error: File logoAnim_holder is not a valid file type for import.
aerender ERROR: Runtime error in After Effects.
aerender version 16.0x235
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched

job son:
 "assets": [
		{
			"src": "file:///Users/[user]/Desktop/temp/ae/assets/logos_anim/logo_anim2.m4v",
			"type": "video",
			"layerName": "logoAnim_holder"
		}
	],

![Screenshot 2019-05-03 at 16 28 47](https://user-images.githubusercontent.com/50240275/57144151-b3406100-6dc0-11e9-9568-af3c0169235a.png)

**Comment by inlife** [comment]
Hello!

What is the footage type of the layer you want to replace, it doesn't look like video footage on the screenshot, or am I mistaken?

**Comment by bblo-seso** [comment]
It is video though. Same applies trying to replace .jpg or .png assets

**Comment by inlife** [comment]
Usually, at least in AE that I've worked with, layer connected to footage items have square brackets around the layer name (or in that case, it will be a file name)

Since AE tells about this error:
> After Effects error: File logoAnim_holder is not a valid file type for import.

You can try either renaming layer to have .mp4 in the title. 

Also, could you provide a screenshot of the footage items you have in your composition?

**Comment by bblo-seso** [comment]
Mmm... when you create a new layer from a footage item, it gets a default name that’s the same as the name of the footage item.  That name is displayed in square brackets. You can give a layer a custom name by right-click rename. When clicking on the header of the layer column, you switch the view between the footage name (as in the project window) and the footage name.

I’d figure that since the job.json file refers to ‘layerName’ it should actually reference the, well, layers name.

It does work like that with the ‘data’ option - setting the source text property of a layer with the layerName ‘myLayerName’.
Not sure how or why it’s implemented differently for the image or video (didn’t try sound yet) types


[random ramblings courtesy of iOS auto-correction]

On 3 May 2019, at 17:01, Vladyslav Hrytsenko <notifications@github.com<mailto:notifications@github.com>> wrote:


Usually, at least in AE that I've worked with, layer connected to footage items have square brackets around the layer name (or in that case, it will be a file name)

Since AE tells about this error:

After Effects error: File logoAnim_holder is not a valid file type for import.

You can try either renaming layer to have .mp4 in the title.

Also, could you provide a screenshot of the footage items you have in your composition?
