### ISSUE TITLE
Rendering on different computer - Unable to Render: File Not Found

### ISSUE THREAD

**Issue by byumark** [inlife/nexrender#156]
We are loving nexrender and excited to implement it.

We are using nexrender with an AE project file created on a different machine, so the paths are different. If we open the project in AE, the relative paths seem to re-link and then everything is fine once we start using nexrender, but if we use nexrender first, then we get this error:

```Unable to Render: File Not Found /path/to/file```

I'm sure this is an issue with `aerender` and not nexrender, but i'm curious if you can think of any ways to not have to open the project in AE before rendering using the command line. It seems like `aerender` should be able to resolve the paths like the UI does.

**Comment by inlife** [comment]
Hey @byumark 

Very glad to hear that!
Usually both arender and nexrender should be able to pick up new relative paths if they located at the same "subpath" relative to the project file you are working with. At least it was the case in older versions of aerender.

In case that doesn't work anymore, I would actually suggest manually settings paths to all assets in the job file description. You don't need to download them if they already exist locally, just use `file://` protocol instead of `http://`. You can read more about that in the "asset substituion" part of readme.

Hope that helps!

**Comment by byumark** [comment]
Thanks, @inlife .

Are you referring to manually setting paths to all assets in the job json that we submit to nexrender? I can see how that would work, but we use a lot of assets that don't need to be dynamic so putting them all in there seems a bit tedious. Plus, would this still present a problem for cross-platform rendering between mac and windows since one uses a drive letter and the other does not? Or can you do relative paths in the assets section of the job json?

**Comment by inlife** [comment]
Well in a way yes. Although I think if automation of that part is possible and it might yield a better and more robust result.

>so putting them all in there seems a bit tedious
That is unfortunately true. However, you have a benefit of telling AE exactly which files you want to use, and where are they located, preventing any possible bugs related to AE guessing wrong folders or taking wrong files.

Regarding relative paths - I'm not sure, that's something that needs to be tested.

Oh, just got an idea while writing this post. You can actually involve some of your own jsx scripting to solve that issue. The concept is to manually add code that would replace paths to your static assets to always verify they are properly located.

So nexrender uses this template script https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/assets/nexrender.jsx
as a base for data injections (/*USERSCRIPT*/) is where the project-specific code will be put.
If you check out your nexrender's temp project folder, you will find a .jsx script there named after project unique id. And that file will contain a set of replacements for assets and data entries from your rules in job file.

You can add there something like that:
```js
// mycustom.jsx
nexrender.selectLayersByName(null, "MyImageLayerName", function(layer) {
    nexrender.replaceFootage(layer, '/foo/bar/image.jpg')
})
nexrender.selectLayersByName(null, "MyImageLayerName2", function(layer) {
    nexrender.replaceFootage(layer, '/foo/bar/image2.jpg')
})
// ... and so on
```

Writing this script once, you can add it to every job you need. Honestly it kinda the same as adding those descriptions to the job definition, but it might work for you better in this form.

**Comment by goodhare** [comment]
I am having this exact same problem. Are you saying I need to write a script to dynamically go through every image and repoint it to a new location?

**Comment by inlife** [comment]
Well, if after effects is not able to do it on its own, I'm afraid that there might be no other way. :(

**Comment by aysimakarca** [comment]
Hi, i am facing this issue too, is there a solution which we can change all paths in the project programmatically? I also couldnt find any temp folder with unique projectId like suggested as well.

**Comment by inlife** [comment]
the discussion has moved to #238
