### ISSUE TITLE
Sample Project

### ISSUE THREAD

**Issue by musdy** [inlife/nexrender#157]
Hello,

Just getting started with dynamic rendering. Was wondering if there is an aep file with dynamic image, text and video rendering examples that I can start playing with?

Getting Started guide will be great for new comers as well. Thanks for the great work! Love the package.

**Comment by inlife** [comment]
Hello @musdy 

Yep, there is a thing similar to what you've described.
If you check out the `packages/nexrender-core/test`, you can find a few testing files I personally used to test nexrender while developing it. You can try to use them as some sort of a reference:
https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/test/manual.js

The files are mentioned here are taken from this repo: https://github.com/inlife/nexrender-boilerplate

I still had no time to update the original boilerplate repo to reflect the new version tho.
Planning on doing that as soon as I will be able to.
