### ISSUE TITLE
'property` and `value` attributes ignored when type == image

### ISSUE THREAD

**Issue by Samanm** [inlife/nexrender#158]
I'm trying to apply property/value when the type is `image` in order to scale up the image size, however they only work if the type is `data` in which case the `src` is ignored...

So when trying the following the `Scale` and `Position` properties are ingored:
```json
"assets": [
        {
            "type": "image",
            "src": "file:///Users/Documents/test.jpg",
            "layerName": "cover.jpg",
            "property": "Scale",
            "value": [100.0, 100.0],
            "property": "Position",
            "value": [530.0, 497.0]
        }
]
``` 

but if change the type to `data` then the image scales up, however the src is not replaced with the one specified here.
```json
"assets": [
        {
            "type": "data",
            "src": "file:///Users/Documents/test.jpg",
            "layerName": "cover.jpg",
            "property": "Scale",
            "value": [100.0, 100.0],
            "property": "Position",
            "value": [530.0, 497.0]
        }
]
``` 

Could you please enable property/value for `image` type as well (in AE the images can have property/values like other types).

**Comment by inlife** [comment]
I see the issue, however before we'll start working on the fix, let's try one more thing
Could try to separate image and data entries to a 2 different "assets". So you would have something like this:
```json
"assets": [
        {
            "type": "image",
            "src": "file:///Users/Documents/test.jpg",
            "layerName": "cover.jpg"
        },
        {
            "type": "data",
            "layerName": "cover.jpg",
            "property": "Scale",
            "value": [100.0, 100.0],
            "property": "Position",
            "value": [530.0, 497.0]
        }
]
```

**Comment by Samanm** [comment]
@inlife Thanks for your quick reply! I just tried what you suggested above and that didn't make any difference. It would be great if we could get this issue resolved as soon as possible as it's currenty blocking me (or if there is a quick workaround that would be fine for now). But hopefully an easy fix and not requiring too much changes.

**Comment by inlife** [comment]
I made a mistake in the previous code snippet, updated it a few moments ago. If you have a chance, could you please try again. Meanwhile, I will think about another quick possible way to fix that.

**Comment by Samanm** [comment]
@inlife That actually worked! Thank you so much for the workaround 👍

**Comment by inlife** [comment]
great to hear!

**Comment by inlife** [comment]
I gave this issue a bit of thought, and it seems to me that the current order-based asset command structure is the most robust way of achieving that.

It might be not the most human-friendly, at least in regards to verbosity, however, that case can be solved via additional tools/utils built separately/additionally, I think.
