### ISSUE TITLE
Make -skip-cleanup default setting

### ISSUE THREAD

**Issue by collindavis** [inlife/nexrender#159]
**Is your feature request related to a problem? Please describe.**
If you don't explicitly set skip-cleanup flag during testing you would never know that your render is actually working. I spent two days trying to figure out why my render wouldn't show up after the system seemed to run it just fine.

**Describe the solution you'd like**
Very simple solution: change flag to -cleanup so that nexrender will need to be told to cleanup files by default vs. skip-cleanup. This could save headaches for any new users who are learning the system.

**Describe alternatives you've considered**
Better documentation disclaiming that -skip-cleanup flag should be used during testing so you're not fooled into thinking something isn't working.

**Additional context**
Although this is a simple change, it's easier to document the method to cleanup files as an "option" vs. doing it by default because it fundamentally changes the way someone tests and learns the software.

Thanks for your consideration!

**Comment by inlife** [comment]
This is a very good point, I fully agree with you. We should change the default behavior. 👍

**Comment by franeko** [comment]
Hi guys
I agree that this flag might be documented in a better way.

On the other hand, I'm going to argue against the change in default behavior: 
1. The change you are proposing will make it easier to debug, but will require more flags for normal usage. I think that default options should be options that are usually used in production, and that would be cleaning up.
2. You are running nexrender with a goal of creating a video file. There are some intermediate steps required. During those intermediate steps some temporary files are created. Removing those temporary files upon successful completion of a task should be the default option.  


Let me know what you think!

**Comment by inlife** [comment]
Well even after about a month I'm still not sure how to solve this issue. Both @collindavis @franeko points seem to be valid, and I just don't know to do at this point.

Since we are talking about 2 environments, maybe it's a good idea to introduce the usage of NODE_ENV? However, that would still result in the verbosity on CLI side.

**Comment by JamesBotterill** [comment]
I wouldn't want to have skip clean up on by default and agree with @franeko completely.

**Comment by brassel** [comment]
> I wouldn't want to have skip clean up on by default and agree with @franeko completely.

Me too. A very similar case is to turn on verbose output when you have problems. Maybe a message like below could help just before the message that the job is finished?

`Temporary AfterEffects project deleted. If you want to inspect it for debugging, use "--skip-cleanup".`

**Comment by inlife** [comment]
Added the exact message @brassel mentioned above https://github.com/inlife/nexrender/commit/6f008fe968f936139130f6c3cf56c0339a27886f. That solution appears to me to be the most concise and elegant.
