### ISSUE TITLE
ability to operate required assets without downloading (local fs)

### ISSUE THREAD

**Issue by Inlife** [Inlife/nexrender#16]
I think that if nexrender is run locally, usage of http server may be slightly pain-in-the-ass-able.

Would be more convenient if you can set some asset paths as your fs paths (relative or absolute);

e.g:

``` js
 "assets": [
            {  "type": "project", "name": "project.aepx", "src": `http://localhost:2323/prj.aep`}, 
            { "type": "image",   "name": "bg.jpg", "src": `../images/bg.jpg` },
            { "type": "image",   "name": "2.png", "src": `/Users/Username/pngs/2.png` },
```

To make this dream come true some changes must be done to `tasks/download.js` or even add a new task, `tasks/copier.js`, (it will be called either just before download or right after download) that will try to copy local fs assets (if they exists) and pass control to next module.

Maybe someone has some thoughts about this one ?

**Comment by southernsun** [comment]
ofcourse people need to consider that using a local file-path will prevent nexrender from running multiple nodes for load-balancing (unless the assests are copied to each machine, which is not wise to do). It should allow UNC paths so file-paths to remote servers can be used as well. This way you can still use multiple nodes.

**Comment by Inlife** [comment]
> unless the assests are copied to each machine

Those assets may be available on some machines, tho.
For example predefined pack of default assets. :)

> It should allow UNC paths

Agree. Didn't know about UNC paths. I assume this is only windows-based systems thing.

Also i only assume that access to those UNC paths is same as for the other local fs-based folders/files. You don't need anything special to use 'em.

Also, seems like using UNC paths is very convenient for the (shared) results folder. 💡
OS-native shared folders!
