### ISSUE TITLE
Json Warning : The structure has changer

### ISSUE THREAD

**Issue by KhejjouM** [inlife/nexrender#161]
The ability to import Json files into after effects and link to that data has been extremely useful. 
However, one gotchya is we need to be able to suppress the warning that results when the structure of the JSON changes.

You will then get a warning "After Effects warning: The structure of the data file for the layer "test.json" has changed.

Do you have any solution ?

**Comment by inlife** [comment]
Hello @KhejjouM 

Can you provide an example of where and how does it happen? I don't remember bumping into anything like what you've described.

**Comment by KhejjouM** [comment]
hello @inlife 
I am using aerender, and i have data on that change on a json file. When the script is launched I get 
<img width="1439" alt="Screen Shot 2019-05-23 at 12 49 04 pm" src="https://user-images.githubusercontent.com/33026935/58247143-39651d00-7d59-11e9-97cd-7dc82826f9ae.png">

**Comment by inlife** [comment]
I'm not sure I even understand what is happening there, on the screenshot. Could you show your code? Or at least describe  the process.

**Comment by KhejjouM** [comment]
I generate a file "updatedData.json" which is an asset on my template. And then when i run the render i have this warning that pop out when i click on OK it works and generate the video. 

What is weird is that I do the same thing with 3 json file and the warning pop only for one file.

**Comment by inlife** [comment]
I don't see the connection with the nexrender, or am I missing something?

**Comment by KhejjouM** [comment]
I use the aerender, and i was seeking for some help

**Comment by inlife** [comment]
Oh, I see. It would be better if you would point out that you are not using nexrender in the first message.
And regarding the question, unfortunately, I don't know how to help you with this one. I can gladly recommend using nexrender tho! :)

Cheers
