### ISSUE TITLE
Expose render progress as callback function

### ISSUE THREAD

**Issue by velocitysystems** [inlife/nexrender#167]
**Describe the solution you'd like**
Similar to the [OnChange](https://github.com/inlife/nexrender#details) method, expose the current render progress % as a callback.

```
{
    "onChange": Function,
    "onRenderProgress": Function
}

```
`onRenderProgress ` is a field that is possible to setup only via _programmatic_ use.
It is a callback which will be triggered every time the rendering progress has changed.
ie. 25%, 50%, 75%.

I am happy to contribute this work as a PR.
@inlife Let me know if you have any thoughts or suggestions?

**Describe alternatives you've considered**
Parsing the console log, however would be nice for this to be available as an optional callback within `nexrender-core`.

**Comment by inlife** [comment]
Ye, I agree, that might be useful.
I guess it can work like this: if there is handler onRenderingProgress, the internal console.log is not triggered, otherwise it is.

**Comment by velocitysystems** [comment]
Thanks @inlife, I have just put up a PR for this.

It seems the render progress is already added to the job object as `job.renderProgress`. So to prevent breaking changes, I have added an optional callback to be invoked when the render progress is changed.

I was thinking about your idea about disabling the console.log, but I quite like the option of having **both** the console logging and the callback. Both may be useful, I would just like to gain access to the render progress for showing progress notifications in a UI.

**Comment by inlife** [comment]
pushed a build with v1.3.0
