### ISSUE TITLE
Still image export option? 

### ISSUE THREAD

**Issue by shealan** [inlife/nexrender#171]
This is truly incredible software, thank you! The projects I have run it on have worked perfectly.

I wanted to find out how hard it would be to support *still image export* as an option?

So essentially adding image format options like *png* or *jpg* to the encoding plugin?

I'd like to use this for dynamically rendering some After Effects compositions as a still image for upload to the web. I have considered using a post render ffmpeg script to extract a frame but I would like to avoid a double compression situation where the videos is compressed and then the image is compressed from that source.

**Comment by inlife** [comment]
Thank you @shealan!

Well, technically you could try to use/add an output module that would do jpg/png export right in the AE, and the provide its name in the job configuration and set up frame limits (using frameStart, frameEnd) so it would render only one (or few) frames in the AE itself.

**Comment by shealan** [comment]
That sounds perfect. Do you mean AE is capable or doing this already and can be instructed by NexRender now, or this is something that would need to be added to NexRender to make possible?

**Comment by inlife** [comment]
>AE is capable or doing this already and can be instructed by NexRender now

Yes, it is capable of doing this already.

Here is info about output modules: https://helpx.adobe.com/after-effects/using/basics-rendering-exporting.html#output_modules_and_output_module_settings

And in the details info for the job description you can see parameters that you need to change:
https://github.com/inlife/nexrender#details

**Comment by shealan** [comment]
Amazing, I'll experiment with that. Thank you!

**Comment by pyskaty** [comment]
Hello, I'm interested in rendering a single image. I read above but unable to figure out how to do it. Please help. Thank you.

**Comment by johkon** [comment]
> Hello, I'm interested in rendering a single image. I read above but unable to figure out how to do it. Please help. Thank you.

If you want to render only image 12 of "yourcomp", this should work:

{
    "template": {
        "src": "file:///users/myuser/documents/myproject.aep",
        "composition": "yourcomp",
        "frameStart": "12",
        "frameEnd": "12",
        "outputExt": "png"
    }
    (Assets, Postrender etc.)
}

**Comment by pyskaty** [comment]
`{
	template: {
		src: 'file:///c:/users/kuba/downloads/playground.aep',
		composition: 'Playground1',
		frameStart: 10,
		frameEnd: 10,
		outputExt: 'png'
	},
	assets: [{
			type: 'data',
			layerIndex: 2,
			property: 'Source Text',
			value: 'yo yo!'
		}
	],
	actions: {
		postrender: [{
				module: '@nexrender/action-encode',
				preset: 'mp4',
				output: 'encoded.mp4'
			}, {
				module: '@nexrender/action-copy',
				input: 'encoded.mp4',
				output: 'd:/render/myresult.mp4'
			}
		]
	}
}`
@johkon thank you for your replay. I've tried that. I should probably apply some postrender action. Snippet that I've attached above work when there is no "outputExt". When I add it - I get error "\nexrender\TsvmSMV1eQGRp8RFUUr7X\result_[#####].png: No such file or directory"  
When I remove postrender actions it finishes without any error but there is no image file (I've tried skipCleanup parameter but sill nothing in temp directory).

**Comment by johkon** [comment]
try this:
1. open the aep-file and add your composition to the render-queue with png sequence as output-setting. Just save it, dont render it. This should fix the issue, that nothing gets rendered
2. remove the entire action-encode part from the JSON.
3. in action-copy use input: "result_00012.png"

This should work, i think

**Comment by pyskaty** [comment]
Thank you, it works!
