### ISSUE TITLE
NexRender FTP Upload feature

### ISSUE THREAD

**Issue by zuntah** [inlife/nexrender#172]
It would be nice if there would be a FTP Upload feature.
You could provide FTP IP and Port and of course username and password.
Once finished, The copy would be sent by FTP to the server.

I might start working on something like this, But my NodeJS Skills are not very strong..
I wish this amazing project would be in Python I could contribute a lot :)

**Comment by inlife** [comment]
Hey @zuntah 

Conceptually an FTP plugin has been planned (at least in some way).
https://github.com/inlife/nexrender/tree/master/packages/nexrender-provider-ftp

Made as alternative to: https://github.com/inlife/nexrender/tree/master/packages/nexrender-provider-s3

**Comment by zuntah** [comment]
I will start working on that :)

**Comment by zuntah** [comment]
FTP Provider ready --> https://github.com/inlife/nexrender/pull/173

Now implementing the provider in action-upload

**Comment by inlife** [comment]
pull request looking good

**Comment by inlife** [comment]
I'm planning to merge that PR, and make some changes to the structure of both upload and download parts of the nexrender
Didn't find enough free time as of yet.

(just wanted to give you an update)

**Comment by zuntah** [comment]
Ok,
Do you need any help?

**Comment by inlife** [comment]
please check out my commit
https://github.com/inlife/nexrender/commit/85a3e9b5105b021253ac9f1a61810dfa7be616ee

**Comment by inlife** [comment]
added improved docs and information in the readme for the provider package:
https://github.com/inlife/nexrender/tree/master/packages/nexrender-provider-ftp
