### ISSUE TITLE
Do we need any kind of license to use aerender with Adobe After Effects at all ?

### ISSUE THREAD

**Issue by rankuptuts** [inlife/nexrender#174]
Do we need any kind of license to use aerender with Adobe After Effects at all ?

E.g. if I install trial version of AE, would aerender still work after AE trial is expired ?

**Comment by inlife** [comment]
There were a few issues around that topic already:

https://github.com/inlife/nexrender/issues/127
https://github.com/inlife/nexrender/issues/133

**Comment by rankuptuts** [comment]
I went through all tickets but missed the last one, thanks for sending links.
