### ISSUE TITLE
downloading assets long time, maybe it is hang up, how can I set download file timeout

### ISSUE THREAD

**Issue by AloneFire** [inlife/nexrender#176]
Describe your question, attach logs, images or anything that might help to better understand it.
downloading assets long time, maybe it is hang up, how can I set download file timeout

**Comment by inlife** [comment]
hello

im assuming your issue is related to the http(s) provider
you can try to pass additional options to the node fetch function that is responsible for the download

https://github.com/bitinn/node-fetch#options

Example:
```js
{
    "assets": [
        {
            "src": "http://example.com/assets/myimage.png",
            "params": { "method": "GET", "timeout": 10000 },
            "type": "image",
            "layerName": "background.png"
        }
    ]
}

**Comment by AloneFire** [comment]
I see thanks
