### ISSUE TITLE
Footage type 'audio' not replacing

### ISSUE THREAD

**Issue by chrstnsmthng** [inlife/nexrender#177]
**Describe the bug**
When attempting to replace an audio file layer (.wav) using Nexrender the layer doesn't get replaced and the placeholder audio is rendered for all jobs.

**Information about environment**
* Which version of nexrender are you using?
v1.4
* What kind of the setup do you have? (server+worker or cli)
Programmatically (node+CLI) 
* Are you using pre-built binaries or globally installed npm packages?
Globally installed NPM packages.
* Which kind (and version) of operating system you are running it in?
Windows 7 SP1
* Any additional information that might be helpful
I'm using image asset replacing and that's working as expected.

**Expected behavior**
When the audio layer is replaced that the intended audio file is rendered.

**Comment by inlife** [comment]
Could you also provide a json of your job, and a screenshot of your layers setup in the AE project?

**Comment by chrstnsmthng** [comment]
![template](https://user-images.githubusercontent.com/24440559/59565300-a188e500-901f-11e9-9f20-8281f1e78de7.PNG)
![template2](https://user-images.githubusercontent.com/24440559/59565301-a188e500-901f-11e9-9af8-102d663e8dd4.PNG)
![template3](https://user-images.githubusercontent.com/24440559/59565315-dc8b1880-901f-11e9-9f6c-df001ef64184.PNG)

I console.logged the URI's of the wav's before hitting the main() function to render them. The images work, so I removed them from a console.log. The console shows the URI and end frame as well. There's two layers in After Effects the image and audio files.

**Comment by inlife** [comment]
you can check the temp folder to see if assets are properly delivered into the working folder

**Comment by chrstnsmthng** [comment]
![Ctrl-c](https://user-images.githubusercontent.com/24440559/59575074-d03aa600-9087-11e9-9cde-b30c0abbf332.PNG)
 Yep, they are making it into the temp folder. When I tried 'layerName' instead of 'layerIndex' yesterday the name of the audio had the name of the layer (track.aif).

**Comment by inlife** [comment]
Seems like the problem might be related to the filename, especially considering the screenshot example. Could you maybe try renaming the original file?

Maybe after effects cant use files if they have 2 different extensions?

**Comment by chrstnsmthng** [comment]
You were right about the filename changed the first song to "1.wav" and it rendered properly. I'm curious about fileURI's and after effects now, but this is great. Thanks for this tool!

**Comment by inlife** [comment]
Glad to hear that, cheers!
