### ISSUE TITLE
add ability to control output module settings via nexrender

### ISSUE THREAD

**Issue by inlife** [inlife/nexrender#179]
Being able to set up various output modules without need to open a freshly installed after effects
https://blogs.adobe.com/creativecloud/new-changed-after-effects-cc-2014/?segment=dva

**Comment by brassel** [comment]
We would help with this issue, but I do not have an inkling how to go about it. Can you give a scribble of how you think this could work?

**Comment by inlife** [comment]
Yea, so probably the easiest way would be to use the `job.settings` struct to set up some values.
And in tasks/script.js probably some handler that would take those arguments, and turn them into instructions of such kind:
> (taken from the example in the link)
```js
var my_renderSettings = {
"Color Depth":"32 bits per channel",
"Quality":"Best",
"Effects":"All On",
"Time Span Duration":"1.0",
"Time Span Start":"2.0"
};
app.project.renderQueue.item(1).setSettings( my_renderSettings );
```

**Comment by brassel** [comment]
So, you are thinking about a new part in the job file `renderSettings` or similar?
Sounds good! I guess the possible settings can maybe somehow be scraped from here?

http://docs.aenhancers.com/renderqueue/renderqueue/

Do you know if we could influence the output format this way? Our use case was to render a single image (via employing PNG Sequence) and not a video.

**Comment by inlife** [comment]
I don't really know, however, I think it might be possible. Since we have access to the scripting env we can try out different new possibilities. 

And something related to actual output module:
http://docs.aenhancers.com/renderqueue/omcollection/
http://docs.aenhancers.com/renderqueue/outputmodule/?highlight=setSettings

This method might be interesting:
```OutputModule.saveAsTemplate()```

As far as I can see quite a recent feature, and not much documentation is available online.
