### ISSUE TITLE
[Question] Variable Videos?

### ISSUE THREAD

**Issue by simaovc** [Inlife/nexrender#18]
Would it be possible to have variable videos? There is to have a video as an asset?

**Comment by Inlife** [comment]
Hey,

I didn't quite understand what do you mean. Could you explain, more detailed, please? :)

Thank you!

**Comment by southernsun** [comment]
Yes, you can change the video using assets and the expression language.

**Comment by simaovc** [comment]
On asset types there are: project, image, audio, script, data, "any-name"(is this "any-name" new?
So if I wanted to use an asset as a video I would just put "video" in the asset type in my project model?

**Comment by southernsun** [comment]
just use 'data', or 'video', they are treated the same way by nexrender.

**Comment by simaovc** [comment]
hmm ok. good to know. I assume that the videos should be the same length and have the same fps to work properly, right?

**Comment by southernsun** [comment]
yes, there are some limitations. Adobe Expression Language only lets you do so much without having to open Adobe AE.

**Comment by Inlife** [comment]
> have the same fps to 

well, i'm sure it needs to be same fps as the one you've used while creating a template project
length can be variable, using expressions you can simply hide the video/mute the sound

**Comment by simaovc** [comment]
But just to clarify, I only have to refer to my new video in the project model. There is no use for expressions?

> using expressions you can simply hide the video/mute the sound

I didn't understand very well this part, can you explain?

**Comment by Inlife** [comment]
>I didn't understand very well this part, can you explain?

https://helpx.adobe.com/after-effects/using/expression-basics.html
you can try to change different properties of object on the scene, I'm pretty sure you can operate with object's position and opacity

**Comment by simaovc** [comment]
Ok. Thank you.
