### ISSUE TITLE
Artifacts in audio

### ISSUE THREAD

**Issue by lleaf** [inlife/nexrender#180]
After rendering the project artifacts appear in the audio.
For example: https://yadi.sk/d/RXIwIkncxSqB8Q
Can be observed at the beginning of the video.
I tried different audio codecs, I took examples from here: https://github.com/inlife/nexrender/tree/master/packages/nexrender-action-encode
I notice this only on hard projects. The problem is reproduced on different PCs.
Is there any solution?

**Comment by inlife** [comment]
I've heard about such bug before. I was related to the mp3/mp4 audio with bitrate value not being high enough. I'd recommend trying to use wav or encoding the mp3 with higher bitrate before sending it to the aerender.

Also, some quotes from discussion on russian:
>решил проблему со звуками, где то на форуме abode нашел информацию что mp3 может быть проблемой или же его кодек.
Как оказалось да, у меня в бэке symfony стоит, она все mp3 записывает в mpga, а после на сервере вместо конвертирования мы просто меняли название и расширение в mp3. Такое не нравилось AE и aerender'у. 
Решил все конвертирование в wav и теперь проблем нет,

>В продолжении темы об искажении аудио звука в видео или будь то mp3, нашли закономерность относительно тех которые были обнаружены ранее.
Всему дело - битрейт и частота кадров, mp3 и mp4 его имеют, а wav максимален и потому проблем нет с ним.
Для исключения таких ситуация, я хотел использовать модуль https://github.com/inlife/nexrender/tree/master/packages/nexrender-action-encode в prerender, то есть не зависимо от того какое видео в рендер придет, я его хотел переконвертировать в битрейт 900 и частоту к примеру 50, в таком случае мы убираем всяческие проблемы с битрейтом и собственно с искажением звуков.

**Comment by lleaf** [comment]
> I've heard about such bug before. I was related to the mp3/mp4 audio with bitrate value not being high enough. I'd recommend trying to use wav or encoding the mp3 with higher bitrate before sending it to the aerender.
> 
> Also, some quotes from discussion on russian:
> 
> > решил проблему со звуками, где то на форуме abode нашел информацию что mp3 может быть проблемой или же его кодек.
> > Как оказалось да, у меня в бэке symfony стоит, она все mp3 записывает в mpga, а после на сервере вместо конвертирования мы просто меняли название и расширение в mp3. Такое не нравилось AE и aerender'у.
> > Решил все конвертирование в wav и теперь проблем нет,
> 
> > В продолжении темы об искажении аудио звука в видео или будь то mp3, нашли закономерность относительно тех которые были обнаружены ранее.
> > Всему дело - битрейт и частота кадров, mp3 и mp4 его имеют, а wav максимален и потому проблем нет с ним.
> > Для исключения таких ситуация, я хотел использовать модуль https://github.com/inlife/nexrender/tree/master/packages/nexrender-action-encode в prerender, то есть не зависимо от того какое видео в рендер придет, я его хотел переконвертировать в битрейт 900 и частоту к примеру 50, в таком случае мы убираем всяческие проблемы с битрейтом и собственно с искажением звуков.

I'll try, thank you

**Comment by lleaf** [comment]
"Wav" work's fine, thank's you!
