### ISSUE TITLE
Cloud rendering or Multimachine rendering?

### ISSUE THREAD

**Issue by musdy** [inlife/nexrender#181]
Is there a way to run nexrender in the cloud or with an online rendering service to make it completely local-machine independent?

We used nexrender to dynamically change the template and get it rendered on our local machines, but we want to put this to a server and get it rendered either at AWS or some online render farm like Turborender.com or something.

Let me know. Thanks for all the support!

**Comment by inlife** [comment]
Hello @musdy 

nexrender has `nexrender-server` and `nexrender-worker` binaries that can be used to create a networked solution. The server is used for job management and distribution to the workers. And workers do the general rendering.

The server is a simple HTTP API and can be deployed on any Linux machine, even the smallest AWS EC2 configuration. Worker, however, requires After Effects to be installed on the system, which needs to run either on Windows or macOS. With AWS, you can use Windows Server 2019. I know of at least one successful case of using it with nexrender.

The deployment process is straightforward, all needed things are packaged inside binaries in the releases, and theoretically, all you need is to download the build, and run it.

Cheers!

**Comment by zuntah** [comment]
@inlife 
What kind of server did you purchase on AWS for the worker?
Do they have windows server with NVIDIA GPU?
Could you send a link here?

Thanks.

**Comment by inlife** [comment]
@zuntah while closing old issues, just noticed that I never responded. 
Sorry about that!

> What kind of server did you purchase on AWS for the worker?
I never did personally purchase any AWS or any other cloud hosting provider.
I was simply relaying what some users of nexrender told me about what they've used it with.
And unfortunately, my info on that is quite limited, so it seems I won't be able to answer most of your questions.
