### ISSUE TITLE
Join multiple AEP files?

### ISSUE THREAD

**Issue by rikuge** [inlife/nexrender#182]
I have several aep files that i want to mix depending on my end goal. Can I use Nexrender to join the seperate AEP files into one render?

**Comment by JamesBotterill** [comment]
you wouldn't be able to do this in a single render. 

You could set it up you have a script that that renders each AEP individually and then a final render which takes the output from the previous renders. 

Using the action-copy you can make sure you'll always have the outputs using the filename and location of your choice. 

Why not combine the AE files into a single project using pre-comps? I've done this for a project and it worked fine.
