### ISSUE TITLE
onRenderProgress callback doesn't get called

### ISSUE THREAD

**Issue by TimP4w** [inlife/nexrender#185]
Hi there!
I'm trying to implement a data-driven pipeline using your amazing project!

Now I have to send to the client the rendering progress, but the callback doesn't seem to work.

**Describe the bug**
onRenderProgress callback doesn't produce any output. (...and also debug = true)

**Information about environment**
* Which version of nexrender are you using?
    "@nexrender/action-copy": "^1.5.0",
    "@nexrender/action-encode": "^1.5.0",
    "@nexrender/action-upload": "^1.5.0",
    "@nexrender/core": "^1.5.0"

* What kind of the setup do you have? 
  See above

* Are you using pre-built binaries or globally installed npm packages? 
Normal package (core version for programmatic rendering)

* Which kind (and version) of operating system you are running it in? 
Windows 10 (Build 17763.557)

* Any additional information that might be helpful: 
Using NestJS (Typescript)

**Expected behavior**
onRenderProgress gets called everytime the rendering progress changes.

**Code Snippet for reproduction**
   ```
 import { Injectable } from '@nestjs/common';
 import { init, render } from '@nexrender/core';

 const settings = init({
        binary: "C:/Program Files/Adobe/Adobe After Effects CC 2019/Support Files/aerender.exe",
        debug: true
    })
    let job = {
        "template": {
            "src": "file:///C:/test.aep",
            "composition": "Test"
        },
        "assets": [
            {
                "layerName": "text-field",
                "type": "data",
                "property": "Source Text",
                "value": text
            }
        ],
        "actions":{
            "postrender": [
                {
                    "module": "@nexrender/action-encode",
                    "preset": "mp4",
                    "output": "encoded.mp4"
                },
                {
                    "module": "@nexrender/action-copy",
                    "input": "encoded.mp4",
                    "output": "C:/Users/beske/video/out.mp4"
                },

            ]
        },
        "onChange": function(render) {
            console.log(render.uid)
            console.log(render.state)
        },
        "onRenderProgress": function() {
            console.log("On Render Progress Callback")
        },
    }
    
    const main = async () => {
        const result = await render(job, settings)
        console.log(result);
    }
    
    main().catch(console.error);

```

***Output***

```
undefined
[0] render:setup
[0] KK5-tRwtOCA6V3Y4wWGAh
[0] render:download
[0] KK5-tRwtOCA6V3Y4wWGAh
[0] render:prerender
[0] KK5-tRwtOCA6V3Y4wWGAh
[0] render:script
[0] KK5-tRwtOCA6V3Y4wWGAh
[0] render:dorender
[0] KK5-tRwtOCA6V3Y4wWGAh
[0] render:postrender
[0] KK5-tRwtOCA6V3Y4wWGAh
[0] render:cleanup
[0] {
[0]   uid: 'KK5-tRwtOCA6V3Y4wWGAh',
[0]   type: 'default',
[0]   state: 'render:cleanup',
[0]   output: 'C:\\...\\result.avi',
[0]   template: {
[0]     src: 'file:///C:/.../test.aep',
[0]     composition: 'Test',
[...]
```

Can you please check it out ? 

Thank you!

**Comment by inlife** [comment]
Hey @TimP4w,

Thank you for the notification, I will investigate.

**Comment by inlife** [comment]
Tried to reproduce, but couldn't.
However, changed the function detection a bit, maybe that should help.

Other note, are you sure the rendering progress isn't happening too fast? Since it relies on parsing the console output of aerender, there is might be a case of some timing involved.

**Comment by TimP4w** [comment]
Thanks! Gonna try it very soon.
I also thought about that and then I created another testing template which took more time to render (c.a. 30 sec) but still couldn't get any output.
I'll look after it again, and if I still have the problem I'll probably try to fix it and if it's the case I send you a pull req., but most probably I can just use the "onChange" for what I need to do.
