### ISSUE TITLE
Add Default input and output params in action-encode

### ISSUE THREAD

**Issue by DmitryDodzin** [inlife/nexrender#186]
If i want to send custom params to action-encode without selecting a preset (totally manually feeding the ffmpeg config) and that causes a problem to get the input from the previous job and not passing manually with `-i` (same applies for `-y`)

So I just added a default clause in the preset selection [here](https://github.com/DmitryDodzin/nexrender/commit/f1d8a19c1ffb7e68dd516d5714c9e1aaa55be3c0).

Alternately a "clean" preset will do the same job but default is a more elegant solution imo.

**Comment by inlife** [comment]
Hello @DmitryDodzin 
That looks great! Would it be hard for you to create a pull request back to this repo for this feature?

**Comment by inlife** [comment]
Thank you @DmitryDodzin
Published in `v1.5.8`
