### ISSUE TITLE
Is the binary release of version 1.5.6 working for you?

### ISSUE THREAD

**Issue by brassel** [inlife/nexrender#187]
We have made the experience that `nexrenderl-cli-win64.exe --version` does not do anything on version 1.5.6 (whereas it prints the version number in all other releases we tested including 1.5.5). And it does not seem to work with other commands as well. Just checking if we are doing something wrong on our side.

**Comment by inlife** [comment]
Thank you, going to check it out. Maybe something went wrong in the building pipeline

**Comment by inlife** [comment]
Indeed, there is an issue with pkg@4.4.0, reverted back the commit upgrade, and pushed a new build job.

**Comment by brassel** [comment]
Thanks a lot for checking and fixing this! I will check the new version out asap!

Cheers!
brassel

**Comment by inlife** [comment]
Hey @brassel, did that fix the issue for you?

**Comment by brassel** [comment]
I think so, dev ops installed the new version and I did render successfully
On the virtual machine. However, I want to make 100% sure on Monday which
version they installed.
Thanks again for the fast fix!

Vladyslav Hrytsenko <notifications@github.com> schrieb am Sa. 13. Juli 2019
um 09:09:

**Comment by brassel** [comment]
We have installed version 1.5.7 and it works fine for us.

Thanks again!
