### ISSUE TITLE
How to action-copy a PNG sequence

### ISSUE THREAD

**Issue by BasicWatermelon** [inlife/nexrender#188]
Hey there,
I currently have Nexrender rendering my project as a PNG sequence, and now I'm wondering how to copy that outputted sequence to my folder.
Currently, it moves the first image, then shows this: 
![image](https://user-images.githubusercontent.com/37552537/61147662-c9f7e800-a4d4-11e9-99c2-35c78f037374.png)

My code looks like this:
![image](https://user-images.githubusercontent.com/37552537/61147711-f01d8800-a4d4-11e9-91d3-ee947a1b55b7.png)

I have tried setting the output to both "output.png" and "output_[#####].png"

Thanks a lot for any help

**Comment by inlife** [comment]
Hello @BasicWatermelon 

I'm afraid the action-copy lacks support for multi-image sequences atm, as you can see the whole code is quite small and takes care only of video files: https://github.com/inlife/nexrender/blob/master/packages/nexrender-action-copy/index.js

**Comment by BasicWatermelon** [comment]
Alright, no problem. I have an idea on how to bodge it to work.
Thanks a lot!

**Comment by atitkothari** [comment]
@BasicWatermelon How did you get it to work? I'm running into a similar issue?

**Comment by BasicWatermelon** [comment]
> @BasicWatermelon How did you get it to work? I'm running into a similar issue?

My end goal use case was extremely specific so I ended up making my own module and not using the action-copy one.
