### ISSUE TITLE
Render network

### ISSUE THREAD

**Issue by Elisabete1908** [Inlife/nexrender#19]
Hey,

Running nexrender and having such error:

=========[RENDERNODE]=========

nexrender.renderer is starting

------------------------------
making request for projects...
looking for suitable projects...
[rkLqeGuh] setting up project...
[rkLqeGuh] downloading assets...
[rkLqeGuh] renaming assets...
[rkLqeGuh] filtering image assets...
[rkLqeGuh] patching project...
[rkLqeGuh] rendering project...
[rkLqeGuh] verifying project...
[rkLqeGuh] applying actions: moving result file...
[rkLqeGuh] cleaning up...
----------------------------
[rkLqeGuh] project finished
----------------------------

making request for projects...
looking for suitable projects...
[rkLqeGuh] setting up project...
[rkLqeGuh] downloading assets...
[rkLqeGuh] renaming assets...
[rkLqeGuh] filtering image assets...
[rkLqeGuh] patching project...
[rkLqeGuh] rendering project...
[rkLqeGuh] verifying project...
[rkLqeGuh] applying actions: moving result file...
[rkLqeGuh] cleaning up...
----------------------------
[rkLqeGuh] project finished
----------------------------

My problem is that output file is created but he renders again (and again) and not stop.
You know why?

**Comment by Inlife** [comment]
Hey!

Seems like it coundn't save the result on the api-server part;
Could you provide logs for the api server too ?

Thank you!

**Comment by Elisabete1908** [comment]
nexrender.server is listening on port: 3000
POST /api/projects/ 200 686 - 22.897 ms
GET /api/projects/ 200 688 - 1.395 ms
PUT /api/projects/rkLqeGuh/ 200 723 - 5.759 ms
PUT /api/projects/rkLqeGuh/ 200 723 - 3.735 ms
GET /api/projects/ 200 725 - 0.297 ms
PUT /api/projects/rkLqeGuh/ 200 723 - 4.905 ms
PUT /api/projects/rkLqeGuh/ 200 723 - 3.970 ms
GET /api/projects/ 200 725 - 0.387 ms
PUT /api/projects/rkLqeGuh/ 200 723 - 3.760 ms
GET /api/projects/rkLqeGuh/ 200 723 - 0.686 ms
GET /api/projects/rkLqeGuh/ 200 723 - 0.752 ms

**Comment by Inlife** [comment]
seems like project ` rkLqeGuh` is not updating (saving data)
i'll test it in my env as soon as i be able to

make sure that created file `db.json` is available for write by node process (but this seems unlikely, it needed perms to write a data from post request, but who knows :D)

**Comment by southernsun** [comment]
mhh i seem to have the same problem with the latest version of nexrender. I will investigate as well.

**Comment by southernsun** [comment]
the setStateAndSave(err, state) method takes two arguments, but only a single argument is passed along (the state), thus err=state and state itself is never set. causing the issue. I don't know the project too well, but i think simply changing the number of arguments on the setStateAndSave() method to a single parameter (state) should be sufficient as the err argument is never used.

**Comment by Inlife** [comment]
i don't know how i messed up
but i did it with success ! :D

**Comment by Inlife** [comment]
never thought that covering this part of project with test would be so important
anyways, merged, fixed(i hope :D), pushed
**nexrender@0.4.12 on npm**

**Comment by Inlife** [comment]
closing the issue
if issue still ocures - please reopen :)
