### ISSUE TITLE
Renew your subscription at adobe.com today

### ISSUE THREAD

**Issue by whatneuron** [inlife/nexrender#197]
I downloaded Adobe AE CC 2019.

It worked well for duration of trial.

Now I am getting this dialog box and it won't proceed.

Is there anyway to get rid of this dialog box please ?

https://image.prntscr.com/image/i_MQsnM4S96HLSglfUciyg.png

![i_MQsnM4S96HLSglfUciyg 1](https://user-images.githubusercontent.com/46560695/61431781-8c58ec00-a926-11e9-9694-a7dfb8c24094.png)

**Comment by inlife** [comment]
Do you have a license file created in your Documents folder?

Look for "ae_render_only_node.txt" on the page for info:
https://helpx.adobe.com/after-effects/using/automated-rendering-network-rendering.html

Are you using windows or macos?

**Comment by whatneuron** [comment]
Do you have a license file created in your Documents folder? I was using a trial which is expired now.

Are you using windows or macos? windows.

Thanks for prompt reply

**Comment by whatneuron** [comment]
it worked thank you!
