### ISSUE TITLE
Allow the use of environment variables in file:// paths

### ISSUE THREAD

**Issue by benbachem** [inlife/nexrender#198]
**Is your feature request related to a problem? Please describe.**
I have this setup:
- An API that generates the nexrender job and passes it to a running nexrender-server
- A rendering node running the nexrender-worker

Currently, I have to hardcode a path like the location of AE project file on the rendering node, in the API that generates the nexrender job and passes it to the nexrender-server.
This doesn't play nice with local testing since I have to change this path all the time. (I'm testing on Mac but the rendering node is running windows, so I can't use the same paths)

**Describe the solution you'd like**
Being able to use a path like file://$NEXRENDER_ASSETS/projects/project2.aep

Then I could just set the $NEXTRENDER_ASSETS environment variable globally on my local machine and on the server and point each of them to their correct directory. This should make working with multiple machines running the nexrender-worker a lot easier.

**Describe alternatives you've considered**
I'm not really sure if there is anything that would solve this otherwise.
If anyone has a better solution, please suggest it.

**Comment by inlife** [comment]
Hey @benbachem 

That is a great suggestion. I like the idea.
Also, if I understand correctly, is possible to use it not only as a global env var, but also on per-worker basis by providing the env var when launching the process.

**Comment by benbachem** [comment]
Yes, I believe that local env vars should work as well.

If you don't mind I will try to implement this as soon as I have time, could be a few days though.

**Comment by inlife** [comment]
Sure, sounds good
