### ISSUE TITLE
Unable to render JPEG sequence

### ISSUE THREAD

**Issue by pradeeprajr93** [Inlife/nexrender#2]
When I render JPEG sequence from nexrender, it is throwing error stating "ENOENT No such file or directory" and showing \path\to\result,jpg

This is happening because jpeg result frames are appended with 000 in the file name.
Help me with this issue.

**Comment by Inlife** [comment]
Hey @pradeeprajr93 
Going to test this case, hold on.

**Comment by Inlife** [comment]
@pradeeprajr93 could you also provide console logs ?
and if you can, project dump. That would be great !

**Comment by pradeeprajr93** [comment]
Here I'm attaching .aepLogs, my After Effects file and snapshot of error I'm getting in command prompt.


[AE 6-24-2016 10-06-17 AM.txt](https://github.com/Inlife/nexrender/files/331207/AE.6-24-2016.10-06-17.AM.txt)

[AEP File.zip](https://github.com/Inlife/nexrender/files/331208/AEP.File.zip)
![capture](https://cloud.githubusercontent.com/assets/9554901/16328088/f20f690c-39f3-11e6-9033-e0a75de035b1.PNG)

**Comment by Inlife** [comment]
Basically, as i understood, rendering successfully ends.
But nexrender thinks other way :D

There is a thing called *validator*, and it fails, expecting single video file to be resulted, but finds there a bunch of images. Im planning to disable validator if "outputExt" == jpeg/jpg. For now at least.
Gonna push changes anytime soon.

>(I'm also having doubt in how to run scripts in AfterEffects before rendering using Nexrender, because I need to run Afterfx -r "path\to\script.jsx" which opens the project and make some changes in composition before rendering. Please help me.)

Main idea of nexrender was not to open after effects app at all.
But, depending on what changes you are wanting to make, you might be able to use built-in function for dynamic data inside project. Here is [docs](https://github.com/Inlife/nexrender/wiki/Project-model#assettype).

Here is the data script, that will be inserted:
```js
var data = {
    "color": [0.63, 0.41, 0.84, 1],
    "style": "techno",
    "desc": "february 2016"
};
var exports = {
    get: function(name) {
        return data[name];
    }
}
```

And here is image how it looks inside of AE.
![image](https://cloud.githubusercontent.com/assets/2182108/16330058/5afbe5c6-39ef-11e6-968b-69d0dcd75f5a.png)

This way you can control timing/properties of most composition elements. But if you need something that only jsx scripting can do, it's better to use only jsx, because, as far as i know, you can even trigger rendering from that thing.

Also, @pradeeprajr93 , could you please answer, why you need to render comp into jpg sequence ? :)

Thank you!

**Comment by pradeeprajr93** [comment]
Rendering into JPEG sequence has a lot more advantages. In case if the project is heavy, we can achieve multi-machine rendering by having network of computers and giving output to a common shared location... please check this [link](https://library.creativecow.net/articles/rabinowitz_aharon/multi_machine_rend/video-tutorial) for better understanding.
And as of now, I'm not clear enough how we can insert dynamic data into After Effects using nexrender (like how we can change text, images, colors). It would be more helpful if you provide some step by step tutorial or blog post that will explain it deeply.

Thanks in advance :)
:+1:

**Comment by Inlife** [comment]
> Rendering into JPEG sequence has a lot more advantages. In case if the project is heavy, we can achieve multi-machine rendering by having network of computers and giving output to a common shared location... please check this link for better understanding.

Yeah, i mentioned that in [readme](https://github.com/Inlife/nexrender#how-it-works). It's just a thing, that you'll gonna need merge/render them anyways later. And that total rendered image sequence folder size is huge :D

My friend and i was also testing other way of doing things: we've rendered 2 h264 pieces, one on his desktop, other on mine. Then we've merged them with a ffpmeg by copying. We've went this way only because our vids were like 1 hour long, in 720p60fps. That means a huge amount of disk space. )
But there were it's own drawbacks though.

> And as of now, I'm not clear enough how we can insert dynamic data into After Effects using nexrender (like how we can change text, images, colors). It would be more helpful if you provide some step by step tutorial or blog post that will explain it deeply.

I was thinking about that for a long time. But now, when i have a reason, i thing im gonna do it! :D

**Comment by pradeeprajr93** [comment]
It's me again :smiley: 
When I post the following JSON
`{
    "template": "FirstDynamic.aep",
    "composition": "DynamicComp",
    "settings": {
        "outputModule": "PSV",
        "outputExt": "JPEG Sequence"
    },
    "assets": [
        {
            "type": "project",
            "src": "http://127.0.0.1:31999/AE/FirstDynamic.aep",
            "name": "FirstDynamic.aep"
        },
        {
            "type": "image",
            "src": "http://127.0.0.1:31999/AE/imgs/HotAirBalloon.png",
            "name": "HotAirBalloon.png"
        }, {
            "type": "script",
            "src": "http://127.0.0.1:31999/AE/test.js",
            "name": "test.js"
        }
    ]
}
`
I'm getting the following error 
![capture](https://cloud.githubusercontent.com/assets/9554901/16344721/9ef40346-3a5b-11e6-87d6-b2700d97d12d.PNG)


For your info, I need to change the source text of the text layer in my comp. Right now I'm referring to `test.js` in my local. I've mentioned the same `test.js` in my JSON with `asset type: script `

Help me with this issue. Thanks is advance :)

**Comment by Inlife** [comment]
@pradeeprajr93, would be great if you'll provide you `test.js`. I think problem is that you trying to execute same code, as you were using a jsx scripts. 
But expressions are different, look at the documentation: https://helpx.adobe.com/after-effects/using/expression-basics.html

But maybe im wrong. Anyways, if AE reports a problem with expression, that means that problem inside that expression. :3

Btw, finally managed to fix(?) your issue, and also update all dependencies. :)

**Comment by pradeeprajr93** [comment]
This is my test.js
`prop = {"name": "PradeepRaj", "desig": "Engineer"};`

**Comment by Inlife** [comment]
well, in that case your code inside expression might look like this:
$.evalFile("C:\\Some\\Path\\That\\Willbe\\Autoreplaced\\test.js"); prop.name

As soon as i download new version of AE (44% now downloaded), i'll be able to show it on your project file.

**Comment by pradeeprajr93** [comment]
Thank you @Inlife Let's make it :+1:

**Comment by Inlife** [comment]
@pradeeprajr93, sorry for a delay.
Well, i checked your project, and seems like everything works fine.

![image](https://cloud.githubusercontent.com/assets/2182108/16355186/f761c8f4-3ab7-11e6-88c2-9243a3f1a48e.png)

And here is contents of the test.js file.
```js
prop = {"name": "Inlife", "desig": "Engineer"};
```

However, this error is not related to nexrender itself. Core of the problem inside AE expression parser.
![image](https://cloud.githubusercontent.com/assets/2182108/16355212/bb2842b8-3ab8-11e6-873d-92f491219002.png)

I've tried to google about that problem. Seems like i cant find anything particular.
What i can do to help you is only to suggest you to "play" with AE expressions, until you succeed :D

**Comment by pradeeprajr93** [comment]
@Inlife Thanks for your time :) Let's see.

**Comment by Inlife** [comment]
@pradeeprajr93 looking forward to see your first video made with nexrender ! 😃

**Comment by Inlife** [comment]
@pradeeprajr93 oh, one other thing i totally forgot about!
**Path auto-replacing for scripts will work only in *.aepx templates.**
So if you want to use expressions, it's better to save projects as *.aepx. !

**Comment by pradeeprajr93** [comment]
Thank you @Inlife I changed to .aepx
But why the project is failing even after creating images in `nexrender/temp/folder/`

**Comment by Inlife** [comment]
@pradeeprajr93 sorry, try update nexrender again with:
```sh
npm install nexrender -g
```
latest version is: _0.4.4_

if there will be errors again, i'm here, and ready to help ! :D

**Comment by pradeeprajr93** [comment]
:sos:  @Inlife help me :P 
I updated to latest nexrender...
But now when I post my JSON 
`{
    "template": "FirstDynamic_.aepx",
    "composition": "DynamicComp",
    "settings": {
        "outputModule": "PSV",
        "outputExt": "JPEG Sequence"
    },
    "assets": [
        {
            "type": "project",
            "src": "http://127.0.0.1:31999/AE/FirstDynamic_.aepx",
            "name": "FirstDynamic_.aepx"
        },
        {
            "type": "image",
            "src": "http://127.0.0.1:31999/AE/imgs/HotAirBalloon.png",
            "name": "HotAirBalloon.png"
        },
        {
            "type": "script",
            "src": "http://127.0.0.1:31999/AE/test.js",
            "name": "test.js"
        }
    ]
}`

I'm getting the following error in API Server (Command prompt)
`TypeError: low(...) is not a function
<br> &nbsp; &nbsp;at Controller.initialize (C:\Users\Pradeepraj.R\AppData\Roaming\npm\node_modules\nexrender\server\controllers\project.js:20:38)
<br> &nbsp; &nbsp;at Controller.create (C:\Users\Pradeepraj.R\AppData\Roaming\npm\node_modules\nexrender\server\controllers\project.js:40:32)
<br> &nbsp; &nbsp;at C:\Users\Pradeepraj.R\AppData\Roaming\npm\node_modules\nexrender\server\routers\project.js:15:33
<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\Pradeepraj.R\AppData\Roaming\npm\node_modules\nexrender\node_modules\express\lib\router\layer.js:95:5)
<br> &nbsp; &nbsp;at next (C:\Users\Pradeepraj.R\AppData\Roaming\npm\node_modules\nexrender\node_modules\express\lib\router\route.js:131:13)
<br> &nbsp; &nbsp;at Route.dispatch (C:\Users\Pradeepraj.R\AppData\Roaming\npm\node_modules\nexrender\node_modules\express\lib\router\route.js:112:3)
<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\Pradeepraj.R\AppData\Roaming\npm\node_modules\nexrender\node_modules\express\lib\router\layer.js:95:5)
<br> &nbsp; &nbsp;at C:\Users\Pradeepraj.R\AppData\Roaming\npm\node_modules\nexrender\node_modules\express\lib\router\index.js:277:22
<br> &nbsp; &nbsp;at Function.process_params (C:\Users\Pradeepraj.R\AppData\Roaming\npm\node_modules\nexrender\node_modules\express\lib\router\index.js:330:12)
<br> &nbsp; &nbsp;at next (C:\Users\Pradeepraj.R\AppData\Roaming\npm\node_modules\nexrender\node_modules\express\lib\router\index.js:271:10)
`

**Comment by Inlife** [comment]
@pradeeprajr93 rescue team arrived !
fixed, and pushed to npm, 0.4.5

**Comment by pradeeprajr93** [comment]
Your team helped me a lot :)

Let me explain what I'm facing right now with **nexrender 0.4.5**

1. I'm running both API server and render node in same machine :+1: 
2. I post my JSON data to server and then I'm restarting my render node :+1: 
3. Render node starts to render and keeps all the images in `nexrender/temp/folder/here` :+1: 
4. After that, I'm getting error in my render node command prompt saying Project Failed :(

Here I'm attaching all the needed files for your reference
![capture](https://cloud.githubusercontent.com/assets/9554901/16356201/dc718300-3aed-11e6-9c22-bf8424069ebe.PNG)
[AE 6-25-2016 3-50-45 PM.txt](https://github.com/Inlife/nexrender/files/333020/AE.6-25-2016.3-50-45.PM.txt)
[FirstDynamic_.zip](https://github.com/Inlife/nexrender/files/333021/FirstDynamic_.zip)
JSON File 
`{
    "template": "FirstDynamic_.aepx",
    "composition": "DynamicComp",
    "settings": {
        "outputModule": "PSV",
        "outputExt": "JPEG Sequence"
    },
    "assets": [
        {
            "type": "project",
            "src": "http://127.0.0.1:31999/AE/FirstDynamic_.aepx",
            "name": "FirstDynamic_.aepx"
        },
        {
            "type": "image",
            "src": "http://127.0.0.1:31999/AE/imgs/HotAirBalloon.png",
            "name": "HotAirBalloon.png"
        },
        {
            "type": "script",
            "src": "http://127.0.0.1:31999/AE/test.js",
            "name": "test.js"
        }
    ]
}
`

**Comment by Inlife** [comment]
ok, @pradeeprajr93, i understood.
as you see, if you look inside `nexrender/temp/folder/here`, all images are successfully rendered and they are lying here.
![image](https://cloud.githubusercontent.com/assets/2182108/16356413/5a2328d0-3adf-11e6-9b46-d8095cc3041b.png)

**So, roughly speaking, it's just error message. You can ignore it.** :D


Meanwhile i will make nexrender able to recognize a jpeg sequence and to copy resulted images to `results` folder. This process might take a few days (few other, non thread related things are popping out).

**Comment by pradeeprajr93** [comment]
Is there any other way to POST my JSON to nexrender...
Right now I'm using "chrome plugin - Postman"
As I'm new to API concepts, help me :D 

Thanks

**Comment by jenishngl** [comment]
You can use jquery

Jenish J

**Comment by Inlife** [comment]
@pradeeprajr93 @jenishngl im pretty sure there is many different POST clients.
You can create interactive shell/batch script using cURL, or somth like that. Or use some programming language to make requests.

Or even use nexrender built-in api from your own node.js application ! :D

**Comment by Inlife** [comment]
Finally has fixed this issue in latest commit.
I will push updates to npm anytime soon. :)
