### ISSUE TITLE
Error message: ENOENT: no such file or directory, stat 'D:\Web\nexpost\temp\Byt2O9uh\result.mp4'

### ISSUE THREAD

**Issue by iadj** [Inlife/nexrender#20]
Cross-posting from https://github.com/Inlife/nexrender-boilerplate/issues/2 (issue also appears with base nexrender)

Running the `nexrender` command with a project in queue causes the following results returned in the CLI:

```
looking for suitable projects...
[Byt2O9uh] setting up project...
[Byt2O9uh] downloading assets...
[Byt2O9uh] renaming assets...
[Byt2O9uh] filtering image assets...
[Byt2O9uh] patching project...
[Byt2O9uh] rendering project...
[Byt2O9uh] verifying project...
--------------------------
[Byt2O9uh] project failed
--------------------------

Error message: ENOENT: no such file or directory, stat 'D:\Web\nexrend\temp\Byt2O9uh\result.mp4'
```

**Comment by southernsun** [comment]
Make sure you set the correct output extension in your settings file.

```
	settings: {
		outputExt: 'avi',
	},

```

**Comment by Inlife** [comment]
> **Note: dont forget to configure AE outputModule to your needs: details. Usually i use h264 output codec and call the outputModule respectively.**

https://helpx.adobe.com/after-effects/using/basics-rendering-exporting.html#output_modules_and_output_module_settings

This configuration gives me mp4 file on the output. If you are expecting other extension, please, set it manually, just like @southernsun mentioned above. :)

**Comment by iadj** [comment]
@southernsun @Inlife Thanks for the answers. This appears to work with the boilerplate (the API & Node give different errors which I will try to figure out).

**Comment by harshthakur92** [comment]
h264 format is not availabel in my after effect 2015 cc . So, i add "DV PAL" to output module and change ext to avi but still it gives error of ENOENT result.avi.

PFA

![untitled](https://user-images.githubusercontent.com/19525609/32509208-aa683eb2-c412-11e7-9804-a5e2c3706108.png)


 "settings": { 
           "outputModule": "DV PAL",
            "startFrame": 0,
            "endFrame": duration,
           "outputExt": "avi"
        },

**Comment by Inlife** [comment]
hey @harshthakur92 
are you sure, that DV PAL will output an avi file ?

that error appears on the last stage, where nexrender tries to verify that file has been successfully rendered
try to look up in that folder, to check was it actually rendered, and what was the resulted file extension, it might be not an avi
in that case, you will need to change the expected outputExt to the one that will be rendered

**Comment by BeatsDJ** [comment]
Getting the same issue, getting ENOENT: no such file or directory - all I did was download the Boilerplate git and tried to run it, did not work. Looks like it doesn't save the rendered file and thus throwing an error saying it didn't find the rendered file.

**Comment by rafaelboschini** [comment]
not works for me too
