### ISSUE TITLE
Change fonts from assets

### ISSUE THREAD

**Issue by franeko** [inlife/nexrender#201]
**Is your feature request related to a problem? Please describe.**
I need to change fonts from template like other properties here:
https://github.com/inlife/nexrender#example-1

**Describe alternatives you've considered**
I have created a `.jsx` script that I can include that will change the font:

```
var proj = app.project;  // get project
var item = proj.item(13) // select composition
var textProp = item.layer("text1").property("Source Text"); // text properties are in this propert
var textDocument = textProp.value;
textDocument.font = "newFont";
textProp.setValue(textDocument);
```

Is it possible to allow changing font from `assets`?

**Comment by inlife** [comment]
Hey @franeko

@brassel, please check this out. This seems like even more advanced case of what you've just done in #190. Seems like a combination of both attributes and properties.

I don't even know how to approach this one. It seems like adding asset type font would be easier, however, there might be other similar cases which won't be covered by this specific addition.

**Comment by brassel** [comment]
So far, we have also changed fonts by using a `jsx` script. I think that now after #190, we could try to approach it directly from the assets part of the job file. We will check it out!

**Comment by franeko** [comment]
Thanks!

Please let me know if that is possible

Captain Fim <notifications@github.com> schrieb am Mo. 22. Juli 2019 um
15:18:

**Comment by brassel** [comment]
So, indeed the required combination of properties and attributes is not working as we would like even with the new approach to change values.
At the moment the answer is sadly, that it can't be done.
However, we would also like to do exactly the kind of thing @franeko proposes here. 
Therefore, we will give the matter some more thought. Maybe we come up with a possibility.

**Comment by brassel** [comment]
We do now have an extension where you can manipulate fonts with assets like this:
``` 
"assets": [    
        {
            "composition": "RenderComp",
            "layerIndex": 1,
            "layerName": "Test",
            "property": "Source Text.font",
            "type": "data",
            "value": "Arial-BoldItalicMT"
        },
        {
            "composition": "RenderComp",
            "layerIndex": 1,
            "layerName": "Test",
            "property": "Source Text.fontSize",
            "type": "data",
            "expression": "2*100"
        }
    ]
```
It works well with this example but we need to test it with the other examples we have before filing a pull request.

**Comment by brassel** [comment]
Created a pull request for the extension. I guess, you will soon be good to go, @franeko!

**Comment by franeko** [comment]
Many thanks @brassel !

**Comment by brassel** [comment]
@inlife merged the request. You should be ready to go, @franeko!

**Comment by franeko** [comment]
Great!

**Comment by brassel** [comment]
Did it work out for you, @franeko?

**Comment by franeko** [comment]
Yes! Thanks a lot

Captain Fim <notifications@github.com> schrieb am Di. 30. Juli 2019 um
22:07:

**Comment by brassel** [comment]
Maybe close this issue, @franeko?

**Comment by franeko** [comment]
Done :)

**Comment by jpaulgale** [comment]
Is is possible to change the font for only part of the text in a layer? ex "These are four words"

**Comment by inlife** [comment]
@jpaulgale it was not possible with AE2023 or lower. And unless Adobe added support for this in AE2024 (I have not tested yet), it is not possible. :(

**Comment by jpaulgale** [comment]
@inlife sincerely appreciate all your work on this invaluable tool. For what it’s worth, I’m eyeing this solution from [atila32 on Reddit](https://www.reddit.com/r/AfterEffects/comments/xinjnv/how_to_have_two_different_font_style_in_one_text/)

may just need to figure out how to do two different layers and write an expression that makes it look as though they are one (aka layer2 follows the spacing of layer1’s final character in the exact right spot as if it was a part of it)

**Comment by inlife** [comment]
Ah @jpaulgale, in that case all you need is [the doc](https://ae-scripting.docsforadobe.dev/), a bit of math, and a lot of patience 😄

**Comment by jpaulgale** [comment]
lol help me god
