### ISSUE TITLE
Worker error stops execution

### ISSUE THREAD

**Issue by Candlelight-video** [inlife/nexrender#202]
**Describe the bug**
When a false job is submited via the api and the worker 
The worker then quits 

**Information about environment**
 I use the latest version. MY setup is the following 
I have a server running on local host and one worker also on my local machine 
then i submit jobs via Postman( just like curl) 

**Expected behavior**
I think that the Worker should mark the job as failed and then continue with the next 

**Screenshots**

```
[ob_lrXXzX5PH2ED9ZS72s] setting up job...
[ob_lrXXzX5PH2ED9ZS72s] working directory is: C:\Users\Jonas\AppData\Local\Temp\nexrender\ob_lrXXzX5PH2ED9ZS72s
[ob_lrXXzX5PH2ED9ZS72s] downloading assets...
(node:45684) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'd:\Nexrender\template.asep'
(node:45684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:45684) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mattmalec** [comment]
> (node:45684) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'd:\Nexrender\template.asep'

This isn't a bug -- it's a typo on your end. Nexrender is looking for `template.asep` since that's exactly what you typed, but rather, it evidently should be `template.aep`. `template.asep` doesn't exist hence the `no such file or directory`.

I highly recommend reading the stacktrace nexrender provides. It's very helpful.
-M

**Comment by Candlelight-video** [comment]
i know that there is a spelling error thats not the bug or the problem the problem is that the worker then terminates in my opinion it should mark it as error and then go on with the next job

**Comment by mattmalec** [comment]
There's an option command line argument you can define for the worker. Add `--stop-on-error=false` as an argument. That should continue regardless if there's an error.

**Comment by inlife** [comment]
this is an additional issue related to #184

**Comment by HarryLafranc** [comment]
> There's an option command line argument you can define for the worker. Add `--stop-on-error=false` as an argument. That should continue regardless if there's an error.

I tried that but unfortunately, the worker still crashes.

**Comment by inlife** [comment]
I can't say for sure

**Comment by HarryLafranc** [comment]
Maybe this ? https://github.com/inlife/nexrender/blob/0591b8dca4c2fd7377b4d962d0318ae526872eb1/packages/nexrender-worker/src/bin.js#L161

It should be `settings['stopOnError'] = settings['stopOnError'] == 'true';` right ?

**Comment by masaldana2** [comment]
same
