### ISSUE TITLE
Upload action crashes 

### ISSUE THREAD

**Issue by Candlelight-video** [inlife/nexrender#203]
**Describe the bug**
i use the action upload as postrender action the provier is ftp 
i then add a job with this action to the que and a worker starts working on it 
it renders fine the after starting action_upload action it just quits the worker and the job wont get marked as finished 
but the upload works 
**Information about environment**
Recent version and a normal ftp server 

**Expected behavior**
Job should be marked as done and the worker shouldn't quit 
**Code**
` "actions":{
          "postrender": [
               {
                  "module": "@nexrender/action-upload",
                "input": "result.avi",
                "provider": "ftp",
                "params": {
                    "host": "clf-studio.de",
    				"port": 21,
					"user": "render",
    				"password": "E#c78bw1"
                }
              }
          ]
      }`

**Comment by mattmalec** [comment]
This type of problem would 100% throw a stacktrace. If you run the worker in the foreground (i.e. starting the worker by manually typing in the command into Command Prompt), the worker will still throw an error, but not completely close out of that Command Prompt instance. Once this error occurs again, please write me back here with the corresponding stacktrace. We'll be able to further dive into this problem then.
-M

**Comment by Candlelight-video** [comment]
thats the wierd thing there was no stacktrace .... it was just the starting message and then i closes

**Comment by mattmalec** [comment]
Does it completely exit the Command Prompt instance that was running the worker?

**Comment by Candlelight-video** [comment]
no the terminal stays open but its back at C:// without anything

**Comment by mattmalec** [comment]
That’s very odd. I had the same issue with S3. I ended up writing a separate piece of software in Java to upload. Seems as if this module has some issues.

**Comment by Candlelight-video** [comment]
the wierd thing that the upload works but then after that it crashes

**Comment by inlife** [comment]
that is weird
hey, @zuntah, have you had any similar occurrences by any chance?

**Comment by zuntah** [comment]
Hi,
I have no error when trying this module on Mac.
That's weird.
The weirder is that there is no exception being thrown Because, at nexrender-action-upload/index.js line #30, there is "throw e".
And inside the FTP-provider, there is no exception handling.

**Comment by Candlelight-video** [comment]
I compared the upload action /ftp provider and the copy action and i think the thing that is missing ist that after the upload the promise get's resolved

**Comment by chrstnsmthng** [comment]
I had the same thing happen on Windows 7 while using the worker with FTP-upload

**Comment by inlife** [comment]
Hey guys,

Added missing promise rejection and resolving for FTP module in `v1.8.3`, please check if that resolves the issue.

Cheers!

**Comment by chrstnsmthng** [comment]
Now when it finishes it says cleaning up (which is new), but when it tries to take another job it crashes with "FetchError: request to {ip}/api/v1/jobs/{uuid} failed, reason: connect ETIMEDOUT {ip}"
