### ISSUE TITLE
Nexrender doesn't throw error on file missing in template

### ISSUE THREAD

**Issue by TimP4w** [inlife/nexrender#206]
**Describe the bug**
Nexrender Core doesn't return error when AE is unable to render because of a File Not Found. 
The video is then accepted as rendered but is just a black screen.
In order to reproduce simply render a video where an image placeholder is missing from the disk.

AE logs show:
```
PROGRESS:  Total Time Elapsed: 0 Seconds
WARNING:After Effects warning: logged one error  error: Unable to Render: File Not Found C:\Users\...\(Footage)\_Ressourcen\Bilder\Platzhalter Bild.jpg
```

**Information about environment**
* Which version of nexrender are you using?
Latest
* What kind of the setup do you have? (server+worker or cli)
Core
* Are you using pre-built binaries or globally installed npm packages?
NPM
* Which kind (and version) of operating system you are running it in?
Latest Win 10, Latest AE

* Any additional information that might be helpful

**Expected behavior**
Nexrender should throw / log an error or warning.

**Screenshots**

**Comment by inlife** [comment]
Acknowledged, will be fixed alongside other issues related to #184

**Comment by AgenteDog** [comment]
This issue still happens. I would personally love if this bug is fixed.

**Comment by inlife** [comment]
Hey @AgenteDog 
Unfortunately still hadn't had a chance to work on the error handling stuff 😞
