### ISSUE TITLE
A way to pass variables to jsx from command line.

### ISSUE THREAD

**Issue by Ruslan-F** [inlife/nexrender#207]
Hello. Thanks for awesome repo!
As the title say - can you, please, help me to understand the best way to pass variables to jsx script?
I need to use nexrender-worker + nexrender-server.
Nexrender reads file.json, which in turn applies jsx script. And jsx reads another json file (generated programmatically) to get some vars from it. Path to this file is defined in jsx code and I need to update it somehow..
So nexrender's file.json and script.jsx is a static assets with same path every time, but the templates it's applied to and input variables are different.
Atm the only solution I see is to generate jsx for every rendering, with different target vars file path..
Is there no better way?
Thanks again.

**Comment by inlife** [comment]
Well, job json doesn't need to be static. The whole idea is that you can push a dynamically generated json onto the server via API, and the worker will just pick it up and use it.

Just take a look at the API section: https://github.com/inlife/nexrender#using-api

**Comment by Ruslan-F** [comment]
Understood, thanks.
