### ISSUE TITLE
 How to use output module templates

### ISSUE THREAD

**Issue by brassel** [inlife/nexrender#208]
We have defined an output module template in After Effects but somehow aerender cannot find it. What are we doing wrong?

**Comment by brassel** [comment]
Searching the web I found the rumor that aerender in render-only mode (if that is the name) cannot make use of custom output modules. Is that true?

**Comment by inlife** [comment]
The only reason I see that it wouldn't work for you, as if they were launched from different user accounts on your system. Since I know that After Effects stores the outputModule settings somewhere in the AppData or Documents folder iirc.

And on the versions that I at least tested it worked fine. Maybe they changed something in the way it works?

**Comment by brassel** [comment]
We have definitely used the same user account. Do you know if we can directly reference a file from the directory you mention? Or copy a file somewhere to make aerender find it?

**Comment by inlife** [comment]
In my case (win) settings are located at:
C:\Users\<USER>\AppData\Roaming\Adobe\After Effects\15.0\Adobe After Effects 15.0 Prefs-indep-output.txt

On mac not sure, probably somewhere in Application Support folder.

------

Another possible way of dealing with that would be actually to involve scripting. I've created an issue while back #179.

**Comment by brassel** [comment]
Yes, I think that being able to deal with output modules without needing to open the AE gui would be a great step forward. But do you have an idea how to approach this?

**Comment by brassel** [comment]
So, we have by now figured it out. Near to what @inlife suggested, it was not a change of user profile but a change of the language. The AE GUI always started in English while the `aerenderer` started in German. Changing the language of Windows to English in general fixed the issue. I guess strongly that changing the locale information of the shell would have worked also.

**Comment by inlife** [comment]
That is actually unexpected, at least to me. Gotta research more on that topic.
