### ISSUE TITLE
Replacing Adobe Illustrator assets

### ISSUE THREAD

**Issue by byumark** [inlife/nexrender#209]
I have a composition of Adobe Illustrator layers. Is there a way to replace the Adobe Illustrator asset once and have it trickle down to all the layers or do I need to replace each layer individually?

**Comment by inlife** [comment]
Hello @byumark 

Honestly, never had any experience with anything like this, so hopefully, somebody from the community will be able to help you out on that one.

**Comment by hdngr** [comment]
This seems to work - treating `.ai` file like any other image asset.  I have not yet explored what nexrender is doing under the hood, why it works would be a good question for @inlife.

```json
{
    "template": {
        "src": "file:///templates/test.aep",
        "composition": "Render Comp"
    },
    "assets": [
        {
            "src": "file:///assets/Envato Logo.ai",
            "type": "image",
            "layerName": "Envato Logo.ai"
        }
    ],
    "actions": {...}
}
```
