### ISSUE TITLE
Job: default options and logger

### ISSUE THREAD

**Issue by Dezzymei** [inlife/nexrender#210]
In stead of having to init the rendered and add the setting for a logger, can we make it so that by default the logger is the console and the settings are optional for the render function? 

e.g.

```
const { init, render } = require('@nexrender/core')

const settings = init({
    logger: console,
})

const main = async () => {
    const result = await render(/*myJobJson*/, settings)
}
```

Would go to
```
const { render } = require('@nexrender/core')

const main = async () => {
    const result = await render(/*myJobJson*/)
}
```

**Comment by inlife** [comment]
Actually yea, it is a good suggestion, I think we can.

**Comment by benbachem** [comment]
Was this ever implemented?
Otherwise I could implement it in https://github.com/inlife/nexrender/issues/248.

**Comment by inlife** [comment]
@benbachem no, it wasn't. And yes, you could as well try, that would be very great.
