### ISSUE TITLE
Where to find suitable templates ?

### ISSUE THREAD

**Issue by whatneuron** [inlife/nexrender#213]
I have been searching for weeks now, and about to give up which is why I am here asking this question.

I want a template with 100 pictures or video placeholders.

Once I have this template, here is what I am expecting...

- Put images I have into image001.jpg, image002.jpg, image003.mp4(it's a clip) .... image100.jpg (extension doesn't matter I can change it)  into template folder

- Use nexrender  aerender to create a slideshow type video for me

I can find numerous templates online for AE slideshow but most of them expect me to open the project in AE and make changes...

Ideally I want to set length of each slide.

Please assist as I am looking for so long without any fruitful result, maybe I am using wrong terminology to search.

Thanks in advance.

**Comment by inlife** [comment]
Not sure if I can help you with this one. I guess this one as well is more or less a general question for the community.

**Comment by earsneyes** [comment]
@whatneuron you need someone who can prepare such template for your needs. An motion designer with AE expression knowledge should be able to do this. You will need a working nexrender pipeline as well.
