### ISSUE TITLE
Does nexrender now supports nested compositions ?

### ISSUE THREAD

**Issue by whatneuron** [inlife/nexrender#214]
Does nexrender now supports nested compositions ?

If not any alternatives ? Thanks

**Comment by inlife** [comment]
It should if I remember correctly, however, setting up the options for that might be tricky. Current composition-layer provider model can be the cause.

**Comment by whatneuron** [comment]
Here is the example minimal json, it throws that TEXT 01 is not present in composition "main", problem is that I have nested compositions like this,

main > subcomp1 > TEXT 01
main > subcomp2 > TEXT 02 
.....
main > subcompN > TEXT N

Problem is that nested composition isn't working with the following json data, can I use any attribute or something to make it work ? thanks in advance...

{
    "template": {
        "src": "http://example.com/assets/myproject.aep",
        "composition": "main"
    },
    "assets": [
        {
            "type": "data",
            "layerName": "TEXT 01",
            "property": "Source Text",
            "value": "Hello world"
        }
    ],
    "actions":{
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "encoded.mp4",
                "output": "d:/mydocuments/results/myresult.mp4"
            }
        ]
    }
}

**Comment by inlife** [comment]
By default, nexrender picks up compositions that are only in the main composition (the one you've provided in the template). To override that you can put asset.composition: "*" for each respective asset.

So it would look this way:

```json

    "assets": [
        {
            "composition": "*",
            "type": "data",
            "layerName": "TEXT 01",
            "property": "Source Text",
            "value": "Hello world"
        }
    ],
```

This requirement might change in the future versions
