### ISSUE TITLE
How does nexrender interpret prerender scripts?

### ISSUE THREAD

**Issue by brassel** [inlife/nexrender#216]
Up to now I thought that nexrender would simply rely on node.js to execute scripts like those in prerender actions. But now we have a script which runs as expected on nodes but does not run on nexrender. In a gist it is:

```
const url = require('url');
var path = url.fileURLToPath("file:///C:/Video/Projects/test/xyz.mp4")
console.log(path)
```

And the function `fileURLToPath` is not defined in nexrender but in normal node. What are we doing wrong?

**Comment by brassel** [comment]
By now I have found out that on my machine nexrender is running version `v10.4.1` while my machine provides `v11.6.0`.

**Comment by inlife** [comment]
This might be the reason

![image](https://user-images.githubusercontent.com/2182108/62551177-3071eb00-b874-11e9-8a6b-a354d1848edb.png)

**Comment by inlife** [comment]
So, in case you have nodejs already installed on your machines, you can install and directly use nexrender npm packages. The binary files are compiled to be fully self-sustained, they contain the nodejs runtime for specific platform inside each one of them

**Comment by brassel** [comment]
> This might be the reason
Yes, that is the reason for sure!
> The binary files are compiled to be fully self-sustained, they contain the nodejs runtime for specific platform inside each one of them
What controls the version of the nodejs runtime being included?

**Comment by inlife** [comment]
These badboys: https://github.com/inlife/nexrender/blob/master/packages/nexrender-worker/package.json#L12-L16

Those pkg options are evaluated when the pkg command is called in the general package: https://github.com/inlife/nexrender/blob/master/package.json#L27

And that one is called by travis when a new git tag is pushed to the repository

**Comment by inlife** [comment]
The nodejs version used for the packaging was supposedly a LTS release, so should've been a valid choice in regards of stability.

As I said, you can simply install needed packages in case you have nodejs on the platform:

```
$ npm install @nexrender/worker @nexrender/action-encode -g
```

And then run worker as always
```
$ nexrender-worker --help
```

**Comment by brassel** [comment]
Thanks for the info, @inlife! We now added a rudimentary function for `fileURLToPath`which will automatically switch to the "real one" when available.

**Comment by brassel** [comment]
> The nodejs version used for the packaging was supposedly a LTS release, so should've been a valid choice in regards of stability.

So, LTS seems to be 10.16.1

https://nodejs.org/en/

But as posted above, the version is 10.4.1.
Any plan to move to the current LTS?

**Comment by inlife** [comment]
Yea, eventually I plan to update it, my recent attempt led to errors with some windows clients.
