### ISSUE TITLE
Windows: ExtendScript: cmd /c curl stops before finishing

### ISSUE THREAD

**Issue by Ruslan-F** [inlife/nexrender#218]
Not sure this is the right place to ask it, but still you may know the answer. Thanks in advance.
- The jsx executing during rendering process need to download a video file.
- The command for it looks like:
`system.callSystem('cmd /C \"curl ' + url + ' > ' + tmpFilePath + ' --trace ' + TMP_SUBDIR + 'curl.log.txt\"');`
- When I run the output of this concatenation (via win+r) - if works fine. Curl downloads the file and closes the cmd window.
- But when the command is executed in nexrender process it's just create an empty output vide file (0 bites) and then curl fails.
- The last lines of curl trace is:
> == Info: Failed writing body (0 != 1432)
> == Info: Marked for [closure]: Transfer returned error
> == Info: multi_done
> == Info: stopped the pause stream!
> == Info: Closing connection 0
> == Info: The cache now contains 0 members

..so I presume aerender just systemCalls my command, but do not wait untill it's finished and kills (?) it.
- Also tried `/K` marker instead of `/C` - same story.

Thaks for any help.

**Comment by inlife** [comment]
Can you please explain what is the intention of this curl instruction?

**Comment by Ruslan-F** [comment]
I need one of my project layers to have dynamic src video file.
Before rendering - the project's total duration must be updated, so this dynamic video can fit in.
I know .json `assets` prop allow to manipulate sources at some level, but footage sources defined by json do not get their duration updated in aep - so if I try to do something like:
`app.project.items[%dynamic video item%].duration` - I'll get old value, even with the actual src file changed by json data.
And the only way I found to bypass it - is to replace item src by jsx itself (`.replace(new File('local/path')) - then duration get its update.
JSX obviosly has more controls over the aep and storing variables inside it looks more logical..
But I'm new to ExtendScript and AAE, so I'm afraid I may walk on a rake or invite bicycle now.

**Comment by inlife** [comment]
So the problem is to figure out total project duration?
If that is the case, I can suggest another way. Just set the whole total composition and layer times to some big value, like 2 hrs lets say. And then when you are preparing to render the composition, use job.settings.frameEnd to set up the finishing frame. I did that similarly in the old boilerplate project: https://github.com/inlife/nexrender-boilerplate

**Comment by Ruslan-F** [comment]
Thanks for the hint. Tho I don't understand how frameEnd can help here anyhow.
>So the problem is to figure out total project duration?
The problem is to figure _dynamic video file_ duration, so I can change project total duration accordingly..
So there's no way to tell aerender to wait for cmd to finish curl before killing it?
In that case the only way to handle my problem is to get dynamic video duration by other means before nexrender starts at all. And pre-define it in jsx as const before it executes.

**Comment by Ruslan-F** [comment]
The problem was in ` > `. Should'v used `--output` instead.
