### ISSUE TITLE
API Server + Node: No such file or directory template.aep / result.mp4

### ISSUE THREAD

**Issue by iadj** [Inlife/nexrender#22]
I'm trying to render a simple project, without any custom data. using the API Server with a render node (same machine).

I run the API server and send a POST request to it containing the following Project model:

```
{
    template: 'template1.aepx',
    composition: 'mainComp',
    type: 'default',
    settings: {
        outputModule: 'Lossless',
        outputExt: 'avi',
        startFrame: 0,
        endFrame: 100
    }
}
```

I have a render node directory which has the directory `templates`, containing `template1.aepx`.

When I run the render node with this data, I get the following error:
`Error message: ENOENT: no such file or directory, lstat 'D:\Web\nexrender-node\templates\template.aep'` 

So I tried saving a copy of the .aepx project as template.aep in `templates`. This results in:
`Error message: ENOENT: no such file or directory, stat 'D:\Web\nexrender-node\temp\HJ9-diFh\result.mp4'`

The output module and extension are correct (tested in `nexrender-boilerplate`).

What am I doing wrong?

**Comment by Inlife** [comment]
hey

are you sure that you were POSTing a valid json model ?
i've tried to copypaste your code (it has no "" for property names)

![image](https://cloud.githubusercontent.com/assets/2182108/18596097/41061e2c-7c50-11e6-9559-1b4ffbdb1e91.png)

the result as you see is an empty project model
might this be the issue ?

**Comment by iadj** [comment]
@Inlife JSON object keys don't have to be strings, but I just tried using apostrophes and got the same error.

**Comment by Inlife** [comment]
you can use this tool to validate json
https://jsonformatter.curiousconcept.com/

also, just to be sure, could you please send a contents of your db.json file ?

**Comment by iadj** [comment]
@Inlife Oh yeah there's definitely something wrong with the object being posted:

```
{
  "projects": [
    {
      "project": {
        "uid": "By5kphth",
        "state": "queued",
        "template": "template1.aepx",
        "composition": "mainComp",
        "type": "default",
        "settings": {
          "outputModule": "Lossless",
          "outputExt": "avi",
          "startFrame": "0",
          "endFrame": "100"
        },
        "errorMessage": "",
        "ticker": "",
        "api": "",
        "error": ""
      },
      "uid": "H1c162Kh",
      "state": "queued",
      "createdAt": "2016-09-16T18:41:37.901Z",
      "updatedAt": "2016-09-16T18:41:42.324Z",
      "type": "default",
      "assets": [],
      "template": "template.aep",
      "settings": {
        "outputModule": "h264",
        "outputExt": "mp4"
      },
      "composition": "comp1",
      "actions": [],
      "errorMessage": "ENOENT: no such file or directory, lstat 'D:\\Web\\nexrender-node\\templates\\template.aep'"
    }
  ]
}
```

It may have to do with how I'm using `request` to post the sample data:
```
const Project = require('nexrender').Project;
    let project = new Project({
    "template": 'template1.aepx',
    "composition": 'mainComp',
    "type": 'default',
    "settings": {
        "outputModule": 'Lossless',
        "outputExt": 'avi',
        "startFrame": 0,
        "endFrame": 100
    },
});

request({
    uri: "http://localhost:3000/api/projects",
    method: "POST",
    form: {
        project
    }
}, function(error, response, body) {
    console.log(body);
});
```

**Comment by iadj** [comment]
@Inlife Got it! Obviously the `project` variable shouldn't be nested inside another json object in `form: { project }` (should be `form: project`). Thank you for the help!

**Comment by Inlife** [comment]
lol, glad to help! 😄

**Comment by iadj** [comment]
@Inlife The simple request script might be a good example for the wiki on how to post data to the api. I also didn't see I had to post to `/api/projects` route, figured that out investigating the api source.

**Comment by Inlife** [comment]
>The simple request script might be a good example for the wiki on how to post data to the api. 
Good idea, never thought about posting it via request tho.
Also, why you even need this if you can use api client ! 😄 
https://github.com/Inlife/nexrender#usage-render-network--nodejs-api-wrapper

> I also didn't see I had to post to /api/projects route
Same here, i totally forgot which route is where. 
Im going to post it somewhere in docs. 👍 

Thank you for the interest in the project! :)

**Comment by iadj** [comment]
@Inlife I didn't even see there was an API wrapper like that! Could use a separate page on the wiki :)
But the reason I wanted to use a 'real' POST request was because I want to test interaction with back-ends in different languages instead of just NodeJS.

**Comment by Inlife** [comment]
Yea, ill try to post it some day. I even created dedicated wiki page back in february.
But, obviously, something gone wrong :D

> 'real' POST request in different languages instead of just NodeJS.

I suppose it should work just fine )
I use Postman app in most cases.

>This project is amazing!

ohh, thank you )))
