### ISSUE TITLE
Nexrender broke after effects

### ISSUE THREAD

**Issue by nickyromeijn** [inlife/nexrender#220]
Hello,

I've tried using the @nexrender/core package with a node app. When I executed it it asked for sudo permissions to install a patch for starting up the render engine. However now I am unable to start up after effects as I normally did. I just get an almost empty screen with which shows "render queue" on top. Most of the applications options from the toolbar are grayed out as well. I was using after effects CC 2019.

Anyone knows how to revert this / fix this?

**Comment by nickyromeijn** [comment]
Nevermind, I just found out it was due to the ae-render-only license.

**Comment by inlife** [comment]
Hello @nickyromeijn 

The only change nexrender does to the After Effects is patching the commandLineRenderer.jsx file:
https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/helpers/patch.js

As you can see from the source code, the backup file is stored to the:
```js
const backupFile   = path.join(afterEffects, 'Backup.Scripts', 'Startup', targetScript)
```

You can copy that file back to the original position to revert everything.
No additional changes are made from the nexrender to the any file in After Effects folder.

**Comment by inlife** [comment]
>Nevermind, I just found out it was due to the ae-render-only license.

Oh I see, good to know.

**Comment by nickyromeijn** [comment]
Thanks for the quick response by the way; reading the documentation the we're very enthusiastic about the functionality. I think I've set everything up properly on my machine but it appears to never get past the "rendering job" part. Any idea what might be the cause of this?

```
[Xabvdv1Dz-ldOqxdPT1Es] setting up job...
[Xabvdv1Dz-ldOqxdPT1Es] working directory is: /var/folders/1x/1_lqcpwd30b916vyh6hxb9cc0000gn/T/nexrender/Xabvdv1Dz-ldOqxdPT1Es
[Xabvdv1Dz-ldOqxdPT1Es] downloading assets...
[Xabvdv1Dz-ldOqxdPT1Es] applying prerender actions...
[Xabvdv1Dz-ldOqxdPT1Es] running script assemble...
[Xabvdv1Dz-ldOqxdPT1Es] rendering job...
```

**Comment by inlife** [comment]
check the working directory, if the file output file was created
also check for log file in the folder above, it has current project id in it's filename

**Comment by nickyromeijn** [comment]
Ah thanks, I found the log files and working dirs. It appears it isn't even able to start aerender.

```
aerender version 16.1.2x55
PROGRESS: Launching After Effects...
aerender ERROR -1712: AESend failed to send apple event at line 771
```

**Comment by NarHakobyan** [comment]
@nickyromeijn I have this problem too, how are you fixed it?

**Comment by nickyromeijn** [comment]
I never fixed it actually. Don’t use my Mac anymore for rendering. We now use a windows server for rendering.

**Comment by NarHakobyan** [comment]
sorry, this question is not related to this topic, do you have any documentation about how to install after effects on the server?

**Comment by imgntn** [comment]
i ran the cli as admin and now my AE is stuck at the "render queue" window also.  i tried reverting to the Backup.Scripts version of `commandLineRenderer.jsx `  but haven't been able to get it to work so far

**Comment by imgntn** [comment]
okay, sorted it - to get back to normal, you've also got to remove the `ae_render_only_node.txt` file from your documents folder.  

https://helpx.adobe.com/after-effects/kb/accidental-render-node-launch-ae.html

is it expected that you can't run the CLI and use AE as normal on the same machine?  have i misunderstood or set something up wrong?  

best!

**Comment by Srinivasb6** [comment]
By Deleting ae_render_only_node.txt file , After Effects Will Work .

**Comment by TheBlackHacker** [comment]
> By Deleting ae_render_only_node.txt file , relaunch After Effects it Will Work .

Save my day <3
