### ISSUE TITLE
Where is the Footage files in the job?

### ISSUE THREAD

**Issue by Mrzy** [inlife/nexrender#222]
I am wondering how to specific Footage files needed by an .aep file in the job json?

I know that the .aep file and Footage files must be in a same directory, but in my situation, my .aep file and footage as a zip file in the remote AWS S3 server, however, the render server（nexrender-worker） is another machine,   I commit a render task via nexrender-api(HTTP) to the render machine, that's the question: I don't know how to transfer the footage files to the render machine, the footage files is essential, please help me.

**Comment by inlife** [comment]
Well, since nexrender allows you to use http/https/ftp/s3/file protocols to deliver assets you actually have multiple ways you could deliver them on the actual rendering machine.

The simplest would be just serving your files from a centralized web server via http. Or maybe you would like to use aws s3 to deliver assets.

There are many different ways.

**Comment by Mrzy** [comment]
Thank you for your reply!
Perhaps my poor english, it seems that you didn't understood my doubt.
I knew it supports multiple protocols to deliver assets to server.

In my situation:
I have a AE template file, the .aep file references a footage directory, if the footage directory missed, it will fail when use nexrender to open the aep, so I have to figure out the way to deliver the footage directory.

The footage directory includes hundreds images assets, however, I just need to replace a few images, but it seems that I have to let all the images with the layerName/layerIndex  to a job json, it's  poor efficiency.
Is there a better way? I hope that I can deliver the footage as a entry(zip) to deliver to server.

**Comment by inlife** [comment]
Unfortunately no, you either need to provide all assets via nexrender, or use a custom solution to deliver those onto your machine.

**Comment by Mrzy** [comment]
Thank you for your reply!
