### ISSUE TITLE
Couldn't find layer by layerName?

### ISSUE THREAD

**Issue by Mrzy** [inlife/nexrender#224]
Each composition includes multiple layer or some embed child-compositions, once a layer was replaced in a child-composition, it will throw a error: Cound't find any layers by provided name inside a composition.

I found a related method from 'nexrender-core/src/assets/nexrender.jsx':
![image](https://user-images.githubusercontent.com/3367805/62917310-59dbcb00-bdce-11e9-8cc3-8b4034f850a8.png)

Following the method, it doesn't match layerName with recursion, how should i do?  Please help me!

**Comment by vc60er** [comment]
I had the same problem . 😢😢😢

**Comment by vc60er** [comment]
like this file [Hanging Photo Gallery（已转换） 副本 副本.aepx.zip](https://github.com/inlife/nexrender/files/3495582/Hanging.Photo.Gallery.aepx.zip)

**Comment by inlife** [comment]
Which version of the nexrender are you using?

**Comment by vc60er** [comment]
1.8.0

**Comment by inlife** [comment]
Have you tried using 1.8.1 ?

**Comment by vc60er** [comment]
ok, i will have a try

**Comment by vc60er** [comment]
that's right, use version 1.81 has fixed my issues
thanks @inlife

**Comment by Mrzy** [comment]
Wonderful!
