### ISSUE TITLE
How to use onChange without nexrender/api?

### ISSUE THREAD

**Issue by Ruslan-F** [inlife/nexrender#225]
I probably misunderstood something, but don't know what..

It's written in readme that with @nexrender/api I can just do this:
```
result.on('created', job => console.log('project has been created'))
result.on('started', job => console.log('project rendering started'))
result.on('finished', job => console.log('project rendering finished'))
result.on('error', err => console.log('project rendering error', err))
```

But I communicate with nexrender-server via http, using php>guzzle>curl.
So in my case - pure json string is sent in request body, which can't hold functions in it..
Tried in same way it's in docs:
```
{
    "template": {
       ...
    },
    "assets": [],
    "actions": {
        "prerender": [],
        "postrender": [],
    },
    "onChange": function(render) {
        console.log(render.uid)
        console.log(render.state)
    },
    "onRenderProgress": Function
}
```
- and get invalid json error in response.

Thanks for any help.

**Comment by inlife** [comment]
Well, you see the api module has a `polling` mechanism
https://github.com/inlife/nexrender/blob/master/packages/nexrender-api/src/job.js#L3-L30

The simplest way to explain is that it just constantly fetching update about a job.
