### ISSUE TITLE
Should `selectCompositionsByName`be called for every matching composition?

### ISSUE THREAD

**Issue by brassel** [inlife/nexrender#226]
The comment about nexrender function `selectCompositionsByName` says that the function should be called for *every* composition matching the name but the code only matches the first. 
If every composition should be matched, the `return` needs to be moved to outside the for loop.

**Comment by inlife** [comment]
Indeed, going to push a fix.

**Comment by brassel** [comment]
Thanks!

**Comment by inlife** [comment]
Pushed update with `v1.8.2`
