### ISSUE TITLE
How to set options such as resolution, fps.etc during the rendering? 

### ISSUE THREAD

**Issue by Mrzy** [inlife/nexrender#228]
I know nexrender provides a postrender module for convert the result video, however, i hope that it can reduce the rendering time cost with lower video encode options during the rendering, how should i do?

**Comment by inlife** [comment]
You can either set up different settings for your composition in the AE template, or try to use different settings for Output Module. All of this can only be done from After Effects GUI only, as far as I know.

**Comment by Mrzy** [comment]
Thanks@inlife. Good answer!
