### ISSUE TITLE
Inconsistency in init method usage

### ISSUE THREAD

**Issue by raaymax** [inlife/nexrender#229]
[link to code](https://github.com/inlife/nexrender/blob/c04b64bd04abbac3f80065aa910b004414d4a067/packages/nexrender-core/src/index.js#L43)
**Describe the bug**
The function is not asynchronous and in the positive case is returning a simple object but the error is returned as a promise.

**Expected behavior**
The error should be thrown by "throw".

**Comment by inlife** [comment]
Pushed patch `v1.8.4` with fix. Thanks!
