### ISSUE TITLE
Customizing nexrender-node

### ISSUE THREAD

**Issue by iadj** [Inlife/nexrender#23]
I want to try to make some changes/improvements to nexrender-node, but I'm not too familiar with globally installed CLI node applications. After installing nexrender to a directory and making some changes (to i.e. `tasks`), how do I get nexrender-node to use my changes? I don't necessarily need to globally install my changed version.

**Comment by iadj** [comment]
Figured it out: `node cli.js --renderer`

**Comment by Inlife** [comment]
yep :D
btw, what changes did you make, im very curious ? 😊

**Comment by iadj** [comment]
@Inlife Trying to make a JPEG Sequence project render in parallel with multiple nodes, and zipping each successful render. The ZIPs should then be sent to a 'master' node to compress into a video format!

**Comment by iadj** [comment]
@Inlife Maybe using API ` project.on('finished'...` is a better way to achieve this?

**Comment by Inlife** [comment]
i think you war is the good way
i thought about this way of achieving multi-sequence rendering

ill be glad to see that as a pull request, if you want to ! :D

**Comment by iadj** [comment]
@Inlife If I can get it to work :D

**Comment by Inlife** [comment]
the idea is that you are creating few projects at runtime, and one of them is "master"
he will have it's status set to "waiting" for example (this way it wont be pulled by render-node)
as soon as all projects will finish rendering (you can have a `Promise.all` callback using api)
you can change status to "queued" and it will be handled by one of the rendernodes

sharing of images can be achieved by using more simple ways, for example: native os shared folder
or shared folder via some of the programs such as bittorrent-sync, or dropbox, or smth like that

thats what im thinking :)

**Comment by southernsun** [comment]
for sharing images: just use npm connect and serve-static to quickly setup a http server to host your files.. that's what i'm doing for my test environment.

var connect = require('connect');

var serveStatic = require('serve-static');
connect().use(serveStatic(__dirname)).listen(8080, function(){
    console.log('Server running on 8080...');
});

**Comment by Inlife** [comment]
@southernsun there is also that (imo more convinient) tool:
https://www.npmjs.com/package/http-server
you can start server like this:
`$ http-server -p 8080`
