### ISSUE TITLE
Prohibited file name in action-upload

### ISSUE THREAD

**Issue by gvjonjones** [inlife/nexrender#230]
Hi,

I'm using action-upload to send to a standard FTP server but I receive the following error when using it:
`Error: Error loading postrender module @nexrender/action-upload: Error: Prohibited file name: C:\Users\User\AppData\Local\Temp\nexrender\U7GWw0F2YAEUhXCfGFfM8\encoded.mp4`

My post render actions are as follows:
```"actions":{
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4"
            },
            {
                "module": "@nexrender/action-upload",
                "input": "encoded.mp4",
                "provider": "ftp",
                "params": {
                    "host": "domain.com",
                    "port": 21,
                    "user": "user@domain.com",
                    "password": "password"
                }
            }
        ]
    }
```
Is there something wrong in my config?

**Comment by inlife** [comment]
I feel like this error is coming from the node FTP module we are using as a dependency, please try looking for something similar in issues for that project.

**Comment by gvjonjones** [comment]
Capturing the FTP traffic on the target server, it seems that it's the server that isn't happy receiving a full windows file path in the put command:
`FTP: 553 Prohibited file name: C:\Users\User\AppData\Local\Temp\nexrender\4pJjH5fCvuzhbhvP23U43\encoded.mp4`

Trying to work out how to get around this. Is there any way to provide the 'output' value in the action-upload module to make sure node-ftp isn't trying to create a file with the full path as the filename?

**Comment by TimP4w** [comment]
Apparently the ftp provider uses the full path as the filename https://github.com/inlife/nexrender/blob/f11514486b16225ff3e254ba496e2eb035e8d765/packages/nexrender-provider-ftp/src/index.js#L50-L55

An easy fix would be to use some regex to get the filename from the path, maybe something like this:
```
var match = /[\w-]+\./.exec(src)
filename = match[0].replace('.', '')

con.put(file, filename, function(err) { 
[...]
```

Here's an example: https://jsfiddle.net/h0qwdk3b/

I will try to transform this in a pull-request this evening, and maybe try to find a better solution since 'file.name.ext' would only match 'file'.

**Comment by gvjonjones** [comment]
Ah, nice solution. 

I'll give it a go - thanks!

**Comment by TimP4w** [comment]
@gvjonjones another solution is to use path.basename from nodejs (https://nodejs.org/api/path.html#path_path_basename_path_ext)
