### ISSUE TITLE
Adding subtitles

### ISSUE THREAD

**Issue by masaldana2** [inlife/nexrender#231]
hello! Thanks for nexrender, wondering if i can pass text with time stamps or how will i go about creating subtitles on templates? 
Thank you!!!

**Comment by inlife** [comment]
Hello @masaldana2 

I think you could make use of After Effects Expressions for that. In particular, they allow you to return a value for a specific text field that is based on the current frame/time.
And you can quite easily set them using nexrender. For each specific layer.

**Comment by mackenly** [comment]
I've been looking into this too. I'd love to be able to automate the transcription. Google Cloud can generate timestamps for every word so it's probably possible with some creative expressions. But it would probably be a mess to actually make work.

**Comment by FinnFrotscher** [comment]
Where you able to solve the problem, @mackenly  @masaldana2

**Comment by mackenly** [comment]
@FinnFrotscher Have not attempted. I don't have the hardware infrastructure to properly test it right now.
