### ISSUE TITLE
An error will be thrown during the rendering when set 'Time Remap' property for layer

### ISSUE THREAD

**Issue by Mrzy** [inlife/nexrender#232]
**Describe the bug**
I added a audio layer, I hope that the audio can auto-cycle, so I set the 'Time Remap' for the layer's property, however, it doesn't work, it will throw an error during rendering, the part json is following:

```
       {
            "type": "data",
            "layerName": "BGM",
            "property": "Time Remap",
            "expression": "loopIn(); loopOut();"
        }
```

it works when I enabled the 'timeRemapEnabled' for layer by changes the output encoded .jsx script, the snippet code is:
```js
(function() {
    nexrender.selectLayersByName(null, 'BGM', function(layer) {
        layer.timeRemapEnabled = true; // it's the point

        var parts = ["Time Remap"];
        var value = { "expression": 'loopIn(); loopOut();' }
        nexrender.changeValueForKeypath(layer, parts, value);

        return true;
    });
})();
```
I use nexrender1.8.4 version on my Mac pro.

Please fix this issue,  thanks!

**Comment by inlife** [comment]
You can try creating a custom jsx script asset, that with this exact snippet (without wrapping function) https://github.com/inlife/nexrender#script-items

```js
// your-custom-script.jsx
nexrender.selectLayersByName(null, 'BGM', function(layer) {
    layer.timeRemapEnabled = true; // it's the point

    var parts = ["Time Remap"];
    var value = { "expression": 'loopIn(); loopOut();' }
    nexrender.changeValueForKeypath(layer, parts, value);

    return true;
});
```

And that script would be embedded directly into the main script.

**Comment by Mrzy** [comment]
Wow, your response was just in time!  Thanks, I will have a try
