### ISSUE TITLE
prerender action to download assets directrories from s3

### ISSUE THREAD

**Issue by Ruslan-F** [inlife/nexrender#233]
Hello again.
I've got a case similar to this one https://github.com/inlife/nexrender/issues/222.
1. As I understand - on aep file open - aerender %somehow% detects if assets are available via absolute paths and if they are not - tries relative, or counterwise, no matter.
2. As I understand - I **have to** add every Footage file to `assets: []` array if I want nexrender to download them from s3.
Please correct me if I'm wrong.
 
So my question is:
Is it possible to create a prerender module to like.. wget whole s3 dir associated with this currently processed aep? 
So all the s3bucket/project-root/file.aep sibling dirs will get to the `nexrender-worker-machine/tmp dir/uid` dir?
I haven't wrote much nodejs code before, so it'l take some time for me to complete it.
Just wanted to ask an advice if there's a point to do it at all.
**_Cause maybe nexrender/aerender already past the point of assets files paths re-definition by this (prerender) moment? _** 
Thanks.

**Comment by inlife** [comment]
Since pre-render happens just before launching the aerender, I guess theoretically it should be possible.
