### ISSUE TITLE
Run 3 render nodes on one machine，but One of them ended at 59%

### ISSUE THREAD

**Issue by chinacc** [inlife/nexrender#234]
I have run 3 render nodes on one computer, one of which synthesizes mp4 files at 59%, 
so this video is incomplete.

I am dying for your help.  how to avoid this error

the computer  24 core ，32g memory

**Comment by JamesBotterill** [comment]
What's you're processor/memory/disk usage when the occurs?

**Comment by inlife** [comment]
May I ask, which version of After Effects are you using? The later ones do not support native mp4 rendering
