### ISSUE TITLE
aerender SYNTAX ERROR: no value given for flag: -mem_usage

### ISSUE THREAD

**Issue by chinacc** [inlife/nexrender#236]
`spawning aerender process: C:\Program Files\Adobe\Adobe After Effects CC\Support Files\aerender.exe -project D:\render_work\522_2525_DGgQrnYM2tv-M1GMUI4WY\template.aep -comp zonghecheng -output D:\render_work\522_2525_DGgQrnYM2tv-M1GMUI4WY\result.mp4 -OMtemplate h264 -RStemplate h264 -r D:\render_work\522_2525_DGgQrnYM2tv-M1GMUI4WY\nexrender-522_2525_DGgQrnYM2tv-M1GMUI4WY-script.jsx -mem_usage 20 20`

aerender SYNTAX ERROR: no value given for flag: -mem_usage

**Comment by inlife** [comment]
I'm not sure why `-mem_usage` flag syntax is considered incorrect. If I remember correctly from the documentation for aerender it is the right way of using it.
https://helpx.adobe.com/after-effects/using/automated-rendering-network-rendering.html

**Comment by lipin-xd** [comment]
I've fix the bug on #261 
https://github.com/inlife/nexrender/pull/261
