### ISSUE TITLE
How to use it with BG Renderer Max which is an AE plugin?

### ISSUE THREAD

**Issue by Mrzy** [inlife/nexrender#237]
About BG Render Max more details: [Click here]( https://bgrenderer.com/about/)
I recognized that nexrender is based on 'aerender' tool from AE, I'm not sure whether nexrender works well with BG Render Max? Please give me some advice, thanks!

**Comment by inlife** [comment]
Not sure, haven't seen BG Render Max before. Do you know backend does it rely on?
