### ISSUE TITLE
Nexrender is getting stuck on 3% - anybody having this issue gefore?

### ISSUE THREAD

**Issue by brassel** [inlife/nexrender#239]
We are using nexrender with great success for a while now. But now, all of a sudden one video is stuck on 3% for an hour and nothing seems to happen. `aerender` still takes some 29% CPU but no progress is made. This is not about output not being flushed, the whole video should have rendered in around 5 minutes. And this is reproducible with nexrender while the video seems to render fine in AE GUI. 

Did anybody have that issue before?

**Comment by nickyromeijn** [comment]
I'm having the same issue with a video. It keeps hanging around 50-60% and nothing appears to be happening. aerender.exe is using 50%cpu and 2gb ram.

**Comment by nickyromeijn** [comment]
It's weird though, I am able to successfully render it with nexrender if I run after effects without the ae_render_node.txt (so with the full gui open)

**Comment by brassel** [comment]
My current suspicion is that `aerender` terminates because of some footage it can find. The AE-GUI seems to be "more creative" at finding such files. We will investigate further.

**Comment by brassel** [comment]
So, yes there was definitely a footage item missing in my case. How about yours, @nickyromeijn ? Were you able to sort out your problem, too?

**Comment by nickyromeijn** [comment]
Not yet, I haven't been able to spend time on that particular case yet. Though I'm pretty sure I have been able to render it with aerender before

**Comment by inlife** [comment]
Are you using mp3 audio files in the project? I know that aerender has bugs that involve mp3 on specific bitrate and frequency values. If that is the case, the simplest solution might be using wav or something similar for that.

**Comment by nickyromeijn** [comment]
I've found out that this usually happens due to remaining plugin configuration within an .aep project or missing footage. Aerender doesn't really throw detailed errors but the logfiles usually contain the information we need to optimize the process.
