### ISSUE TITLE
[external] google docs integration

### ISSUE THREAD

**Issue by inlife** [inlife/nexrender#24]
This feature is an external (possibly made as separate binary).
Main idea is to sync data from google docs spreadsheet to an api server.

Sample spreadsheet can look something like that:

![image](https://cloud.githubusercontent.com/assets/2182108/19618399/5e8052ba-9852-11e6-9ba3-28267ace37da.png)

I suppose best way to do this is to combine google docs api and nexrender api in one app, that will be running in a background and will be constantly checking for changes in the docs, and publish changes there (updates of render status).

This feature/application was described there as a prototype-concept, and can be developed by anyone who wants to help this project. :p
Currently, I don't have plant to work on this feature in the nearest future.

**Comment by ronCYA** [comment]
@inlife What kind of preliminary work do you have on this? I know how to update Google Sheets through its API but not too savvy about combining it with the Nexrender API.

**Comment by inlife** [comment]
Hey @ronCYA,

Nothing was done in this regards, at least from my side. I'm thinking that should either probably be a separate service that can communicate with both nexrender API and google sheets API, or a some sort of a plugin to the nexrender server (there is no plugin system or even a concept for the server tho)

**Comment by ronCYA** [comment]
Ah right, I see! If I manage to wrap my head around the Nexrender API more I'll have a crack at something that can perhaps be called with prerender and postrender.

**Comment by inlife** [comment]
the api package itself has some basic information about itself, that might be useful: https://github.com/inlife/nexrender/tree/master/packages/nexrender-api
