### ISSUE TITLE
Setting different values with respect to time

### ISSUE THREAD

**Issue by MrVerifit** [inlife/nexrender#242]
Is there any way we can set different values of a property with respect to time?
Like i want to set different position of image at more than 3 times!

**Comment by inlife** [comment]
You could use expressions for that. Readme, for example, contains the simplest form of an expression:

```js
        {
            "type": "data",
            "layerName": "my text field",
            "property": "Source Text",
            "expression": "time > 100 ? 'Bye bye' : 'Hello world'"
        },
```

However, you can go more advanced:

```js
    {
        ...
        "expression": "time > 1000 ? 'value1' : time > 2000 ? 'value2' : time > 3000 ? 'value3' : 'value4'"
    }
```

(or even wrap and call big local javascript functions within the expression)
