### ISSUE TITLE
Location files when using nexrender-server nexrender-worker

### ISSUE THREAD

**Issue by oskobri** [inlife/nexrender#243]
Hello,

I am using nexrender server and worker. The server is on a linux vm and worker on a windows vm.
Do the files .aep, images, videos, ... need to be on the windows server ? Because worker send me an error and can't open the aep file.

**Comment by JamesBotterill** [comment]
What's the error message? and is the project (AEP and assets) stored locally on the Worker vm?

**Comment by benbachem** [comment]
The files do need to be on the same machine as the worker, since the worker is doing the actual rendering.
The server is basically just a basic job-queue and scheduler, that mutliple workers can tap into.

**Comment by oskobri** [comment]
Ok thanks
