### ISSUE TITLE
Can't find a property sequence

### ISSUE THREAD

**Issue by Ruslan-F** [inlife/nexrender#244]
Hi there.
Not sure if it's bug or I'm doing something wrong, but:
- I got this test project, with ellipse whose I color want to change https://www.screencast.com/t/j3FlEfYC.
- This is a part of JSON `assets` array sent to nexrender (not sure value is in correct format, but execution haven't come to it yet anyway):
```
    {
      "type": "data",
      "layerName": "Shape Layer 2",
      "composition": "ANIMATION_COMP",
      "property": "Contents.Ellipse 1.Fill 1.Color",
      "value": "#ff0000"
    }
```
- This is a part of nexrender custom script:
```
(function() {
    nexrender.selectLayersByName('ANIMATION_COMP', 'Shape Layer 2', function(layer) {

        var parts = ["Contents","Ellipse 1","Fill 1","Color"];
        var value = { "value": '#ff0000' }
        
        nexrender.changeValueForKeypath(layer, parts, value);

        return true;
    });
})();
```
- And this is the error I get while rendering:
`Error: nexrender: Can't find a property sequence Fill 1.Color for key: Fill 1`

Can you give me a hint on what I'm doing wrong?
Thanks.

`"@nexrender/worker": "^1.8.4"` *

**Comment by Ruslan-F** [comment]
My fault. Tried to modify wrong property chain.

**Comment by inlife** [comment]
Glad to hear the issue got resolved :)

**Comment by bluematter** [comment]
How did you end up solving this? I am facing the same issue.

**Comment by Ruslan-F** [comment]
> How did you end up solving this? I am facing the same issue.
Been long since I wrote it. But as I remember - the problem was - I tried to modify unmodifieable (like calculated) property. And just should'v used other "path" to change the color.

**Comment by yuto425** [comment]
I am facing the same issue.

> Been long since I wrote it. But as I remember - the problem was - I tried to modify unmodifieable (like calculated) property. And just should'v used other "path" to change the color.

How can I know the path?

**Comment by sitestrokes** [comment]
> My fault. Tried to modify wrong property chain.

Hey,
