### ISSUE TITLE
Pipe aerender stdout and stderr to logger in debug mode

### ISSUE THREAD

**Issue by bezbac** [inlife/nexrender#248]
**Is your feature request related to a problem? Please describe.**
I recently spend quite a lot of time debugging my AE project file since it didn't work with nexrender.
Thing is, that nexrender-core actually has a debug option, so I looked at what it does and found out it does pretty much nothing.

**Describe the solution you'd like**
If the debug option in nexrender-core is set to true, pipe all the regular streams to the specified logger, so you can see the output of aerender in realtime.

**_If you deem this a good feature/ improvement, I'll prepare a pull-request._**

**Comment by zuntah** [comment]
Sound's like a very good idea. I am also lost buy finding bugs thru all the temp log files that are being created.
Also, look into my feature suggestion about adding a 3rd party logging service integration:
https://github.com/inlife/nexrender/issues/252

Thanks!

**Comment by inlife** [comment]
Oh @benbachem I must have missed the issue when you created it.
I think it is actually a good idea. Maybe even can be done via `--verbose` flag that would enable more detailed logs overall, and proxy all output from after effects. 👍

**Comment by benbachem** [comment]
@inlife No worries :)
Could you explain why a `--verbose` flag is needed?
There is already the debug setting and if I'm not mistaken the nexrender-action-ecode is doing exactly what I proposed based on that setting.

See here:
https://github.com/inlife/nexrender/blob/d5a8d66d59512358ae64c6b02e647a7a2a093da0/packages/nexrender-action-encode/index.js#L154

**Comment by inlife** [comment]
Oh I see. I forgot about this.

It seems to me that `--verbose` would be more logical as a flag for achieving this specific result. Both for core, and other modules, including action-encode. Wouldn't you agree?

Since its less about debugging, but more about detailed output.

**Comment by benbachem** [comment]
I do agree that `--verbose` better describes the state of the program but I don't think calling the flag `--debug` is wrong either, since the reason you wan't a more detailed output is likeley that something is going wrong. (Otherwise there is no point in having the information)

What do you think about introducing a log-level mechanism with multiple levels. Something along the lines of:
- Quiet
- Errors
- Warnings
- Info
- Degug/ Verbose

**Comment by inlife** [comment]
Sure, I don't see why not. A simple log-level mechanism might be even more beneficial for users.

**Comment by benbachem** [comment]
Alright, I'll implement this and open a pull request once I'm done.
Thank you for all the insight @inlife
