### ISSUE TITLE
How to use nexrender using after effects CC 2017 on mac using node JS 

### ISSUE THREAD

**Issue by naveedaziz** [inlife/nexrender#249]
Dear, i am trying to use nexrender from last 10 days but all in vein. Please can anyone guide me in simple steps how to use nexrender on mac using node JS and npm. I want to make video from AEP file with dynamic images, text and audio and need final mp4 version of that. Please also provide some reference file of AE so i can see how all happens. Your support will be very appreciated. Thanks in advance.

**Comment by inlife** [comment]
Hello,

If reading readme didn't help, try also checking out a video from our community: https://www.youtube.com/watch?v=E64dXZ_AReQ

**Comment by inlife** [comment]
As you see, you have an error in your After Effects configuration
You are trying to use an output module that you didn't add to the AE
![image](https://user-images.githubusercontent.com/2182108/64759479-e699b600-d53f-11e9-9436-ca79265bd216.png)

**Comment by inlife** [comment]
Also, bolilerplate uses an old version of nexrender.
Please read the full readme in this repo

**Comment by naveedaziz** [comment]
Dear Vladyslav Hrytsenko,

Thanks for all support. I have a final question. When i render it makes an
AVI file with a huge size approx 9GB. How i can reduce size or make a mp4
with lesser size.
Thanks and regards
Naveed Aziz

**Comment by inlife** [comment]
Hello,

So yea, after it finishes rendering the lossless avi usually takes quite a lot of space. That is one of the reasons why @nexrender/action-encode has been introduced. 

https://github.com/inlife/nexrender/tree/master/packages/nexrender-action-encode

**Comment by naveedaziz** [comment]
Hi,
This is my code

'use strict';

/**
 * Parameters for rendering
 */
let mixfile     = 'deep_60s.mp3';
let background  = '2016-aug-deep.jpg';
let datascript  = '2016-aug-deep.js';
let duration    = 3600;
// set max duration for 1 minute (equal to audio length)

let aepxfile  = 'nm05ae12.aepx';
let audio     = 'mp3';

/**
 * Settings for renderer
 * DONT FORGET TO CHANGE aebinary ACCORDING TO YOUR SYSTEM
 * On Windows might look like: 'C:\Program Files\Adobe\Adobe After
Effects CC 2018\Support Files\aerender.exe'
 */
const aebinary  =
'C:/Program Files/Adobe/Adobe After Effects CC 2018/Support Files/aerender.exe'
;
const port      = 23234;

/**
 * Dependencies
 */
const http      = require('http');
const url       = require('url');
const path      = require('path');
const fs        = require('fs');

const Project   = require('nexrender').Project;
const renderer  = require('nexrender').renderer;

/**
 * HTTP server
 */
let server = http.createServer((req, res) => {

    let uri         = url.parse(req.url).pathname;
    let filename    = path.join(process.cwd(), uri);

    fs.exists(filename, (exists) => {
        if(!exists) {
            res.writeHead(404, {"Content-Type": "text/plain"});
            res.write("404 Not Found\n");

            return res.end();
        }

        fs.readFile(filename, "binary", function(err, file) {
            if(err) {
                res.writeHead(500, {"Content-Type": "text/plain"});
                res.write(err + "\n");
                return res.end();
            }

            // send 200
            res.writeHead(200);
            res.write(file, "binary");
            return res.end();
        });
    });
});

/**
 * Renderer
 */
server.listen(port, () => {

    console.log('Started local static server at port:', port);

    // addtional info about configuring project can be found at:
    // https://github.com/Inlife/nexrender/wiki/Project-model
    let project = new Project({
        "template": "project.aepx",
        "composition": "main",
        "type": "default",
        "settings": {
            // dont forget to setup the right output module; info:

// The default outputModule for Windows users is "Lossless" & the
default outputExt is "avi"

// You can create custom modules from Edit -> Templates -> Output
Modules but the name and outputExt have to be in sync

// Go to Composition -> Add Output Module to create customModule names
            //
https://helpx.adobe.com/after-effects/using/basics-rendering-exporting.html#output_modules_and_output_module_settings
            "outputModule": "h264",
            "startFrame": 0,
            "endFrame": duration,
            "outputExt": "avi",
        },
        "assets": [
            { "type": "project", "name": "project.aepx",    "src": `
http://localhost:${port}/bda/${aepxfile}`},
            { "type": "image",   "name": "background.jpg",  "src": `
http://localhost:${port}/assets/${background}`, "filters": [ {"name":"cover"
, "params": [1280, 720] }] },
            { "type": "image",   "name": "nm.png",          "src": `
http://localhost:${port}/assets/nm.png` },
            { "type": "audio",   "name": `audio.${audio}`,  "src": `
http://localhost:${port}/assets/${mixfile}` },
            { "type": "script",  "name": "data.js",         "src": `
http://localhost:${port}/assets/${datascript}` }
        ],
        "actions":{
            "postrender": [
                {
                    "module": "@nexrender/action-encode",
                    "preset": "mp4",
                    "output": "encoded.mp4"
                },
                {
                    "module": "@nexrender/action-copy",
                    "input": "encoded.mp4",
                    "output": "myresult.mp4"
                }
            ]
        }
    });

    console.log(project);

    // start rendering
    renderer.render(aebinary, project).then(() => {
        // success
        server.close();
        console.log('rendering finished');
    }).catch((err) => {
        // error
        console.error(err);
        server.close();
    });

});

*It won't do any post render and also remove temp folder once done all. Can
you please guide whats the issue. *

**Comment by inlife** [comment]
You are using an OLD version of nexrender. Please switch to the actual stable version. Here are the details on how to migrate: https://github.com/inlife/nexrender#migrating-from-v0x

Cheers!

**Comment by naveedaziz** [comment]
Dear, Sorry for again asking you.
I have tried the new code
const { init, render } = require('@nexrender/core')

const settings = init({
logger: console,
})
const js = {
"template": {
"src": "template.aep",
"composition": "main"
},
"assets": [
{
"src": "bg.png",
"type": "image",
"layerName": "background.png"
}
],
"actions": {
"postrender": [
{
"module": "@nexrender/action-encode",
"preset": "mp4",
"output": "encoded.mp4"
},
{
"module": "@nexrender/action-copy",
"input": "encoded.mp4",
"output": "myresult.mp4"
}
]
}
};
const main = async () => {
const result = await render(js, settings)
}

main().catch(console.error);


It give error

[image: image.png]

Can you please help.

I just need to render aep or aepx file to mp4 using nexrender using dynamic
assets, thats the only goal.

Thanks

**Comment by naveedaziz** [comment]
Dear, Can you please provide a small piece of code that just take aep or
aepx file (with dynamic json of background and text only) and render to mp4
using node js and post render thing u mentioned in above threat.  Or please
guide me what i am doing wrong.
Thanks

**Comment by inlife** [comment]
I can give you even a video: https://www.youtube.com/watch?v=E64dXZ_AReQ
The new version allows you to use nexrender both programmatically (via nodejs), and without installing nodejs as a plain binary (like shown in the video)

In case you are interested in purely nodejs based render, you can check the test folder:
https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/test/manual.js

Also please, read the full main README file very carefully, possibly multiple times. It is the main source of information.

**Comment by naveedaziz** [comment]
Thanks for all support.
I have done it using packages/worker and packages/server.
Finally i have created mp4 using these code. 👍
