### ISSUE TITLE
Integrating with 3rd party logging services like Logz.io

### ISSUE THREAD

**Issue by zuntah** [inlife/nexrender#252]
**Is your feature request related to a problem? Please describe.**
Not related to a specific problem.

**Describe the solution you'd like**
An option to add for nexrender-worker & nexrender-server params that will make them connect and send logs to a 3rd party service (like Logz.io)
Right now, If you want to run a nexrender-server and then multiple nexrender-workers you are basically blind and you have to look into many servers & log files in order to find out bugs and problems.
Integration with 3rd party logs service and sending all logs to a central place would make this process much better.
A very good solution is logz.io which has a free plan and using ELK stack.
They also have a nice node js package than can easily be integrated into the code.

Links:
https://docs.logz.io/shipping/log-sources/nodejs.html
https://github.com/logzio/logzio-nodejs

**Comment by inlife** [comment]
I agree that 3rd party logging system could be useful, however I don't think it's a good idea to vendor lock it. I think would be much better if we would find a way to make it more like plugin/option based.
