### ISSUE TITLE
Is it possible to allow changing font from assets?

### ISSUE THREAD

**Issue by pixelfactorydevelopmentteam** [inlife/nexrender#253]
Hello! Thanks for nexrender:)
Is it possible to allow changing font from assets?

I need to change fonts from a template like other properties here:
https://github.com/inlife/nexrender#example-1

Can you tell me what I did wrong?

**Comment by inlife** [comment]
Hello,

First issue: looking at your job json, you should stick with either using layerIndex or layerName for the layer selection.

Regarding the font selection, please check out those 2 issues:
https://github.com/inlife/nexrender/issues/201#issuecomment-514134918
https://github.com/inlife/nexrender/issues/190

Seems like error message is related to the fact while executing custom jsx it cannot find the needed layer or property for such layer.
