### ISSUE TITLE
Problem to install (pc)

### ISSUE THREAD

**Issue by rikpare** [inlife/nexrender#255]
Hello, anyone have this problem when im trying to install the installation window dont start.
Just a widow open and close  immediately.

**Comment by inlife** [comment]
Hey @rikpare 

The binaries you've downloaded are not installers but actual binaries. In case you work on windows, the possible usage for you might be opening cmd.exe or powershell and running the binary from there.

Cheers!

**Comment by MHanutko** [comment]
Hi @rikpare 

[This video](https://www.youtube.com/watch?v=E64dXZ_AReQ) should help you out.

**Comment by rikpare** [comment]
thanks!! sorry im news on this don't know about code, binaries etc but i really like this tool and what can do and all the possibilities,
so i will learn more.
