### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by senthudms** [inlife/nexrender#256]
I would like to change color of the layer, please help for this

![Picture](https://user-images.githubusercontent.com/12815209/66249947-1b70e580-e759-11e9-9278-101e77b20cf6.png)

I try like this :+1: 
![code](https://user-images.githubusercontent.com/12815209/66249959-570baf80-e759-11e9-8c86-1a36e10cf59d.png)

Thanks for the help

**Comment by JamesBotterill** [comment]
Yes, look at data items in the docs.

**Comment by senthudms** [comment]
> Yes, look at data items in the docs.

Thanks for the reply

You mean "type": "data".

**Comment by senthudms** [comment]
Hi again

I try like this. but still not working

I like to change the background color

![2](https://user-images.githubusercontent.com/12815209/66317474-339e5b80-e937-11e9-9da5-299dd642f645.png)


I try like this

![1](https://user-images.githubusercontent.com/12815209/66317502-4153e100-e937-11e9-94ea-5a2701efff75.png)


Thanks for try to help me

**Comment by JamesBotterill** [comment]
I would remove the spaces in your BG COLOR layer. It's good practice not to have spaces as it doesn't generally play nicely with scripting. So I'd change the layer name in AE to BG_COLOR and the same in the request.

I'd also check that it's a RGB value that being entered and not HSL which I believe it has been in the past.

**Comment by senthudms** [comment]
Yes. it's working now :+1: 

Thank you so much
