### ISSUE TITLE
Upload the file to google Cloud

### ISSUE THREAD

**Issue by senthudms** [inlife/nexrender#258]
Thanks for create this amazing project :+1: 

I like to know how we can upload the rendered video to Google Cloud Server like S3 and FTP server

Regards
Senthuran

**Comment by inlife** [comment]
Hello @senthudms 

Try to check out post rendering actions:

https://github.com/inlife/nexrender#actions
https://github.com/inlife/nexrender/tree/master/packages/nexrender-action-upload

And then also select the driver you want to use:

https://github.com/inlife/nexrender#protocols
https://github.com/inlife/nexrender/tree/master/packages/nexrender-provider-s3
https://github.com/inlife/nexrender/tree/master/packages/nexrender-provider-ftp

**Comment by senthudms** [comment]
Thank @inlife 

I'm testing that. I will update you asap

**Comment by johnrico2000** [comment]
Hi, the latest release seems to support uploading to Google Cloud Storage as a post render action now.

**Comment by senthudms** [comment]
HI

Thank you so much :)
