### ISSUE TITLE
Is there any parameter to make the picture render as a cover photo?

### ISSUE THREAD

**Issue by piedasing** [inlife/nexrender#262]
In the doucument:
- type: string, for data items, is always data
- layerName: string, target layer name in the After Effects project
- layerIndex: integer, can be used instead of layerName to select a layer by providing an index, starting from 1 (default behavior of AE jsx scripting env)
- property: string, indicates which layer property you want to change
- value: mixed, optional, indicates which value you want to be set to a specified property
- expression: string, optional, allows you to specify an expression that can be executed every frame to calculate the value
- composition: string, composition where the layer is, useful for searching layer in pre-compositions. If none is provided, it uses the default composition set in the template.

and my setting is :
```
job.assets.push({
        src: assets_data.src,
        type: "image",
        layerName: assets_data.name,
        composition: "*"
});
```

I don't know how to set 'cover' into my image setting.
If there is any parameter to set 'cover', please tell and help me!

**Comment by inlife** [comment]
Hello!

Could you please explain in more details what do you mean by 'cover'?

**Comment by piedasing** [comment]
hi,
'cover' just means a cover photo
because my project can not render the photo fit to composition
but use the way by 'add to render queue' in AE, it can fit very well.

Sorry, my English is very poor...

Please translate these words...
我的專案在 AE 內，使用 add to render queue ，渲染出來的影片，圖片是可以自適應至 comp 內的設定
但使用 aerender 直接下命令 或 nexrender 渲染出來的影片，圖片都變得很小
從 AE 的設定得知一個 fit to comp 的設定，想知道 nexrender 有沒有此功能？
而 cover 這個名稱是從舊版的 nexrender 中的屬性得知的
但新版的 nexrender 文件中，並沒有看見此屬性
請務必協助我，在此由衷感謝。


Vladyslav Hrytsenko <notifications@github.com> 於 2019年10月17日 週四 20:34 寫道：

**Comment by JamesBotterill** [comment]
@piedasing  are you trying to capture a single frame of the render as a poster image? 

I achieved this by writing a small post render module to capture a thumbnail the size, of the source video.

thinking aloud now you could add a custom param to nexrender-action-encode to do this also, why didn't I do that before, doh

**Comment by piedasing** [comment]
@JamesBotterill 
Hello, I am not very familiar with the parameter setting of nexrender-action-encode that you said.
Could you please tell me more about it? Or provide me with relevant documentation, thank you.

**Comment by piedasing** [comment]
I found the problem in my project!
There is a composition setting "scale" in AE. It can set image auto fit to comp size.

In my AE  project, it can read my "config.js" file in root directory.
But, when I use "aerender.exe" by command line or nexrender in node server, it cannot read it.
Maybe it is just a wrong file path in my setting.
Finally, I figure it out by put "config.js" into the directory where the aerender.exe is located.

**Comment by oreporan** [comment]
@JamesBotterill Could you publish your thumbnail creator plugin to npm so we can use it?
