### ISSUE TITLE
Downloading assets breaks when query parameters are in the URL

### ISSUE THREAD

**Issue by nickyromeijn** [inlife/nexrender#264]
**Describe the bug**
A clear and concise description of what the bug is, and ways to reproduce it.

When using a http url as asset src the download action breaks when there are query parameters within the url. The generated destination / file path includes the query parameters after the extension which causes a write error. 

Nexrender version 1.8.0
Running on windows server 2016

**Comment by inlife** [comment]
Oh that is very bad bug indeed, I'll try to come up with a fix asap.

**Comment by inlife** [comment]
published as fix in `v.1.8.10`

**Comment by nickyromeijn** [comment]
While the issue is fixed, there is still an issue with urls where the extension is not explicitly stated within the url. For example https://foo.bar/files/<id>. The worker downloads the file just fine but because it cannot find an extension it gets saved without one and can't be used in after effects. Is it possible to provide our own filename in this scenario? I retrieve extensions by content-type headers and mime types.

**Comment by inlife** [comment]
I'm not sure yet on how to tackle this issue. Does anybody have any ideas?

**Comment by nickyromeijn** [comment]
> I'm not sure yet on how to tackle this issue. Does anybody have any ideas?

Could do a HEAD request to the url given to determine its content type which should be the same as the returned file.

**Comment by inlife** [comment]
Asset now has option to provide an extension for the file: `asset.extension`, so that should solve the later issue
