### ISSUE TITLE
Shift Layer to OutPoint from previous Layer

### ISSUE THREAD

**Issue by MHanutko** [inlife/nexrender#267]
Hello,

I've come up with a request for an addon to nexrender (perhaps it exists already, but I can't found it)
I need to shift layers to other dynamic layers.
For an upcoming template it would be a huge timesaver to have some sort of an addon that can set the inpoint from one layer to the outpoint from another layer.

Let's say I have a videoclip (dynamic in lengh) which changes every week. After that clip will be a transition to the next dynamic clip. That transition needs to be every week exactly between these two videos.

Example from Templater: https://www.youtube.com/watch?v=BXTbUoH7mJs

Thanks in advance

**Comment by inlife** [comment]
Hey @MHanutko 

Thank you for the suggestion. I'll think about what can be done in this regard.
It seems quite a simple thing, but I have no idea yet on how to implement something like that.

**Comment by MHanutko** [comment]
Hi @inlife 

I just scrolled the Code section a bit more and saw the ability to include scripts. This could be done with simple scripting, I guess.

**Comment by inlife** [comment]
Yes, indeed it can be done via scripting. However, I think a dedicated feature for that as you suggested would be quite cool actually.

**Comment by MHanutko** [comment]
I would use it right away! If you have some ideas in mind about how to implement that directly into nexrender, go for it.
I wrote a little script in the meantime:

`var myComp;
var myLayer1;
var myLayer2;
var myLayer3;
var myOverlay1;
var myOverlay2;

// set undo steps to 1 

app.beginUndoGroup("undo")

// find comp with a specific name and rearrange dynamic footage

for (var i = 1; i <= app.project.numItems; i ++) {
    if ((app.project.item(i) instanceof CompItem) && (app.project.item(i).name === "Main")) {
        if (myComp) {
            
            myComp = app.project.item(i);
            myLayer1 = myComp.layer(5);
            myLayer2 = myComp.layer(3);
            myLayer3 = myComp.layer(1);
            myOverlay1 = myComp.layer(4);
            myOverlay2 = myComp.layer(2);
            myLayer1.startTime = 0;                                         // set in point to frame 1 of comp
            myLayer2.startTime = myLayer1.outPoint;             // set in point to out point from layer 1
            myLayer3.startTime = myLayer2.outPoint;             // set in point to out point from layer 2
            myOverlay1.startTime = myLayer1.startTime+3;    // set in point to in point from layer 1 + x seconds
            myOverlay2.startTime = myLayer2.startTime+3;    // set in point to in point from layer 2 + x seconds
            myComp.duration = myLayer3.outPoint;                // set work area out to out point of layer 3 
            myComp.workAreaStart = myLayer1.startTime;      // set work area in to in point of layer 1 
        }
        
    }
}
app.endUndoGroup`

That works for my particular case, but I would like to have the layer selection made by the script as well. If the template has just 2 dynamic footage files I would need to rewrite the layer section.
It would be cool that the script reads the last layer (end of comp) and the first layer(start of comp) by itself and arranges the mid-layers to every out point of the previous layer.
If anyone has done something similar in the past, help is much appreciated.
I'm not a **scripter** by any means.

**Comment by FinnFrotscher** [comment]
any progress?

**Comment by inlife** [comment]
negative
