### ISSUE TITLE
color not updating

### ISSUE THREAD

**Issue by senthudms** [inlife/nexrender#268]
HI friends.

I try to change the layer color ( please check the attached image ) it's not updating. always showing white color ( i try with RGB, RGBA and HSL) . can anyone help me for this please 

![error](https://user-images.githubusercontent.com/12815209/67896054-9921e880-fb81-11e9-8b81-adb15669eb70.jpg)

Regards
Senthuran

**Comment by inlife** [comment]
Didn't you succeed in solving that issue before?
https://github.com/inlife/nexrender/issues/256

Or it's something different?

**Comment by senthudms** [comment]
Thanks for the reply.

still learning about your nexrender, 

still not solved.

**Comment by senthudms** [comment]
it's working on rgb 0-1 

how we can use RGB 0-255

**Comment by inlife** [comment]
Oh, have you considered it might be a value of 0...1?
So try to divide each of your rgb components by 255 `[23/255, 242/255, 100/255]`

**Comment by senthudms** [comment]
YES!!!. it's working nicely 

as you said i divide each of rgb components by 255

Thank you so much
