### ISSUE TITLE
Do you recommend any kind of cloud service/render farm?

### ISSUE THREAD

**Issue by netunlimited** [Inlife/nexrender#27]
Hi,
Great piece of work! I'm considering to use it for a personalised video service. 
Due to seasonal high load (not whole year), I was wondering if you would recommend some kind of scaleable cloud service or render farm? For example something from Amazon AWS? Do you have experience with such a setup?

I'm asking because I want to minimize the work required for setting up and maintaining servers. :)

Thanks!

**Comment by Inlife** [comment]
Hello,

Thank you!)

Yea, i guess AWS might be a best choice. However, considering a fact that you need to have either macos or windows for the actual after effects that might be a pricy, you know )

But yea, AWS is a best one i know, and can recommend.
And yet, i still "urge" you to maybe research a bit more. Maybe there will be something even much more simpler, and cost less.
If you find something interesting, please share it back! :D
(issue will be closed, but you still be able to write there)

Anyway, i wish you good luck. 😉

**Comment by netunlimited** [comment]
Hi, thanks for your fast response!

I think I'm actually going to research using Natron ( https://natron.fr ) for now, since it's open-source and cross-platform so it will be hopefully easier/cheaper to deploy for such large scale project.

Thanks again!

**Comment by jcmidia** [comment]
Hello! Do you know some tutorial about how to setup a Amazon server to run After Effects?

**Comment by Inlife** [comment]
Not really, however i can say that you will need either macos or windows environments.
I believe there are should be tutorials for that (if its possible ofc) 😄

**Comment by jcmidia** [comment]
Yes, that's the problem =/
In Amazon we just have the Windows option
Thanks for answer, I'll try to do it
