### ISSUE TITLE
How to run cleanup when render failed?

### ISSUE THREAD

**Issue by AntonPrusov** [inlife/nexrender#271]
When I got error while render job cleanup is sciped. How can I run it force?  I use it on web app and i need to clean up after any render (successfull or not) to save free space.

**Comment by inlife** [comment]
Unfortunately, it is not possible atm.
Which way you are running the nexrender, is it pure cli, or server + worker mode?

**Comment by AntonPrusov** [comment]
I use nexrender cli.

**Comment by inlife** [comment]
added a `--cleanup` option for nexrender-cli in https://github.com/inlife/nexrender/commit/544d0e5735a9d78d0cb455d6cb015ed6a782f869

allows to fully remove all stuff created by nexrender in its temp folder
