### ISSUE TITLE
How to get the status of a task that is in the queue?

### ISSUE THREAD

**Issue by panchenkoprog** [inlife/nexrender#273]
Hi, thank you for your library, I have a question regarding the way how I can use it.
I am using your latest release in binary file for Windows.
And I have a question:
1) if there's a way to get status of ongoing task in the queue? For example, if I will send UID and receive responce with current status (queued, success), for example http://prntscr.com/pvml1g.
2) is there any way to transfer a webhook that will be called right after the file is created? I am not a big expert at NodeJS so need to know if there's a way to send parameters in JSON, for example http://prntscr.com/pvmlph.
I need to receive response from server-worker or from `server-api right after rendering and creation of .mp4 file , in order to get this file from server-worker. Preferably without using NodeJS.
I tried to upload files vis FTP, but this way doesn't work for me becauseit allows to upload files only in common directory, and my goal is to place videos for each user in different directories.

I looked at these issues, some of them are closed, but the functionality of webhooks has not been implemented yet, and I have not found any implementation for obtaining status.

https://github.com/inlife/nexrender/issues/219
https://github.com/inlife/nexrender/issues/26
https://github.com/inlife/nexrender/issues/68

thanks in advance!

**Comment by inlife** [comment]
Hello,

1. To get information about a particular task, you can either use nodejs API package, or direct HTTP GET call to the /jobs/:uid

2. Yes, unfortunately, webhooks action hasn't been implemented yet.
