### ISSUE TITLE
Can a single nexrender-server work with multiple nexrender-workers? 

### ISSUE THREAD

**Issue by panchenkoprog** [inlife/nexrender#276]
Hello!
I have a question:
Can a single nexrender-server work with multiple nexrender-workers? For example, when I have one queue on the site-0.com server (nexrender-server is installed) and this queue distributed tasks to several site-1.com, site-2.com, site-3.com servers (with nexrender-worker installed on each of them). For example: http://prntscr.com/pxxyub.
If so, then I want to understand --host http://prntscr.com/py2r5i is my server address where is nexrender-server located? I want to understand this, because I did all my tests on the same machine on which nexrender-server + nexrender-worker were located at the same time and the address was the same, so I got a little confused. I must understand this correctly to rebuild my system.
Thanks in advance!

**Comment by inlife** [comment]
Hello,

Yes, that is actually the intended way it should work.
And yes, `host` points to the actual address where your `nexrender-server` is running.
