### ISSUE TITLE
Rendering comp with sub comps

### ISSUE THREAD

**Issue by bdb400** [inlife/nexrender#277]
When I rendered a comp with another comp in it, the rendered video is just black. any solutions.

**Comment by bdb400** [comment]
I found that if i put and element in the comp it renders all comps. maybe a bug?

**Comment by inlife** [comment]
In theory, the behavior of the renderer is almost the same, like rendering with After Effects. So I'm not sure I can say what is happening there.

**Comment by bdb400** [comment]
Is it a bug?

**Comment by inlife** [comment]
If it is a bug, I fell like it must be a bug related to After Effects/aerender itself. Please correct me if I'm wrong.
