### ISSUE TITLE
Edit composition properties / enable & disable compositions

### ISSUE THREAD

**Issue by dowu-creavo** [inlife/nexrender#279]
Hi, thanks for your app!
I'm currently working on automating to render a template about wheater. There are single sub-compositions in this template that have to be enabled/disabled, depending on the given data.
Is there a way to disable/enable these? I can only find ways to edit layers.

Thanks for helping!

**Comment by inlife** [comment]
Hello,

I think it should be possible via After Effects Scripting, and since you can include scripts theoretically, I think it is doable. However, based on my limited knowledge of the scripting APIs, I, unfortunately, can't guarantee that.

Cheers!
