### ISSUE TITLE
Adobe After Effects CC 2017

### ISSUE THREAD

**Issue by wst-shorty** [Inlife/nexrender#28]
Hey There,

I'm trying to use nexrender with AE CC 2017, however i keep getting the error 

"aerender ERROR: No output module template was found with the given name" which i believe is because it now expects you to use Adobe Media Encoder now, is there anyway to link nexrender into this?

Thanks,

Aaron

**Comment by Inlife** [comment]
Hello,

Are you sure, you've set up everything properly.
Try looking this link
https://github.com/Inlife/nexrender/wiki/Project-model#settingsoutputmodule

There is some information about output module templates.

**Comment by wst-shorty** [comment]
Thank you for coming back. I am confident that i have things set up
properly. I am using an output module i have setup myself (h264) and it
keeps giving me the following error during the verifying project stage:

"Error message: ENOENT: no such file or directory, stat
'temp/rkTyi5Wjx/result.mp4'

{ [Error: ENOENT: no such file or directory, stat
'temp/rkTyi5Wjx/result.mp4']

  errno: -2,

  code: 'ENOENT',

  syscall: 'stat',

  path: 'temp/rkTyi5Wjx/result.mp4' }"

Do you have any idea why this could be?

Thanks!

**Comment by Inlife** [comment]
Hmm, could you please check
are there any files inside your `temp/rkTyi5Wjx` folder ?
if the verifying stage was only one to throw an error, and actual video file was generated, probably its error with different file extension

**Comment by wst-shorty** [comment]
Ahh yes it is error for file extension. It is looking for .mp4 but a /mov
is produced...

However in AE 2017 the only option is create mov it seems (as there is
nothing for mp4)
[image: Inline image 1]

Is there anyway to use Adobe Media Encoder with nexrender?

Thanks again for your help.

**Comment by williamccrobinson** [comment]
Ah yes experienced the same situation as you @wst-shorty ;

As a solution I use nexrender to generate a .mov as shown by the author's examples, and then I use FFMPEG on the .mov file to convert it h264 .mp4. 

FFMPEG (https://ffmpeg.org/) works great for this final render step; you can encode audio and video with MANY different codes. I use the fluent-ffmpeg npm package (https://github.com/fluent-ffmpeg/node-fluent-ffmpeg) that provides a simple interface to generate FFMPEG commands in javascript

**Comment by Inlife** [comment]
@wst-shorty yea, seems like they might change this "h264-mp4" hack
and now we can only use the default mov/avi on each platform

>Is there anyway to use Adobe Media Encoder with nexrender?
as far as i know, there is no ability to run media encoder console, so no :(

>As a solution I use nexrender to generate a .mov as shown by the author's examples, and then I use FFMPEG on the .mov file to convert it h264 .mp4.
@williamccrobinson thats a very nice way of doing it 👍 

ffpmeg is a very powerful thingy, i totally recommend it !
