### ISSUE TITLE
Dealing with includes within script ? New Indirect / dependency asset type ?

### ISSUE THREAD

**Issue by ddcrobert** [inlife/nexrender#280]
**Is your feature request related to a problem? Please describe.**
ExtendScript can quickly become a mess. Gathering things within externals .jsx files into kind of a library is required.
However, when nexrender take the main jsx file, relatives includes are broken.

**Describe the solution you'd like**
An "inactive/dependency" asset type which can be either a folder or a file. All the existing files are kind of directly used by nexrender or after effects. This one would be an indirect one.
It can be a file or a folder, both are useful depending if you know ahead what the jsx structure is going to look like.

**Describe alternatives you've considered**
- Parse the main jsx, detect all the includes recursively and add them as assets too. And write the included files so they don't produce anything when they're run alone.
- Parse the main jsx, detect all the includes recursively and replace the relatives path by absolute path (my files are already clones ahead of nexrender, i don't need to undo this).
- Detect the temp folder, copy the includes near the main jsx file within that folder.

I would like to avoid exploring theses, they're really dirty.

**Comment by inlife** [comment]
It is a complicated problem, indeed. The alternative solutions you've described, I think, make the experience much more comfortable while using the tool. Still, they are more involved in terms of implementation and maintenance, while the original proposition even tho is relatively more straightforward, but on the other side might lead to a constant ton of issues asking about ways of dealing with such stuff.

**Comment by ddcrobert** [comment]
FYI, I relied on Gulp which saved me some time. I added a gulp sequence ahead of nexrender. It finds jsx files within the template folder, then merges them into one, then search and destroy imports.
