### ISSUE TITLE
Replace Audio File Problem

### ISSUE THREAD

**Issue by piedasing** [inlife/nexrender#282]
Excuse me, I have a problem on replace audio file ( *.mp3 ) 

When I use Add To Render Queue in AE, it can render a video correctly.
But when I use NEXRENDER to replace audio file, the rendered video's music has something trouble.

### It is not expected sound about first second !!!

That sound sounds like some music effect, but I do not set any effect in AE or my program.

And it just happened when I replace MP3.
( If I do not replace MP3, it can render a correct video. )

#### The document's example for assets setting :
```
{
    "assets": [
        {
            "src": "https://example.com/assets/image.jpg",
            "type": "image",
            "layerName": "MyNicePicture.jpg"
        },
        {
            "src": "file:///home/assets/audio.mp3",
            "type": "audio",
            "layerIndex": 15
        }
    ]
}
```

#### My program for audio setting:
```
{
        src: "file:///" + config.root_path + assets_data.src,
        type: "audio",
        layerName: "BGM",
        composition: "*"
}
```

Thanks for helping.

**Comment by inlife** [comment]
Hello @piedasing 

There were some problems with aerender related to mp3 files.

> I've heard about such bug before. I was related to the mp3/mp4 audio with bitrate value not being high enough. I'd recommend trying to use wav or encoding the mp3 with higher bitrate before sending it to the aerender.

So as in the quote above, try changing audio to wav/aiff or try converting your mp3 file bitrate to 900 for example, and audio frequency to 50 for example.

**Comment by piedasing** [comment]
Thanks for reply. I will try it later !
