### ISSUE TITLE
Aerender paths have problem in Windows

### ISSUE THREAD

**Issue by aysimakarca** [inlife/nexrender#284]
Hi,

I was running nexrender on my nodejs server sucessfully on MAC but i had to switch to Windows 10 and i faced some problems about nexrender not being able to find correct paths.

I have these settings for binary:
const settings = init({
  logger: console,
  binary: "C:/Program Files/Adobe/Adobe After Effects 2020/Support Files/"
})

At first i got the error below, then i noticed in patch.js, code was removing Support Files from path and looking for Scripts folder directly under Adobe which is supposed to be under Support Files. I changed the code to use binary directly and it worked.
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Program Files\\Adobe\\Adobe After Effects 2020\\Scripts\\Startup\\commandLineRenderer.jsx

But now i get the error below while trying to render, here is the latest error i got:
Error: Error starting aerender process: Error: spawn C:/Program Files/Adobe/Adobe After Effects 2020/Support Files ENOENT
task_queues.js:97
message:"Error starting aerender process: Error: spawn C:/Program Files/Adobe/Adobe After Effects 2020/Support Files ENOENT"
stack:"Error: Error starting aerender process: Error: spawn C:/Program Files/Adobe/Adobe After Effects 2020/Support Files ENOENT\n    at ChildProcess.<anonymous> (c:\Users\47939\Documents\Repos\core-renderer\node_modules\@nexrender\core\src\tasks\render.js:101:44)\n    at ChildProcess.emit (events.js:219:5)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)\n    at onErrorNT (internal/child_process.js:468:16)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"

Can you help?

Thanks,
Aysima

**Comment by inlife** [comment]
Hello, in case you are using the default path on windows or macos, you don't even need to provide the binary option, it is included in "autofind" feature. And if you do need, you can take a look how it is provided internally: https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/helpers/autofind.js#L26

**Comment by aysimakarca** [comment]
Thank you, it worked when i remove the bin path
