### ISSUE TITLE
render fail : (node:4188) UnhandledPromiseRejectionWarning: Error: spawn EBUSY

### ISSUE THREAD

**Issue by bdb400** [inlife/nexrender#285]
I thought it was because I installed node.js, but on my other pc that I didn't install node on the same error happened.

![image](https://user-images.githubusercontent.com/5695811/70769870-66dedb80-1d28-11ea-8f41-1f563a5753e2.png)

**Comment by inlife** [comment]
A see that issue appearing more and more. Have you recently also updated windows by any case?

**Comment by bdb400** [comment]
I updated windows after the error started happening.

**Comment by johnrico2000** [comment]
I'm experiencing this , too, now. Suddenly the @action/encode part using ffmpeg produces this error, The video rendering with aerender works fine though. I can't explain either. I haven't changed anything relevant to my system, that I could recall.

**Comment by johnrico2000** [comment]
Ok, looks like I found the issue (at least on my machine). The Windows malware defender/anti-virus service must have blocked access to the files. You just need to exclude the nexrender working directory folder from the malware protection.
See here how to do that:
https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-security

**Comment by bdb400** [comment]
Thank you! It worked!

**Comment by inlife** [comment]
Oh no. It seems we found the issue.
@johnrico2000 thank you!

**Comment by brassel** [comment]
Since I get the same error I would be interested in the solution for this issue.
But I am not fully sure if we would need to follow the instructions @FRANK-AND-FREE suggests or if @inlife has found some other fix for this. In the latter case I would have a different problem maybe?

```
Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg) Error: spawn EBUSY
```

**Comment by inlife** [comment]
@brassel so far from browsing the web this kind of error seems to appear on windows for exact same reasons: system telling nodejs that It can't allow it to touch the specific file for reasons of it doing something with that file already. Like antimalware software reading into it or blocking it altogether. 

That is at least the consensus that comes from my small research. Unfortunately, I'm not sure if there is anything we can do about it.
