### ISSUE TITLE
Edit Keyframe  

### ISSUE THREAD

**Issue by afroty** [inlife/nexrender#286]
How do I edit a keyframe using nexrender programatically 
 
See below.. How can I access this offset property. 
![image](https://user-images.githubusercontent.com/11652379/70856190-c3fb9e00-1e9c-11ea-8f9b-65700c547245.png)

**Comment by inlife** [comment]
Hello,

I'm assuming if there is a way to change it via expression, it can be done via nexrender as well. As an alternative you could try to research the docs for After Effects ExtendedScript and try to change those values via custom jsx script, which can also be embedded via nexrender.
