### ISSUE TITLE
Image size is not updated after being replaced

### ISSUE THREAD

**Issue by ddcrobert** [inlife/nexrender#287]
Recently I had to do some script based on a image which was replaced, and I found out its size has not been updated, it still is the **former** image size.

The script is like 

```
var imageLayer = comp.layer("image");
var height = imageLayer.height; //same with trying sourceRectAtTime
```

The **original image** is a square of _1121_.
If I **debug the script via VSCode**, the returned size is _1121_.
If I **replace manually** the image and **debug**, the returned size is _984_.
However, if I do the full **process via nexrender**, the **image is correctly replaced**, but the script still returns _1121_ (I printed the value in a TextLayer to double-check).

If it haven't changed, Nexrender replaced the image indirectly via AE : it deposits a file with the correct name near to the .aep file and AE replace the absolute path.
In that case, I don't think we can do something since that would be an AE bug.

**Comment by inlife** [comment]
I feel like after effects scripting doesn't trigger some internal image data updating, which in turn, returns old value for the height. How do you think, is that the case?
