### ISSUE TITLE
Nexrender does not wait for finished rendering when reusing a running After Effects instance

### ISSUE THREAD

**Issue by FRANK-AND-FREE** [inlife/nexrender#288]
**Describe the bug**
I have a running GUI instance of After Effects and would like the nexrender worker to use that (via --reuse flag) as the rendering instance. This appears to work since when nexrender starts to process the job, is gets opened and rendered by that GUI instance. After some time the result.avi is complete and is available in the job directory.
Unfortunately the nexrender workflow does not wait for the rendering to finish before proceeding with the post render actions.  This results in the rendered result.avi file not being found (as it is not there, yet). Acutal rendering took about 10 seconds, but nexrender says it took only ~0.361 seconds.

Has someone already successfully tried to reuse an opened instance of After Effects for their render job in a worker?

Here's the console output:
D:\mvm-workspace\nexrender>.\nexrender-worker-win64.exe --binary="D:\Adobe CC\Adobe After Effects 2020\Support Files\aerender.exe" --workpath=".\job-workdir" --host=http://localhost:3001 --debug --multi-frames --reuse --skip-cleanup
> starting nexrender-worker endpoint http://localhost:3001; using secret: no
adding default render-only-node licenses for After Effects at:
 - C:\Users\Frank Bruns\Documents\ae_render_only_node.txt
 - C:\Users\Frank Bruns\Documents\Adobe\ae_render_only_node.txt
checking After Effects command line renderer patch...
command line patch already is in place
[hSaoNfGyonqupYhl30OdJ] setting up job...
[hSaoNfGyonqupYhl30OdJ] working directory is: D:\mvm-workspace\nexrender\job-workdir\hSaoNfGyonqupYhl30OdJ
[hSaoNfGyonqupYhl30OdJ] downloading assets...
[hSaoNfGyonqupYhl30OdJ] applying prerender actions...
[hSaoNfGyonqupYhl30OdJ] running script assemble...
[hSaoNfGyonqupYhl30OdJ] rendering job...
[hSaoNfGyonqupYhl30OdJ] spawning aerender process: D:\Adobe CC\Adobe After Effects 2020\Support Files\aerender.exe -project D:\mvm-workspace\nexrender\job-workdir\hSaoNfGyonqupYhl30OdJ\test-template-480x270.aep -comp main -output D:\mvm-workspace\nexrender\job-workdir\hSaoNfGyonqupYhl30OdJ\result.avi -s 0 -e 250 -r D:\mvm-workspace\nexrender\job-workdir\hSaoNfGyonqupYhl30OdJ\nexrender-hSaoNfGyonqupYhl30OdJ-script.jsx -mp -reuse
[hSaoNfGyonqupYhl30OdJ] rendering took ~0.361 sec.
[hSaoNfGyonqupYhl30OdJ] writing aerender job log to: D:\mvm-workspace\nexrender\job-workdir\aerender-hSaoNfGyonqupYhl30OdJ.log
[hSaoNfGyonqupYhl30OdJ] applying postrender actions...
[hSaoNfGyonqupYhl30OdJ] starting action-encode action (ffmpeg)
[hSaoNfGyonqupYhl30OdJ] action-encode: input file D:\mvm-workspace\nexrender\job-workdir\hSaoNfGyonqupYhl30OdJ\result.avi
[hSaoNfGyonqupYhl30OdJ] action-encode: output file D:\mvm-workspace\nexrender\job-workdir\hSaoNfGyonqupYhl30OdJ\encoded.mp4
[hSaoNfGyonqupYhl30OdJ] ffmpeg version git-2019-10-06-66d45af Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20191005
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf

[hSaoNfGyonqupYhl30OdJ]   libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 59.101 / 58. 59.101
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 62.100 /  7. 62.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
D:\mvm-workspace\nexrender\job-workdir\hSaoNfGyonqupYhl30OdJ\result.avi: No such file or directory

[hSaoNfGyonqupYhl30OdJ] error occurred: Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg)
    at C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\tasks\actions.js
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async start (C:\snapshot\nexrender\packages\nexrender-worker\src\index.js)

**Comment by inlife** [comment]
Seems like aerender binary exists successfully much earlier than expected. Looking at the render time, I feel like it only "submits" the job to the After Effects and immediately closes itself.

It seems to me that wasn't a case before, but I might be wrong. Which version of After Effects are you using?

**Comment by johnrico2000** [comment]
Hi, sorry, I should have stated the version in the first place. It is after effects v17. 0.0 from CC2020. I'm aware that there is a 17.0.1 available, but AE doesn't open up correctly for me when updating to that.

**Comment by johnrico2000** [comment]
The Problem exists with After Effects CC 2019 (v16.x.x) as well.

**Comment by vrrdnt** [comment]
I'm having this problem as well. AE CC 2019 v16.Here's my log:

`> starting nexrender-cli
using automatically determined directory of After Effects installation:
 - C:\Program Files\Adobe\Adobe After Effects CC 2019\Support Files\aerender.exe
adding default render-only-node licenses for After Effects at:
 - C:\Users\[user]\Documents\ae_render_only_node.txt
 - C:\Users\[user]\Documents\Adobe\ae_render_only_node.txt
checking After Effects command line renderer patch...
command line patch already is in place
[MtoYI6ucz0MDZVPTOSsDl] setting up job...
[MtoYI6ucz0MDZVPTOSsDl] working directory is: C:\Users\[user]\AppData\Local\Temp\nexrender\MtoYI6ucz0MDZVPTOSsDl
[MtoYI6ucz0MDZVPTOSsDl] downloading assets...
[MtoYI6ucz0MDZVPTOSsDl] applying prerender actions...
[MtoYI6ucz0MDZVPTOSsDl] running script assemble...
[MtoYI6ucz0MDZVPTOSsDl] rendering job...
[MtoYI6ucz0MDZVPTOSsDl] spawning aerender process: C:\Program Files\Adobe\Adobe After Effects CC 2019\Support Files\aerender.exe -project C:\Users\[user]\AppData\Local\Temp\nexrender\MtoYI6ucz0MDZVPTOSsDl\Video.aep -comp Main -output C:\Users\[user]\AppData\Local\Temp\nexrender\MtoYI6ucz0MDZVPTOSsDl\result.avi -r C:\Users\[user]\AppData\Local\Temp\nexrender\MtoYI6ucz0MDZVPTOSsDl\nexrender-MtoYI6ucz0MDZVPTOSsDl-script.jsx
[MtoYI6ucz0MDZVPTOSsDl] rendering took ~17.129 sec.
[MtoYI6ucz0MDZVPTOSsDl] writing aerender job log to: C:\Users\[user]\AppData\Local\Temp\nexrender\aerender-MtoYI6ucz0MDZVPTOSsDl.log
[MtoYI6ucz0MDZVPTOSsDl] applying postrender actions...
[MtoYI6ucz0MDZVPTOSsDl] starting action-encode action (ffmpeg)
[MtoYI6ucz0MDZVPTOSsDl] action-encode: input file C:\Users\[user]\AppData\Local\Temp\nexrender\MtoYI6ucz0MDZVPTOSsDl\result.avi
[MtoYI6ucz0MDZVPTOSsDl] action-encode: output file C:\Users\[user]\AppData\Local\Temp\nexrender\MtoYI6ucz0MDZVPTOSsDl\encoded.mp4
[MtoYI6ucz0MDZVPTOSsDl] ffmpeg version git-2019-10-06-66d45af Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20191005
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf

[MtoYI6ucz0MDZVPTOSsDl]   libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 59.101 / 58. 59.101
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 62.100 /  7. 62.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
C:\Users\[user]\AppData\Local\Temp\nexrender\MtoYI6ucz0MDZVPTOSsDl\result.avi: No such file or directory

> job rendering failed
Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg)
    at C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\actions.js
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by admsyn** [comment]
I also seem to be experiencing this issue with AE2020 (`aerender version 17.1x72`). I get jobs that 'render' in ~0.2 seconds, report as failed due to missing output files, but do eventually render their output.

[It may be a regression in AE2020 / AE17](https://community.adobe.com/t5/after-effects/aerender-in-ae17-2020-says-its-done-immediatly-but-its-not/td-p/10745882?page=1)

In my case, downgrading to AE 16.1.3 worked correctly with `-reuse`. @FRANK-AND-FREE maybe check if you were still using the aerender from 17.x?

**Comment by inlife** [comment]
> It may be a regression in AE2020 / AE17
If that is the case, I'm not even sure what we can do about it. If that continues, probably the only reliable way of telling if something has finished rendering would be to do it from our side. I'm not sure yet, however, how we could achieve something like that.

**Comment by brassel** [comment]
Any news on this topic? We would be very interested in using the "--reuse" flag  with AE 2020 as well.

**Comment by inlife** [comment]
Sadly, no. Options like listening for file changes or watching the process list all sound quite unreliable and nothing else came to my mind yet. :(

**Comment by rofthy** [comment]
Same Problem with the AE2021 v18.0. Does anyone have a solution for it?

**Comment by jitendra-koodo** [comment]
> Sadly, no. Options like listening for file changes or watching the process list all sound quite unreliable and nothing else came to my mind yet. :(

Does this mean :

"reuse" flag does not work at all?
or
it works but it does not wait for render to finish to start another one?
