### ISSUE TITLE
Want to reduce Render Time Server to Nexrender-worker

### ISSUE THREAD

**Issue by pixelfactorydevelopmentteam** [inlife/nexrender#289]
I have a nexrender-server and 10 workers which are connected and pulling jobs every 30 seconds (Default values).

**I have two questions for you.**
01_ During the communication between Nexrender Server to Nexrender-worker taking 30 sec for sending the JOB (How to reduce time)?
02_ Taking the time during sending the response from nexrender-worker to nexrender-server after the complete the rendering(How to reduce time)?

**Comment by inlife** [comment]
Hello!

In case you are using the binary, you can check `--help`. There is a mention about `--polling` option, that allows you to set time in ms, of how long it needs to wait till making a next request.

And as far as I remember both described points by you should be resolved by this option.
