### ISSUE TITLE
Is it possible to retrieve layer names before rendering output?

### ISSUE THREAD

**Issue by aysimakarca** [inlife/nexrender#291]
Hi,

I am trying to develop an application which i can change assets and render different videos but i also want to learn existing layer names without opening the project. Can i retrieve existing layer names in a ae project without running after effects? I know it is possible with extendscript toolkit but i want to run the script from the same nodejs application which i use nexrender in and without running after effects. Is it possible with nexrender or do you have any suggestions for that?

Thank you,

**Comment by inlife** [comment]
You could try learing more, or maybe even using these projects:
* https://github.com/actumn/aepx.js
* https://github.com/inlife/aftereffects-project-research
