### ISSUE TITLE
Automating Render farm: split a single job 

### ISSUE THREAD

**Issue by Binipro** [inlife/nexrender#296]
Hello @inlife 

As per the projects plan and as commented on this issue #191, there is a plan to automate the rendering of a single job on multiple workers. Do you have any update on the section of splitting a job?

I will be working on an independent package for the second part of converting the image sequences ( inside a watch folder)  to a  video and then collecting them to generate the final output video. This package will also be inspired by parallel frameworks such as CUDA, OpenCL, etc.

So in order to proceed it would be crucial to have the splitting part.
As initial phase it could be a trivial algorithm, such as you check the total frame length and if it's greater than N , replicate the job adding starFrame and endFrame as much as the number of worker nodes then push them to the API calls.

Let me know if it sounds for you and if you plan to implement it.

Thanks!

**Comment by inlife** [comment]
Hello @Binipro 

Yea, unfortunately, the situation hasn't changed. The current status is still the same:
> I haven't had a chance to do actual work on it, so I would say its still in the research/planning phase.

Your package concept sounds quite promising. What kind of help do you need from me?

Cheers!

**Comment by Binipro** [comment]
@inlife ,

what I need from you is to make Nexrender support split a single job to a number workers. 
This part of the comment was my suggestion for you:
> As initial phase it could be a trivial algorithm, such as you check the total frame length and if it's greater than N , replicate the job adding starFrame and endFrame as much as the number of worker nodes then push them to the API calls.

As you know  when you split a job on AE render farm the only supported output is an image sequences (still image)  so I will work on an independent package to gather the results and encode each sequence to produce the final video.

Thanks!

**Comment by inlife** [comment]
I can't tell you when i will be able to do this at this time, but I will try to find some time soon.
