### ISSUE TITLE
How to run nexrender-server on Linux (e.g. Ubuntu)?

### ISSUE THREAD

**Issue by johnrico2000** [inlife/nexrender#297]
Hi,
being mainly a Windows user that only casually works on Linux machines, I somewhat struggle with running the nexrender-server on a Ubuntu server.
Similar to running the nexrender-server-win64.exe on Windows via the windows shell I downloaded the file "nexrender-server-linux" from the release site in Gitlab.
I figured I just need to put that file on my Ubuntu server and start it via the command line.
The downloaded file is a file with no file extension (like .deb) or something. I honestly don't know what kind of file it is and how to run it from the command line.

Could someone be so nice and give me a hint on how to execute that file?

Thanks,
Frank

**Comment by JamesBotterill** [comment]
If it's linux in the terminal I would use ./nexrender-server-linux in the directory that the binary sits in, I believe that's correct but could be wrong.

**Comment by johkon** [comment]
you could install it with npm.

**Comment by inlife** [comment]
As @JamesBotterill noted that is indeed the correct way. Just make sure to check if the binary has permissions to be executed:

```
$ chmod +x nexrender-server-linux
$ ./nexrender-server-linux --help
```

**Comment by johnrico2000** [comment]
Hi,
sorry for answering late (I'm moving houses at the moment), but making the file executable solved the issue. Thanks for everyone taking their time to help me out.

Best
Frank
