### ISSUE TITLE
Network posting job. fetching job forever.

### ISSUE THREAD

**Issue by bdb400** [inlife/nexrender#299]
I send a job from my server to the nexrender-server-win64 exe I get this message 'project has been created' then in the nexrender-server-win64 exe console it says 'creating now job ID' then repeats fetching job with the same ID forever. 

![image](https://user-images.githubusercontent.com/5695811/72485996-c23c3780-37c6-11ea-81b6-18f7db68783c.png)

![image](https://user-images.githubusercontent.com/5695811/72486007-ccf6cc80-37c6-11ea-9517-f35a84cc32c9.png)

**Comment by inlife** [comment]
that is an interesting problem, can it be replicated only on windows, have you had any chance testing it somewhere else?

**Comment by bdb400** [comment]
No I haven't tried it anywhere else.

**Comment by bdb400** [comment]
Maybe I'm doing something wrong I installed nexrender api via npm install @nexrender/api --save on my node.js express server. Then used the sample code to create a job.


        const { createClient } = require('@nexrender/api')

        const client = createClient({
            host: 'http://0.0.0.0:3000',
            secret: 'myapisecret',
        })

        const main = async () => {
            const result = await client.addJob({
                
                    "template":{
                        "src": "http://localhost:3050/TESTTEMPLATE.aep",
                        "composition": "COMP"
                    }
                })

            result.on('created', job => console.log('project has been created'))
            result.on('started', job => console.log('project rendering started'))
            result.on('finished', job => console.log('project rendering finished'))
            result.on('error', err => console.log('project rendering error', err))
        }

        main().catch(console.error);`

**Comment by inlife** [comment]
oh, wait i guess i know what is happening
so I assume you don't have any workers running, correct?

since the api client is constantly checking for the current status of the job the http server just prints that someone tried to fetch it (meaning get information about it in this case) so that is probably what happens

**Comment by bdb400** [comment]
How do I run a worker? and does the worker have to be on another machine?

**Comment by inlife** [comment]
well worker can be either on that, or on any other machine, it's up to you

to run it you need to download it (binary in releases)
![image](https://user-images.githubusercontent.com/2182108/72750591-f26c4780-3bc5-11ea-9455-c3d180baa71f.png)

more info:
https://github.com/inlife/nexrender#nexrender-worker

**Comment by bdb400** [comment]
I downloaded it and ran it but the same thing happens

**Comment by bdb400** [comment]
when i run it a command prompt opens then quickly closes

**Comment by inlife** [comment]
try to open cmd.exe/powershell in the folder with the executable, and then run it

**Comment by inlife** [comment]
keep in mind, network rendering (a thing you are trying to do) is more advanced way of setting up a bunch of machines to work with nexrender

if you want to simply render a job locally you can just use `nexrender-cli`
there is a video tutorial for that: https://www.youtube.com/watch?v=E64dXZ_AReQ

**Comment by bdb400** [comment]
Yes I know I've gotten quite familiar with the local `nexrender-cli` process.

**Comment by bdb400** [comment]
I ran it from cmd 
![image](https://user-images.githubusercontent.com/5695811/72751197-2c186080-3b7c-11ea-8114-2ec6d65e6bfb.png)

**Comment by bdb400** [comment]
Do I need to add this? --binary="E:\Program Files\Adobe After Effects 2020\Support Files\aerender.exe"

**Comment by bdb400** [comment]
Yes I added `--binary="E:\Program Files\Adobe After Effects 2020\Support Files\aerender.exe"` and it works

**Comment by inlife** [comment]
Great, I guess i need to make that error message "slightly" more readable 😄

**Comment by bdb400** [comment]
Thanks for your help!!!

**Comment by inlife** [comment]
No problemo!
