### ISSUE TITLE
Forward Slash getting replaced with filepath

### ISSUE THREAD

**Issue by pradeeprajr93** [inlife/nexrender#3]
I'm using some Forward Slashes (/) in my expression for divide operation. When I save this project as .aepx file and render using nexrender, the new .aep file created by nexrender in `nexrender\temp` replaced with some default file path.
For the time being I'm converting my divide operations with multiplication using `Math.pow(val,exp)` in AfterEffects.

Kindly resolve this bug :)

Thanks

**Comment by Inlife** [comment]
Sorry for such a long response time.
I've tried to fix this issue, but currently had no luck :C
Maybe someday i will figure out how to write a better regular expressions than that one:
`/(?:(?:[A-Z]\:|~){0,1}(?:\/|\\\\|\\)(?=[^\s\/]))(?:(?:[\ a-zA-Z0-9\-\_\.\$\●\-]+(?:\/|\\\\|\\)))*/gm`

For now, I can recommend you to use space between operations in expressions tho:
`"123 / 23"`

**Comment by Inlife** [comment]
Oops, accidentally closed that issue 😬 😄
