### ISSUE TITLE
Importing a Vector File

### ISSUE THREAD

**Issue by wst-shorty** [Inlife/nexrender#30]
Hey There,

I was wondering if it is possible to import a vector image file with nexrender? I have tried using the same technique as importing an image file but it doesn't seem to work like the other image files do.
It copies it to the temp folder but the original vector files are not updated in the actual after effects image file.

Any help would be greatly appreciated.

**Comment by wst-shorty** [comment]
*Sorry it was still referencing the direct links rather than the relative files (had to delete the old files so it wouldn't reference them)

**Comment by Inlife** [comment]
yeah, its kinda stupid problem with ae 😄
