### ISSUE TITLE
using nexrender to edit the .aep file and copy the modified aep file using postrender

### ISSUE THREAD

**Issue by digitGrove89** [inlife/nexrender#300]
Hi, I'm new to this tool. I have been playing with lots of options available in nexrender.
I wonder whether this option is available..

I wanted to make a copy of the template aep file to a temp location and using the scripts in assets i wanted to edit and modify the text, image in the aep compositions and I wanted to skip the rendering process and copy the modified aep file in temp location to my desired location using postrender option..

Please shed some light on this.. As this option would be really useful for me.

**Comment by inlife** [comment]
actually, I think that might be possible

so, the main idea for this would be "abusing" the jsx scripting, to save the project file after doing all necessary modifications to it
![image](https://user-images.githubusercontent.com/2182108/72799046-03ac6700-3c4d-11ea-88b1-345550881e0e.png)
(taken from https://readthedocs.org/projects/after-effects-scripting-guide/downloads/pdf/latest/)

you would still need to render something tho, just to launch after effects engine to execute the scripts, even if the total render amount of frames is going to be 1

and as the last step you would use `action-copy` and would copy the modified aep file rather than the output file

so together it would probably look like something along those lines:
```json
{
    "template": {
        "src": "file:///d:/documents/original.aep",
        "composition": "main",
        "frameStart": 0,
        "frameEnd": 1
    },
    "assets": [
        {
            "src": "file:///d:/images/myimage.png",
            "type": "image",
            "layerName": "background.png"
        },
        {
            "src": "file:///d:/scripts/myscript.jsx",
            "type": "script"
        }
    ],
    "actions":{
        "postrender": [
            {
                "module": "@nexrender/action-copy",
                "input": "original.aep",
                "output": "d:/mydocuments/modified.aep"
            }
        ]
    }
}
```

**Comment by digitGrove89** [comment]
wow that was a fast and clever solution. 

Can you kindly give more info about "src": "file:///d:/scripts/myscript.jsx", from where it came into the picture. pardon me if this is really a noob question.

I tried your suggestion..

`{
    "template" : {
        "src" : "file:///d:/template.aep",
        "composition" : "main",
        "frameStart" : 0,
        "frameEnd" : 1
    },
    "assets": [
        {
            "type": "data",
            "layerIndex": 2,
            "composition": "main",
            "property": "Source Text",
            "value": "modified text"
        }        
    ],
    "actions":{
        "postrender": [
            {
                "module": "@nexrender/action-copy",
                "input": "template.aep",
                "output": "d:/output_folder/modified_template.aep"
            }
        ]
    }
}`

I ran this json file with --skip-cleanup and I noticed one jsx file got generated along with the rendered output in temp file..

so you were stating that I have to copy that generated jsx file

Please point me out on the right direction :) thanks in advance..

**Comment by inlife** [comment]
So, the `myscript.jsx` is the script you should create. It is going to be responsible to make any additional scripting modifications to your project. If you don't need additional scripting involved, it still should be there, just to have a single line of code:
```js
// myscript.jsx
app.project.save();
```

That line will initiate project save, that will override the existing temporary project files with changes.
If you do add any additional scripting, make sure that it would be added before. As this line should be the last instruction for the after-effects scripting engine.

>  noticed one jsx file got generated along with the rendered output in temp file.

That is always going to happen, that file is needed for nexrender to work properly. That is not the file you are looking for, so I suggest just to ignore it.

**Comment by digitGrove89** [comment]
Awesome.. That worked like a charm.. 
Thanks a lot for for your solution. I'm really grateful :)

**Comment by inlife** [comment]
Glad to hear that!

**Comment by digitGrove89** [comment]
Dear inlife, this solution is not working for relatively larger aep file.. with 10 - 15 compositions and few nested compositions.. render is running successfully but the post render is copying only the original aep file to the output location rather than copying the modified and saved aep file .

// myscript.jsx
app.project.save();
{
            "src": "file:///d:/scripts/myscript.jsx",
            "type": "script"
 }

any suggestions / idea..

**Comment by inlife** [comment]
I feel like it's just not getting saved in time the render finishes. (Takes longer than expected).
What if you try to make the rendering longer, few hundered frames for example or so. That would increase the delay between when .save() was called and actual copy action was triggered, and maybe that will help.

Try that just to test the theory.

**Comment by digitGrove89** [comment]
Yes you are right.. Though I didn't generate extra frames.. 
but introducing a delay of 5 - 10 seconds in myscript.jsx solved it..

// myscript.jsx
$.sleep(5000);
app.project.save();

I Will have to see in long run if this solution will work for even more complex and larger After effect files..
