### ISSUE TITLE
encode qtrle with alpha

### ISSUE THREAD

**Issue by hippocampestudio** [inlife/nexrender#302]
When I do : 
{
    "module": "@nexrender/action-encode",
    "params": {
      "-vcodec":"qtrle",
      "-pix_fmt": "rgba"
    },
    "output": "myvideo.mov"
}
I don't have any alpha channel.
Is there a way to do this ?

**Comment by inlife** [comment]
the encode module directly passes all arguments to the ffmpeg binary
so the behaviour, in theory, should be exactly the same, and if you have any questions related to that you can try to find answers for ffmpeg

**Comment by hippocampestudio** [comment]
OK, but is he able to understand that my after Effects composition has a transparent background?
Because I tried all the possible settings to export and each time, I have a black background and not transparent.

**Comment by inlife** [comment]
by default nexrender & after effects renders avi/mov, which i believe do not support global alpha channels
you would need to find a different codec and change after effects output module settings to change the behavior

**Comment by JamesBotterill** [comment]
To export from AE with an alpha channel included you would probably need to set the Output Module in the template settings to something like: 

"outputModule": "Lossless with Alpha" (not sure on the exact string this is taken from AE2019)

By default it's Lossless I believe
