### ISSUE TITLE
nexrender-worker - [*] error while updating job state to started. Job abandoned

### ISSUE THREAD

**Issue by meghalagrawal** [inlife/nexrender#305]
**Describe the bug**
I've setup nexrender server in a remote server(Ubuntu 16.04) and using my local machine(Mac OSX) as a worker.

The worker is just throwing this error without any further information: [*] error while updating job state to started. Job abandoned.

I checked the code for the worker! It's not printing the error anywhere and so it's a little tough to debug the issue 

**Screenshots**
If applicable, add screenshots to help explain your [problem.](url)
<img width="580" alt="Screenshot 2020-01-29 at 3 58 40 PM" src="https://user-images.githubusercontent.com/18400951/73349127-a5b4fa80-42b0-11ea-9c2d-7b2a488ba238.png">

**Comment by inlife** [comment]
could you also provide `nexrender-worker` and `nexrender-server` versions?
and could you also provide logs that are coming from the server side?

**Comment by inlife** [comment]
as a little improvement, added an additional line to print the error stack, published as `v1.10.2`

**Comment by meghalagrawal** [comment]
Hi, @inlife Thank you so much for adding the error log :)

Here are the updated screenshots for both worker & server, I'm using the latest versions for both worker & server.

worker-version: 1.10.2
server-version: 1.10.0

server:
<img width="586" alt="Screenshot 2020-01-29 at 9 35 01 PM" src="https://user-images.githubusercontent.com/18400951/73373821-3c001500-42df-11ea-839b-989cd47f05b1.png">

 
worker: 
<img width="674" alt="Screenshot 2020-01-29 at 9 33 50 PM" src="https://user-images.githubusercontent.com/18400951/73373784-2d196280-42df-11ea-835f-94fbd3ea2b39.png">

**Comment by inlife** [comment]
Oh, I see the issue now, pushed a fix (its server side), so you would need to update it to `v1.10.3`

**Comment by meghalagrawal** [comment]
It's fixed! Thank you so much 👍

**Comment by inlife** [comment]
Glad to hear :)
