### ISSUE TITLE
Dynamic end_frame argument to pass to aerender?

### ISSUE THREAD

**Issue by vrrdnt** [inlife/nexrender#306]
Hey there!

I see that in the template section of the job .json, you can add fields like frameStart and frameEnd.

Is there a way to make it measure the duration of a specific layer and use that as frameEnd?

For example, audio.mp3 is 3 minutes long at 24 fps. That's ‭4,320‬ frames. frameEnd needs the number 4320. However, if audio.mp3 changes to 2:30, then the frame number obviously changes.

**Comment by inlife** [comment]
As mentioned on discord, there is no built-in automatic way to do that. You would need to calculate that value before-hand and provide inside json when creating a job, alongside your mp3 file.

**Comment by dukuo** [comment]
My PR ([307[(https://github.com/inlife/nexrender/pull/307)) has a working solution to implement dynamic variables. Currently strings, numbers, null or empty values are working correctly, but functions are still a work in progress, planning on releasing a fix soon.
