### ISSUE TITLE
"!=" vs "!==" bugs

### ISSUE THREAD

**Issue by danielgwilson** [inlife/nexrender#308]
**Describe the bug**
The current implementations of `selectCompositionsByName` and `selectLayersByName` are buggy; they incorrectly compare strings using `!=` where they should check `!==`. This results in all expressions executing **_N_** times where **_N = number of compositions_**—regardless of the fact that all compositions may have different names.

```javascript
/* envoke callback for every compostion matching specific name */
nexrender.selectCompositionsByName = function(name, callback) {
    var items = [];

    /* step 1: collect all matching compositions */
    var len = app.project.items.length;
    for (var i = 1; i <= len; i++) {
        var item = app.project.items[i];
        if (!(item instanceof CompItem)) continue;

        if (name != "*" && item.name != name) {
            continue;
        } else {
            items.push(item);        
        }
    }

    /* step 2: envoke callback for every match */
    var len = items.length;
    for (var i = 0; i < len; i++) {
        callback(items[i]);        
    }

    if (len == 0) {
        throw new Error("nexrender: Cound't find any compositions by provided name (" + name + ")");
    }
};

/* call callback for an every layer matching specific name and composition */
nexrender.selectLayersByName = function(compositionName, name, callback, types) {
    var foundOnce = false;

    if (!compositionName) compositionName = nexrender.defaultCompositionName;
    if (!types) types = nexrender.types;

    nexrender.selectCompositionsByName(compositionName, function(comp) {
        var items = [];

        /* step 1: collect all matching layers */
        for (var j = 1; j <= comp.numLayers; j++) {
            var layer = comp.layer(j);
            if (layer.name != name) continue;

            if (nexrender.typesMatch(types, layer)) {
                foundOnce = true;
                items.push(layer);
            }
        }

        /* step 2: envoke callback for every match */
        var len = items.length;
        for (var i = 0; i < len; i++) {
            callback(items[i], name);
        }
    });

    if (!foundOnce) {
        throw new Error("nexrender: Cound't find any layers by provided name (" + name + ") inside a composition: " + compositionName);
    }
};
```

Instead of the above, string comparators should be:

```javascript
...
if (name !== "*" && item.name !== name) {
  continue;
} else {
  items.push(item);        
}
...

...
if (layer.name !== name) continue;
...
```

**Information about environment**
- N/A

* Which version of nexrender are you using?
- 1.10.1

* What kind of the setup do you have? (server+worker or cli)
- Node + TypeScript (local)

* Are you using pre-built binaries or globally installed npm packages?
- NPM

* Which kind (and version) of operating system you are running it in?
- OSX

* Any additional information that might be helpful

**Expected behavior**
Comparison occurs with `===` and `!==`

**Comment by danielgwilson** [comment]
Related; `selectLayersByName()` and `selectLayersByIndex()` global selects across all compositions. E.g., if you call `selectLayersByIndex(1)`, you affect the first layer of every composition.

I don't believe this should be the expected behavior; rather, I had assumed the default composition target would match the composition defined in the job.

**Comment by danielgwilson** [comment]
> `composition`: string, composition where the layer is, useful for searching layer in pre-compositions. **If none is provided, it uses the default composition set in the template.** Providing "*" will result in a wildcard composition matching, and will apply this data to every matching layer in every matching composition.

Ah, ok—definitely a bug.

**Comment by inlife** [comment]
Thank you @danielgwilson for the report, I'll push a fix soon.

**Comment by inlife** [comment]
Hey @danielgwilson, actually while reviewing the description you provided, I have a question:
If I understood correctly you propose to change `!=` and `==` to `!==` and `===` respectively. In which cases that change would make any influence? I just can't seem to think of any cases where that would lead to a problem.

**Comment by inlife** [comment]
Also regarding your last comment, it seems to be the case the default behavior was changed to actually match all compositions by default, and we forgot to reflect that fact in the documentation.

**Comment by danielgwilson** [comment]
> Also regarding your last comment, it seems to be the case the default behavior was changed to actually match all compositions by default, and we forgot to reflect that fact in the documentation.

Ah, ok—I actually think this may be counter-intuitive; I expected that the default composition being matched was the one defined in the job itself. What are some example scenarios in which matching across all compositions makes more sense?

> you propose to change != and == to !== and === respectively. In which cases that change would make any influence?

Minor bug, mostly fine; I think this is really only problematic if `name` or `item.name` are weird, e.g. `""` (empty string), `[object Object]`, `false` (boolean, not string)

See https://stackoverflow.com/questions/3586775/what-is-the-correct-way-to-check-for-string-equality-in-javascript

IMO, perhaps not absolutely necessary, but easy tweak to potentially save someone a huge headache.

**Comment by inlife** [comment]
I'm going to implement a change that you proposed, I believe changing compares to triple equal signs won't harm anybody.

And regarding why does it match every composition: I tried to find the issue we had a discussion in, but couldn't do that. The main reason, I believe, was the fact that it's quite confusing for some people to understand how to use that. Or something along those lines.

**Comment by danielgwilson** [comment]
> I'm going to implement a change that you proposed, I believe changing compares to triple equal signs won't harm anybody.

Dope!

> The main reason, I believe, was the fact that it's quite confusing for some people to understand how to use that.

Mm I buy that—my experience was having multiple layers with the same name across different comps changed accidentally, but I can see how other scenarios might cause just as much confusion.

**Comment by inlife** [comment]
The `!==` changes are pushed, and will be available in the next release
