### ISSUE TITLE
layerName vs. downloaded Filename issue -> TypeError Null is not object

### ISSUE THREAD

**Issue by FinnFrotscher** [inlife/nexrender#309]
**Describe the bug**
When running job with `layerName !== src.fileName`
```
  {
      layerName: 'output.mp4',
      src: 'https://storage.de1.cloud.ovh.net/v1/AUTH_008a58f0cc7c4ea5909c02b7cfb6339f/v0/19.09.01_0.mp4',
      type: 'video'
    },
```
i receive:
```
TypeError: null is not an object
```
But when running the exact same script with `layerName === src.fileName`:
```
   {
      layerName: 'output.mp4',
      src: 'https://storage.de1.cloud.ovh.net/v1/AUTH_008a58f0cc7c4ea5909c02b7cfb6339f/v0/output.mp4'
    }
```
Its working.
There seems to be an issue in the downloader.

**Information about environment**

aerender version 17.0.2x26
@nexrender/core 1.11.3
@nexrender/action-* 1.8.16

* What kind of the setup do you have? (server+worker or cli)
core
* Are you using pre-built binaries or globally installed npm packages?
locally installed node modules
* Which kind (and version) of operating system you are running it in?
up to date MacOS
* Any additional information that might be helpful

**Comment by inlife** [comment]
@FinnFrotscher thanks for the report, I'll take a look.

**Comment by inlife** [comment]
@FinnFrotscher could you provide additional information, on which step that error appears. Is this happens when asset is being downloaded, or when the job actually starts rendering?

**Comment by FinnFrotscher** [comment]
sorry for not getting back. i was deep in the weeds. will post today.

**Comment by inlife** [comment]
Sure, no problem

**Comment by FinnFrotscher** [comment]
```
checking After Effects command line renderer patch...
command line patch already is in place
[iiiuVDD_ww31TwkHoYwDu] setting up job...
[iiiuVDD_ww31TwkHoYwDu] working directory is: /Users/finnfrotscher/code/api.renderer/tmp/iiiuVDD_ww31TwkHoYwDu
[iiiuVDD_ww31TwkHoYwDu] downloading assets...
[iiiuVDD_ww31TwkHoYwDu] applying prerender actions...
[iiiuVDD_ww31TwkHoYwDu] running script assemble...
"subtitles"
[iiiuVDD_ww31TwkHoYwDu] rendering job...
error Error: Running Script: /Users/finnfrotscher/code/api.renderer/tmp/iiiuVDD_ww31TwkHoYwDu/nexrender-iiiuVDD_ww31TwkHoYwDu-script.jsx
aerender ERROR: Error executing script: /Users/finnfrotscher/code/api.renderer/tmp/iiiuVDD_ww31TwkHoYwDu/nexrender-iiiuVDD_ww31TwkHoYwDu-script.jsx
TypeError: null is not an object
aerender ERROR: Runtime error in After Effects.
aerender version 17.0.2x26
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched

    at ChildProcess.<anonymous> (/Users/finnfrotscher/code/api.renderer/node_modules/@nexrender/core/src/tasks/render.js:118:31)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

```

**Comment by FinnFrotscher** [comment]
I have made progress in the debugging process. there is a conflict in logic, namely:
in a later part of the render, a custom script is executed where i rely on the original layer name `output.mp4`. but the `replaceFootage` method renames the layer to the name of the input file. thus my script fails. 
i will try to pass the input file name to `NX`

**Comment by FinnFrotscher** [comment]
My assessment was correct and this solution works:

inside `job.js`
```
  {
    src: `file://${context.path}/assets/composition.jsx`,
    type: "script",
    parameters: [
      {
        key: "videoName",
        value:  video.split("/")[video.split("/").length - 1],
      },
    ],
  });
}
```
Inside `composition.jsx`

```
    layerOutput = comp.layer(NX.videoName);
```
