### ISSUE TITLE
Newbie Question: sending an API request from web to Home PC

### ISSUE THREAD

**Issue by chromodome** [inlife/nexrender#310]
First of all, and needless to say but hey I'll say it: Thank you for this amazing project.
I've gotten familiar over the past couple of days with the different ways of rendering, whether nexrender-cli or using nexrender-worker and server. I've managed to send jobs through the API to a server and have it rendered on a worker (different machine), but in a local network.
My question is, what are the requirements to send a job from the web to that server. Obviously i would need the PC's public IP to start right? But would that be enough to make the call? would i need to install any other type of webserver? what about firewall exceptions? would that request be able to communicate with the "home" server directly?
I realize my questions might be trivial, but I don't know where to start.

**Environment:**
Home PC running windows 10 pro
NodeJS installed
nexrender-server running on port 3050

Many Thanks

**Comment by johkon** [comment]
Are you sure, you want to run the server at home? The cheapest VPS for 1€/month is good enough to run nexrender-server reliably. And you don't have any complexity with dynamic dns etc.

**Comment by chromodome** [comment]
Hey johkon. I wanna run it just to understand how it works first.
Regarding your suggestion, would it work then to have the nexrender-server run on a VPS and the nexrender-worker(s) can be local network machines that listen to that server?

**Comment by johkon** [comment]
Yes exactly, the render workers and your template-files can all be local. 😊

**Comment by chromodome** [comment]
Ok. This sounds great. Do you have any recommendations for a cheap VPS that could run nexrender-server?

**Comment by johkon** [comment]
There surely are other options, but I use 1&1 Ionos VPS S for testing. For 1€/month it's dirt cheap and has a fast snapshot function. So if I screw up, I just reset the configuration.

**Comment by inlife** [comment]
hey @chromodome 
as @johkon mentioned, all you need to make such setup work is to have a publicly available IP for the nexrender-server (which is essentially a simple HTTP server running on a port you define).
You can host it on pretty much anything :)

After that, only sky is the limit! You can have local workers, remote workers, and any combination of former running on whatever machines, located in any part of the world, as long as they will be able to send HTTP requests to that `nexrender-server` instance.

So yea, getting a simple super cheap VPS that gives you a static, always available instance is a good start, from that you can expand beyond imagination :D

**Comment by chromodome** [comment]
@johkon just tried IONOS (it's 2$ now, still...)...and it works!
@inlife thx again. One more question (you'll be hearing probably a lot more of me from now on). With such simple 1vCPU servers and barely 1GB ram, what's the load that nexrender-server can take (roughly)? can it handle 10-20-30 concurrent job submissions?

**Comment by inlife** [comment]
job submissions are nothing more than a bunch of HTTP requests with some json in them, now I would not be able to say exact amount of memory nodejs would consume per request, and it might differ per each nodejs version, but I think it should be able to handle even from couple hundred to couple thousand concurrent job submissions
