### ISSUE TITLE
Script block does not support scripts with //@include "script.jsx"

### ISSUE THREAD

**Issue by danielgwilson** [inlife/nexrender#313]
## Current
Currently, script blocks copy script contents into the main nexrender script. This breaks any scripts which use `//@include "script.jsx"` as `script.jsx` isn't copied into the working directory.

## Expected:
All relevant scripts and assets are copied into the working directory.

**Comment by inlife** [comment]
Hey,

Could you also provide an example of such a pair of scripts?

**Comment by danielgwilson** [comment]
> Hey,
> 
> Could you also provide an example of such a pair of scripts?

Sure—

```javascript
// main.js
//@include "/path/to/my/util.js"
var comp = getComp("my-comp");
```

```javascript
// util.js
function getComp(compName) {
  var comp;
  for (var i = 1; i <= app.project.numItems; i++) {
    if (
      app.project.item(i) instanceof CompItem &&
      app.project.item(i).name === compName
    ) {
      comp = app.project.item(i);
      break;
    }
  }
  if (!comp) throw new Error("Failed to find comp named " + compName);
  return comp;
}
```

**Comment by danielgwilson** [comment]
Also, for added clarity—this may actually be better marked as a feature request. This works if you use the full path rather than the local one; i.e.:

```javascript
//@include "util.js" // doesn't work, even if next to original script file
//@include "/full/path/to/my/util.js" // does work under current implementation
```

**Comment by inlife** [comment]
That is indeed a feature request, for some sort of scripting bundler/manager. We will see what we can do with that.

**Comment by danielgwilson** [comment]
> That is indeed a feature request, for some sort of scripting bundler/manager. We will see what we can do with that.

I think there may be a major opportunity here to improve and simplify this library—some early thinking:
- I moved from template literals to JS and @dukuo's #307 which works excellently
- More recently, I've been using JS generated from TypeScript with [Types for Adobe](https://github.com/pravdomil/Types-for-Adobe)
- The above `//@include` approach allows _significantly_ cleaner code separation, and TypeScript prevents unexpected confusion caused by param passing / imports
- This approach was so much cleaner that I have moved to using TypeScript entirely—foregoing the otherwise convenient asset modules like `{ type: "video" ... }` and `{ data: ... }`

What if the scripting modules looked more like the following?

```typescript
job.assets.push({
  type: "script",
  src: "/full/path/to/user/script.js",
  globals: [{ objName: { key: value } }]
});
```

Where the output of nexrender was more like

```javascript
try{Object... // Minified stuff up top

/* start of nexrender script */
//@include "nexrender-util.js"
/* end of nexrender script */

/* start of custom user script */

(function () {
var objName = 
  key: value
};
//@include "/full/path/to/user/script.js"
})();
```

Thoughts?

**Comment by inlife** [comment]
Yes, that is a nice possible way of evolving the scripting environment, I was thinking something of that sort for some time now. The only question that boggles my mind with going deep into scripting "enhancement" is how to make a nice debugging experience.

**Comment by danielgwilson** [comment]
> Yes, that is a nice possible way of evolving the scripting environment, I was thinking something of that sort for some time now. The only question that boggles my mind with going deep into scripting "enhancement" is how to make a nice debugging experience.

Oof, yeah I feel that—I already struggle with the fact that there are no line numbers in the CLI output when an error occurs.

Have you tried TypeScript? I've been generating my .jsx files by using TypeScript and the aforementioned Types for Adobe to great success. Their library is missing quite a few types which are valid in AE, but it's still far superior to vanilla ExtendScript. Doesn't really help much with debugging, though, but it does make it easier to try individual scripts directly in AE.

**Comment by FinnFrotscher** [comment]
Progress?
