### ISSUE TITLE
how to get renderprocess function in Json

### ISSUE THREAD

**Issue by sitestrokes** [inlife/nexrender#316]
Describe your question, attach logs, images or anything that might help to better understand it.
Hello,
below is my JSON file
{
    "template": {
        "src": String,
        "composition": String,

        "frameStart": Number,
        "frameEnd": Number,
        "frameIncrement": Number,

        "continueOnMissing": Boolean,
        "settingsTemplate": String,
        "outputModule": String,
        "outputExt": String,
    },
    "assets": [],
    "actions": {
        "prerender": [],
        "postrender": [],
    },
    "onChange": Function,
    "onRenderProgress": Function
}

can you please tell me how to write "onRenderProgress" function.
I tried but I think i missed something.

I want to show render progress in percentage-wise but I am not getting how to get this?

Thanks.

**Comment by inlife** [comment]
Hello, here is an example:
https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/test/manual.js#L59

However, as you understand it is impossible to do that in json, you would need to do that from a nodejs environment.
