### ISSUE TITLE
Error: Couldn't find a result file

### ISSUE THREAD

**Issue by levathiank1** [inlife/nexrender#318]
Getting this error when i try to use nexrender

`Error: Couldn't find a result file
    at ChildProcess.<anonymous> (C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\render.js)`

The following is my json file:

> {
    "template": {
        "src": "file:///E:/Kinetics-v01/kinetic-titles.aep",
        "composition": "title01-textA"
    },
    "assets": [ {
        "composition": "title01-textA",
        "type": "data",
        "layerName": "test",
        "property": "Source Text",
        "expression": "'Hello'"
        }],
    "actions":{
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "encoded.mp4",
                "output": "E:/Kinetics-v01/myresult.mp4"
            }
        ]
    }
}

I looked the error up on render.js and it seems that the "outputFile" does not exist so it throws this error? but the output path I provided exists.

**Comment by inlife** [comment]
you can check the logs of the AE in the temp folder, and also check if the rendered file actually exists

**Comment by levathiank1** [comment]
> you can check the logs of the AE in the temp folder, and also check if the rendered file actually exists

The log file is empty, it only has the aerender version. The rendered file doesn't exist.

**Comment by inlife** [comment]
something went wrong during rendering inside of after effects
the log should tell about it, at least it usually does

**Comment by levathiank1** [comment]
> something went wrong during rendering inside of after effects
> the log should tell about it, at least it usually does

Fixed by using AE CS6 instead of CC 2019.
