### ISSUE TITLE
Render composition without asset substitution

### ISSUE THREAD

**Issue by phlexib** [inlife/nexrender#321]
**Is your feature request related to a problem? Please describe.**
As part of some pipeline, I'd like to be able to render different compositions from a project within the same job. Some composition might have asset replacement, some not. Right now, if no asset is provided, the Job fails with the following error :
_Error veryifing job: TypeError: Cannot read property 'map' of null_
If an empty Array of empty object is provided , the following error occurs:
_Error veryifing job: AssertionError [ERR_ASSERTION]: job asset must have type defined_

**Describe the solution you'd like**
adding a new flag in the cli **--no-asset** that would bypass the job.assets validation id the "assets" field is empty.
Maybe it's a new asset type "no-data". That would be easier to  implement in the job validation and still ask for the user to be explicit about it to avoid errors with empty "assets" field.

**Describe alternatives you've considered**
- Using aerender directly but we loose the benefits of NexRender binary with ffmpeg.
- Having a dummy asset in the json with some property values that are actually not changing the layer.

**Additional context**
I'm writing a program that automatically creates multiple Json files for the same After Effect project, rendering  different compositions. Sometimes with new data , sometimes not. It would be nice to be able to use nexRender, which by the way is Awesome, to have all the renders in the same pipeline, and also benefits of nexRender packages like encoding, copy,upload...

Thank you so much for the awesome work. And the help.
Ben

**Comment by inlife** [comment]
Hello,

Have you tried providing an empty array for the assets field in the job?
Like this: `"assets": []`

**Comment by phlexib** [comment]
Boom , that works. Nevermind.
Great great work.
Thank you

**Comment by Marcuzzz** [comment]
If I would like to replace a json file in the project is that also possible?
Error veryifing job: AssertionError [ERR_ASSERTION]: unknown job asset type: Json
![Screenshot 2020-04-22 at 11 41 56](https://user-images.githubusercontent.com/7437046/79966865-58e75700-848e-11ea-9d33-744d658b6069.png)
