### ISSUE TITLE
Job rendering failed

### ISSUE THREAD

**Issue by archprateek** [inlife/nexrender#322]
I have a very basic knowledge of AE and Node. On creating an aep file with only an image asset, I tried following the steps mentioned in the document.

**Error I Get**
admin$ sudo nexrender-cli --file /Users/10times-71/Documents/myjob.json --workpath "/Users/10times-71/Documents"
> starting nexrender-cli
using automatically determined directory of After Effects installation:
 - /Applications/Adobe After Effects 2020/aerender
checking After Effects command line renderer patch...
command line patch already is in place
[Tc6GfveDiDAkBnwNdxsWk] setting up job...
[Tc6GfveDiDAkBnwNdxsWk] working directory is: /Users/10times-71/Documents/Tc6GfveDiDAkBnwNdxsWk
[Tc6GfveDiDAkBnwNdxsWk] downloading assets...
[Tc6GfveDiDAkBnwNdxsWk] applying prerender actions...
[Tc6GfveDiDAkBnwNdxsWk] running script assemble...
[Tc6GfveDiDAkBnwNdxsWk] rendering job...
[Tc6GfveDiDAkBnwNdxsWk] rendering took ~4.096 sec.
[Tc6GfveDiDAkBnwNdxsWk] writing aerender job log to: /Users/10times-71/Documents/aerender-Tc6GfveDiDAkBnwNdxsWk.log
[Tc6GfveDiDAkBnwNdxsWk] dumping aerender log:
aerender version 17.0.4x59
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched

> job rendering failed
Error: Couldn't find a result file
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@nexrender/cli/node_modules/@nexrender/core/src/tasks/render.js:137:31)
    at ChildProcess.emit (events.js:321:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**JSON File**

{
"template": {
        "src": "file:////Users/10times-71/Documents/test_logo.aep",
        "composition": "main"
    },
"assets": [
        {
            "src": "https://im.gifbt.com/images/bootlogo.png",
            "type": "image",
            "layerName": "05.png"
        }
        ],
    "actions":{
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "encoded.mp4",
                "output": "/Users/10times-71/Documents/abc.mp4"
            }
        ]
    }

}

I must be doing some basic mistake here which I am not aware of. Can anyone help me with identifying this? TIA.

**Comment by inlife** [comment]
check the result folder, if there is a rendered file (it probably wont exist)
also check the ae render log, there must be some information about why it was not rendered

**Comment by archprateek** [comment]
Neither file is there, nor the render log has any detail.

**Render log**
aerender version 17.0.4x59
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched

I am on mac os and using AE 2020

**Comment by inlife** [comment]
something definitely went wrong with the rendering process, could you try enabling debug mode (via `--debug`)?
there should be a line in the log that displays command that is going to be used to start aerender process, try running that manually

**Comment by ujjwalagrawal17** [comment]
I am also facing the same issue.
```

[Wst6jn7xTW1sFAovkg3ha] error occurred: Error: Couldn't find a result file
    at ChildProcess.instance.on (/usr/local/lib/node_modules/@nexrender/worker/node_modules/@nexrender/core/src/tasks/render.js:143:31)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
```

**Comment by ujjwalagrawal17** [comment]
On running in debug mode I am getting permission error:

aerender Error: After Effects error: Error in output for render queue item 1, output module 1. Can not create a file in directory /tmp/nexrender/P9-5xGz69qJF1RQCSsodA. Try checking write permissions.
aerender version 17.0.5x16

**Comment by ujjwalagrawal17** [comment]
Solved by removing `sudo`
