### ISSUE TITLE
Cloud and Local Setup

### ISSUE THREAD

**Issue by mackenly** [inlife/nexrender#324]
Has anyone ever done a setup with the server being ran in the cloud and worker nodes being ran on a local network? I'd like to run server on the cloud and be able to add different worker clusters at different physical locations for redundancy.

Running workers on cloud servers gets $$$$ really quickly so I'd love to be able to keep the powerful worker machines with me locally.

If this is super simple could anyone point me in the right direction with what to search for? Thanks!

**Comment by inlife** [comment]
Yes, you can install nexrender-server on any cloud platform, and it would manage all your jobs.
After that you can connect as many workers as you need, from any place in the world, including your local machines, just provide a public http host to the server. (Server is a simple tiny http server)

**Comment by mackenly** [comment]
@inlife Thank you!
