### ISSUE TITLE
Don't log scripts to the console

### ISSUE THREAD

**Issue by danielgwilson** [inlife/nexrender#325]
# Current behavior

Line 455 of `script.js` logs the entire script to the logger (defaults to console).
https://github.com/inlife/nexrender/blob/162ad4ab5036d5e623134815a265818f1dbe0dff/packages/nexrender-core/src/tasks/script.js#L455

This is noisy and effectively wipes the console if you have a longer script.

# Expected behavior

Ideally, the logger should not log the entire script

**Comment by inlife** [comment]
@dukuo could you take a look at this?

**Comment by dukuo** [comment]
I completely agree. Should the script be printed in some log level or not at all? Maybe with a flag?

**Comment by danielgwilson** [comment]
I think no; given that the script is already retrievable by not cleaning up the working directory, I don't think it's necessary to support logging the script at all.

—_then again, it could be useful in extremely verbose logs if used for auditing jobs later (where the working directory was already removed)._

**Comment by inlife** [comment]
Script logging was disabled, and will be available in the next release
