### ISSUE TITLE
Improve documentation for settings parameter

### ISSUE THREAD

**Issue by danielgwilson** [inlife/nexrender#326]
I've had to go digging through the source a few times now to remember what settings options are available—it would be nice to get these back in the documentation README.

**Comment by inlife** [comment]
There is some information on core package page https://github.com/inlife/nexrender/tree/master/packages/nexrender-core#information

Is it incomplete? Or maybe it would be a good idea to copy that information to the main readme page as well?

**Comment by danielgwilson** [comment]
Ah, completely missed this—I think either copying it to the main docs or having a more explicit section linking to each package docs page would be nice 👍

**Comment by inlife** [comment]
Added that info, closing the issue! :)
