### ISSUE TITLE
How to install and start the server

### ISSUE THREAD

**Issue by patricktsg** [inlife/nexrender#327]
I'm not sure how I go about getting the server running on my mac. There's no specific docs for this.

**Comment by inlife** [comment]
The best way for me would be to describe it via a screenshot:
![image](https://user-images.githubusercontent.com/2182108/75539039-47e80f80-5a22-11ea-8087-1d7c61ca7b35.png)

**Comment by patricktsg** [comment]
nexrender-server: command not found

**Comment by inlife** [comment]
![image](https://user-images.githubusercontent.com/2182108/75539149-736afa00-5a22-11ea-886c-fd6a192f9f02.png)

**Comment by inlife** [comment]
You would probably need to rename the executable if you want to run it with the command provided above. The instruction It is intended to be cross-platform and assumes that the user will either rename the binary or change the command.

**Comment by patricktsg** [comment]
Not familiar with installing binaries, bit lost :(

**Comment by patricktsg** [comment]
I downloaded the boilerplate and got that running 👍

**Comment by patricktsg** [comment]
Ok, I installed the server globally using npm install -g @nexrender/server and have it running, but now I am trying to get a worker to connect to it but it keeps falling back to trying to connect to localhost

`nexrender-worker host=http://mydevserver.com:3050 --secret=myapisecret`

` message: 'request to http://localhost:3000/api/v1/jobs/pickup failed, reason: connect ECONNREFUSED 127.0.0.1:3000`

**Comment by inlife** [comment]
do you actually need a networked worker + server setup?
maybe `nexrender-cli` is what you are looking for?

**Comment by patricktsg** [comment]
I will need networked. I have a server running now but need to setup 3-4 workers to poll jobs from that server

**Comment by inlife** [comment]
oh ok
btw in the example you showed above of worker command, you provide host argument without 2 dash symbols
it should be
```sh
$ nexrender-worker --host="https://mydevserver.com:3050" --secret="myapisecret"
```

**Comment by patricktsg** [comment]
Awesome! Thank you so much
