### ISSUE TITLE
aerender ReferenceError: PREFType is undefined

### ISSUE THREAD

**Issue by pushpendrabansal** [inlife/nexrender#333]
starting nexrender-cli
checking After Effects command line renderer patch...
command line patch already is in place
[eGc8ptnHoPH0rG-7MjV6j] setting up job...
[eGc8ptnHoPH0rG-7MjV6j] working directory is: C:\Users\BANSAL~1\AppData\Local\Temp\2\nexrender\eGc8ptnHoPH0rG-7MjV6j
[eGc8ptnHoPH0rG-7MjV6j] downloading assets...
[eGc8ptnHoPH0rG-7MjV6j] applying prerender actions...
[eGc8ptnHoPH0rG-7MjV6j] running script assemble...
[eGc8ptnHoPH0rG-7MjV6j] rendering job...
[eGc8ptnHoPH0rG-7MjV6j] rendering took ~19.505 sec.
[eGc8ptnHoPH0rG-7MjV6j] writing aerender job log to: C:\Users\BANSAL~1\AppData\Local\Temp\2\nexrender\aerender-eGc8ptnHoPH0rG-7MjV6j.log
[eGc8ptnHoPH0rG-7MjV6j] dumping aerender log:
aerender version 10.0x458
Running Script: C:\Users\BANSAL~1\AppData\Local\Temp\2\nexrender\eGc8ptnHoPH0rG-7MjV6j\nexrender-eGc8ptnHoPH0rG-7MjV6j-script.jsx
**aerender ReferenceError: PREFType is undefined

> job rendering failed
Error: Couldn't find a result file**
    at ChildProcess.<anonymous> (C:\Users\bansalpunitib\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\render.js:143:31)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by pushpendrabansal** [comment]
I tried reinstalling after effects. By aerender it was working fine but on using nexrender cli first time
![Screenshot from 2020-03-04 12-57-59](https://user-images.githubusercontent.com/13747857/75855311-fc65a500-5e17-11ea-983f-a74d49576964.png)


It's asking to run as admin manager then after for both nexrender and aerender it showing sane error - PREFType is undefined

**Comment by inlife** [comment]
Oh, I'm not sure that CS5 is even supported, it is a bit old isn't?

**Comment by pushpendrabansal** [comment]
Yeah it working fine now after upgrade

Thanks.
