### ISSUE TITLE
@nexrender/action-upload : credentials error.

### ISSUE THREAD

**Issue by pushpendrabansal** [inlife/nexrender#336]
I am trying to upload video output on s3 but its showing @nexrender/action-upload : credentials error.

but aws key, secret key, region name everything is fine.

![Capture](https://user-images.githubusercontent.com/13747857/76313838-a5574880-62cd-11ea-891c-1ea1b979d766.PNG)

**Comment by chromodome** [comment]
How did you set your AWS and Secret key?
Here's a link on how to do it :
[](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html)

on windows, just got to your C:\users\[user] folder
make a folder name ".aws" (yes with a dot) then create a file named "credentials" without any extensions.
Inside drop the following

```
[default]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```

**Comment by pushpendrabansal** [comment]
It worked Thanks @chromodome
