### ISSUE TITLE
Converting aep file to aepx file

### ISSUE THREAD

**Issue by aysimakarca** [inlife/nexrender#337]
Hi,

Is there a way to convert aep file to aepx file programmatically? I get aep projects from customers and there is much to do with aepx like finding layer names etc, but i cant do anything manual like opening AE GUI so i need to find a way to get aepx file from aep. Do you know if i can run AE and save project as aepx programmatically or is there any other way to do that?

Thank you,

**Comment by inlife** [comment]
Hey,

You can try to check if there is an option to make use of scripting to achieve that, and if that is the case, use afterfx.exe to run a script that would do that.
