### ISSUE TITLE
How to target Source Text of Layer inside a Composition in the Composition

### ISSUE THREAD

**Issue by patricktsg** [inlife/nexrender#339]
The AE file I have contains a 'main' composition, in this I have a couple of basic text fields, but also a composition called 'myComposition' which has source text in I wish to change. How do I target that source text in my assets definition?

`
         {
            value: 'Angry Cat',
            type: 'data',
            composition: 'myComposition'
            layerName: 'personName',
            property: 'Source Text'
          },`

**Comment by inlife** [comment]
the piece of code you provided should work just fine
another way is to target all compositions by using `*`symbold
