### ISSUE TITLE
php exec

### ISSUE THREAD

**Issue by kick-push** [inlife/nexrender#34]
I currently have a website that allows a user to add text which then uses php to create the txt file and calls php.exec to call the nexrender start.js (and uses the text file as data for the project)

However if 2 people use this concurrently it breaks it as i don't think it is capable of running php exec multiple times at once on the command line. Would you recommend creating a server instead?

I'm not really sure where to start in setting this up...

I need the video returned back to the user on the server once it is rendered which is proving quite difficult. Any help would be greatly appreciated.

**Comment by Inlife** [comment]
well, first of all, the nature of application (and node js) is more or less asynchronous
so i would recommend you to make page kinda in not-blocking manner:
user loads a page, presses a button - request sent to start rendering, then he is polling every 1 sec (or more/less) and checks whether or not his video was rendered

also, for the backend web part i would recommend to use nodejs (you are using it anyway)
and use nexrender in separate `api-server` and `render node` mode.
this way you will be able to talk to api server, to queue new projects, and to check whether  or not they've been rendered already
`nexrender api` (for nodejs) even gives you nifty callbacks for that

so you will be able to queue as many projects as you can, and even move or scale amount of your render nodes with multiple instances or different machines

the easiest way i see it, to install nexrender globally and run api server and render node (as i showed in the article)
https://medium.com/@inlife/guide-to-after-effects-automation-and-personalization-6039e9fa10d1

and then just put rendered video into a public directory, available for webserver, and as a result for user to download
and notify him using his constant polling the webserver via ajax
or push him information about this via websocket/socket.io

there are planty ways to do this, my recommendation is to use nodejs stack
