### ISSUE TITLE
Templater vs Nexrender

### ISSUE THREAD

**Issue by matteoraggi** [inlife/nexrender#340]
Describe your question, attach logs, images or anything that might help to better understand it.
Is templater more easy and documented of Nexrender? Is it mroe easy too? in what precisely Templater give more features?

**Comment by inlife** [comment]
Hey,

I feel like that is something you can understand better by visiting Dataclay's website: https://dataclay.com/templater/

**Comment by matteoraggi** [comment]
How tempalter and nexrender can work together?

**Comment by inlife** [comment]
I, personally, haven't tried so I can't say for sure. However, I remember one user saying that he is able to use both successfully, and with great benefit to his project. 

So I think in theory it should be possible.
