### ISSUE TITLE
Can I run multiple nexrender workers on a big machine? 

### ISSUE THREAD

**Issue by ujjwalagrawal17** [inlife/nexrender#341]
Can I run multiple workers on a big machine? Will it be able to do 2 tasks parallely in nearly same time?

**Comment by ujjwalagrawal17** [comment]
How many workers can I run in a 4 core 16GB Windows machine to get maximum output?

**Comment by inlife** [comment]
Hello @ujjwalagrawal17,

All of that technically depends on your After Effects settings. If it has multi-thread rendering enabled, it will use multiple cores for a single rendering job. The same applies for memory settings. Set those up to your needs, and from there you will be able to figure out how many simultaneous jobs you can sustain with a given "hardware" configuration.

Cheers!

**Comment by ujjwalagrawal17** [comment]
Thanks @inlife I will try out that.
