### ISSUE TITLE
Video tutorials

### ISSUE THREAD

**Issue by matteoraggi** [inlife/nexrender#343]
Online I found only this tutorial about nexrender, are there others online that I didn't found? 
https://www.youtube.com/watch?v=E64dXZ_AReQ
Any plans to publish more video tutorial about nexrender?

**Comment by inlife** [comment]
That video tutorial is not "official" per se, it was made by a member of our community. No plans to publish anything from my side. 

However, I just hope someday new videos will pop up just like this one did from other members of the community as well. :)

Cheers!
