### ISSUE TITLE
cli server and worker

### ISSUE THREAD

**Issue by matteoraggi** [inlife/nexrender#344]
About the Server and Worker I found some infos, 
https://github.com/inlife/nexrender#nexrender-server
https://github.com/inlife/nexrender#nexrender-worker
but it is not so much clear to me how they works yet..
Plus I found about nothing about the client.
could you pelase explain me in simple word which is the connection between these 3 type of binaries?

**Comment by inlife** [comment]
Made a picture that might explain a bit how things work for network rendering:

![network_rendering](https://user-images.githubusercontent.com/2182108/77616726-02443700-6f3b-11ea-8e27-b59656d9efe1.png)

**Comment by matteoraggi** [comment]
Thanks, great! but where is the cli in this picture?

**Comment by inlife** [comment]
cli is not there since its self-contained local renderer, without networking part
it is useful for local, single instance rendering

**Comment by jonnymangothinkjam** [comment]
i think it's more getting the server and the workers running so we can run through the examples

nexrender-server \
        --port=3050 \
        --secret=myapisecret

more info just takes you to the package, which is great, but all the other examples have an install command too, npm i --save @nexrender/action-copy for example

I've downloaded the packages and done npm i on both, tried npm run start on the server (which seems to start it)

just not sure how to communicate with the two, again running nexrender-worker -h in terminal results in nexrender-worker: command not found

am i misunderstanding installing the two packages?

**Comment by inlife** [comment]
Option 1: Download compiled binaries directly from releases section of this repo
Option 2: Manually install npm packages for each application with all optional modules you wish to have

To install worker you need to run: ```npm i @nexrender/worker ... -g``` 
Where `...` is any additional module you wish to have installed, like `@nexrender/action-copy`
