### ISSUE TITLE
nexrender-server-linux must be installed ona vps or it work on shared hosting too?

### ISSUE THREAD

**Issue by matteoraggi** [inlife/nexrender#345]
Hi, nexrender-server-linux must be installed ona vps or it works on shared hosting too?

**Comment by inlife** [comment]
Well, you would need an environment that supports interactive cli, to start the process. So, shared hosting, at least in the meaning that I understand won't work.

**Comment by matteoraggi** [comment]
And what about the cli? it needs a vps too?

**Comment by inlife** [comment]
cli is an interactive console wrapper around nexrender core, which means yes, it would need a vps
however since its a rendering process, it would require windows/macos vps
