### ISSUE TITLE
Multiple data, multiple videos

### ISSUE THREAD

**Issue by piskello** [inlife/nexrender#346]
Hi, I'm writing after I've searched through the issues, as well as on the internet, but I did not found the answer, so in case sorry it was already asked, sorry in advance :)
I wonder how to structure the JSON files so nexrender renders multiple videos, with different data. For instance, given the data below
city 1,  temp 25
city 2, temp 30
city 3, temp 16

I would have three different outputs
video1.mp4 which features "City 1" as text and its relative temperature (25)
video2.mp4 which features "City 2" as text and its relative temperature (30)
video3.mp4 which features "City 3" as text and its relative temperature (16)

I currently tried as below, but it is not working...

Thank you in advance,
Matteo

"assets": [
        {
            "type": "data",
            "layerName": "city",
            "property": "Source Text",
            "value": "City 1"
        }
    ],
    "actions": {
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "/Users/home/Desktop/city1.mp4"
            }
        ]
    },
    "assets": [
        {
            "type": "data",
            "layerName": "txt",
            "property": "Source Text",
            "value": "City 2"
        }
    ],
    "actions": {
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "/Users/home/Desktop/city2.mp4"
            }
        ]
    }

**Comment by inlife** [comment]
For that you would need to create 3 separate jobs, providing required assets for each one, and then render them separately.
