### ISSUE TITLE
where are myproject.aep and audio file and the background music?

### ISSUE THREAD

**Issue by matteoraggi** [inlife/nexrender#347]
I have inserted this code into myjob.json: 
`// myjob.json
{
    "template": {
        "src": "file:///users/myuser/documents/myproject.aep",
        "composition": "main"
    }
}`

Do you know from where the file myproject.aep come rom?

If I run this command nexrender-server-win64.exe --file myjob.json
Then I get this error:
`C:\snapshot\nexrender-server\node_modules\arg\index.js:90
                                                throw err;
                                                ^

Error: Unknown or unexpected option: --file
    at arg (C:\snapshot\nexrender-server\node_modules\?[4marg?[24m\index.js:88:1
9)
    at Object.<anonymous> (C:\snapshot\nexrender-server\src\bin.js)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10
)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:813:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:14)?[39m
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
?[90m    at internal/main/run_main_module.js:17:11?[39m {
  code: ?[32m'ARG_UNKNOWN_OPTION'?[39m
}`

Here the screenshot of what I have done till now:
https://matteoraggi-gmail.tinytake.com/tt/NDE2ODUzMF8xMjkxMzE3Mg

**Comment by matteoraggi** [comment]
Ok the author has sent me the .aep file, but I still receive the same error:
the file myjob.json looks like thi:
`{
    "template": {
        "src": "project.aep",
        "composition": "main"
    }
}`
and then  running this command:

> nexrender-server-win64.exe --file myjob.json

I receive this answer:
`E:\NEW-CLIENTS\matteo\Contabo\auto\TODO\nexrender>nexrender-server-win64.exe --f
ile myjob.json
C:\snapshot\nexrender-server\node_modules\arg\index.js:90
                                                throw err;
                                                ^

Error: Unknown or unexpected option: --file
    at arg (C:\snapshot\nexrender-server\node_modules\?[4marg?[24m\index.js:88:1
9)
    at Object.<anonymous> (C:\snapshot\nexrender-server\src\bin.js)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10
)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:813:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:14)?[39m
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
?[90m    at internal/main/run_main_module.js:17:11?[39m {
  code: ?[32m'ARG_UNKNOWN_OPTION'?[39m
}`
**Error: Unknown or unexpected option: --file**

**Comment by inlife** [comment]
You need to be using `nexrender-cli`, not a `nexrender-server`
