### ISSUE TITLE
Using Prerendering composition with nexrender

### ISSUE THREAD

**Issue by afsadmalik** [inlife/nexrender#348]
I have an after effect project with 13 composition merged into one final composition containing all these composition. Out of these 13 composition, 5 composition are static and i need the same to be prerendered to reduce the rendering time of final composition ? is it possible in nexrender ?

**Comment by inlife** [comment]
well not really, closest thing that comes to my mind is:
you pre-render those static compositions as videos and store them somewhere, and then after rendering the needed dynamic comps, you can combine them together via ffmpeg
