### ISSUE TITLE
Composition is not selected properly (jsx)

### ISSUE THREAD

**Issue by TimP4w** [inlife/nexrender#350]
**Describe the bug**
Choosing a composition doesn't actually have any effect on the generated JSX.
The composition is set as the renderCompositionName:

```
          renderCompositionName: "MyComp",
          defaultCompositionName: "*",
```

But  this is never passed to `nexrender.selectLayersByName` 

see: `nexrender.selectLayersByName(null, "URL", function(layer) {`

and therefore it will use "*" because of this line
```
if (!compositionName)
            compositionName = nexrender.defaultCompositionName;
```

The problem arises when a template has multiple compositions and those have different layers.
In my case, I was trying to replace a media layer on a composition which wasn't the default one and I always got `error: Unable to Render: File Not Found`. I assume it's because the layers are different in the two compositions and the source was replaced only in the first one while I was trying to render the second.

**Information about environment**
* Which version of nexrender are you using? "@nexrender/core": "^1.8.4",
* What kind of the setup do you have? (server+worker or cli): core
* Are you using pre-built binaries or globally installed npm packages?: NPM
* Which kind (and version) of operating system you are running it in?: Mac OS X (latest)
* Any additional information that might be helpful

**Expected behavior**
Choosing a composition will actually make the JSX match the layer with the composition chosen.

**Comment by TimP4w** [comment]
UPDATE: neverming, bumped to 1.12.1 and it works

**Comment by TimP4w** [comment]
UPDATE: I leave this open because by bumping the nexrender-core version my problem was fixed, but I'm still not convinced that this works as it is supposed to. I'm going to investigate in the next days

**Comment by inlife** [comment]
hey @TimP4w were there any updates?

**Comment by TimP4w** [comment]
@inlife sadly I didn't have much time this past month to fix this. I can only confirm that this is indeed a bug, in the sense that all the layers are searched in the "*" composition. 

I will try to provide a PR in the next days. One important thing, in order not to break existing systems, is to check if a layer is present in either the render composition or try to fallback to the default ("*") and only if it's missing in both to throw an error.

**Comment by TimP4w** [comment]
@inlife well... my bad :/ this is actually the expected behaviour. 

Just had another read at the docs and found:

> composition: string, composition where the layer is, useful for searching layer in specific compositions. If none is provided, it uses the wildcard composition "*", that will result in a wildcard composition matching, and will apply this data to every matching layer in every matching composition.

**Comment by inlife** [comment]
oh, everything seems ok then :)
