### ISSUE TITLE
Error: Couldn't find module @nexrender/provider-c, Unknown protocol provided.

### ISSUE THREAD

**Issue by matteoraggi** [inlife/nexrender#351]
Here my first experience with nexrender cli:
myjob.json has  the following things in it:
`{
    "template": {
        "src": "C:/Users/DEBASHIS ROY/OneDrive/Desktop/nexrender/project.aep",		
        "composition": "main"
    }
}`
then running the following command
nexrender-cli-win64.exe --skip-cleanup --file myjob.json
Then I got the following messages
`> starting nexrender-cli
using automatically determined directory of After Effects installation:
 - C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe
checking After Effects command line renderer patch...
command line patch already is in place
[9pSh-KemhZW_hf1SOu2u5] setting up job...
[9pSh-KemhZW_hf1SOu2u5] working directory is: C:\Users\DEBASH~1\AppData\Local\Temp\nexrender\9pSh-KemhZW_hf1SOu2u5
[9pSh-KemhZW_hf1SOu2u5] downloading assets...
> job rendering failed
Error: Couldn't find module @nexrender/provider-c, Unknown protocol provided.
    at download (C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\download.js)
    at C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\download.js
    at C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\helpers\state.js
    at C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\index.js
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:62:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1317:13)
    at internal/main/run_main_module.js:17:11`
https://matteoraggi-gmail.tinytake.com/tt/NDE4MTE4Ml8xMjk3NDIyMA

**Comment by inlife** [comment]
As you might've noticed, src follows URI specification and requires the string to be formatted accordingly. Take a look at this example of the job (specifically `job.template` part): https://github.com/inlife/nexrender#assets

**Comment by matteoraggi** [comment]
now myjob.json looks like below
===================
```
{
    "template": {
        "src": "file:///C:/nexrender/project.aep",
        "composition": "main"
    }
}
```
answer:
`nexrender-cli-win64.exe --skip-cleanup --file myjob.json
> starting nexrender-cli
using automatically determined directory of After Effects installation:
 - C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe
checking After Effects command line renderer patch...
command line patch already is in place
[AlskhRriltRWaUskfH6Sw] setting up job...
[AlskhRriltRWaUskfH6Sw] working directory is: C:\Users\DEBASH~1\AppData\Local\Temp\nexrender\AlskhRriltRWaUskfH6Sw
[AlskhRriltRWaUskfH6Sw] downloading assets...
[AlskhRriltRWaUskfH6Sw] applying prerender actions...
[AlskhRriltRWaUskfH6Sw] running script assemble...
[AlskhRriltRWaUskfH6Sw] rendering job...
[AlskhRriltRWaUskfH6Sw] rendering took ~15.214 sec.
[AlskhRriltRWaUskfH6Sw] writing aerender job log to: C:\Users\DEBASH~1\AppData\Local\Temp\nexrender\aerender-AlskhRriltRWaUskfH6Sw.log
[AlskhRriltRWaUskfH6Sw] dumping aerender log:
aerender version 17.0.2x26
Using DXGI: Device: "Intel(R) HD Graphics 5500" has dedicated video RAM (MB): 128 and has shared video RAM (MB): 8147 (Total: 8275 MB)
Skipping DX support for pre-Skylake Intel GPU.
    name                                    : AMD Radeon R7 M270
    VendorId                                : 4098
    DeviceId                                : 26116
    SubSysId                                : 107941928
    Revision                                : 0
    DedicatedVideoMemory                    : 4273061888
    DedicatedSystemMemory                   : 0
    SharedSystemMemory                      : 8543629312
    MemoryBudget                            : 3632102604
    AdapterLuid.LowPart                     : 45063
    AdapterLuid.HighPart                    : 0
    Flags                                   : 0
        DoublePrecisionFloatShaderOps           : yes
        ConservativeRasterizationTier           : 0
        CrossNodeSharingTier                    : 0
        ResourceBindingTier                     : 3
        ResourceHeapTier                        : 2
        TiledResourcesTier                      : 1
        NodeIndex                               : 0
        TileBasedRenderer                       : no
        UMA                                     : no
        CacheCoherentUMA                        : no
        feature level                           : 0x00009100
        feature level                           : 0x00009200
        feature level                           : 0x00009300
        feature level                           : 0x0000a000
        feature level                           : 0x0000a100
        feature level                           : 0x0000b000
        feature level                           : 0x0000b100
        feature level                           : 0x0000c000
        feature level                           : 0x0000c100
        MaxSupportedFeatureLevel                : 0x0000b100
        HighestShaderModel                      : 0x51
        WaveOps                                 : no
        WaveLaneCountMin                        : 4
        WaveLaneCountMax                        : 4
        TotalLaneCount                          : 4
        ExpandedComputeResourceStates           : yes
        Int64ShaderOps                          : no
        RootSignature.HighestVersion            : 0x2
Skipping DX support: Microsoft Basic Render Driver
WARNING:After Effects warning: Grouped_Message_{This project contains references to missing effects. Please install the following effects to restore these references.|||This project contains a reference to a missing effect. Please install the following effect to restore this reference.###@0 missing effects.}Particular
WARNING:After Effects warning: Grouped_Message_{This project contains references to missing effects. Please install the following effects to restore these references.|||This project contains a reference to a missing effect. Please install the following effect to restore this reference.###@0 missing effects.}Saber
WARNING:After Effects warning: Grouped_Message_{This project contains references to missing effects. Please install the following effects to restore these references.|||This project contains a reference to a missing effect. Please install the following effect to restore this reference.###@0 missing effects.}Sound Keys
WARNING:After Effects warning: Project has missing fonts.

Running Script: C:\Users\DEBASH~1\AppData\Local\Temp\nexrender\AlskhRriltRWaUskfH6Sw\nexrender-AlskhRriltRWaUskfH6Sw-script.jsx
aerender ERROR: No comp was found with the given name.

> job rendering failed
Error: Couldn't find a result file
    at ChildProcess.<anonymous> (C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\render.js)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)`

**Comment by inlife** [comment]
The error that appears is:
> aerender ERROR: No comp was found with the given name.

Please, check if you are using the correct composition name from your aep project.

**Comment by matteoraggi** [comment]
Where do we have to put the composition name?

**Comment by inlife** [comment]
Right there: 
![Uploading image.png…]()

**Comment by deb4it** [comment]
Hi @inlife 
yes we have used      
{
    "template": {
        "src": "file:///C:/nexrender/project.aep",
        "composition": "main"
    }
}

what should be the value of this to resolve this error

**"Running Script: C:\Users\DEBASH~1\AppData\Local\Temp\nexrender\AlskhRriltRWaUskfH6Sw\nexrender-AlskhRriltRWaUskfH6Sw-script.jsx
aerender ERROR: No comp was found with the given name. "**

**Comment by deb4it** [comment]
Hi @inlife 
I and @matteoraggi  are working together. Thanks for your helps. 
Please response for 
![image](https://user-images.githubusercontent.com/10611035/78265478-4b415000-7526-11ea-80f7-3a145811841b.png)

Please help use get ur software up and running for us. we are novice guys to this things.

**Comment by inlife** [comment]
Hi @deb4it 

Please read very carefully, and don't ask the same question that I already answered above for the **3rd** time:

> aerender ERROR: No comp was found with the given name. 

Your error message states that After Effects could not find a composition with a given name in your aep/aepx file. That means that you need to provide a different value.

To do that you need to change that value in your json job. Change `"composition": "main"`, to a composition name that your aep/aepx project actually has created.

**Comment by rsm0128** [comment]
Thank you really
