### ISSUE TITLE
nexrender/api New Feature Request: onChange and onRenderProgress in is not getting called (network call)

### ISSUE THREAD

**Issue by ujjwalagrawal17** [inlife/nexrender#355]
**Describe the bug**
OnChange and onProgressChange in nexrender/api is not getting called. 

**Information about environment**
I am using nodeJS and nexrender/api module to send request to nextender server. The workers are printing the progress in the terminal but in my node app. the functions are not getting called. 

> 
> const { createClient } = require("@nexrender/api");
> 
> const client = createClient({
>   host: "http://localhost:3050",
>   secret: "myapisecret",
>   polling: 1000
> });
> 
> const main = async data => {
>   let assets = data["data"];
>   let aep_url = data["aep_file_path"];
>   let video_card_id = data["card_id"];
>   let composition = data["composition"];
>   console.log("data");
> 
>   const result = await client.addJob({
>     template: {
>       src: aep_url,
>       composition: composition
>     },
>     assets: assets,
>     actions: {
>       postrender: [
>         {
>           module: "@nexrender/action-encode",
>           preset: "mp4",
>           // output: "encoded.mp4",
>           // output: "C:/Users/cntest/Desktop/woohoo/encodednew.mp4"
>           output: "/Users/ujjwalagrawal/Desktop/dynamic-video1.mp4"
>         },
>         {
>           input: "/Users/ujjwalagrawal/Desktop/dynamic-video1.mp4",
>           module: "nexrender-worker-s3",
>           card_id: video_card_id
>         }
>       ]
>     },
>     onChange: function(render) {
>       console.log(render.uid);
>       console.log(render.state)
>     },
>     onRenderProgress: function(job, value) {
>       console.log(job);
>       console.log(value)
>     }
> 
>         // (job, value) =>
>         // console.log("testing onRenderProgress:", value)
>   });
> 

**Expected behaviour**

**Screenshots**

<img width="652" alt="Screen Shot 2020-04-04 at 6 15 25 am" src="https://user-images.githubusercontent.com/19607555/78414840-c2b4d380-763b-11ea-8248-4065977b0675.png">
<img width="584" alt="Screen Shot 2020-04-04 at 6 15 34 am" src="https://user-images.githubusercontent.com/19607555/78414841-c3e60080-763b-11ea-85ea-6bd0c3c483b3.png">

**Comment by ujjwalagrawal17** [comment]
the nextender worker and server are working as expected but the callbacks are not working properly.

@inlife can you have a look and tell me if I am missing something.

**Comment by ujjwalagrawal17** [comment]
since we are already doing polling. Can we not get the rendering percentage of the video in the workers in the callback similar to status?

Along with created, started, finished and error, adding 1 more option will do the work 1 think.

**Comment by ujjwalagrawal17** [comment]
roject rendering finished { uid: 'OV4c7aX9vi21D6hFX1gJZ',
  type: 'default',
  state: 'finished',
  output:
   '/var/folders/bk/n20xrzl149l1lvhn6c69pl4m0000gn/T/nexrender/OV4c7aX9vi21D6hFX1gJZ/result.mov',
  template:
   { src: 'file:///Users/ujjwalagrawal/Desktop/std/std.aep',
     composition: 'final_render',
     dest:
      '/var/folders/bk/n20xrzl149l1lvhn6c69pl4m0000gn/T/nexrender/OV4c7aX9vi21D6hFX1gJZ/std.aep' },
  assets:
   [  ],
  actions: { postrender: [ [Object], [Object] ] },
  updatedAt: '2020-04-04T00:56:26.548Z',
  resultname: 'result.mov',
  workpath:
   '/var/folders/bk/n20xrzl149l1lvhn6c69pl4m0000gn/T/nexrender/OV4c7aX9vi21D6hFX1gJZ',
  scriptfile:
   '/var/folders/bk/n20xrzl149l1lvhn6c69pl4m0000gn/T/nexrender/OV4c7aX9vi21D6hFX1gJZ/nexrender-OV4c7aX9vi21D6hFX1gJZ-script.jsx',
  renderProgress: 52 }


I am getting progress: 52%, when the whole rendering is completed. I want to get every single change in 500ms/200ms.

**Comment by ujjwalagrawal17** [comment]
@inlife can you have a look the problem.

**Comment by inlife** [comment]
Hey

>since we are already doing polling. Can we not get the rendering percentage of the video in the workers in the callback similar to status?

Funny thing is that the worker->server progress report feature is supposed to be working properly. And from your report, it seems that it does not. Also seems like there is some confusion in regards to which callbacks are available and where; I'll try to explain that stuff a little better in the documentation.

https://github.com/inlife/nexrender/blob/master/packages/nexrender-worker/src/index.js#L62-L73

To quickly answer your question, I believe that onChange and onRenderProgress are available only on render side platform (using cli, program render, inside worker), and are not dispatched via the network.

I'll try also to take a look at the progress reporting, and why it might not send updates to the server. Can you also answer me what is your total render time for the composition, and how small is the delay between each percent of the progress? Possibly that I was testing on a project that had much longer delays and that was the reason it worked fine for me.

**Comment by TimP4w** [comment]
Had a similar problem with the "core" version, but it went away with the latest updates (not sure exactly which one, but after a bump it started working).

**Comment by ujjwalagrawal17** [comment]
Thanks, @inlife for the detailed explanation, would we like to have a feature to have a network call for the same? I can try and send a PR if we think that is a good option. 

Most people won't need to write any code in the worker in that case (apart from configuration). I initially thought getting the progress, status is a very basic feature and should be available in the API (I think all people using nex-render will want to see the progress of the video that is rendering to show it to the end-user in Web/Mobile Apps).


My total rendering time of this video was around 7 minutes.

**Comment by inlife** [comment]
>  I can try and send a PR if we think that is a good option.

I don't see why not. The rendering time seems to be one of the most requested features for the nexrender, for the past 4 years. 😄 

P.S. sorry for the long response

**Comment by clotyxf** [comment]
> **Describe the bug**
> OnChange and onProgressChange in nexrender/api is not getting called.
> 
> **Information about environment**
> I am using nodeJS and nexrender/api module to send request to nextender server. The workers are printing the progress in the terminal but in my node app. the functions are not getting called.
> 
> > const { createClient } = require("@nexrender/api");
> > const client = createClient({
> > host: "http://localhost:3050",
> > secret: "myapisecret",
> > polling: 1000
> > });
> > const main = async data => {
> > let assets = data["data"];
> > let aep_url = data["aep_file_path"];
> > let video_card_id = data["card_id"];
> > let composition = data["composition"];
> > console.log("data");
> > const result = await client.addJob({
> > template: {
> > src: aep_url,
> > composition: composition
> > },
> > assets: assets,
> > actions: {
> > postrender: [
> > {
> > module: "@nexrender/action-encode",
> > preset: "mp4",
> > // output: "encoded.mp4",
> > // output: "C:/Users/cntest/Desktop/woohoo/encodednew.mp4"
> > output: "/Users/ujjwalagrawal/Desktop/dynamic-video1.mp4"
> > },
> > {
> > input: "/Users/ujjwalagrawal/Desktop/dynamic-video1.mp4",
> > module: "nexrender-worker-s3",
> > card_id: video_card_id
> > }
> > ]
> > },
> > onChange: function(render) {
> > console.log(render.uid);
> > console.log(render.state)
> > },
> > onRenderProgress: function(job, value) {
> > console.log(job);
> > console.log(value)
> > }
> > ```
> >     // (job, value) =>
> >     // console.log("testing onRenderProgress:", value)
> > ```
> > 
> > 
> > });
> 
> **Expected behaviour**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> 
> <img alt="Screen Shot 2020-04-04 at 6 15 25 am" width="652" src="https://user-images.githubusercontent.com/19607555/78414840-c2b4d380-763b-11ea-8248-4065977b0675.png">
> 
> <img alt="Screen Shot 2020-04-04 at 6 15 34 am" width="584" src="https://user-images.githubusercontent.com/19607555/78414841-c3e60080-763b-11ea-85ea-6bd0c3c483b3.png">

how do display the [xxxx] rendering progress x% of nexrender-worker?

**Comment by inlife** [comment]
@clotyxf not sure I understand the question
