### ISSUE TITLE
Error after rendering: EISDIR - Illegal operation on directory

### ISSUE THREAD

**Issue by shinylab** [inlife/nexrender#357]
Hi, having an issue after rendering (rendering is fine so far) but job fails anyway.
Here is the error I get:

> job rendering failed
Error: Error loading postrender module @nexrender/action-copy: Error: EISDIR: illegal operation on a directory, open '/Users/steve/Desktop/TEMP/NEXRENDERTESTS/'
    at /snapshot/nexrender/packages/nexrender-cli/node_modules/@nexrender/core/src/tasks/actions.js

I managed to resolve myself a couple of errors before that, but so far I'm stuck with this one.
I'm using this version on macos:
  nexrender-cli - nexrender standalone renderer
  version - v1.12.1

Any idea how to solve this?
Many thanks :)

**Comment by shinylab** [comment]
Bram97 helped me resolve this :) - Thank you!

**Comment by inlife** [comment]
what was the reason @shinylab for that error?
