### ISSUE TITLE
Layer and Effect Selection

### ISSUE THREAD

**Issue by yogesh030** [inlife/nexrender#358]
Describe your question, attach logs, images or anything that might help to better understand it.
Hi.

I am trying to set the Effects.Hue/Saturation.Master Hue Value and i am using this block

   {
			 "type": "data",
            "layerName": "CC",
            "property": "Effects.Hue/Saturation.Master Hue",
			"value": [-85,-219]
          }

as master hue value can go negative as well.

Project Config:
https://gyazo.com/395f70ea446cbe44d23df5ae43f0e034

Error:

Error: After Effects error: Unable to call setValue because of parameter 1. Array is not a number.
aerender ERROR: Runtime error in After Effects.

If i give single positive value then i get this error:

Error: nexrender: Can't find a property sequence Hue/Saturation.Master Hue for key: Hue/Saturation
aerender ERROR: Runtime error in After Effects

If i try via layer index or anything then it gives cant find layer error. 

Any Help is really appreciated.

**Comment by yogesh030** [comment]
@inlife I have sent you msg via FB as well. Do check it..

**Comment by yogesh030** [comment]
https://gyazo.com/10be3c0156402b80e4c3ae15c57cd9a7

above is another example.

**Comment by inlife** [comment]
Seems to me that the first error message is the important one
```
After Effects error: Unable to call �setValue� because of parameter 1. Array is not a number.
```

Try changing asset value from an array `[-85,-219]` to a single value `85` so it would look like that:
```js
{
    "type": "data",
    "layerName": "CC",
    "property": "Effects.Hue/Saturation.Master Hue",
    "value": -85
}
```
