### ISSUE TITLE
Latest Version for Windows is Incorrect

### ISSUE THREAD

**Issue by yogesh030** [inlife/nexrender#359]
Hi.

I tried to download latest version for windows but when ran with command -v it gives version 1.12.1

It should be 1.12.3 right?

Also the render progress was reporting earlier but now it isnt reporting any render progress. i really miss it and really want it. Any Help will be greatful.

**Comment by inlife** [comment]
That is not a major bug, but rather they way how lerna updates package version when dependencies change and the main one does not. I'll think on possible ways of fixing that.

Cheers!
