### ISSUE TITLE
Eperm : operation not permitted, unlink error is coming sometimes

### ISSUE THREAD

**Issue by pushpendrabansal** [inlife/nexrender#367]
Hey I am using nexrender server/worker and api sometimes result is shwoing error below but video render complete and uploaded to s3

error occurred: Error: EPERM: operation not permitted, unlink 'C:\Users\BANSAL~1\AppData\Local\Temp\2\nexrender\YjX5IyDrX-4HP_qMzB_JQ\ffmpeg.exe'
    at Object.unlinkSync (fs.js:1035:3)
    at C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\tasks\cleanup.js
    at Array.map (<anonymous>)
    at rmdirRecursively (C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\tasks\cleanup.js)
    at C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\tasks\cleanup.js
    at C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\helpers\state.js
    at C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\index.js
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async start (C:\snapshot\nexrender\packages\nexrender-worker\src\index.js)

```
{
    "result": {
        "uid": "YjX5IyDrX-4HP_qMzB_JQ",
        "type": "default",
        "state": "error",
        "output": "",
        "template": {
            "src": "file:///C:/Users/bansalpunitib/Desktop/nodeRoot/templates/1/template.aep",
            "composition": "main",
            "dest": "C:\\Users\\BANSAL~1\\AppData\\Local\\Temp\\2\\nexrender\\YjX5IyDrX-4HP_qMzB_JQ\\template.aep"
        },
        "assets": [
            {
                "type": "data",
                "layerName": "text",
                "property": "Source Text",
                "value": "new"
            }
        ],
        "actions": {
            "postrender": [
                {
                    "module": "@nexrender/action-encode",
                    "preset": "mp4",
                    "output": "encoded.mp4"
                },
                {
                    "module": "@nexrender/action-upload",
                    "input": "encoded.mp4",
                    "provider": "s3",
                    "params": {
                        "region": "ap-south-1",
                        "bucket": "xvrvmaker",
                        "key": "videos/11.mp4",
                        "acl": "public-read"
                    }
                }
            ]
        },
        "updatedAt": "2020-04-22T15:46:57.171Z",
        "resultname": "result.avi",
        "workpath": "C:\\Users\\BANSAL~1\\AppData\\Local\\Temp\\2\\nexrender\\YjX5IyDrX-4HP_qMzB_JQ",
        "scriptfile": "C:\\Users\\BANSAL~1\\AppData\\Local\\Temp\\2\\nexrender\\YjX5IyDrX-4HP_qMzB_JQ\\nexrender-YjX5IyDrX-4HP_qMzB_JQ-script.jsx",
        "renderProgress": 91,
        "error": {
            "errno": -4048,
            "syscall": "unlink",
            "code": "EPERM",
            "path": "C:\\Users\\BANSAL~1\\AppData\\Local\\Temp\\2\\nexrender\\YjX5IyDrX-4HP_qMzB_JQ\\ffmpeg.exe"
        }
    }
}
```

**Comment by inlife** [comment]
Seems like it errors out when attempting to cleanup the FFmpeg binary from the workfolder. If that happens next time, could you please check if that binary is still being active or exists in the process list? That would explain why error is happening.

**Comment by pushpendrabansal** [comment]
Hey,
Yeah so both servers and workers are executing and active so sometimes it shows success and sometimes shows this error.

The temp folder created in the work folder is also not deleted.
