### ISSUE TITLE
Question: add/remove clips in timeline

### ISSUE THREAD

**Issue by naranjamecanica** [inlife/nexrender#37]
We would like to use nexrender in a project, I have a question.

Is it possible to add/remove video clips in the timeline at a specific point in time? If it's not possible right now in nexrender, do you think it is a feature that is possible to add in the current way this project is set up? (we would love to contribute)

**Comment by Inlife** [comment]
Hello,

Well, its a hard question. And theoretically it might be possible, however its kinda complicated:  
First, nexrender is capable of replacing images or **video clips** per project. So different projects can have different clips.  
Second, you can use AE expressions to manipulate start/end times of video clip, IIRC, just how i did in the [example](https://github.com/Inlife/nexrender-boilerplate) project.
