### ISSUE TITLE
next-core expose method to run scripts on aep files without rendering

### ISSUE THREAD

**Issue by pdkn** [inlife/nexrender#373]
**Is your feature request related to a problem? Please describe.**
I'm keen to run some jsx scripts on .aep files without the need to actually render an output, just to interrogate the project. As an example, to extract all text layers in a composition for later use.

**Describe the solution you'd like**
in @nexrender/core/tasks/render the only params needed to run scripts are:
```
 params.push('-project', expandEnvironmentVariables(job.template.dest));
 params.push('-comp', job.template.composition);
 option(params, '-r', job.scriptfile);
```
however the system has a requirement that a results output is returned. I wonder if a new settings prop could be added? i.e `settings.runScriptsOnly = true` or `settings.skipRender = true` which, if set, ignores logic to render an output file?

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

Thoughts?

**Comment by pdkn** [comment]
Pull request submitted - https://github.com/inlife/nexrender/pull/375

**Comment by inlife** [comment]
added minor change request to pr, but overall looks good!
