### ISSUE TITLE
Does this support gif output

### ISSUE THREAD

**Issue by arlonlove** [inlife/nexrender#374]
Does this support gif output , how can i do it?

**Comment by pdkn** [comment]
some pointers - it should be possible to make a gif from a video using FFMEG - https://engineering.giphy.com/how-to-make-gifs-with-ffmpeg/. Therefore it *should* be possible to make a video using @nexrender/action-encode https://github.com/inlife/nexrender/tree/master/packages/nexrender-action-encode ? Haven't time to actually do POV yet

**Comment by arlonlove** [comment]
make a gif from a video may change the gif width and height or transparent.

**Comment by inlife** [comment]
as @pdkn mentioned, ffmpeg is capable of generating gif based on your input settings and a videofile produced by after effects

but, just to be sure, please check if after effects is capable of generating a gif on its own, maybe you do not need to even use FFmpeg for that

**Comment by inlife** [comment]
gif is now supported as an preset option for action-encode
