### ISSUE TITLE
Replace footage + move everything after that based on the new length?

### ISSUE THREAD

**Issue by Taapo** [inlife/nexrender#376]
Don't know how I could have missed this application - after years of building my own scripts.

I'm in the middle of a project and wanted to check quickly if this is possible - before trying to set this up.

When I "replace" an existing footage file with a longer or shorter file, is there an option to have everything that's related to the new length be moved backwards or forwards?

Or is this still something that needs to be done in Extendscript?

**Comment by inlife** [comment]
Hello @Taapo 

I'm afraid that is something that needs to be done in extend script, nexrender is not capable doing anything like that at the moment, and even if it did, it would still be scripting based, I believe
