### ISSUE TITLE
Error on windows with 1.13.0

### ISSUE THREAD

**Issue by sl1126497036** [inlife/nexrender#377]
### When I use the new version of nexrender-cli-win64.exe (1.13.0) on Windows, I get a ffmpeg error. But it works in 1.9.1, any help.

> starting nexrender-cli
using automatically determined directory of After Effects installation:
 - C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe
checking After Effects command line renderer patch...
command line patch already is in place
[VAw4dAIxHY0z9XwKLKkfR] setting up job...
[VAw4dAIxHY0z9XwKLKkfR] working directory is: C:\Users\ADMINI~1\AppData\Local\Temp\1\nexrender\VAw4dAIxHY0z9XwKLKkfR
[VAw4dAIxHY0z9XwKLKkfR] downloading assets...
[VAw4dAIxHY0z9XwKLKkfR] applying prerender actions...
[VAw4dAIxHY0z9XwKLKkfR] running script assemble...
[VAw4dAIxHY0z9XwKLKkfR] rendering job...
[VAw4dAIxHY0z9XwKLKkfR] rendering took ~33.997 sec.
[VAw4dAIxHY0z9XwKLKkfR] writing aerender job log to: C:\Users\ADMINI~1\AppData\Local\Temp\1\nexrender\aerender-VAw4dAIxHY0z9XwKLKkfR.log
[VAw4dAIxHY0z9XwKLKkfR] applying postrender actions...
[VAw4dAIxHY0z9XwKLKkfR] starting action-encode action (ffmpeg)
[VAw4dAIxHY0z9XwKLKkfR] action-encode: input file C:\Users\ADMINI~1\AppData\Local\Temp\1\nexrender\VAw4dAIxHY0z9XwKLKkfR\result.avi
[VAw4dAIxHY0z9XwKLKkfR] action-encode: output file C:\Users\ADMINI~1\AppData\Local\Temp\1\nexrender\VAw4dAIxHY0z9XwKLKkfR\0.mp4
> job rendering failed
Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg) TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\actions.js
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by pdkn** [comment]
have you got `settings.skipCleanup: true` ?

**Comment by inlife** [comment]
@sl1126497036 please try using newer version, that should be fixed in `1.13.1` and later

**Comment by djpmedia** [comment]
> @sl1126497036 please try using newer version, that should be fixed in `1.13.1` and later

With the latest update everything is working correctly and will I render correctly the video in MP4. Thanks for fixing.

**Comment by devsun** [comment]
@inlife I seem to be getting the same error with nexrender-worker-win64.exe
I have used these versions of nexrender-worker-win64: 1.13.0 and the most recent one 1.14.2
How can I fix this? Thanks for the great work on this software!

`Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg) TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
at C:\snapshot\nexrender\packages\nexrender-cli\node_modules@nexrender\core\src\tasks\actions.js
at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by inlife** [comment]
Just to be sure, could you show your job json description?

**Comment by devsun** [comment]
Sure, here is the simplest job json I've tried. I've used more complicated job jsons as well and they haven't worked in nexrender-windows-worker. 
Also, I have tested a number of job jsons on the nexrender-macos-cli and it works wonderfully. So I think it might be related to the nexrender-windows-worker.

```
{
  "template": {
    "src": "https://s3.amazonaws.com/.../test.aep",
    "composition": "Final Comp"
  },
  "assets": [
    {
      "src": "https://i.pinimg.com/originals/07/30/fa/0730fa3fc6a8d13836014e0763ba42ed.jpg",
      "type": "image",
      "layerName": "Image 01"
    }
  ],
  "actions":{
    "postrender": [
      {
        "module": "@nexrender/action-encode",
        "preset": "mp4",
        "output": "C:\\nexrender\\encoded.mp4"
      }
    ]
  }
}

```

**Comment by nin-o** [comment]
It's happening to me as well. I'm using Windows 10. Side note: Everytime I download a 1.13.x release the `-v` flag always returns 1.13.0.

JSON:
```
{
      "template": {
          "src": "file:///C:/Users/MyUser/Downloads/project.aep",
          "composition": "Main"
      },
      "assets": [
          {
              "src": "file:///C:/Users/MyUser/Downloads/Assets/background.png",
              "type": "image",
              "layerName": "background.png"
          },
          {
            "src": "file:///C:/Users/MyUser/Downloads/Assets/Audio.mp3",
            "type": "audio",
            "layerName": "audio.mp3"
          }
      ],
      "actions":{
          "postrender": [
              {
                  "module": "@nexrender/action-encode",
                  "preset": "mp4",
                  "output": "encoded.mp4",
                  "params": {"-vcodec": "libx264", "-r": 25}
              },
              {
                  "module": "@nexrender/action-copy",
                  "input":  "encoded.mp4",
                  "output": "C:/Users/MyUser/Downloads/result.mp4"
              }
          ]
      }
}
```

Version 1.14.4:
```
> job rendering failed
Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg) TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\actions.js
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Version 1.13.3
```
> job rendering failed
Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg) TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\actions.js
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```


Version 1.13.1
```
> job rendering failed
Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg) TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\actions.js
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Version 1.9.1
```
(node:20844) UnhandledPromiseRejectionWarning: Error: spawn EBUSY
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:540:9)
    at childProcess.spawn (pkg/prelude/bootstrap.js:1413:27)
    at C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\node_modules\@nexrender\action-encode\index.js
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:20844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by inlife** [comment]
Published a fix in `v1.14.5` that should resolve the issue, please let me know the results

**Comment by nin-o** [comment]
@inlife 
I tried `v1.14.5`:

```
> job rendering failed
Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg) Error: Could not find ffmpeg binary, expected path: undefined
    at C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\actions.js
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Note: `process.platform` returns `win32` for me.

I noticed when I ran `v1.9.1` ffmpeg.exe appeared in: `C:\Users\MyUser\AppData\Local\Temp\nexrender\t_<Some ID>`

**Comment by inlife** [comment]
Hey @nin-o 

I added a debug filesystem print, that should show us the layout of how it looks inside of the binary on your system, would it be possible to try it out?

https://mega.nz/file/9clXRSiZ#kKP7ZkddbolzskgseIgRzS6mTelFuUc73uavK3klvPg

**Comment by nin-o** [comment]
Working as of 1.16.3. Thank you!
