### ISSUE TITLE
Job is not loaded by worker when static assets are used

### ISSUE THREAD

**Issue by fabiolambreschi** [inlife/nexrender#378]
When adding assets of type 'static' to the json, the job is created by the nexrender-server as it should but the nexrender-worker does not fetch the job or download the data. 

Tried with and without definition of name for the static asset.
Static assets used: .mov, .psd. .png

**Comment by inlife** [comment]
could you show the way you create a job, so I could try to reproduce it?

**Comment by fabiolambreschi** [comment]
That's the json my app generates (real FQDN replaced):
{
   "template":{
      "src":"http:\/\/FQDN\/templates\/b1f51719e0fa9168a261cd89604817f3\/project.aep",
      "composition":"Main"
   },
   "assets":[
      {
         "src":"http:\/\/FQDN\/templates\/b1f51719e0fa9168a261cd89604817f3\/opener_flag_animation.mov",
         "type":"static"
      },
      {
         "value":"Headline Text",
         "type":"data",
         "layerName":"headline",
         "property":"Source Text",
         "composition":"Main"
      },
      {
         "value":"Subline Text",
         "type":"data",
         "layerName":"subline",
         "property":"Source Text",
         "composition":"Main"
      }
   ],
   "action":{
      "postrender":[
         {
            "module":"@nexrender\/action-encode",
            "preset":"mp4",
            "output":"output.mp4"
         }
      ]
   }
}

and the job is sent to the nexrender-server by curl: 

$url = "http://localhost:3000/api/v1/jobs";
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array(
            'Content-Type: application/json',
            'nexrender-secret: [SECRET HERE]',
        ));

        curl_setopt($ch, CURLOPT_POSTFIELDS, $json);
        $response = curl_exec($ch);

        curl_close($ch);

**Comment by inlife** [comment]
The job actions property seems to be incorrect, it should be "actions" not "action", try changing that
Also could you show me how does the submitted job look like on the server? (you can either print the response from submit or fetch the job by its id via `GET /api/v1/jobs/{uid}` )

**Comment by fabiolambreschi** [comment]
I renamed "action" to "actions". There's no response from submit or by fetching id when the json contains the static asset.
Without the static asset I receive the job-json an duid, type, state, output info

**Comment by fabiolambreschi** [comment]
Could it be that the case „static“ is missing in nexrender/packages/nexrender-core/src/tasks/script.js line 484?

**Comment by nvanrees** [comment]
@fabiolambreschi I also encountered this issue. Since you closed it, do you mind explaining what you did to resolve this? Everytime I try to add a static asset it gives me a 400 Bad request, unless I add a layerName.
