### ISSUE TITLE
Rocks on AE CC 2017

### ISSUE THREAD

**Issue by 5opr4ni** [Inlife/nexrender#38]
Thanks for a wonderful work.
Works smooth with AE CC 2017

/olle
http://svt.se

**Comment by Inlife** [comment]
Oh, thats good to know!
I had no chance to test it on the 2017 yet, so
Thank you! 👍  😄

**Comment by Troy-Yang** [comment]
unfortunally, not works for my AE CC 2017 because of H264.  Removing OMtemplate will have it work and generate a lossless huge AVI file (29G). Trying to use Ffmpeg to solve it.
