### ISSUE TITLE
New comp / composition settings

### ISSUE THREAD

**Issue by Fredalter** [inlife/nexrender#383]
Hi,
I'm testing this amazing project, and i try to use a low resolution  rendering to quickly show the result to the user :
In my project i am creating a comp (MAINSD) with "new comp from selection" (from the main comp) and change composition settings.
The render from AE GUI (2020) is fine, but with nexrender, targetting MAINSD produce a blank video, with the good duration.

"template": {
		"src": "file:///Nexrender/GlobalLuxuryTextIntro/Global Luxury Text Intro.aep",
		"composition": "MAINSD"

Am i missing something ?

**Comment by inlife** [comment]
Hey!

Try checking the logs coming form aerender, in the temp folder of nexrender. It seems to me in your case aerender can't find paths to assets used in the composition and renders them blank.

The log should give you more information.

**Comment by Fredalter** [comment]
Hi,

Thanks for quick reply, it's OK now without any change, I have another issue, with the last windows binary, ffmpeg is not present in temp file, may be a packaging fail ? so action-encode fail

**Comment by inlife** [comment]
Hey,

Yes, most likely it is. I'm still not sure where is the issue starts to happen. Will continue the investigation.
