### ISSUE TITLE
special characters encode

### ISSUE THREAD

**Issue by Fredalter** [inlife/nexrender#384]
Hi,

I have an issue with "é" that become Ã‰ in vidéo export
My asset is : 
"type": "data",
            "layerName": "text2",
            "property": "Source Text",
            "value": "présente"
regards

**Comment by Fredalter** [comment]
Hello,
I reply to myself, é are OK with 2019 release of after effects, it seems to be an issue with 2020 release.
However, running the jsx aerender generated script from 2020 GUI after effects works fine, can't figure where it fail !

**Comment by aysimakarca** [comment]
I also have same problem, after i upgraded the nexrender version my special characters have all been broken. Is it on purpose or is there a plan to fix it?

**Comment by inlife** [comment]
@aysimakarca which version did you upgrade from? Maybe we can trace it back to a particular change that happened within nexrender.

**Comment by inlife** [comment]
Please, check if the release `v1.16.0` fixes that issue.

**Comment by driedel** [comment]
> Please, check if the release `v1.16.0` fixes that issue.

It works for me. Thank you!! <3
