### ISSUE TITLE
Clustering Via Multi-aerender setting 

### ISSUE THREAD

**Issue by pixelfactorydevelopmentteam** [inlife/nexrender#385]
Hi Team , 

We are trying to making the multiple instance via multiple AE folder  with reuse  previous AE render instance  like 

![image](https://user-images.githubusercontent.com/39171759/81778459-8e70e480-9510-11ea-881b-51c10c3f556b.png)

I have running command like 

nexrender-worker --host=http://localhost:4000  --binary="C:\Program Files\Adobe\Adobe After Effects CC 2020\Support Files\aerender.exe" --reuse=ro --workpath="C:\Users\Administrator\Documents\temp\temp1"                                

and 

nexrender-worker --host=http://localhost:4000  --binary="C:\Program Files\Adobe\Adobe After Effects CC 2019_01\Support Files\aerender.exe" --reuse=ro --workpath="C:\Users\Administrator\Documents\temp\temp2"                                

during running these commands we are getting result from one render but another one always running...

getting error  on after effect 2020:

$ nexrender-worker --host=http://localhost:4000  --binary="C:\Program Files\Adobe\Adobe After Effects CC 2020\Support Files\aerender.exe" --reuse=ro --workpath="C:\Users\Administrator\Documents\temp\temp1" --debug
> starting nexrender-worker endpoint http://localhost:4000; using secret: no
using automatically determined directory of After Effects installation:
 - C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe
adding default render-only-node licenses for After Effects at:
 - C:\Users\Administrator\Documents\ae_render_only_node.txt
 - C:\Users\Administrator\Documents\Adobe\ae_render_only_node.txt
checking After Effects command line renderer patch...
command line patch already is in place
[Z1KlA-yNVe84TdgUghwJ3] setting up job...
[Z1KlA-yNVe84TdgUghwJ3] working directory is: C:\Users\Administrator\Documents\temp\temp1\Z1KlA-yNVe84TdgUghwJ3
[Z1KlA-yNVe84TdgUghwJ3] downloading assets...
[Z1KlA-yNVe84TdgUghwJ3] applying prerender actions...
[Z1KlA-yNVe84TdgUghwJ3] running script assemble...
[Z1KlA-yNVe84TdgUghwJ3] rendering job...
[Z1KlA-yNVe84TdgUghwJ3] spawning aerender process: C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe -project C:\Users\Administrator\Documents\temp\temp1\Z1KlA-yNVe84TdgUghwJ3\Project_controller.aepx -comp Render_Youtube 16:9_1920*1080 -output C:\Users\Administrator\Documents\temp\temp1\Z1KlA-yNVe84TdgUghwJ3\result_[#####].jpg -OMtemplate Image preview -RStemplate Image preview -s 00032 -e 00032 -r C:\Users\Administrator\Documents\temp\temp1\Z1KlA-yNVe84TdgUghwJ3\nexrender-Z1KlA-yNVe84TdgUghwJ3-script.jsx -reuse
[Z1KlA-yNVe84TdgUghwJ3] rendering took ~3.198 sec.
[Z1KlA-yNVe84TdgUghwJ3] writing aerender job log to: C:\Users\Administrator\Documents\temp\temp1\aerender-Z1KlA-yNVe84TdgUghwJ3.log
[Z1KlA-yNVe84TdgUghwJ3] applying postrender actions...
[Z1KlA-yNVe84TdgUghwJ3] error occurred: Error: Error loading postrender module @nexrender/action-copy: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Documents\temp\temp1\Z1KlA-yNVe84TdgUghwJ3\result_00000.jpg'
    at requireg.catch.err (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\@nexrender\core\src\tasks\actions.js:25:35)
[g4kRm7kLa-iGZQVWvI-8z] setting up job...
[g4kRm7kLa-iGZQVWvI-8z] working directory is: C:\Users\Administrator\Documents\temp\temp1\g4kRm7kLa-iGZQVWvI-8z
[g4kRm7kLa-iGZQVWvI-8z] downloading assets...
[g4kRm7kLa-iGZQVWvI-8z] applying prerender actions...
[g4kRm7kLa-iGZQVWvI-8z] running script assemble...
[g4kRm7kLa-iGZQVWvI-8z] rendering job...
[g4kRm7kLa-iGZQVWvI-8z] spawning aerender process: C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe -project C:\Users\Administrator\Documents\temp\temp1\g4kRm7kLa-iGZQVWvI-8z\Project_controller.aepx -comp Render_Youtube 16:9_1920*1080 -output C:\Users\Administrator\Documents\temp\temp1\g4kRm7kLa-iGZQVWvI-8z\result_[#####].jpg -OMtemplate Image preview -RStemplate Image preview -s 00032 -e 00032 -r C:\Users\Administrator\Documents\temp\temp1\g4kRm7kLa-iGZQVWvI-8z\nexrender-g4kRm7kLa-iGZQVWvI-8z-script.jsx -reuse
[g4kRm7kLa-iGZQVWvI-8z] rendering took ~0.404 sec.
[g4kRm7kLa-iGZQVWvI-8z] writing aerender job log to: C:\Users\Administrator\Documents\temp\temp1\aerender-g4kRm7kLa-iGZQVWvI-8z.log
[g4kRm7kLa-iGZQVWvI-8z] applying postrender actions...
[g4kRm7kLa-iGZQVWvI-8z] error occurred: Error: Error loading postrender module @nexrender/action-copy: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Documents\temp\temp1\g4kRm7kLa-iGZQVWvI-8z\result_00000.jpg'
    at requireg.catch.err (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\@nexrender\core\src\tasks\actions.js:25:35)

Administrator@iZ0xibhyxnnr2mZ MINGW64 ~/Desktop

============================================

Please help me out for solve these issues related to the Multiple render with  multi-aerender.exe file with reuse them

**Comment by inlife** [comment]
So, in theory you don't have to use multiple temp folders and create multiple copies of the process to render many videos at the same time. 

Reuse, however, is a very specific thing, and it works on the after effects level. I would even say it is quite dangerous. I don't think you can run 2 instances of after effects GUI app, and expect that 2 spawned aerender instances will definitely reuse 2 existing processes. I feel it is as likely as both will attempt to use a first running process, and one of them will immediately fail.

What I would recommend is either:

Using `reuse` flag and doing that on "microscopic level": small virtual environments with a controlled amount of memory and CPU cores, running a SINGLE copy of after effects, and doing a single render at a time using `reuse` flag.

OR

Changing the settings within aerender to influence the number of cores/memory used, and running multiple aerender jobs right on the host machine, without `reuse` flag.

In all other cases, it seems to me that combining `reuse` and multiple instances on a single machine is a very bad idea.

**Comment by pixelfactorydevelopmentteam** [comment]
@inlife Thank you!
