### ISSUE TITLE
action-encode fail with 1.15.1 release of nexrender-cli-win64

### ISSUE THREAD

**Issue by Fredalter** [inlife/nexrender#386]
**Describe the bug**
With the 1.15.1 release the ffmpeg.exe is not present in the temp file (-- skip-cleanup used in command line), so @nexrender/action-encode fail to produce mp4 file

**Information about environment**
* Which version of nexrender are you using? 1.15.1
* What kind of the setup do you have? (server+worker or cli) cli
* Are you using pre-built binaries or globally installed npm packages? pre-built
* Which kind (and version) of operating system you are running it in? windows 10 pro 1909
* Any additional information that might be helpful

**Expected behavior**

**Screenshots**

**Comment by Jack-Stencil** [comment]
This issue exists for me on Mac using nexrender-cli version 1.14.3.

```
[_bXCNLlufAafZmYRS5iR8] rendering took ~569.815 sec.
[_bXCNLlufAafZmYRS5iR8] writing aerender job log to: /var/folders/3_/f_vd74w974v2qyrcdqf3x_d00000gn/T/nexrender/aerender-_bXCNLlufAafZmYRS5iR8.log
[_bXCNLlufAafZmYRS5iR8] applying postrender actions...
[_bXCNLlufAafZmYRS5iR8] starting action-encode action (ffmpeg)
[_bXCNLlufAafZmYRS5iR8] action-encode: input file /var/folders/3_/f_vd74w974v2qyrcdqf3x_d00000gn/T/nexrender/_bXCNLlufAafZmYRS5iR8/result.mov
[_bXCNLlufAafZmYRS5iR8] action-encode: output file /var/folders/3_/f_vd74w974v2qyrcdqf3x_d00000gn/T/nexrender/_bXCNLlufAafZmYRS5iR8/test_Facebook_5ec1895b7d40b00b28a45c72.mp4
> job rendering failed
Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg) TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at /snapshot/nexrender/packages/nexrender-cli/node_modules/@nexrender/core/src/tasks/actions.js
    at runMicrotasks (<anonymous>)
```

**Comment by inlife** [comment]
Please, check if the release `v1.16.0` fixes that issue.

**Comment by Jack-Stencil** [comment]
@inlife Thank you issue is resolved for me.

**Comment by Fredalter** [comment]
the last binary from https://github.com/inlife/nexrender/releases is the 1.15.1 :(

**Comment by inlife** [comment]
Indeed, there were issues with travis, pushed a new build that hopefully should fix that as well. :)

**Comment by Fredalter** [comment]
@inlife  thank you, resolved with 1.16.2 !

**Comment by Thiago-Dantas** [comment]
I'm seeing this again on version 1.22, ffmpeg is not present in temp folder
I'm starting the worker with `-w C:\tmp`, if it makes any difference
The precise error is 
```
Error loading postrender module @nexrender/action-encode: TypeError: Cannot use 'in' operator to search for '-i' in undefined
    at C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\tasks\actions.js
```
Downloaded ffmpeg and placed it manually in the temp folder but it continued throwing
Setting env var with `set NEXRENDER_FFMPEG=C:\tmp\ffmpeg.exe` then starting worker again did nothing also :(

**Comment by ilhamzacky** [comment]
@inlife i am also having the same issue

**Comment by inlife** [comment]
Seems like a new bug introduced in one of the https://github.com/inlife/nexrender/pull/513
I'll try to work on a fix ASAP 👍 

Thanks for the reports,
Cheers!

**Comment by inlife** [comment]
Pushed as `v1.23.2`, please try if that fixes it @Thiago-Dantas @ilhamzacky

**Comment by Thiago-Dantas** [comment]
Just tested 1.23.2 and worker was able to download ffmpeg
