### ISSUE TITLE
AE CC render much faster than AeRender 

### ISSUE THREAD

**Issue by Troy-Yang** [Inlife/nexrender#39]
Hey guys,

I am pretty new for AE CC but with the help of nexrender, I am successfully to setup my custom video auto-render service, thanks @Inlife for this great tool!

However, I noticed a difference performance issue between using AE CC 2015 (GUI) and AeRender,  Rendering the aepx in AE CC is much faster than using AeRender. For same one .aepx file, Using Ae CC manually adding into render queue only takes less 10 seconds but using AeRender in command line will take around 60 seconds.  Plus, Using multi-thread in AeRender will make things more worse. 

My perference output module is using QuickTime and H.264 as video encoding format. Also select the Web Video size 320*240. The two kinds output videos's details are almost same except the rendering time. A stupid question is do you guys know where the rendering setting of AeRender is in? Does it will use the same setting as Ae CC (GUI)?

Here is my command-line arguments:
```
aerender.exe -project "E:\Git\auto-generate-ae-video\AeRender.Test\output\Troy\main.aepx" -output "E:\Git\auto-generate-ae-video\AeRender.Test\output\Troy\main.mp4" -comp main -OMtemplate H264 -mp -continueOnMissingFootage
```
Thanks in advanced.

Troy

**Comment by Inlife** [comment]
Hey!

As far as i know, AeRender should use settings from GUI application, at least some of them.
However im pretty sure, AE CC also passes some additional options into process it is spawning

there is a some info about available parameters on the adobe's site:
https://helpx.adobe.com/after-effects/using/automated-rendering-network-rendering.html

and if later u'll find something and will want to use with nexrender, i tried to pass some of the parameters into render node as flags
https://github.com/Inlife/nexrender/wiki/Rendering-node#details

hope that will help you!

**Comment by Troy-Yang** [comment]
Thanks @Inlife , I'll do more tests with difference parameters and will update here if I get anything.

**Comment by Inlife** [comment]
Wonderful !
Thank you @Troy-Yang ! :)
