### ISSUE TITLE
Is there an AfterEffects RenderFarm Service that supports Nexrender?

### ISSUE THREAD

**Issue by FinnFrotscher** [inlife/nexrender#392]
Hi,
i was wondering if there is a Render service like https://turborender.com/ or https://www.garagefarm.net/after-effects, that supports Nexrender out of the box?

Background to this question:
I need to build a render service that can handle upwards of 1000 nexrender projects a day.
I dont want to have any hardware inhouse.

I would like to pass `that service` either a nexrender json object and they take care of all the downloads etc, or i run my node project inside of an environment that has access to a aerender binary.

Does that exist?

**Comment by inlife** [comment]
Hey,

I don't think there are established render services that support nexrender out there. I assume most of the people that need something similar just spin up a nexrender network on Azure/AWS/Google Cloud.

**Comment by FinnFrotscher** [comment]
`spin up a nexrender network on Azure/AWS/Google`
Do you have a reference implementation of this? or know someone who might?

**Comment by inlife** [comment]
I don't have a reference, but you can search for open/closed issues here, and you will probably find somebody who did something like that.

**Comment by devsun** [comment]
@FinnFrotscher If you need an implementation of this on AWS/Google, let me know.  I have something custom running for this.

**Comment by FinnFrotscher** [comment]
@devsun yes i would appreciate this very much

**Comment by dzg** [comment]
>If you need an implementation of this on AWS/Google, let me know. I have something custom running for this.
Hey @devsun I'm also interested! Are you running just nexrender, or also aerender on AWS/Google/Azure?
Thank you!

**Comment by shanewaite** [comment]
@devsun Also interested!
