### ISSUE TITLE
Is there any way to fetch the data from AE file

### ISSUE THREAD

**Issue by darshakgosar** [inlife/nexrender#393]
Hi,
Is there any way to fetch the data like layers, errors, fonts, compositions from the AE file using nexrender.
Background to this question:
I need to build a render service which will fetch the data from the AE files using nexrender and display information on UI.

Thanks,
Darshak Gosar

**Comment by inlife** [comment]
Hey,

The answer is probably not. I would recommend either using this project: https://github.com/Jam3/ae-to-json or looking at this one: https://github.com/actumn/aepx.js

Cheers!

**Comment by darshak-gosar** [comment]
Hi,
Thank you so much for the Response. I will check this out.

Thanks,
Darshak Gosar
