### ISSUE TITLE
its not working at my side... i trying to change my fill color using same code...

### ISSUE THREAD

**Issue by Ebadsb** [inlife/nexrender#396]
add an expression to the fill of your shape: 
`rgb = hexToRgb(thisComp.layer("e1e1e1").text.sourceText.value); content("Rectangle 1").content("Fill 1").color = rgb`

its give me the error...

**Comment by inlife** [comment]
Which error does it give you?

Suggestion: Make sure to test out all of your expressions in the actual after effects GUI, and only then use them within nexrender
