### ISSUE TITLE
hi can show on render progress on html

### ISSUE THREAD

**Issue by chaza1984** [inlife/nexrender#397]
hi, first Thanx very much for this incredible module. I am new on Node/express. I could install the nexrender and all works ok. I use the method 👍 
```
 main().finally(function () {
          console.log(" task finished")    
        })
```
And all work fine but I want to do think after the task has finished, but all functions I put inside the terminal return me a promise error for example

```
 main().finally(function () {
          console.log(" task finished")
          res.render('task finished')
        })
```
The second question how can I show the progress on the front end, is there another main() function? or the key is with onrender progress that is inside the jsdon after actions?

thanx

**Comment by inlife** [comment]
Hey @chaza1984 

Could you show your full code, what is the `main` function, etc.
Also most likely it is the problem related to the promises/javascript language in general, so I would also recommend reading more on those. Possibly you will be able to fix everything on your own.

Regarding progress, it should be reported via various ways, depending on what exact package are you using. You can refer to the source code as well, that right now is the best source of "truth" if readme does not cover the topic.

Cheers!

**Comment by chaza1984** [comment]
HI, probably you are right, I am try to apply the promise and asyc await without good results. My code is working but i now its not good write.  Maybe you can helpme with the progress. At the end I render a html and I show a mensage but all the time I receive undefined. 

thanx



//MULTER (Module for capture images)

const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, 'src/public/images/')
  },
  filename: (req, file, cb) => {
    archivoFoto = file.fieldname + '-' + Date.now() + path.extname(file.originalname)
    //fieldname va a estampar en el archivo el nombre que tenga "name" en la etiqueta input. (para no usar el nombre que viene con el archivo.)
    cb(null, archivoFoto)

  }
});

const upload = multer({
  storage: storage,
  limits: { fileSize: 1000000 },
  fileFilter: function (req, file, cb) {
    checkFileType(file, cb);
  }
}).single('photoUpload');


function checkFileType(file, cb) {
 const filetypes = /jpeg|jpg|png|gif/;
  const extname = filetypes.test(path.extname(file.originalname).toLowerCase());
 const mimetype = filetypes.test(file.mimetype);

  if (mimetype && extname) {
    return cb(null, true);
  }
  else {
    cb('Error: Images Only!');
  }
}






router.post('/Frozen2', async (req, res) => {
procesos();
})

  upload(req, res, (err) => {

    if (err) {
      res.render('Frozen2', {
        msg: err
      });
    }

    else {
      if (req.file == undefined) {
        res.render('Frozen2', {
          msg: 'Error: No File Selected'
        })
      }

      else {

  
        let fechaNombre = Date.now()
        const { fecha1, fecha2, mensaje1, mensaje2, direccion1, direccion2, direccion3, despedida1, despedida2 } = req.body

        if (!fecha1 || !direccion1 || !direccion2 || !despedida1) {
          res.render('Frozen2.ejs', {
            msg: 'Error: Completa todos los campos'
          })

        } 




        const job = {

          "template": {
            "src": "file:///C:/Users/chaza/Desktop/paginas/invitaciones/assets/frozen 2/after 
                       effects/frozen2ok15.aep",
            "composition": "frozen2"
          },
          "assets": [
            {
              "src": "file:///C:/Users/chaza/Desktop/paginas/invitaciones/prueba 4/src/public/images/" + 
                         archivoFotoReSize,
              "type": "image",
              "layerName": "fotomia"
            },
            {
              "type": "data",
              "layerName": "1fecha",
              "property": "Source Text",
              "value": fecha1
            }

          ],
          "actions": {


            "postrender": [
              {
                "module": "@nexrender/action-encode",
                "output": "encode.mp4",
                "preset": "mp4",
                "params": { "-vcodec": "libx264", "-r": 25 }
              },

              {
                "module": "@nexrender/action-copy",
                "output": "C:/Users/chaza/Documents/nexrender/exports mp4 copis/thisIsACopy" + 
                                 fechaNombre + ".mp4"
              },

            ]
          },

          onChange: (job, state) => console.log("testing onChange en json:", state),


          onRenderProgress: (job, value) => ("onrender progres:", value)


        }



        console.log(job)
        const json_videos = JSON.stringify(job)


      
       


 
        //res.send('recibido')

        const main = async () => {

          const result = await render(job, {
            workpath: 'C:/Users/chaza/Documents/nexrender/',
            //binary: 'C:/Program Files/Adobe After Effects CC 2019/Support Files/aerender.exe',
            binary: 'C:/Program Files/Adobe/Adobe After Effects CC 2018/Support Files/aerender.exe',
            skipCleanup: true,
            addLicense: false,
            debug: true,

          })


        }

        main().catch(console.error);
        console.log("error catch del main")

        main().finally(function () {
          console.log("Tarea finalizada!!!!!!!!!!!!!!!!!!!!!!!!!!")

        })


        main().then(function () {

          
          res.render('frozen2', {
            msgProgress: "progress : + job.value (Here would like yo show the progress) "
          })

        })


      }

    }

  })



})

**Comment by inlife** [comment]
Yea, I feel like there are some issues in your javascript code that might cause invalid behavior.
First thing I see is that you are calling `main` (and as result `render`) function 3 times, and additionally you are not returning the result from render outside of main function.
