### ISSUE TITLE
Is there any way to install plugin/fonts if there is any missing plugin/fonts using nexrender

### ISSUE THREAD

**Issue by darshak-gosar** [inlife/nexrender#398]
Is there any way to install plugin/fonts if there is any missing plugin/fonts using nexrender while rendering the file or reading the file ?

**Comment by inlife** [comment]
Hello,

Fonts should be a system-wide thing, if I understand correctly. And nexrender does not have a built-in functionality to manage system fonts. You could add your own action, however, to do so. Same probably goes for plugins. I'm not entirely sure tho which plugins are you talking about :)

Cheers!

**Comment by darshakgosar** [comment]
Hi,
Consider a scenario where I want to install the plugin in AE, if their is a plugin missing issue during rendering the file it should Install the plugin automatically and continue rendering process. Is this possible ?

Thanks.

**Comment by inlife** [comment]
Unfortunately, nexrender does not provide such functionality. That however would be a great addition to the ecosystem. Saying that just in case you would want to create and contribute something like that :)
