### ISSUE TITLE
Documentation for nexrender-server 

### ISSUE THREAD

**Issue by xanderdemidoff** [inlife/nexrender#399]
Hello Vladyslav,

Most of nexrender modules has Readme files with explanation how this service works, but not the nexrender-server module (https://github.com/inlife/nexrender/tree/master/packages/nexrender-server). 
Could you please publish any documentation for nexrender-server API: endpoints list and ways how to communicate with this endpoints; examples.
It would be really appreciated.

**Comment by inlife** [comment]
Sure, I'll work on that!

**Comment by inlife** [comment]
Please, check it out: https://github.com/inlife/nexrender/tree/master/packages/nexrender-server
Feel free to suggest any changes, fixes, or improvements. :)

**Comment by xanderdemidoff** [comment]
Thank you!
