### ISSUE TITLE
aerender path

### ISSUE THREAD

**Issue by gontz** [Inlife/nexrender#4]
Hello

I can't enter the aerender path

nexrender --renderer -- host=localhost:3000 \ --aerender="c:/Program Files/Adobe/Adobe After Effects CC 2015/Support Files/aerender.exe"

                                   | |
 _ __   _____  ___ __ ___ _ __   __| | ___ _ __
| '_ \ / _ \ \/ / '__/ _ \ '_ \ / _` |/ _ \ '__|
| | | |  __/>  <| | |  __/ | | | (_| |  __/ |
|_| |_|\___/_/\_\_|  \___|_| |_|\__,_|\___|_|

                  VERSION: 0.4.5

For support and information, please visit:
http://github.com/Inlife/nexrender

[error] provide --aerender=PATH for aerender binary file

Thanks

**Comment by pradeeprajr93** [comment]
Your command
`nexrender --renderer -- host=localhost:3000 \ --aerender="c:/Program Files/Adobe/Adobe After Effects CC 2015/Support Files/aerender.exe"`

I think the backslash ("\") after 3000 has no work to do, so we can remove it :)

Try this
`nexrender --renderer --host="127.0.0.1:3000" --aerender="C:\program files\adobe\adobe after effects cc 2015\Support files\aerender.exe"`

**Comment by gontz** [comment]
my rookie mistake
it was the space before host
