### ISSUE TITLE
aepx template

### ISSUE THREAD

**Issue by leq382121** [Inlife/nexrender#40]
Hey man, i do really appreciate your work. The potential of it is huge and since i'm working in automatisation development field, this is a really good piece of code. Anyways, i'm not itself super familiar with AE. Could you please explain how to properly create .aepx template in order to make "variables" and how to connect them. I have deeply analysed the package itself, but there is nothing about the project file itself. Thank you!

P.s. I'm trying to use this code i made accordingly to your boilerplate, but i'm getting 1mb files which are not able to open (used your template and it worked).

```js
'use strict';



let background  = '2016-aug-deep.jpg';
let duration    = 600; //video duration in secs.

let aepxfile  = 'test.aepx';


const aebinary  = '/Applications/Adobe\ After\ Effects\ CC\ 2017/aerender';
const port      = 23234;


const http      = require('http');
const url       = require('url');
const path      = require('path');
const fs        = require('fs');

const Project   = require('nexrender').Project;
const renderer  = require('nexrender').renderer;


let server = http.createServer((req, res) => {

    let uri         = url.parse(req.url).pathname;
    let filename    = path.join(process.cwd(), uri);

    fs.exists(filename, (exists) => {
        if(!exists) {
            res.writeHead(404, {"Content-Type": "text/plain"});
            res.write("404 Not Found\n");
            
            return res.end();
        }

        fs.readFile(filename, "binary", function(err, file) {
            if(err) {    
                res.writeHead(500, {"Content-Type": "text/plain"});
                res.write(err + "\n");
                return res.end();
            }

            // send 200
            res.writeHead(200);
            res.write(file, "binary");
            return res.end();
        });
    });
});


server.listen(port, () => {

    console.log('Started local static server at port:', port);

    // addtional info about configuring project can be found at:
    // https://github.com/Inlife/nexrender/wiki/Project-model
    let project = new Project(
        {
        "template": "test.aepx",
        "composition": "main",
        "type": "default",
        "settings": {
            // dont forget to setup the right output module; info:
            // https://helpx.adobe.com/after-effects/using/basics-rendering-exporting.html#output_modules_and_output_module_settings
            "outputModule": "Lossless", //h264
            "startFrame": 0, //this option let's us to cut the whole project in smaller pieces, like time based sprites.
            "endFrame": duration
        },
        "assets": [
            { "type": "project", "name": "project.aepx",  "src": `http://localhost:${port}/assets/${aepxfile}`}, 
            { "type": "image",   "name": "testas.jpg",  "src": `http://localhost:${port}/assets/${background}`, "filters": [ {"name":"cover", "params": [1280, 720] }] } //for more info about customization: https://github.com/oliver-moran/jimp
        ]
    }
);

    console.log(project);

    // start rendering
    renderer.render(aebinary, project).then(() => {
        // success
        server.close();
        console.log('rendering finished');
    }).catch((err) => {
        // error
        console.error(err);
        server.close();
    });

});

```

**Comment by Inlife** [comment]
hello,

first of all try to change the name of project asset in the `assets` part of project, so they all will be same: 
```js
    "assets": [
            { "type": "project", "name": "test.aepx"
```

About the **aepx** file:
Aepx is after effects project template file, which can be created via after effects itself.
When you save the project, you have an option in the **File** menu (iirc) to save it as template.  
It will be an XML file. You can later open any project template file via text editor and check what is inside 😃 

Variables can be made quite simple way, it was even described there: #7

**Comment by leq382121** [comment]
You are a savior, man! Thanks! Will try that tomorrow and will let you know how it goes. I truly wish you luck with your MMO networking project for now!

**Comment by leq382121** [comment]
Okay, so I have tried to tweak a bit according your suggestions since I couldn't wait until tomorrow. I still somehow can't manage to make it work. I have made some pictures. I'm pretty sure i'm missing something relatively stupid ant i can't see or understand.. Thanks for your help!


This is my template i've made:

<img width="1280" alt="screen shot 2017-09-07 at 20 31 27" src="https://user-images.githubusercontent.com/15140250/30179392-859854ae-940c-11e7-9fbc-98b02d5dfa02.png">

It renders:

<img width="1280" alt="screen shot 2017-09-07 at 20 32 34" src="https://user-images.githubusercontent.com/15140250/30179406-929dc044-940c-11e7-91e6-958bd5080a42.png">

And I get this:

<img width="654" alt="screen shot 2017-09-07 at 20 35 53" src="https://user-images.githubusercontent.com/15140250/30179430-ac532510-940c-11e7-81b3-4ffa3cc0b7c7.png">

`
'use strict';

let background  = '2016-aug-deep.jpg';
let duration    = 600; //video duration in secs.

let aepxfile  = 'GG.aepx';

const aebinary  = '/Applications/Adobe\ After\ Effects\ CC\ 2017/aerender';
const port      = 23234;

const http      = require('http');
const url       = require('url');
const path      = require('path');
const fs        = require('fs');

const Project   = require('nexrender').Project;
const renderer  = require('nexrender').renderer;

let server = http.createServer((req, res) => {

    let uri         = url.parse(req.url).pathname;
    let filename    = path.join(process.cwd(), uri);

    fs.exists(filename, (exists) => {
        if(!exists) {
            res.writeHead(404, {"Content-Type": "text/plain"});
            res.write("404 Not Found\n");
            
            return res.end();
        }

        fs.readFile(filename, "binary", function(err, file) {
            if(err) {    
                res.writeHead(500, {"Content-Type": "text/plain"});
                res.write(err + "\n");
                return res.end();
            }

            // send 200
            res.writeHead(200);
            res.write(file, "binary");
            return res.end();
        });
    });
});

server.listen(port, () => {

    console.log('Started local static server at port:', port);

    // addtional info about configuring project can be found at:
    // https://github.com/Inlife/nexrender/wiki/Project-model
    let project = new Project(
        {
        "template": "projektas.aepx",
        "composition": "main",
        "type": "default",
        "settings": {
            // dont forget to setup the right output module; info:
            // https://helpx.adobe.com/after-effects/using/basics-rendering-exporting.html#output_modules_and_output_module_settings
            "outputModule": "Lossless", //h264
            "startFrame": 0, //this option let's us to cut the whole project in smaller pieces, like time based sprites.
            "endFrame": duration
        },
        "assets": [
            { "type": "project", "name": "projektas.aepx",  "src": `http://localhost:${port}/assets/${aepxfile}`}, 
            { "type": "image",   "name": "aaa.jpg",  "src": `http://localhost:${port}/assets/${background}`, "filters": [ {"name":"cover", "params": [1280, 720] }] } //for more info about customization: https://github.com/oliver-moran/jimp
        ]
    }
);

    console.log(project);

    // start rendering
    renderer.render(aebinary, project).then(() => {
        // success
        server.close();
        console.log('rendering finished');
    }).catch((err) => {
        // error
        console.error(err);
        server.close();
    });

});


`

**Comment by leq382121** [comment]
p.s. After Rendering it weights only 1mb which tells me that there was some problem.

**Comment by leq382121** [comment]
Okay, so i figured out, that these two names, the missing file and asset name has to be identical! 

<img width="772" alt="screen shot 2017-09-07 at 20 31 27" src="https://user-images.githubusercontent.com/15140250/30213005-72f47e72-94a7-11e7-88d8-7d2da7ca0130.png">


But is there are any way to make an asset without creating and deleting files? Is there are any way to specify the type of it? or i have to create some jpg file f.ex, upload it while choosing "JPEG" file type, since it automatically selects "importerJPEG", then delete it and use the name of the asset same as the deleted file?

**Comment by Inlife** [comment]
yes, `asset.name` is a name in which file will be renamed after downloading

>But is there are any way to make an asset without creating and deleting files? Is there are any way to specify the type of it? or i have to create some jpg file f.ex, upload it while choosing "JPEG" file type, since it automatically selects "importerJPEG", then delete it and use the name of the asset same as the deleted file?

not sure i understand what are you asking about :/

Also thing about file substitution, is that adobe will first look for a file at the place where project last seen it, via absolute path.
So if you are doing everything on the local machine, make sure  that after you saved the project, you move/remove the folder with project and all assets where you last saved it working in the AE.

**Comment by leq382121** [comment]
Okay I will try to formulate the question differently.

 When i create a new template i create an composition. If I want to create an empty placeholder/layer/container/variable (idk how it's called in after effects), I do like this:

![screen shot 2017-09-08 at 15 48 59](https://user-images.githubusercontent.com/15140250/30214581-4f9a25c0-94ad-11e7-9aa2-366803bc1247.png)

But when I create it's type "placeholder". 

![screen shot 2017-09-08 at 15 50 03](https://user-images.githubusercontent.com/15140250/30214626-72c52004-94ad-11e7-82cf-1a2ba80e9f60.png)

And when i use placeholder name in the code

![screen shot 2017-09-08 at 15 51 06](https://user-images.githubusercontent.com/15140250/30214673-91c468ac-94ad-11e7-9334-4646ba69bac3.png)

I get an corrupted file, yet it creates one. (it weights 1mb)

The solution I've found is that I have to use some sort of image file, upload it, then delete/rename it. This way i get the filetype, which, in my belief, is important for nexrender.

**Comment by Inlife** [comment]
Oh, i see.

I never tried using placeholders, and they will not work for that.
I usually just add the needed asset onto composition.
also that "name" param in project asset is actually a filename into which that asset will be renamed
it should be the SAME as the FILENAME of the original asset in the COMPOSITION

**Comment by leq382121** [comment]
Hmm, okay. 

The reason of my approach to nexrender is to develop an ability to make one template and feed it with json data to make data driven video at one click. Is it possible to make 100 videos by running this package once? 

f.ex. i have json file containing data and accordingly to that data i would like to use specific colors, animations etc. and i would expect 100 videos, made from same template, but different data putted in the same containers/placeholders. ?

**Comment by Inlife** [comment]
yes, this is possible

i would recommending you running it in API-server + rendernode mode
that way you will be able to track all current projects

and also, you will be able to run multiple instances of rendernodes (if your machine will be able to handle it)

which can give you rendering multiple projects at the same time

https://github.com/Inlife/nexrender/wiki/API-server
https://github.com/Inlife/nexrender/wiki/Rendering-node

**Comment by leq382121** [comment]
We are considering that we should use one computer as "a tower" to connect, so it will run an API-server and be the same machine which will be used to render and output/spit files after rendering. 

Okay, so I will try to figure out the logic how to make few videos in one click, since i'm a junior developer with big hopes and persistence. 

Anyways. Your package is great and i hope it will save our team many weeks!

**Comment by Inlife** [comment]
>We are considering that we should use one computer as "a tower" to connect
yeah, that should work just fine

Thank you 😁  
Glad you guys like it, keep up the good work ! )
