### ISSUE TITLE
Unclear how to use Parameter Type `function`

### ISSUE THREAD

**Issue by FinnFrotscher** [inlife/nexrender#400]
I have to reduce our reliance on `jsx` scripts. thats why i isolated some core functionality and attached it to the nexrender object. ie. `nexrender.copy()` copies compoositions, `nexrender.fit()` aligns a resource in the containing composition, etc.

now  i have to somehow call these core functions.
my plan was to call them from functions that i pass via assets, including all the parameters they need.
I build the attached routine.
```
  const job = await Nexrender();
  job.project.assets.push({
    type: 'script',
    src: 'data:text/plain;base64,TlguY2FsbCgicnVuIikK', // decoded "NX.call("run")"
    parameters: [
      {
        key: 'run',
        type: 'function',
        value: `
(nexrender.copy)
  ({
    newCompositionName: NX.arg('new'),
    sourceCompositionName: NX.arg('source'),
    targetCompositionName: NX.arg('target')
  })`,
        arguments: [
          {
            key: 'new',
            value: 'newCompName',
          },
          {
            key: 'source',
            value: 'Empty',
          },
          {
            key: 'target',
            value: 'main',
          },
        ],
      },
    ],
  }),
  await nex.render(job.project, nex.init(job.settings));
```

which shows up in the build `nexrender-:id-script.jsx` as
```
      // Parameter injection from job configuration
          NX.set(
            'run',
            "(nexrender.copy)({newCompositionName: NX.arg('new'), sourceCompositionName: NX.arg('source'), targetCompositionName: NX.arg('target')})"
          );

          NX.call('run');
        })();

        /* end of custom user script */
```

its missing the arguments that i passed to `asset.parameters.arguments`. 
and its not calling the function.
what am i doing wrong?

**Comment by FinnFrotscher** [comment]
I developed around it by encoding the function call in base64 and passing  the argumetns as parameters.
i would still like to know what i did wrong, for the future.

**Comment by inlife** [comment]
We would probably need @dukuo to get us an additional explanation about that

**Comment by dukuo** [comment]
Hey, sorry for the delay. 
Is this function `run` supposed to be an arrow function like `() => {}` ? I haven't ran your job. My first thought is that the signature of the function is unclear to me. 
```js

        key: 'run',
        type: 'function',
        value: `
(nexrender.copy)
  ({
    newCompositionName: NX.arg('new'),
    sourceCompositionName: NX.arg('source'),
    targetCompositionName: NX.arg('target')
  })`,
        arguments: [
          {
            key: 'new',
            value: 'newCompName',
          },
          {
            key: 'source',
            value: 'Empty',
          },
          {
            key: 'target',
            value: 'main',
          },
        ],
      },

```

**Comment by FinnFrotscher** [comment]
@dukuo thank you for the input.
I  will let this issue go stale or close it temporarily until i have time and the need to test this.
