### ISSUE TITLE
Setting the output path to copy the video .mp4

### ISSUE THREAD

**Issue by Arcetrix** [inlife/nexrender#404]
Hi, 

My 'worker' run on C./ drive and i need to copy the video file .mp4 to a different drive let say Z:\ (a samba shared drive).
I have tried in many ways to do that setting the path value for 'output' to:
"output": "Z:/bigBunny7.mp4"
or
"output": "file:///Z:/bigBunny7.mp4"
or (relative path):
"output": "../../../Z:/bigBunny7.mp4"

but the worker return error.

Have you some suggestions about this problem? 

Below the portion of JSON:
```
"actions":{
"postrender": [
{
"module": "@nexrender/action-encode",
"output": "encoded.mp4",
"preset": "mp4",
"params": {"-vcodec": "libx264", "-r": 25}
},
{
"module": "@nexrender/action-copy",
"input": "encoded.mp4",
"output": "Z:/bigBunny7.mp4"

```
Thank you

**Information about environment**
* Which version of nexrender are you using?
- 1.16.3
* What kind of the setup do you have? (server+worker or cli)
- server + worker on windows 10 PC. call by curl from another linux machine. Windows e Linux share a Z:\ drive via Samba  
* Are you using pre-built binaries or globally installed npm packages?
- pre-built binaries

than you

**Comment by inlife** [comment]
Could you show the error that is happening in your case?
Maybe it will tell us more about the reasons behind it.

**Comment by Arcetrix** [comment]
Hi @inlife,

below the error:
[libx264 @ 000002a4bd4e2f80] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8:  0.2%  0.0%  0.0%  direct: 0.0%  skip:99.8%  L0:22.6% L1:77.3% BI: 0.0%
[libx264 @ 000002a4bd4e2f80] 8x8 transform intra:75.3% inter:90.9%
[libx264 @ 000002a4bd4e2f80] coded y,u,v intra: 27.5% 20.3% 18.4% inter: 0.0% 0.0% 0.0%
[libx264 @ 000002a4bd4e2f80] i16 v,h,dc,p: 52% 20%  4% 24%
[libx264 @ 000002a4bd4e2f80] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu:  4%  3% 86%  1%  1%  1%  1%  2%  2%
[libx264 @ 000002a4bd4e2f80] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 21%  9%  6%  7%  7%  6%  9%  7%
[libx264 @ 000002a4bd4e2f80] Weighted P-Frames: Y:0.2% UV:0.2%
[libx264 @ 000002a4bd4e2f80] ref P L0: 59.9%  0.8% 30.9%  8.4%
[libx264 @ 000002a4bd4e2f80] ref B L0: 23.7% 76.2%  0.1%
[libx264 @ 000002a4bd4e2f80] ref B L1: 99.1%  0.9%
[libx264 @ 000002a4bd4e2f80] kb/s:62.47

[WXopwn5AS7krd5TB1kc-X] [aac @ 000002a4bd4e4e40] Qavg: 45041.078

[WXopwn5AS7krd5TB1kc-X] error occurred: Error: Error loading postrender module @nexrender/action-copy: Error: ENOENT: no such file or directory, open 'C:\Users\IOL\AppData\Local\Temp\nexrender\WXopwn5AS7krd5TB1kc-X\file:\Z:\nexrender\bigBunnyZ.mp4'
    at C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\tasks\actions.js
    at async start (C:\snapshot\nexrender\packages\nexrender-worker\src\index.js)

**Comment by inlife** [comment]
In this case error is 
> ENOENT: no such file or directory, open

for path: `'C:\Users\IOL\AppData\Local\Temp\nexrender\WXopwn5AS7krd5TB1kc-X\file:\Z:\nexrender\bigBunnyZ.mp4'`

As you can see it does not look as a valid path, which settings were used for this specific attempt?

**Comment by Arcetrix** [comment]
Hi @inlife,

in this case i tried this settings:
            {
                "module": "@nexrender/action-copy",
                "input":  "encoded.mp4",
                "output": "file:///Z:/nexrender/bigBunnyZ.mp4"
            }

**Comment by inlife** [comment]
Could you try with this, and show the resulting error?
```js
{
    "module": "@nexrender/action-copy",
    "input": "encoded.mp4",
    "output": "Z:/nexrender/bigBunnyZ.mp4"
}

**Comment by Arcetrix** [comment]
Hi @inlife 

It's work fine! The file was copied to the shared drive.
I'm sorry but I was sure to have tested also this base setting... thank you.

**Comment by inlife** [comment]
Oh, that is great then! Glad it got resolved. :)

**Comment by nazemi0101** [comment]
![n1](https://user-images.githubusercontent.com/47674802/87223329-d5246480-c330-11ea-9d6c-2d87e0ef6b76.png)
 
i have look like problem in windows server machine vps: my render job has finish and video create at this path address but dont work action copy to move this file . my path video create address in    C:\Users\Administrator\AppData\Local\Temp\2\nexrender\tSM1FyM2rGEitf-ifotkQ
