### ISSUE TITLE
How to pass AWS upload credentials to worker binary?

### ISSUE THREAD

**Issue by FinnFrotscher** [inlife/nexrender#405]
When running the latest worker binary, it throws an error after rendering and encoding. 
error says its missing aws  credentials. but they are passed as part of the project object. the artifact can be uplaoded when not using the worker binary.
thus, how to pass the credentials to the worker binary?

```
[F8R2dLypbzpd89otCAsPo] action-upload: output file https://s3-eu-central-1.amazonaws.com/files/ck93wvq6802931co1p4beud6o.mp4
[F8R2dLypbzpd89otCAsPo] error occurred: Error: Error loading postrender module @nexrender/action-upload: CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
    at /snapshot/nexrender/packages/nexrender-worker/node_modules/@nexrender/core/src/tasks/actions.js
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async start (/snapshot/nexrender/packages/nexrender-worker/src/index.js)
```

```

  project.actions.postrender = [
    {
      module: "@nexrender/action-encode",
      preset: "mp4",
      output: "encoded.mp4",
    },
    {
      module: "@nexrender/action-upload",
      input: "encoded.mp4",
      provider: "s3",
      params: {
        region: process.env.AWS_S3_REGION,
        bucket: process.env.AWS_S3_BUCKET,
        key: `${context.project.id}.mp4`,
        acl: "bucket-owner-full-control",
      }
  ];
  job.output = `https://s3-${params.region}.amazonaws.com/${params.bucket}/${params.key}`;
};
```

**Comment by inlife** [comment]
Most likely its an error coming from AWS-S3 module. Check if you have those 2 env vars set up: https://github.com/inlife/nexrender/tree/master/packages/nexrender-provider-s3#installation

**Comment by FinnFrotscher** [comment]
I am passing the variables via the job object. are they ignored when using the worker?

**Comment by inlife** [comment]
I don't think you can pass environmental variables via job definition. They are system-based things.

**Comment by FinnFrotscher** [comment]
My question is Why do i have to pass the aws credentials as environment variables to the Worker?
The worker receives a finished job object, where the aws credentials are passed as part of the `@nexrender/action-upload`

this code is running in my api service. here the job is being built and the aws credentials are assigned. 
```
  project.actions.postrender = [
    {
      module: "@nexrender/action-upload",
      input: "encoded.mp4",
      provider: "s3",
      params: {
        region: process.env.AWS_S3_REGION,
        bucket: process.env.AWS_S3_BUCKET,
        key: `${context.project.id}.mp4`,
        acl: "bucket-owner-full-control",
      }
  ];
```
