### ISSUE TITLE
Can we create a document file using scripting 

### ISSUE THREAD

**Issue by darshakgosar** [inlife/nexrender#407]
Hi,
Is it possible to create a document file on the fly using scripting functionality.
JSON
```
{
 "template": {
        "src": "file:///template.aep",
        "composition": "BLANK_COMP"
    },
 "assets": [
    {
        "src": "file:///C:/sample/script.jsx",
        "type": "script"   
    }
 ] 
}
```
script.jsx
```
var Loginfo = new File("./testnew.txt");
Loginfo.open("w", "TEXT");
Loginfo.write("Welcome");
Loginfo.close();
```

Thanks

**Comment by inlife** [comment]
Hello,

Since it is a full scripting environment, it should be indeed possible.
The only issue might be with paths and the file location. As an alternative, you could try using absolute paths as well.

Cheers!
