### ISSUE TITLE
Api and worker integration issue. Api never calls `onFinish` and repeats  `is at 42% `

### ISSUE THREAD

**Issue by FinnFrotscher** [inlife/nexrender#408]
I use the `nexrender/api` to push a job to the `nexrender/server`, that is then picked up by the `nexrender/worker binary`.

```
  console.log("project  JSON size" + memorySizeOf(project));
  const result = await client.addJob(project);
  return new Promise((resolve, reject) => {
    result.on('created', (job) => console.log('project has been created'));
    result.on('started', (job) => console.log('project rendering started'));
    result.on('progress', (job, percents) => console.log('project is at: ' + percents + '%'));
    result.on('finished', (job) => {
      console.log('project rendering finished');
      resolve(job);
    });
    result.on('error', (err) => {
      console.log('project rendering error', err);
      reject(err);
    });
  });
```
the logs of the binary are as expected.
the logs that reach  the api client are all out of order. 
![tumblr_pqrllwiN5X1tc88d9_540](https://user-images.githubusercontent.com/11148454/84282668-545c2800-ab3a-11ea-99d4-ca3ba7144836.jpg)

result.on(finish) is never called.  even after the worker has been finished for quite a while.
api logs:
```
Project JSON size: 9.384 MiB
project has been created
project rendering started
project is at: 9%
project is at: 9%
project is at: 9%
project is at: 9%
project is at: 9%
project is at: 9%
project is at: 9%
project is at: 9%
project is at: 9%
project is at: 1%
project is at: 34%
project is at: 75%
project is at: 84%
project is at: 84%
project is at: 67%
project is at: 50%
project is at: 76%
project is at: 42%
project is at: 42%
project is at: 42%
project is at: 42%
project is at: 42%
project is at: 42%
project is at: 42%
[project is at: 42%] //  infinite
```
what could be the  source of that?

**Comment by inlife** [comment]
Wow, that is indeed weird. Does it happen with all projects, or only with particular?
Does it maybe depend on project rendering time?

P.S. Nice picture :D

**Comment by FinnFrotscher** [comment]
it happens with all projects that are of a certain size. i encode some scripts and assets in base64 and thus my projects are easily 10mb in size.
the issue was the implementation of the database. since its a pretty simple json file database, there is no caching or diffing. everytime the api or the worker post an update, the entire content of alll projects is read and written. since my proejcts are large, it gets slow. the issue above emerges from inconsistent `io`. 
i went around this by saving the project body (assets, tempalte) in a seperate  file and keeping only meta info inside the database.
generally, everywhere in communication  with the server, you allways send the entire job object. this can/should be optimized.

**Comment by inlife** [comment]
Yeah, I see the issue. The job-network communication was not designed for "heavy" jobs. Probably a good thing to think about for the next major release.
