### ISSUE TITLE
JSON.stringify() function doesn't work in scripts ?

### ISSUE THREAD

**Issue by darshakgosar** [inlife/nexrender#409]
Hi,
While I am using JSON.stringify() in the script for converting my json into a string and storing it into a json file, which is being called through nexrender, the rendering process just get freeze. Can you help me out what could be the issue.
Thanks :)

**Comment by SMakc** [comment]
@darshakgosar, you can use `json2.js` in your JSX  
```
var json2 = "/path/scripts/json2.js";
$.evalFile(json2);
```
https://github.com/douglascrockford/JSON-js
