### ISSUE TITLE
Worker getting hung up on Windows Server

### ISSUE THREAD

**Issue by isaacberge** [inlife/nexrender#411]
I am running the newest Nexrender server CLI on Windows Server 2019. I've got everything working properly; however, the worker seems to get stuck randomly and I have to click enter in the command line for it to continue normally. It happens at random times, such as when a new job is created, I have to click enter for the worker to start processing it.

I am expecting the worker to run from start to finish without intervention; however, that's not the case right now. Any suggestions?

**Comment by inlife** [comment]
Please check if that issue is not related to any of those:
https://github.com/inlife/nexrender/issues/191#issuecomment-512980182
https://github.com/inlife/nexrender/issues/239
