### ISSUE TITLE
Submitting more assets at pre-render

### ISSUE THREAD

**Issue by Guzmank90** [inlife/nexrender#414]
Hello,
I'm trying to add more assets via pre-render action:
`{
"src":"file://C:\\dev\\pWPsmalLeAqVq1UEtoqFo\\(Footage)//icons//like_icon.png",
"layerName":"like_icon.png",
"useOriginal":true,
"name":"like_icon.png",
"dest":"C:\\dev\\pWPsmalLeAqVq1UEtoqFo\\(Footage)\\icons\\like_icon.png",
"type":"image"
}`
tried all slashing variations possible - it won't go through.
Upgraded Server + Api + Core today.

Some why if i don't define dest (which i shouldn't) it fails with following error which is pretty the default you get:
`error occurred: TypeError: Cannot read property 'replace' of undefined`
No matter how i spin it i get:
`aerender ERROR: Error executing script: C:\dev\ZSXJ9NIGBIVREWmHWwU0m\nexrender-ZSXJ9NIGBIVREWmHWwU0m-script.jsx
Error: After Effects error: layer does not have a source.
aerender ERROR: Runtime error in After Effects.

[ZSXJ9NIGBIVREWmHWwU0m] error occurred: Error: Couldn't find a result file
    at ChildProcess.instance.on (C:\dev\server\node_modules\@nexrender\core\src\tasks\render.js:152:31)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)`

Thanks,
Hopefully you can help.

**Comment by Guzmank90** [comment]
Update: 
Tried with file-url module or node based url to encode the path to URI..
Can't understand why i can't add a path so it would be replaced..

**Comment by inlife** [comment]
Please try to keep path formatting consistent across full length of the string, and make sure you follow the URI specification of the file protocol.

**Comment by Guzmank90** [comment]
- I've tried through full path
- Tried proper format with '/' Slashes tried with `\` slashes.
- Tried with https://www.npmjs.com/package/file-url
- Tried with Node.js url via require module
- Tried with and without some values...

It won't work...i suspect that assets are already converted to URI...Logicly it should work, technically it won't go through...let's say is "useOriginal":true, it is checked before pre-render so it won't help..it doesn't use local files direclty.

**Comment by inlife** [comment]
Could you explain what are you trying to achieve? Maybe I did not understand fully what is happening there.
