### ISSUE TITLE
Custom upload action

### ISSUE THREAD

**Issue by limzykenneth** [inlife/nexrender#415]
**Is your feature request related to a problem? Please describe.**
In postrender action `action-upload`, the current list of upload solutions (s3, gcs, ftp) does not fit my current project's requirement and I find myself looking to write some custom bindings to upload to other services.

**Describe the solution you'd like**
It would be nice to be able to provide my own solution for other servies that I can use with `action-upload`.

**Describe alternatives you've considered**
Failing that I can of course write the solution as a postrender action on its own but since the code is already there for upload action I don't want to duplicate that part if not necessary.

**Comment by inlife** [comment]
Hello @limzykenneth 

As you can see from the source code, action-upload relies on the dynamic package matching. I believe that expression could be modified further so that it would support not only modules prefixed with `@nexrender/provider-` but any wildcard-type name, as a second-priority case, and fail only if both provider and wildcard cases were not matched.

That way action-upload would become a truly generic action, in a way. What do you think about that?

**Comment by limzykenneth** [comment]
I'm thinking something along those lines too. For the `provider` parameter the officially supported modules can be provided with a string as it is now, I'm a bit less sure about how a custom named action can be implemented: would they need to be globally installed as well?

**Comment by inlife** [comment]
Well, that would possibly be one of the ways. Alternatively, even right now a relative/absolute module/script path can be used. Do you have some other possible options in mind?

**Comment by limzykenneth** [comment]
My current setup is using `nexrender-server`, `nexrender-client`(possibly on a different machine), and `nexrender-api`, with that setup I assume globally installed modules is the only solution? I would have liked to provide a function as the value of `provider` but since it is passed around as JSON, that would make it unfeasible. I can't think of any good solution other than globally installed module in this case.

**Comment by inlife** [comment]
Yep, probably you are right. A globally installed module in that case right now would be one of the, if not only, viable solutions.
Do you maybe have some other ideas/improvements, how the whole plugin system can look?

**Comment by limzykenneth** [comment]
What I'm thinking of, usage wise, is the provider field works first as usual for any officially supported ones (s3, gcs, ftp, etc) then if `requireg` cannot find the `@nexrender/provider-{provider}` package, it search globally installed modules literally. For example if I installed something like `nexrender-upload-backblaze` globally and pass the name to the provider field, it first look for `@nexrender/provider-nexrender-upload-backblaze` which doesn't exist, then it will look for `nexrender-upload-backblaze` installed globally.

One thing that would make the process easier is to have either a template file or sufficient documentation for third party implementation of something like `nexrender-upload-backblaze` to be created from it without having to dig into the source for `@nexrender/provider-s3` etc.

**Comment by inlife** [comment]
Yes, I agree that it sounds like a good and viable strategy for the module lookup.
Sorry for the long response.

**Comment by limzykenneth** [comment]
I'm a bit occupied for now but I can file a PR probably in a couple weeks' time. If you or someone else wants to give this a go don't wait for me.

**Comment by inlife** [comment]
That is fine, we are in no rush. Take your time :)
