### ISSUE TITLE
Can't find a property sequence Source Text for key: Source Text

### ISSUE THREAD

**Issue by jonnymangothinkjam** [inlife/nexrender#416]
**Describe the bug**
A clear and concise description of what the bug is, and ways to reproduce it.

I'm getting an error on 2 pieces of text and getting the error:
 nexrender: Can't find a property sequence Source Text for key: Source Text

here's a screenshot of the text layer in AE:

![image](https://user-images.githubusercontent.com/25662069/85136505-a1758380-b237-11ea-9938-92efb8c3c090.png)

all other text layers in the file are fine, just this one. not sure if there's something different with the layer

**Information about environment**
* Which version of nexrender are you using?

1.0.1

* What kind of the setup do you have? (server+worker or cli)
node.js environment - no server/worker

* Are you using pre-built binaries or globally installed npm packages?
globally installed
* Which kind (and version) of operating system you are running it in?
windows
* Any additional information that might be helpful

**Comment by inlife** [comment]
Could you show what property sequence are you using? 
After Effetcs has some quirks related to naming.

Also please check out this issue, it might be helpful: https://github.com/inlife/nexrender/issues/126

**Comment by jonnymangothinkjam** [comment]
Sorry for the delayed response - i did actually get this working, i took the spaces out of the text layer name and it sorted it. 

weird as i was copy/pasting the text direct so shouldnt have been any funky spaces. 

thanks though!!

**Comment by SMakc** [comment]
@jonnymangothinkjam, Today I got same error. 
The problem was that the text layer and composition had the same name.
Please check, maybe you have Composition with name 'MARH 19'?

**Comment by jonnymangothinkjam** [comment]
no it wasn't that - the comp name was the same as the file name. it was something to do with the text layer naming. renaming solved the issue (taking out spaces, FYI)
