### ISSUE TITLE
is there a possibility to scale images in relation to composition without losing aspect ratio?

### ISSUE THREAD

**Issue by iandtek** [inlife/nexrender#420]
Hello there, I started using nexrender yesterday and so far I love it. I was using templater before but now I will change my workflow to nexrender and give my money to nexrender project!

In Templater I had the possibility to adjust automatically the images to fit a composition without losing the aspect ratio, is there a possibility to do it in nexrender?

In templater the option was called scale factor and fit image style.

Thank you!

<img width="905" alt="Screen Shot 2020-06-30 at 11 55 47 AM" src="https://user-images.githubusercontent.com/20668458/86148465-a56f9400-bac8-11ea-8f74-6700d14546ac.png">

**Comment by inlife** [comment]
Hey @iandtek 

Glad to hear that!
There is no direct way of doing that as far as I know. Unless some of the users created a custom pre-render action for that.

Alternatively, that sounds like something that could be also done with AE scripting, or even expressions. So you could try to check those out as well.

Cheers!

**Comment by iandtek** [comment]
@inlife 

Great, Thank you so much, If I develop a custom action will post it here or if I find the way using scripting or expression will post it here.

Thank you!

**Comment by inlife** [comment]
That sounds good!

**Comment by iandtek** [comment]
I found the way to do it with expressions! 

Here is an example of the request:

`"assets": [
        {
            "src": "https://htmlemail.io/img/blog-shopify.jpg",
            "type": "image",
            "layerName": "logo"
        },
        {
            "type": "data",
            "layerName": "logo",
            "property": "Scale",
            "expression": "s = (thisComp.height/height)*100; [s,s]" // This is the magic expressions that scales the image based on the height of the composition
        },
        {
            "type": "data",
            "layerName": "page",
            "property" : "Source Text",
            "value": "shopify.com"
        }
    ],`
