### ISSUE TITLE
Is it possible to run Nexrender from WSL?

### ISSUE THREAD

**Issue by Klastic** [inlife/nexrender#422]
I am running into an issues I can't seem to figure out when trying to follow the CLI getting started example. 

I am able to start rendering the project, creating the temp folder and can write out logs, however, when aerender goes to call openFast, it seems the path is pointed to **C:** instead of to **Z:** (my WSL mapping).

If I flag it to skip rendering it will complete.

Is there any way to point this to the proper drive I have mapped for WSL?

![image](https://user-images.githubusercontent.com/11662370/86202773-d5e71a80-bb28-11ea-8fa9-9d23e5708f1f.png)

**Comment by inlife** [comment]
Hey @Klastic 

You are probably the first person to use it with WSL :)

Seems like the error you are referring to comes from within the after effects. Have you tried checking if the version of after effects you have installed supports WSL mapping?

Cheers!

**Comment by Klastic** [comment]
@inlife 

I should of mentioned I had previously tried to render a .aep, which was generated by Nexrender, from the GUI. It rendered correctly into the tmp folder which was created by Nexrender in WSL.

I did some more testing and found I was able to run the arreander command, which Nexrender was trying to run, from WSL with a modification to the path.

![image](https://user-images.githubusercontent.com/11662370/86216138-279c9e80-bb43-11ea-8032-0255f96852bf.png)

Next I dug into the code of Nexrender and found where the rendering process was being created inside of render.js. I modified the paths to include my WSL map.

![image](https://user-images.githubusercontent.com/11662370/86216335-7e09dd00-bb43-11ea-88c7-f15d6452610a.png)

which yielded a successful render.

![image](https://user-images.githubusercontent.com/11662370/86216544-d04afe00-bb43-11ea-8e73-7ee34f889ff8.png)


I would be willing to build a feature for this if there is not already something which can help with this.

My knowledge of the codebase is limited so please correct me if this is not ideal, however, I was thinking a flag such as -wsl which would allow a drive path to be passed in; so for the CLI `-wsl Z` and for programmatic `{ wsl: "Z"}` . This would append the drive location to the front of the path. This flag would also tell the `autofind.js` to use `/mnt/c/` instead of `C:\` preventing the dev from needing to use the -b flag.

**Comment by inlife** [comment]
I think You can try it, I don't see why not.
My only worry is it should not break existing setups for other people that are not using that feature, i.e. it should be backward compatible.

**Comment by Klastic** [comment]
Understandable, I will create a fork and once I feel it is stable I will open a PR.  

Thanks.

**Comment by FinnFrotscher** [comment]
the docs dont yet specify how to use with the `binary`.  since the binary is to be run under linux and not win or macos, it seems there is a need for a new binary type. correct?

https://github.com/inlife/nexrender/blob/master/package.json#L23
https://github.com/inlife/nexrender#nexrender-worker

**Comment by Klastic** [comment]
> the docs dont yet specify how to use with the `binary`. since the binary is to be run under linux and not win or macos, it seems there is a need for a new binary type. correct?
> 
> https://github.com/inlife/nexrender/blob/master/package.json#L23
> https://github.com/inlife/nexrender#nexrender-worker

I provided a quick guide to the binary [here](https://github.com/inlife/nexrender#wsl-binary). We are triggering the Windows binary from WSL. I will look at making it more clear that you are using the Windows binary.

**Comment by FinnFrotscher** [comment]
I think we are refering to different binaries. I am not talking about the after effects (aerender.exe) binary, but the binary of the nexrender-worker that is build on each nexrender release.

the difference is, that the cli consumes ONE job object and the worker consumes from the queue and runs indefinetely. 
```
nexrender-cli \
     -f mywsljob.json \
      -b "/mnt/d/Program Files/Adobe/Adobe After Effects 2020/Support Files/aerender.exe"
```
vs
```
nexrender-worker \
        --host=https://my.server.com:3050 \
        --secret=myapisecret
```
