### ISSUE TITLE
Successive jobs for rendering using api/server/worker？

### ISSUE THREAD

**Issue by soundquiet** [inlife/nexrender#423]
Hi, I want to know how to run multiple jobs together?

I create a client to receive ae render requests, and nexrender server with one or two workers. 
I send two requests, same job json on the same template, with a short interval, so the first job is not yet done. 

Then one of the jobs will fail and with error 
```
Error: nexrender: Cound't find any layers by provided name (P_img) inside a composition: *
aerender ERROR: Runtime error in After Effects.
aerender version 15.1.2x69
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched

[msyPUbal3mRscFPoGPE7G] error occurred: Error: Couldn't find a result file
    at ChildProcess.instance.on (/usr/local/lib/node_modules/@nexrender/worker/node_modules/@nexrender/core/src/tasks/render.js:152:31)
    at ChildProcess.emit (events.js:198:13)`
```

At first, I thought it was caused by the same AE template file, but I made a copy to render on two different AE files, still one of them would fail.

Then I start two workers, with same error.

It works well if I send the second request until the first job is done.

**So my question is,** 
how to make jobs run in parallel or even in serial? Did I misunderstand the usage of nexrender?
Thank you very much!

I work with 
- nexrender-worker: 1.17.1
- @nexrender/api": "^1.14.4",
- @nexrender/server": "^1.17.0",

**Comment by inlife** [comment]
It should work just fine the way you expected it to. nexrender should be capable of rending as many different jobs at a single time as there are running workers.

Looking at the error message you showed:
> Error: nexrender: Cound't find any layers by provided name (P_img) inside a composition: *

I can see there is some error within the project file, nexrender is not able to find a particular layer name.

Could you show the json jobs that you submit via API, and also which parameters are you using for workers when you launch them?

**Comment by soundquiet** [comment]
I saw the discussion in #235 where mensioned that layerName sometimes will be changed by source.
So I replace "layerName" into "layerIndex" and "composition" of P_img. And it works now! 

But I still wonder why layerName doesn't work if multiple jobs running. 

I use `nexrender-worker --host="http://localhost:3050"` to start workers.

Thank you!

**Comment by inlife** [comment]
My initial suspicion was that it might be caused by a --reuse flag, but I see that you are not using that. So yea, I also wonder now. :D

**Comment by soundquiet** [comment]
Hi @inlife , we have found the issue. 
It is nothing to do with nexrender, it is due to the aep file. Layer `P_img` has the same name as the asset file. 
Fixed by changing the name in aep to avoid same name of layers and asset files.

Thank you!

**Comment by darshak-gosar** [comment]
Hi @inlife ,
I am facing same issue, I have check the composition name along with layer names and they seem to be intact. Could you help me out with this issue.
ERROR: nexrender: Couldn't find any layers by provided name (LayerName) inside a composition: *

**Comment by inlife** [comment]
could you share your job definition?

**Comment by darshak-gosar** [comment]
Sure
```
let projectJson = {
        template: {
            src: `file://${path.join(path.dirname(__dirname), '/public/assets/Project/filename.aepx')}`,
            composition: 'compositionName',
            outputModule: 'Team', 
            outputExt: 'mov', 
        },
        assets,
        actions: {
            postrender: [{
                module: '@nexrender/action-encode',
                preset: 'mp4',
                output: 'encoded.mp4'
            },
            {
                module: '@nexrender/action-copy',
                input: 'encoded.mp4',
                output: `${dir}/${remakeTitle}.mp4`
            }
            ]
        }
    };
    // Start rendering
    const data = await nexrender(projectJson, settings)
```
