### ISSUE TITLE
Positional change of a component through assets

### ISSUE THREAD

**Issue by sriram-backend** [inlife/nexrender#424]
Hi,

When I try to change the position of a layer through assets, it perfectly renders without any issues.

```
{
    "assets": [
        {
            "type": "data",
            "layerName": "product.image.1",
            "property": "Position",
            "value": [500, 100]
        }
    ]
}
```
But, I'm running into an issue when I try to change the position of a component, ended up getting the following error,

`After Effects error: Can not call setValue() on a property with keyframes. Use setValueAtTime() or setValueAtKey() instead.`

Can you help me out?
Thanks in advance.

**Comment by inlife** [comment]
Seems like the built-in functionality won't cut it for you with this given example. I would suggest trying using scripting manually. That could look something like that (**NOTE**: that is not a 100% valid code, just a suggestion):
```js
nexrender.selectLayersByName("*", "product.image.1", function(layer) {
    layer.property("product").property("image").property(1).setValueAtTime([500, 100], 100)
});
```

**Comment by sriram-backend** [comment]
> Seems like the built-in functionality won't cut it for you with this given example. I would suggest trying using scripting manually. That could look something like that (**NOTE**: that is not a 100% valid code, just a suggestion):
> 
> ```js
> nexrender.selectLayersByName("*", "product.image.1", function(layer) {
>     layer.property("Position").setValueAtTime([500, 100], 100)
> });
> ```

**Comment by sriram-backend** [comment]
Thanks a lot for your prompt response and suggestion :)
