### ISSUE TITLE
Render always generates result.avi file which is too big and causes memory problems

### ISSUE THREAD

**Issue by aysimakarca** [inlife/nexrender#427]
Hi,

I saw some memory problems while i was trying to render 20 videos in paralel and then noticed that nexrender folder under temp folder consumes almost 38 GB memory and biggest consumer is result.avi file which is created after render. I am getting my output as mp4 and mp4 file is really small but avi file is 50 times bigger than my mp4 file. Is there a way to render the video directly as mp4 and render to one path so it is not going to deal with copying the file.

Also i would like to hear if you have any other suggestions about memory optimization. As i see if i run 50 render then it will create 50 folder with all project files and result.avi which gets too big.

Thank you in advance,
Aysima

**Comment by inlife** [comment]
Hey @aysimakarca 

One of the reasons why action-encode was added, is this issue with After Effects no longer being able to render mp4 directly. (It had such functionality before AE CC 2016, iirc, then it got removed). Right now there is no way to render to mp4 without going through a temp stage, unfortunately.

Suggestions on memory optimization can be as following: render fewer frames, or less time, use pre-rendered footage, research different built-in codecs for AE (maybe one of them will be less storage-hungry compared to avi), or simply increase the overall storage capacity. Judging by the number of jobs you want to render and how big the files can get, probably a 10-20 TB should be enough.

Cheers!
