### ISSUE TITLE
aerender Error: After Effects�: 2"y 1 ���

### ISSUE THREAD

**Issue by yunnian** [inlife/nexrender#428]
`Running Script: /tmp/nexrender/cfsZgEsZKwJU50vm56mKt/nexrender-cfsZgEsZKwJU50vm56mKt-script.jsx
PROGRESS: Adding specified comp to Render Queue
aerender Error: After Effects�: 2"y 1 ���
                                         ��!W 1�'(�U /tmp/nexrender/cfsZgEsZKwJU50vm56mKt -����'��eCP
aerender version 17.1.1x34
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched`

How can I solve this problem？

**Comment by yunnian** [comment]
resolve  remove 'sudo'

**Comment by inlife** [comment]
Glad you got it resolved 👍
