### ISSUE TITLE
Tested it!

### ISSUE THREAD

**Issue by max-kovpak** [Inlife/nexrender#43]
I tested render node & api server on MacOS Sierra 10.12.6 and Windows Server 2016 with AE CC 2018 Version 15.0.0 (Build 180). Works fine 👍

**Comment by Inlife** [comment]
oh, great news, so it is actually working fine
and was it mp4 rendering, or avi/mov, or maybe any other ?

**Comment by max-kovpak** [comment]
@Inlife on both systems it was mov

**Comment by Inlife** [comment]
oh i see
and i almost sure new AE doesn't allow to setup the h264 output
