### ISSUE TITLE
Do `nexrender-worker` machines need "Installed licensed/trial version of Adobe After Effects"?

### ISSUE THREAD

**Issue by pdkn** [inlife/nexrender#431]
Hi Guys,

The docs mention, as a requirement, that `nexrender-worker` machines need a "Installed licensed/trial version of Adobe After Effects"? However I think the aerender binary (rendering engine) can be installed on workers without the need for them to each have AE licence. See

![Screenshot 2020-07-14 at 11 26 40](https://user-images.githubusercontent.com/186148/87415384-eeddda00-c5c4-11ea-96d4-fe411e1b3036.png)

[https://helpx.adobe.com/after-effects/using/automated-rendering-network-rendering.html](https://helpx.adobe.com/after-effects/using/automated-rendering-network-rendering.html)

Do the docs need amending or have I got wrong?

**Comment by inlife** [comment]
nexrender has a built-in utility that allows you to create ae_render_only.txt file within the worker, you can check the bottom of the options list here: https://github.com/inlife/nexrender#information

**Comment by pdkn** [comment]
sweet, so the workers don't need a "Installed licensed/trial version of Adobe After Effects"? (as a requirements here ["https://github.com/inlife/nexrender/tree/master#requirements-1"](https://github.com/inlife/nexrender/tree/master#requirements-1) ?

**Comment by inlife** [comment]
In a way yea, they do not, that is why it's hinted there about `trial` version as well.
I don't think mentioning openly about something like that would be a good idea tho, I'm not sure if that is something we can safely do legal-wise :D

**Comment by pdkn** [comment]
Aha, I'm pretty sure that's the point of the aerender binary, else it would be excessively expensive to setup render farms. The link is from Adobe themselves which shows only one licence is needed for the aep project creation. Obv keen to make sure everything is legit, hence mentioning it as might put people off render farms if they think they need multiple licenses when they don't? It's not super clear. (especially if you're handed a aep project and just want to do rendering, you might not need a licence at all, legitimately) I might reach out to Adobe for confirmation...

**Comment by inlife** [comment]
if you do that, and they do respond, I would be very interested to know the answer!
