### ISSUE TITLE
network rendering - downloading .aep linked assets i.e (Footage) folder

### ISSUE THREAD

**Issue by pdkn** [inlife/nexrender#436]
I've got local network rendering working using S3. I'm also using http://localhost.run/ to help run on local network. `worker` machines are downloading the .aep file from S3, rendering, and uploading final .mp4 back to S3. However `nexrender-core/src/tasks/download.js` only downloads the .aep file set in the `job.template.src`. Are there any thoughts on how to download linked assets too? i.e the standard `(Footage)` folder ?

**Comment by inlife** [comment]
Could you actually show how that folder looks like?
Both on the filesystem, and inside AE interface. 

I remember a lot of people mentioned about this issue already, maybe we can find a good solution for this.

**Comment by pdkn** [comment]
I can’t upload complete folder structure but the standard is there’s a folder called ‘(Footage)’ that sits alongside the .aep file. 2 thought, either allow adding an assets folder to job.template.assetsFolder which is used to download/copy folder. Witty assumption that all linked assets to project are there. Or add to job.template.folder Which is the containing folder of everything for download/copy and then set job.template.aeFilename which is relative to Folder. Both give some flexibility without needing to know too much specific about setup. First option might be more backward compatible...

**Comment by inlife** [comment]
I see, that sounds like something nexrender-core should be responsible for, and any action won't be able to help at this point.
This first option you suggested sounds better, even tho the better name for it might probably be something like `defaultFootage: (true/false)`, what do you think?

The other thing I'm not yet sure, how would it understand and be able to "serve" those files to the workers.

**Comment by pdkn** [comment]
Yup, totally agree it’s for core to handle. If You’re just using networked folders then Adobe recommends .aep use absolute paths. https://helpx.adobe.com/lv/after-effects/using/automated-rendering-network-rendering.html.  but that won’t work for S3. For S3, if the footage folder is downloaded to same location as the .aep file, all should be good. So if we go for defaultFootage, there needs to be an expectation that relative paths are used (which is fine by me if documented)?

**Comment by inlife** [comment]
@pdkn so if I understand correctly, if AE project is not using absolute paths for the footage files from within (Footage) folder, it wont be imported properly on the target machine?

**Comment by pdkn** [comment]
There's 2 senarios, 
**Files on local networked drive**
If the projects are stored on a networked drive, than all `worker` machines should be able to access it. As only the .aep file is copied to the `worker` machine, then it will need absolute paths to reference back to the network drive assets which aren't currently copied to the `worker`. 
**Files stored in Cloud**
The other senario is that the AE projects are copied & stored in the cloud i.e S3 for downloading & processing. Here, absolute paths won't work as AE project can't point directly to S3 and will likely reference an inaccessible machine. So they need to be relative paths and the assets need to be downloaded along with the .aep file for processing on a `worker` machine.

**Comment by pdkn** [comment]
To be consistent, and atomic, allowing for both scenarios. I'd suggest making sure assets are relative and also copied to the `worker` machine, along with the .aep file. I'm not sure yet how easy it is to manage absolute/relative paths in AE. (i.e I haven't found a setting that can enforce it yet)

**Comment by inlife** [comment]
another problem related to absolute paths, that comes to my mind, after having that experience working in the legacy nexrender version (pre 1.0), was that if such a path is found on a local machine, ae will always use that path, and skip looking for assets within relative folder nearby the aep file

I'm not sure yet how to tackle this seemingly small but quite complex problem. The perfect way would probably be if nexrender was able to automatically describe which other files are used within the aep file, automatically create a job based on those (or add them to an existing job), and find a way to serve those files. Reason for that being that now we know that doing manual replacing within the jsx is the safest and reliable way of substituting assets.
