### ISSUE TITLE
WSL os.release() doesnt match

### ISSUE THREAD

**Issue by FinnFrotscher** [inlife/nexrender#441]
I am test wsl and am encountering an issue arround the matching of os.release

On my system:
```
$ os.release() 
=> '4.4.0-17763-Microsoft'
```

which doenst match `os.release().match('microsoft')` because of case sensitivity.

https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/index.js#L42

**Comment by Klastic** [comment]
> I am test wsl and am encountering an issue arround the matching of os.release
> 
> On my system:
> 
> ```
> $ os.release() 
> => '4.4.0-17763-Microsoft'
> ```
> 
> which doenst match `os.release().match('microsoft')` because of case sensitivity.
> 
> https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/index.js#L42

Thanks for testing! I will look into fixing this asap.

**Comment by limzykenneth** [comment]
If you want to check for WSL, [this package](https://www.npmjs.com/package/is-wsl) could potentially be helpful?

**Comment by Klastic** [comment]
> If you want to check for WSL, [this package](https://www.npmjs.com/package/is-wsl) could potentially be helpful?

That will work, it's in the direction I was headed. I was ideally trying not to add more dependencies to nexrender.

**Comment by limzykenneth** [comment]
The source for it is rather simple so you can just copy it instead if you don't want to add it as a dependency.
