### ISSUE TITLE
WSL Flag in nexrender-worker

### ISSUE THREAD

**Issue by limzykenneth** [inlife/nexrender#442]
**Is your feature request related to a problem? Please describe.**
I see that there's recently added support for WSL but it seems to only work for nexrender-cli. It would be great to enable the relevant flag to nexrender-worker as well.

**Describe the solution you'd like**
Enable `-m`/`-wsl-map` flags for nexrender-worker

**Describe alternatives you've considered**
I'm using nexrender-worker as a render farm setup, it's got a lot of problems, I'm hoping WSL can solve some of them.

**Comment by inlife** [comment]
CC @Klastic 
What do you think about this? :)

**Comment by Klastic** [comment]
Sounds good to me, it was a bit outside my use case when I submitted the PR, so I did not add support for it.

I will add support for the worker when I fix #441.

**Comment by inlife** [comment]
hey @Klastic, were there any updates on that fix and feature? :)

**Comment by Klastic** [comment]
> hey @Klastic, were there any updates on that fix and feature? :)

Negative, I have not had a chance to get to it. I will slate some time tomorrow to get it fixed. 😁
