### ISSUE TITLE
Spawn EBUSY error in latest versions

### ISSUE THREAD

**Issue by aysimakarca** [inlife/nexrender#444]
Hi,

After i upgraded the nexrender dependencies, i started to see the error Spawn Busy in postrender module. Result avi file is created successfully but it is not converted to mp4. I have read about same error in previous versions but i am using the latest versions for all modules.

Here is the error i get:
Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg) Error: spawn EBUSY
    at C:\Users\aysima\Documents\Repos\core-renderer\node_modules\@nexrender\core\src\tasks\actions.js:25:35
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
> ffmpeg binary b4.2.2 was successfully downloadedeconds

Does anyone have any idea about how to solve this?

Thanks in advance,
Aysima

**Comment by inlife** [comment]
Could you try downloading a custom latest version of FFmpeg binary, and providing path to it in the env variable: NEXRENDER_FFMPEG=.... before launching the nexrender?

**Comment by aysimakarca** [comment]
What is FFmpeg binary? I dont think i have ever installed that. What is the node module name?

I will try giving the path but i am not sure how to download it. But it also happened in a new environment which i downloaded everything with latest versions.

Thanks for quick response btw.

**Comment by aysimakarca** [comment]
Thanks for your quick response. I did download the compiled version of latest FFmpeg and placed it under C with the name FFmpeg, error has changed but i still get the error below:

Error: Error loading postrender module @nexrender/action-encode: Error: Error starting ffmpeg process: Error: spawn C:\FFmpeg\bin ENOENT

Do you think i am doing sth wrong here?

**Comment by inlife** [comment]
I see you've provided path C:\FFmpeg\Bin, try actually providing full path to the exe: C:\FFmpeg\bin\ffmpeg.exe

**Comment by aysimakarca** [comment]
It worked, thank you a lot! @inlife

**Comment by Wence-May** [comment]
Hi! I also ran into the same problem with the latest version, and now it works well with the solution above.

But what confuse me a lot is, I am providnig ffmpeg version4.3 path to the env variable. But when I run nexrender,  it successful call FFmpeg-b4.2.2.exe. Something in worker's log like:

> using an existing ffmpeg binary b4.2.2 at: C:\Users\xxx\AppData\Local\Temp\nexrender\ffmpeg-b4.2.2.exe
[wuqysmMf49w79MuLQFRCX] ffmpeg version git-2020-01-26-5e62100 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls ......

So why ffmpeg version4.3 is needed?
