### ISSUE TITLE
Is it a good idea to extend cli to forward arbitrary AfterEffects parameter?

### ISSUE THREAD

**Issue by brassel** [inlife/nexrender#446]
Recently, we have found the need to render with the `–close SAVE_CHANGES` parameter for AfterEffects.
As far as i see this is not yet possible with nexrender.
I could add this single option and create a pull request.
However, I think it might be more useful to extend the cli to forward any such parameter.
This could look like this:

`nexrender --aerender-parameter 'close SAVE_CHANGES' --ae 'i 10' job.json`

with `--ae` being a short hand for `--aerender-parameter`.

Then this kind of issue would be solved for good.

What do you think?

**Comment by inlife** [comment]
Hey @brassel 
Good to hear back from you!

I think you are right with the second assumption. I also catch myself thinking over and over that having a way to directly pass parameters to aerender would be much more beneficial, than just adding more and more custom differently names parameters.

So I think adding a pass option like you've mentioned is a great idea. My only 2 concerns are:
1. Ability to override parameters passed by nexrender by default (assuming that users that are using custom pass parameters knows what they are doing; that can be much more beneficial to them)
2. Format, preferably generally used one, for passing parameters, that would allow (1) to be easily achievable.

What do you think about those points?

And finally, the --ae and --aerender-parameter names look good to me.

**Comment by brassel** [comment]
Hey @inlife, big hello back! :o)

If I understand point 1 correctly, it is about where to put the transfer of the command line settings to the render settings in render.js, maybe? I would put this last as the command line parameters seem to me most specific. And the specific should override the less sepcific. This way any nexrender defaults could be overridden by command line parameters. But maybe I misunderstood the question?

As to point 2, my suggestion would use exactly the format given to `aerender`. Is that what you meant?

**Comment by inlife** [comment]
Let me clarify things:

1. nexrender passes a lot of parameters to the aerender binary, that happens in the tasks/render.js. My point was that, if we provide any additional arguments via the method you suggested, they should override those that are already passed in tasks/render.js.

2. By format I meant some usual case how it is done. From my experience, I've came to see often something like being used: `$ parent -a -b -c -- -childa -childb -childc`, where children arguments start after -- sequence, we can follow same Unix (I believe) concept here as well

Does it help with understanding?

**Comment by brassel** [comment]
> Does it help with understanding?

Yes, now I got it! Thanks for clarifying.

> if we provide any additional arguments via the method you suggested, they should override those that are already passed in tasks/render.js.

Yes, I also think that this is the best way to go. I have done this in render.js, as you will see in the pull request.

>  we can follow same Unix (I believe) concept here as well

Yes, I agree. In this case the format is 

`nexrender --ae 'key value' --ae 'key value'`

which would be the usual Unix way to add a parameter with an argument. Following these patterns is also the reason why I suggest to take the `-`  away for the `key' and combining the flags. For example to have 

`nexrender --ae 'close SAVE_CHANGES'`

instead of 

`nexrender --ae -close SAVE_CHANGES`

which would be very confusing with regard to the Unix pattern as `close` is not a parameter for nexrender.

As a next step I would prepare the pull request. 

Please have a look if it is to your liking.

Cheers!

**Comment by brassel** [comment]
Pull request has been created.
