### ISSUE TITLE
Is is possible to control layer visibility when rendering a composition?

### ISSUE THREAD

**Issue by uscivics** [inlife/nexrender#447]
I realize working with footage items, I can easily replace assets.  The project file i've been given, has the replacement assets as layers within the same composition.  Is there a way to structure the job.json file to simply turn on or off certain layers by name?  What is the best way to achieve this?

**Comment by inlife** [comment]
I can't say for sure if there is a way to turn on/off layers by scripting (I feel like there should be tho).
But another way how you can achieve this is by "abusing" expressions, basically injecting them into layers that you need, and rendering them invisible/outside of screen/etc

**Comment by veejar** [comment]
@uscivics did you find some good solution for that? I have solution how to render layer outside of the screen, but I want to skip layer rendering to optimise render time.

@inlife please help too if you can

**Comment by phlexib** [comment]
Layer visibility is only accessible with a  script. You will have to Use Nexrender with an extendscript file. 
Other solution, don’t change visibility but the opacity of the layer. You can do that as a standard property in nexrender Job file

**Comment by inlife** [comment]
>  I have solution how to render layer outside of the screen,

There is always a chance that AE might be optimizing out any layers outside of visible space already, so maybe what you are trying to do was already solved by smart engineers from their side (just a thought tho) :D
