### ISSUE TITLE
Passing Crop parameters to AE on render setup

### ISSUE THREAD

**Issue by Guzmank90** [inlife/nexrender#449]
**Is your feature request related to a problem? Please describe.**
Currently we are providing format and all AE rendering settings which pass perfectly, is there anyway to access crop option?

**Describe the solution you'd like**
I would like to pass crop values as we are currently passing format, frameStart and frameEnd

**Describe alternatives you've considered**
After effects by default has cropping option for output.. Adding post-render action would be a poor alternative.

**Additional context**
- Crop true/false
- 4 parameters, Top, bottom, right and left.
![Crop-win](https://user-images.githubusercontent.com/66524060/88640721-f0c89280-d0c6-11ea-84ca-2027d42c0fe3.png)

**Comment by inlife** [comment]
Actually not sure if that is possible. I don't remember similar options available for aerender. There can be, however, a way to achieve that using scripting. Have you tried that? Maybe there is just a simple function that can be called on top of a composition object or something like that?

**Comment by Guzmank90** [comment]
> Actually not sure if that is possible. I don't remember similar options available for aerender. There can be, however, a way to achieve that using scripting. Have you tried that? Maybe there is just a simple function that can be called on top of a composition object or something like that?

That could be a good a solution actually - First need to make scripting work.
Tried for a day, no luck. Able to set params via job, but nothing is executed.

**Comment by inlife** [comment]
You'll get there, I believe. Scripting via assets is quite simple, once you get how it works.
Cheers!
