### ISSUE TITLE
Rendering issue in Nexrender: Couldn't find a result file

### ISSUE THREAD

**Issue by palekarsagar** [inlife/nexrender#450]
cannot get an mp4 file.... rendering only produces an AVi.

Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg) Error: spawn EBUSY
    at C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\actions.js
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by inlife** [comment]
Can't say what is going on. Could you provide more details?

**Comment by palekarsagar** [comment]
Hi @inlife 
i  solved it using another question you had answered.

It was the ffmpeg path in the environment... once i set it... i was sorted.
Btw... thanks for nexrender... its really great... love experimenting on it
