### ISSUE TITLE
generated video not showing typekit font 

### ISSUE THREAD

**Issue by stevenyeo1234** [inlife/nexrender#451]
hi,

i generated a video from AE using typekit font for the text. After exporting via bodymovin, i can see the typekit font in lotties via adobe webproject. However, when i try generating the video using nexrender, the video generated did not show the typekit font. 

May i know what could be the possible issues?

regards,
Steven

**Comment by inlife** [comment]
Hey,

You can try checking After Effects logs in the nexrender temp folder, maybe they will tell us something useful.

Cheers!
