### ISSUE TITLE
Call function from scripting

### ISSUE THREAD

**Issue by Guzmank90** [inlife/nexrender#454]
**Describe your question, attach logs, images or anything that might help to better understand it.**
Trying my luck with scripting, For 2 days already... tried to Add them on job... everything goes fine from job side, script is properly injected but it looks like nothing is called or in other words everything is static.

Can't really call a function from within JSX script - that means you can't use them for scripting for creating comps, layers and etc...
Tried even with your docs suggestions:
Assets:
```
{
        "src": "file:///C:/sample/sampleParamInjection.jsx",
        "type": "script",
        "parameters": [
            {
                "key": "name",
                "value": "Dilip"
            }
        ]
    }
```
JSX file:
```
{
    return "Hello " + NX.get("name") || "John";
}
```
Can't see that output string anywhere. it outputs on job Started, progress and finished. On worker it complains to change it to default t with null.
```
project has been created
Started Rendering...Job is: {...Shows Job's Object...}
project is at: 96%
project is at: 100%
project rendering finished
```

Worker:

```
aerender ERROR: Error executing script: ...\vVmrP4WNS9nRZdZJTGuBJ\nexrender-vVmrP4WNS9nRZdZJTGuBJ-script.jsx
TypeError: null is not an object
aerender ERROR: Runtime error in After Effects.
```

**What I'm trying to achieve:**
Shortly, I'm trying to pass a index or comp name(which could be used from within nexrender auto-created script and trigger it)(from Job) to a function(JSX script).

Longingly, The Function Targets Composition index(Using Composition names from nexrender would be nice), Creates text layer, Defines layer's name, sets content and has bunch of font options.. Everything is cool and dandy but it's not executed... and const when set from JSX returns undefined error on job.

```
function addTextLayer(i) {
var newLayer = app.project.item(compIndex).layers.addText("Text-Test");
// Define Name
newLayer.name = "Text-Test";

// Position Text
newLayer.position.setValue([210,1050]);

// FONT OPTIONS
var textProp = newLayer.property("Source Text");
var textDocument = textProp.value;
myString = "Teeeesttttt";
textDocument.resetCharStyle();
textDocument.fontSize = 30;
textDocument.fillColor = [1, 1, 1];
// textDocument.strokeColor = [0, 0, 0];
// textDocument.strokeWidth = 2;
textDocument.font = "ribbon trim";
// textDocument.strokeOverFill = true;
// textDocument.applyStroke = true;
// textDocument.applyFill = true;
textDocument.text = myString;
// textDocument.justification = ParagraphJustification.CENTER_JUSTIFY;
// textDocument.tracking = 50;
textProp.setValue(textDocument);
}
```

Any suggestions what I'm doing wrong?

**Comment by Guzmank90** [comment]
hello?

**Comment by inlife** [comment]
Do you really need this function to be triggered by something else? Technically you can call it yourself, right in the script.
It is executed inside the AE environment, after all, assets are replaced and prepared, and rendering will start the next tick.

**Comment by Guzmank90** [comment]
> Do you really need this function to be triggered by something else? Technically you can call it yourself, right in the script.
> It is executed inside the AE environment, after all, assets are replaced and prepared, and rendering will start the next tick.

Not a must... Just need it triggered. AE by default doesn't use comp names, it would be nice to use search for comp name as nexrender does for composition name - instead of creating same functionality from within JSX file.
How to call it? Let's say i'll pass comp name but it would have no idea how to handle comp names nor there is a function to pass them to..

Technically, I've added it to assets as script type, passing props manually,everything is injected but it results in error when running function script:
```
Running Script: ...\EH6J_-jyALEdqjCJ7Cj1H\nexrender-EH6J_-jyALEdqjCJ7Cj1H-script.jsx
aerender ERROR: Error executing script: ...\EH6J_-jyALEdqjCJ7Cj1H\nexrender-EH6J_-jyALEdqjCJ7Cj1H-script.jsx
ReferenceError: Function myFunctionName is undefined
aerender ERROR: Runtime error in After Effects.
```
When not in function:
```
Running Script: ...\7dlFF_y-sk-wP7ARHokP4\nexrender-7dlFF_y-sk-wP7ARHokP4-script.jsx
aerender ERROR: Error executing script: ...\7dlFF_y-sk-wP7ARHokP4\nexrender-7dlFF_y-sk-wP7ARHokP4-script.jsx
TypeError: undefined is not an object
aerender ERROR: Runtime error in After Effects.
```
How do you troubleshoot something like this?
I have a feeling that it has no idea what is AE's app object from scripts file.
In AE I import it and it works perfectly.

**Comment by inlife** [comment]
All functions that do the finding of compositions and layers by nexrender are just scripting functions. You can check them here: https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/assets/nexrender.jsx

And they are all available for your scripts as well, since they are embedded directly inside of that file, and executed just before rendering starts.

**Comment by Guzmank90** [comment]
Gotcha, Thanks a ton!
