### ISSUE TITLE
When Job fails return an full job object with error

### ISSUE THREAD

**Issue by Guzmank90** [inlife/nexrender#455]
**Describe the solution you'd like**
I'm trying to access job from within error.
When job fails currently it returns only err, is there anyway to return full job with error?

**Currently:**
`result.on("error", (err) => console.log("project rendering error", err));`

**Needed:**
`result.on("error", (job, err) => console.log(job.uid + " has Failed", err));`

**Comment by inlife** [comment]
Usually, in a callback, the error is returned first. And the job object can be returned as a second argument, not sure tho if that is the case with current implementation.
