### ISSUE TITLE
Generate thumbnail from rendered video

### ISSUE THREAD

**Issue by kalmicka** [inlife/nexrender#457]
Is there a way to generate a thumbnail from a specific frame / timestamp of the created video once it is done rendering? Is there an action, I didn't see, that takes care of generating such a thumbnail and also uploads it alongside the video?

**Comment by inlife** [comment]
Hey @kalmicka 

That sounds like a custom post-render action, that uses ffmpeg module from action-encode combined possibly with action-upload. Quite a combination I would say :D

**Comment by kalmicka** [comment]
That's why I am asking if such an action might already exist :)
Is there a good tutorial out there that might tell me how to build custom actions?

**Comment by inlife** [comment]
Unfortunately, no proper tutorial for that exists. There is only a tiny part of doc here: https://github.com/inlife/nexrender#custom-actions

And additionally, existing actions can be used as references.

**Comment by kalmicka** [comment]
Thanks for the help. Awesome project by the way! :)

**Comment by inlife** [comment]
Thank you, glad to be of help! :)
