### ISSUE TITLE
How to specify ffmpeg's path for workers

### ISSUE THREAD

**Issue by soundquiet** [inlife/nexrender#459]
Hi, I would like to know the right way to specify the ffmpeg path to avoid repeated downloading after the temp folder is cleaned.

I saw the answer in [this issue](https://github.com/inlife/nexrender/issues/444#issuecomment-663674895), but it didn't work for me to set a env variable NEXRENDER_FFMPEG before starting workers.

Thank you!

**Comment by inlife** [comment]
If NEXRENDER_FFMPEG is set, it should prefer an executable you provide as a path in that var, rather then downloading and using the preconfigured one.

**Comment by soundquiet** [comment]
I found this work for released binary workers, I was using the npm-downloaded worker before.
Thank you!
