### ISSUE TITLE
While using Network Rendering using nexrender worker-server configuration, The core functions aren't supported

### ISSUE THREAD

**Issue by darshak-gosar** [inlife/nexrender#460]
Hi @inlife ,
I am using nexrender server-worker configuration and want to return the promise once the rendering is completed, but while I am using onRenderProgress & onChange functions it doesn't work as expected. 

```
let projectJson = {
        template: {
            src: 'FilePath'
            composition: fileName
        },
        assets,
        actions: {
            postrender: [{
                module: '@nexrender/action-encode',
                preset: 'mp4',
                output: 'encoded.mp4'
            },
            {
                module: '@nexrender/action-copy',
                input: 'encoded.mp4',
                output: `test.mp4`
            }
            }
            ]
        },
        onRenderProgress: job => {
            const {
                renderProgress
            } = job;
            console.log(renderProgress);
        },
        onChange: job => {
            const {
                state: renderMessage
            } = job;
            console.log(renderMessage);
        }
    };
const data = await client.addJob(projectJson)
```
I have tried using the below callback function:
1. progress - data.on('progress', (job, percents) => {})
2. finished - data.on('finished', job => {})
but using this callbacks it returns the promise to the calling function before the rendering is finish

Thanks.

**Comment by inlife** [comment]
Yes, those callbacks won't work on the job side, since they are local to the worker/cli renderer.
What can you do however, is something like that:

```js
const job = await client.addJob(projectJson)
const finished = await new Promise((resolve, reject) => {
    data.on('finished', job => resolve(job))
    data.on('error', err => reject(err))
})
```

**Comment by darshak-gosar** [comment]
Hi @inlife,
Thanks for the response, I will try this. but if my data.on('finish') looks something like this:
data.on('finished', job => {
        const {
            renderProgress,
        } = job;
        var updatedfinalVideoUrl = finalVideoUrl;
        update(id, {
            renderProgress
        });
    })

**Comment by darshak-gosar** [comment]
Hi @inlife ,
The above logic help a lot to overcome the problem I was facing. Thanks a lot :)
