### ISSUE TITLE
Can't find a property sequence

### ISSUE THREAD

**Issue by darshak-gosar** [inlife/nexrender#461]
Hi @inlife ,
I am getting the following issue:
`Error: nexrender: Can't find a property sequence Source Text.fontSize for key: Source Text`
Code:
```
const sourceTextFontSize = {
        type: 'data',
        layerIndex: 2,
        property: 'Source Text.fontSize',
        value: 100
    };
    assets.push(sourceTextFontSize);
    const result = await client.addJob({
        template: {
            src: `FilePath`,
            composition: 'compName'
        },
        assets,
        actions: {
            postrender: [{
                    module: '@nexrender/action-encode',
                    preset: 'mp4',
                    output: 'encoded.mp4'
                },
                {
                    module: '@nexrender/action-copy',
                    input: 'encoded.mp4',
                    output: `file.mp4`
                }
            ]
        },
    })
```

**Comment by inlife** [comment]
I remember there were similar issues to this one, please try to look for an answer there. I feel like the key should be called differently. Looks similar to font color setting, that one, seems to me, was definitely mentioned somewhere already :)

**Comment by darshak-gosar** [comment]
Hi @inlife ,
I have check this https://github.com/inlife/nexrender/issues/244 but still the issue persist.

**Comment by darshak-gosar** [comment]
Hi @inlife ,
The issue is solve, The Layer Name was different So I changed it and then script got rendered.

Thanks :)
