### ISSUE TITLE
Is it possible to access some kind of ETA to complete render?

### ISSUE THREAD

**Issue by patricktsg** [inlife/nexrender#462]
I wondering if it's possible to access some ETA for how long a render that starts will take.

Also, does AE offer a way to grade how complete a render is? So say the video length is < 10 seconds we can assume it will render quickly enough, but something 10 minutes in length would take longer.

The reason I ask is so I can present some kind of interface to show a queue of jobs on the server and how long they might take.

**Comment by inlife** [comment]
You can check the AE log txt file to see what info does aerender return to us. I don't remember the details, but it seems to me there is no ETA from their side.
It probably can be calculated based off the amount of time passed since the beginning and current progress. 

What do you think?
