### ISSUE TITLE
Add request options when downloading assets.

### ISSUE THREAD

**Issue by soundquiet** [inlife/nexrender#463]
Hi!
I am wondering if there is a way to specify options like `rejectUnauthorized: false` and others for the requests of downloading assets, in case some URLs cannot be handled commonly.

Thank you!

**Comment by inlife** [comment]
Hey @soundquiet 

Not sure I understand, could you give an example?

Cheers!

**Comment by soundquiet** [comment]
for example.
``` js
const fetch = require('node-fetch');
const https = require('https');

const httpsAgent = new https.Agent({
      keepAlive: true,
      rejectUnauthorized: false,
    });

const response = await fetch(url, {
      method: 'POST',
      headers: headers,
      body: body,
      agent: httpsAgent,
    });
```

I looked up the `download.js` in core and found it only have 
```js
fetch(src, asset.params || {}).then(...)
```

so how can we add more params about the network in `asset.params` when building a job json?

**Comment by inlife** [comment]
Well, that would work for static parameters, like method, headers, body, etc. But as you can see, the agent is an object, which is required to be constructed separately and passed inside. And as far as I know, there is no simple way to do that right now, unless you are using core directly (programmatically).

**Comment by soundquiet** [comment]
Got it. Thank you!
