### ISSUE TITLE
Way to modify the layer or composition duration

### ISSUE THREAD

**Issue by amarCosmospace** [inlife/nexrender#465]
Is it possible to edit a layer or composition to fit a media duration ?

Thanks in advance

**Comment by soundquiet** [comment]
In our case, we did that by using a `.jsx` file as an asset and change the `startTime` and `outPoint` of the layer in the code. 

Maybe you can find more useful properties and methods [here](https://helpx.adobe.com/after-effects/using/legacy-and-extend-script-engine.html#shorthand-syntax).

**Comment by amarCosmospace** [comment]
Ok, thanks will give that a test

**Comment by inlife** [comment]
@soundquiet that is actually a quite neat and elegant way of solving that issue! Never seen anything like that before. Very cool! 👍
