### ISSUE TITLE
S3 Provider: Environment variables for AWS Credentials

### ISSUE THREAD

**Issue by byumark** [inlife/nexrender#466]
A while ago I was able to use AWS environment variables for credentials but now they don't work like they used to. Here is what I found on AWS docs (https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-environment.html):

```
The SDK automatically detects AWS credentials set as variables in your environment and uses them for SDK requests, eliminating the need to manage credentials in your application. The environment variables that you set to provide your credentials are:

AWS_ACCESS_KEY_ID

AWS_SECRET_ACCESS_KEY

AWS_SESSION_TOKEN (optional)
```

At some point, however, inside of the S3 provider package these were hardcoded to `ACCESS_KEY_ID` and `SECRET_ACCESS_KEY` with no mention of the session token. See lines 13 and 14 here: https://github.com/inlife/nexrender/blob/master/packages/nexrender-provider-s3/src/index.js#L13

I'd propose we remove those lines and go back to the AWS defaults which would also work for session tokens. Is this doable?

**Comment by inlife** [comment]
Hey @byumark 

I think you are right. I found myself using existing aws credentials setup much more often than actually manually providing access keys. So I did a small change, that should keep old code working fine for other people, as well as respecting the values from configured credentials/env vars by default. You can check the commit: https://github.com/inlife/nexrender/commit/f991c9e5927eb0cccf8623fdc7f94eb223c85f52

**Comment by byumark** [comment]
Awesome. Looks good! Thanks for doing that.
