### ISSUE TITLE
Can I Apply Presets in the Layers

### ISSUE THREAD

**Issue by adiwithadidas** [inlife/nexrender#470]
Hi,

I was wondering If It is possible to apply predefined Animation / Transition Presets (Already Defined inside After Effect) to the layer from NexRender? 

If yes, then can you please guide how can I do so?. Also if there is any workaround to do so?

Thanks

**Comment by inlife** [comment]
Hello @adiwithadidas 

I can't definitely answer on how to achieve something like that, but what I can suggest is to check out if that is something that is possible to do with the scripting. And in case it is, I think the road after that is quite straightforward. :)

Cheers!

**Comment by adiwithadidas** [comment]
I can do it in scripting, I tried by adding it through extended SCript toolkit for After Effect  and it works fine
but in nexrender when I do the same through external jsx script . it throws an error
`aerender ERROR An existing connection was forcibly closed by the remote host.                                           : Unable to receive at line 316                                                                                         aerender ERROR: After Effects can not render for aerender. Another instance of aerender, or another script, may be running; or, AE may be waiting for response from a modal dialog, or for a render to complete. Try running aerender without the -reuse flag to invoke a separate instance of After Effects`
When I remove the part that Apply Presets,  everything works fine.

**Comment by inlife** [comment]
Judging by the error log, maybe AE instance opens up a dialog window there? It is something scripting cannot "click" on, unfortunately 😄

**Comment by berendvaneerde** [comment]
I am running in to a similar issue, except that I am not getting an error thrown in terminal.

 This is my included 'script.jsx' code 
`var comp = comp.app.project.item(1);
var layer = comp.layer(1);
layer.selected = true;
var preset = File("/Users/name/Desktop/preset.ffx");  
layer.applyPreset(preset);`
The script works fine when run in the application, but when using in a nexrender job it hangs on `rendering job...` removing the last line makes the job finish. Can it have something to do with file access?

**Comment by inlife** [comment]
> Can it have something to do with file access?

That is also a possibility, have you tried commenting out the preset file loading function to see if its working?

**Comment by berendvaneerde** [comment]
I applied presets.exists to a textlayer in the script and removed the
applyPreset(preset) rule. This works. Leaving that rule hangs the
'rendering job...' So it seems that the file can be found and called by
script with succes but not applied?! I am not sure if one can call the
applyPreset without a File argument but I can try when behind my laptop.

Op ma 5 okt. 2020 07:44 schreef Vladyslav Hrytsenko <
notifications@github.com>:

**Comment by berendvaneerde** [comment]
So I tried applying preset without a File but this does not work. Calling the file or commenting out the call to file does not make a difference. The problem seems to lay in the applyPreset() method. 

This is what terminal produces as an error result after a long wait. Hopefully it can be helpful. I am a bit lost here.
```
aerender ERROR -609: AESend failed to send apple event at line 885

> job rendering failed
Error: Couldn't find a result file: /var/folders/d3/2ryw442s0r73j2fxj9mzk5mm0000gn/T/nexrender/WYuMMJvgMW7LNctzGQTBp/result.mov
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@nexrender/cli/node_modules/@nexrender/core/src/tasks/render.js:171:31)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
```

**Comment by phlexib** [comment]
Is it all you have in your script.jsx ??
If not, here's a few ideas :
> var comp = comp.app.project.item(1); var layer = comp.layer(1); layer.selected = true; var preset = File("/Users/name/Desktop/preset.ffx"); layer.applyPreset(preset);

There's an error in your scrip : 
`comp.app.project.item(1)` should be `app.project.item(1)`

Also , as Nexrender creates a new project , if there's anything else going on in your job, there's no guarantee that your Comp still is a the project first item. you should reference it by name, creates a function to find it, or use the dynamic parameters offers by Nexrender. 
Also a good idea would be to scope your script. When you run it with AE open, it's possible that your variables are already set by running the script previously or by another script. So Because Nexrender runs a new instance of AE, those variables are gone.

**Comment by berendvaneerde** [comment]
Sorry no... It was a simplified and apparently mistyped version :) Thanks for your useful tips and attention. I'd love to contribute to nexrender btw, but I guess I need some guidance... 

Here is my updated and tested script. The same thing happens. The out commented line results in hanging the rendering job for a long while and eventually returning the error mentioned before. Without that line it returns a file with the text "true".

Any ideas where to look?
```
(function myScript(){
    var myComp;
    for (var i = 1; i <= app.project.numItems; i++) {
        if ((app.project.item(i) instanceof CompItem) && (app.project.item(i).name === 'myComp')) {
            myComp = app.project.item(i);
            break;
        }
    }

    var myPreset = File("/Users/botoboto/Desktop/myPreset.ffx"); 
    var myLayer = myComp.layer(1); 
    myLayer.selected = true;
    //myLayer.applyPreset(myPreset);
    myComp.layers.addText(myPreset.exists); 
})();



```

**Comment by inlife** [comment]
That indeed seems like a valid script, and theoretically, everything should be fine. Hopefully, somebody might have some insights into what might be going wrong here.

**Comment by jiushiwoyuze** [comment]
> Sorry no... It was a simplified and apparently mistyped version :) Thanks for your useful tips and attention. I'd love to contribute to nexrender btw, but I guess I need some guidance...
> 
> Here is my updated and tested script. The same thing happens. The out commented line results in hanging the rendering job for a long while and eventually returning the error mentioned before. Without that line it returns a file with the text "true".
> 
> Any ideas where to look?
> 
> ```
> (function myScript(){
>     var myComp;
>     for (var i = 1; i <= app.project.numItems; i++) {
>         if ((app.project.item(i) instanceof CompItem) && (app.project.item(i).name === 'myComp')) {
>             myComp = app.project.item(i);
>             break;
>         }
>     }
> 
>     var myPreset = File("/Users/myName/Desktop/myPreset.ffx"); 
>     var myLayer = myComp.layer(1); 
>     myLayer.selected = true;
>     //myLayer.applyPreset(myPreset);
>     myComp.layers.addText(myPreset.exists); 
> })();
> ```

Any update here? I have the same issue, and I haven't fix this problem yet, please give me some help, thank you very much

**Comment by njho** [comment]
Yep samesies here! Good to know that this i a documented issue though and I'm not crazy!
