### ISSUE TITLE
Support new JavaScript features available through CEP

### ISSUE THREAD

**Issue by miracle2k** [inlife/nexrender#473]
**Is your feature request related to a problem? Please describe.**
I had a `[].map()` call in my `jsx` script which worked just fine when I execute it via VSCode and it's ExtendScript plugin. But running that script via nexrender says that `map is not a function`.

From googling it seems to be some kind of new version of ExtendScript through the [CEP platform](https://github.com/Adobe-CEP/CEP-Resources)? [See here](https://community.adobe.com/t5/after-effects/native-js-es5-features-quot-randomly-quot-not-supported-in-some-environments-ae2020/td-p/10870294?page=1).

Could this be supported by nexrender?

**Comment by inlife** [comment]
I would need some time to research what CEP is, I've heard about it a couple of times, but not entirely sure what is that, and how it works.
Maybe you have some high-level general explanation, to help me ease into it?

Cheers!

**Comment by miracle2k** [comment]
I wrote my first script for Adobe that day, noticed that my `.map()` broke in nexrender and did a Google Search about what might be going on. I don't think I can be of any help! 😢

**Comment by inlife** [comment]
Interestingly enough, there is an additional layer of wrapping for the user script, that should improve overall scripting experience within after effects. And I was sure map should be supported there as well. Unfortunately, seems like it isn't.

Also, could you please share some minimal version of your code, so that I could see the code we are dealing with?

**Comment by phlexib** [comment]
You can’t use ES6 features in a .jsx file run by the current extendscript engine. 
That’s not a something that can be added on  nexrender. Nexrender is just passing a file reference to After Effect. Until Adobe updates it’s scripting engine to a more modern one that’s not gonna happen. 
I suggest you close this issue.
