### ISSUE TITLE
Just trying to start out

### ISSUE THREAD

**Issue by Somebuddy1** [inlife/nexrender#475]
I'm sorry for this absolutely basic question, but I can't even seem to get started with Nexrender on MacOS Mojave. I am following the instructions trying to run `nexrender-cli-macos --file myjob.json` in the terminal but all I get is `Permission denied`. 

I've tried changing permissions, moving to different directories, re-downloading... same result. What am I doing wrong?

Please, any help is absolutely appreciated 🙏

Thanks,
Mike

**Comment by inlife** [comment]
Hey

Seems like some general issue related to system permissions for executable. Do you have multiple system users with a different sets of permissions?

**Comment by Somebuddy1** [comment]
Thanks for your response. I've tried on 2 different computers, one with multiple accounts that I do not have administrator privileges and another with only one account where I am the administrator.

I've tried changing the permissions but nothing seems to work. Has anyone else encountered an issue like this? Or am I doing something wrong?

Thanks

**Comment by Somebuddy1** [comment]
So, it turns out that if I run `chmod 755 nexrender-cli-macos` from within the directory that the file is located then my issue is resolved. It tells the system the file is executable, where previously it was not.

When I first download the file it appears like this on my system:
<img width="237" alt="Screen Shot 2020-08-29 at 5 06 57 PM" src="https://user-images.githubusercontent.com/44332189/91646178-7028e900-ea1a-11ea-8579-3d3928f31b4b.png">

After running the command `chmod 755 nexrender-cli-macos` it changes to look like this and then works as expected:
<img width="238" alt="Screen Shot 2020-08-29 at 5 07 07 PM" src="https://user-images.githubusercontent.com/44332189/91646199-b716de80-ea1a-11ea-9ef0-d6f78f73b84f.png">

Sorry if this was a stupid question, but I would never have known that this was necessary to begin.

Thanks,
Mike

**Comment by inlife** [comment]
Ah, worry not! It's quite a common problem not just with nexrender but in general.
Probably would be a good idea to mention that somewhere on the readme as well 😄
