### ISSUE TITLE
Required Setting for WSL for running Nexrender Worker with Mapping drive for assets

### ISSUE THREAD

**Issue by pixelfactorydevelopmentteam** [inlife/nexrender#479]
Required Setting for WSL for running Nexrender Worker with Mapping drive for assets

@ I have set up the WSL on the window server and mapping D drive something like /mnt/f
@ We have access the file with mount drive  Via Power shell command but not able to access via nexrender-worker

We required the settings for accessing the file system for assets parameter in File protocol and temp setting for WSL-map enable

**Comment by inlife** [comment]
Hey @pixelfactorydevelopmentteam,

Pretty much all of the information about WSL for nexrender is available here: https://github.com/inlife/nexrender/issues/422
Seems like `-wsl` param is what you are looking for, unless I'm mistaken

Cheers!

**Comment by limzykenneth** [comment]
I think for `nexrender-worker` the wsl flag has not been added yet as per #442

**Comment by inlife** [comment]
Seems like you are right @limzykenneth, i checked the code, and it is not added yet

**Comment by pixelfactorydevelopmentteam** [comment]
Hi Team,

Required Setting for WSL for running Nexrender Worker with Mapping drive for assets

@ I require the make the WSL drive on the window server 
Mapping Drive Path : Z:\projectsfiles
Conversion Path for WSL: /Volumes/DATA_TK_01/projectsfiles

@ We have access the file with mount drive Via Power shell command but not able to access via nexrender-worker

We required the settings for accessing the file system for assets parameter in File protocol and temp setting for WSL-map enable
or Please share the reference link if you have for making these properties on it

**Comment by inlife** [comment]
Hey @pixelfactorydevelopmentteam 

Could you elaborate more on things you've mentioned in your last message. I read it multiple times, and yet still confused about what are you trying to say here, hehe :)

Cheers!

**Comment by pixelfactorydevelopmentteam** [comment]
Thanks
