### ISSUE TITLE
Multiple comp rendering

### ISSUE THREAD

**Issue by MrSKYone** [inlife/nexrender#48]
Hi,

First of all, fantastic job with this app, It's really easy to use and super efficient!
I was wondering if it is possible to render multiple comp within a same AE project?
Let's say I have a project with two comps using the same assets. the only difference would be the resolution: ex 1920x1080 (comp1) and 1080x1920 (comp2). Could I queue up both comps at the same time or do I need to create separate start.js files?

If you have any idea about the way to to that let me know! cheers

**Comment by inlife** [comment]
Hello,
Thank you, im glad you like it !)

Yes, you can queue up both comps by providing 2 different composition field values using a project option: https://github.com/inlife/nexrender/wiki/Project-model#composition

That should help

**Comment by MrSKYone** [comment]
in my option fields, having the following 
```

let project = new Project({
        "template": "project.aepx",
        "composition": "square_1080",
        "composition": "portrait_1080",
        "type": "default",
...
```

has no impact, only one comp is rendered.
Did I misunderstood?

**Comment by inlife** [comment]
Yes, you misunderstood.
Right now, in current version, you need to create and queue up 2 different projects to be able to render multiple compositions.

Like:

```js
let project1 = new Project({
        "template": "project.aepx",
        "composition": "square_1080",

/// ......

let project2 = new Project({
        "template": "project.aepx",
        "composition": "portrait_1080",
```

**Comment by MrSKYone** [comment]
sorry for the long dealy but it's working properly, you can close this :) thank!

**Comment by Byberg33** [comment]
I know this is an old thread but how would you do this now that the jobs are defined as an json object?

**Comment by inlife** [comment]
@Byberg33 essentially the same way, create 2 json jobs, and then submit them to rendering :)
