### ISSUE TITLE
Rendering takes longer than it takes in after effects

### ISSUE THREAD

**Issue by atitkothari** [inlife/nexrender#480]
I'm rendering one image as a png. It takes one second or less when I run it in After Effects CC 2019 but when I run it through the nexrender-worker-win64 with the latest release, it takes ~18 seconds. 
I do see the rendered image in the folder within a second, why does it take 18 seconds for logs to appear in the worker terminal?
Is it because it takes some time to open the aftereffects file?
<img width="963" alt="Screen Shot 2020-09-21 at 2 04 21 AM" src="https://user-images.githubusercontent.com/17554869/93736760-4beea100-fbaf-11ea-8a0f-3d2016ce6c0f.png">

**Comment by atitkothari** [comment]
log file

> Using DXGI: Device: "NVIDIA Tesla M60" has dedicated video RAM (MB): 7592
> 2020-09-21 06:27:18:851 : ERROR *** IVCAutoReleasePool: Object 0000000022FD8270 of class vcfoundation::data::DataWrapper autoreleased with no pool in place - just leaking
> 2020-09-21 06:27:18:851 : ERROR *** IVCAutoReleasePool: Object 0000000022FD81B0 of class vcfoundation::data::DataWrapper autoreleased with no pool in place - just leaking
> Unable to read VR Path Registry from C:\Users\ar\AppData\Local\openvr\openvrpaths.vrpath
>     name                                    : NVIDIA Tesla M60
>     VendorId                                : 4318
>     DeviceId                                : 5106
>     SubSysId                                : 289018078
>     Revision                                : 161
>     DedicatedVideoMemory                    : 7960854528
>     DedicatedSystemMemory                   : 0
>     SharedSystemMemory                      : 65498046464
>     MemoryBudget                            : 6766726348
>     AdapterLuid.LowPart                     : 5641190
>     AdapterLuid.HighPart                    : 0
>     Flags                                   : 0
>         DoublePrecisionFloatShaderOps           : yes
>         ConservativeRasterizationTier           : 1
>         CrossNodeSharingTier                    : 0
>         ResourceBindingTier                     : 3
>         ResourceHeapTier                        : 1
>         TiledResourcesTier                      : 3
>         NodeIndex                               : 0
>         TileBasedRenderer                       : no
>         UMA                                     : no
>         CacheCoherentUMA                        : no
>         feature level                           : 0x00009100
>         feature level                           : 0x00009200
>         feature level                           : 0x00009300
>         feature level                           : 0x0000a000
>         feature level                           : 0x0000a100
>         feature level                           : 0x0000b000
>         feature level                           : 0x0000b100
>         feature level                           : 0x0000c000
>         feature level                           : 0x0000c100
>         MaxSupportedFeatureLevel                : 0x0000c100
>         HighestShaderModel                      : 0x60
>         WaveOps                                 : yes
>         WaveLaneCountMin                        : 32
>         WaveLaneCountMax                        : 32
>         TotalLaneCount                          : 2048
>         ExpandedComputeResourceStates           : yes
>         Int64ShaderOps                          : yes
>         RootSignature.HighestVersion            : 0x2
> Skipping DX support: Microsoft Basic Render Driver
> aerender version 16.1.3x5
> Running Script: C:\Users\ar\AppData\Local\Temp\2\nexrender\88Oq5V6ny6IpdkKJsjhrS\nexrender-88Oq5V6ny6IpdkKJsjhrS-script.jsx
> PROGRESS:  9/21/2020 6:27:27 AM: Starting composition RenderComp.
> 
> 
> PROGRESS:  Render Settings: Best Settings
> PROGRESS:  Quality: Best
> PROGRESS:  Resolution: Full
> PROGRESS:  Size: 1125 x 2000
> PROGRESS:  Proxy Use: Use No Proxies
> PROGRESS:  Effects: Current Settings
> PROGRESS:  Disk Cache: Read Only
> PROGRESS:  Color Depth: Current Settings
> PROGRESS:  Frame Blending: Off for All Layers
> PROGRESS:  Field Render: Off
> PROGRESS:  Pulldown: Off
> PROGRESS:  Motion Blur: Off for All Layers
> PROGRESS:  Solos: Current Settings
> PROGRESS:  Time Span: Work Area
> PROGRESS:  Start: 0;00;00;00
> PROGRESS:  End: 0;00;00;00
> PROGRESS:  Duration: 0;00;00;01
> PROGRESS:  Frame Rate: 29.97 (comp)
> PROGRESS:  Guide Layers: All Off
> PROGRESS:  Skip Existing Files: Off
> PROGRESS:  
> PROGRESS:  Output Module: JPEGSeq
> PROGRESS:  Output To: C:\Users\ar\AppData\Local\Temp\2\nexrender\88Oq5V6ny6IpdkKJsjhrS\result_[#####].jpg
> PROGRESS:  Format: JPEG Sequence
> PROGRESS:  Output Info: -
> PROGRESS:  Start Frame: 0
> PROGRESS:  Output Audio: -
> PROGRESS:  Channels: RGB
> PROGRESS:  Depth: Millions of Colors
> PROGRESS:  Color: Premultiplied
> PROGRESS:  Resize: -
> PROGRESS:  Crop: -
> PROGRESS:  Final Size: 1125 x 2000
> PROGRESS:  Profile: -
> PROGRESS:  Post-Render Action: None
> PROGRESS:  
> PROGRESS:  0;00;00;00 (1): 1 Seconds
> PROGRESS:  9/21/2020 6:27:29 AM: Finished composition RenderComp.
> 
> 
> 
> PROGRESS:  Total Time Elapsed: 2 Seconds
> aerender ERROR: After Effects can not render for aerender. Another instance of aerender, or another script, may be running; or, AE may be waiting for response from a modal dialog, or for a render to complete. Try running aerender without the -reuse flag to invoke a separate instance of After Effects
>

**Comment by inlife** [comment]
Hello @atitkothari 

> Is it because it takes some time to open the aftereffects file?

The most likely reason for why is it taking such time is the process of initializing the After Effects engine (which technically probably should take a similar time to the GUI app).

You could try using a `--reuse` flag that tells aerender to attempt to use an existing open After Effects GUI application's rendering engine to render the job. However, that approach introduces collisions and bugs if you attempt to run multiple instances of rendering at the same time, so that is a word of caution from me :)

Cheers!

**Comment by atitkothari** [comment]
You're right. If I keep AE GUI open and run renderer with `--reuse` flag, rendering time goes down to ~2.2 seconds!

How do I speed up the GUI open time? It's a AWS instance so I can beef up specs if need be (This might be a noob question 😅)

**Comment by inlife** [comment]
Unfortunately not sure if that is somehow possible. The only thing I think could probably help is a fast SSD instead of HDD for AE to load from & work with.

**Comment by atitkothari** [comment]
One more questions-
When I use the `--reuse` flag to use the AE GUI. Do I need to have that project's AE open or as long as an AE GUI is open it will reuse it?

**Comment by inlife** [comment]
You do not have to have a specific project open. All you need is the GUI app. At least as far as I understand. You can try to search for a more reliable on adobe forums.
