### ISSUE TITLE
Custom UID

### ISSUE THREAD

**Issue by phlexib** [inlife/nexrender#482]
**Is your feature request related to a problem? Please describe.**
When generated new projects with nexrennder, I sometimes need to keep the project for later use (which the **work path** flag allows), but also to match a naming convention for the project name itself.

**Describe the solution you'd like**
Being able to set the **uid** in the job file.
`{"uid": "CustomName",
  "template": {
    "src": "file:///path/to/file",
    "composition": "main"
  },...}`

Solution : In the Crete function from Job.js file in nexrender-types, just replace `"uid":nanouid()` with `uid: job.uid ? job.uid : nanoid(),`
I have tested this solution in my fork.

**Describe alternatives you've considered**

**Additional context**

Thank you for the awesome work.
Ben

**Comment by inlife** [comment]
Hey

Sounds good. And if you tested in your fork that successfully, I believe you can even do a PR?
Unless that is something you wouldn't want to do.

Cheers!

**Comment by inlife** [comment]
Closing, since the feature was merged and released. :)
