### ISSUE TITLE
No Video Render output if AEP project is moved to another location. However open Once and Save solves Problem.

### ISSUE THREAD

**Issue by mahsanamin** [inlife/nexrender#485]
**Describe the bug**

If the source Project of After effects are moved to another location and uses node code of `nexrender` the output of the video becomes empty because after effect try to find the asset paths from old locations (absolute paths).

Just by opening the copied project and saving it once again and later using the same code fixes the problem. However logically this should not be the case.

Note that I used `aerender` directly with the same moved project (without opening) which renders right.

This is Google Drive Link for small Node source code and small .aep project in case you want to use it.
https://drive.google.com/file/d/1HOjjXwNjAKwYYvg6xKWu898Px1Vi0p4G/view?usp=sharing

**Steps to Produce: (with my zip)**
1. Download the zip file and use the node code attached to run it, there will be empty video output.
2. Just open the Project manually in After Effect and Save and close, repeat the above process(1), and video output will be there.

**(Steps to Produce on your machine directly)**
1. Take any .aep project e.g `\Volume\data\project1\testProject.aep` and use node code to render the output, if the project was once opened on your machine the video output will just be fine. 

2. Just rename the directory or move the project to some other path and later `nexrender` to render the project on a new path, now Video output will be empty/wrong (Note: do not copy as with copy the old path still exists so the project will work) 

**Information about environment**
* Which version of nexrender are you using ("@nexrender/core": "^1.19.2")
* What kind of setup do you have? (simple `nodejs` code on single machine to test nexrender (via npm))
* Are you using pre-built binaries or globally installed npm packages? (globally installed npm packages)
* Which kind (and version) of operating system you are running it in? (Mac OSX, Mojave (10.14.6), After Effect 2020 (17.0.5))
* Any additional information that might be helpful

**Expected behavior**
Logically any .aep project should be able to render, even if it is moved or downloaded from anywhere.

**Screenshots**
The screenshots are High Resolution so Zoom in to see.

Screenshot 1
(Success) where the original project which has the correct path of my machine is rendered.
![Screenshot1](https://user-images.githubusercontent.com/4756877/94889753-b4366000-0496-11eb-9549-59daec2c744f.jpg)

Screenshot 2
 (Failed Case), I just renamed the directory containing the project to mimic (Move the Project) and results in no Video Output
![Screenshot2](https://user-images.githubusercontent.com/4756877/94889775-c6180300-0496-11eb-9da1-6dd0d7a8c3aa.jpg)

**Comment by mahsanamin** [comment]
Forgot to add `package-lock.json` in my zipped code, so please `npm update`

**Comment by inlife** [comment]
Hello @mahsanamin 

By default, as far as I know, the assets are looked up by after effects in absolute paths first. So if you change a path, it won't be able to find the asset. In that case, you either need to provide the same folder asset structure placed relatively to the project file location or as you said, open and re-save the project file so AE would pick up the changes.

As far as I know from my previous testing aerender behaved in the exact same way, so any changes to the folder would need to be applied similarly. Can you confirm this is not the case any longer? And if yes, how do you think what might be causing such differences between pure aerender cmd, vs the one that nexrender spawns internally?

Cheers!

**Comment by mahsanamin** [comment]
Hey @inlife, thanks a lot for sparing time for this one, and apologies for the delayed response from my side.

As far as core `aerender` is concerned it automatically picks the asset files even if the project is not opened manually. However, the assets e.g (Footage) folder should be on the same path where the `.aep` file exists. In that case `aerender` re-establish the paths.

In the case of `nexrender` logic, it only copies the `.aep` file to a temporary path but does not copy the assets i.e(Footage) directory so in that case even `aerender` can't relate the paths, probably their internal logic only tries to re-find the assets on the root where `.aep` exists.

One solution I thought is to change the copied version `.jsx` script and also embed the path of the original `.aep` and later find the `assets` from the original path but kind of time constraint didn't' allow me to do that.

Later I ended up writing my own `spawn` code for extracting metadata of `.aep` and later render the video using `aerender` directly. In my case, I kind of can use the original `.aep` file because my Work Flow first download the `.zip` file from Cloud and later I can use exact same original directory (without copying). Note that the after I extract .zip the assets will still be wrong for example it could be `c:\someproject\(footage)\someAsset.png` but in my extracted zip my absolute path could be`\tmp\renderer\someproject\(footage)\someAsset.png`, but as you asked `aredner` handles this case very well.

However, Nexrender is a great project and gave me a very good start of things I am doing and I can say many thanks for it :).

Regards,
-Ahsan

**Comment by danixeee** [comment]
Hey @inlife @mahsanamin 

I have faced the same issue.

What do you think about creating a symlink(shortcut) for `(Footage)` directory?

```javascript
const srcFootagePath = path.join(path.dirname(src), '(Footage)');
const destFootagePath = path.join(path.dirname(dest), '(Footage)');

await fs.promises.symlink(srcFootagePath, destFootagePath, 'dir');
```

**Comment by adiwithadidas** [comment]
I am facing the same issue. Can you please suggest how to fix this issue. I am using nexrender

**Comment by pixelfactorydevelopmentteam** [comment]
> ```js
> const srcFootagePath = path.join(path.dirname(src), '(Footage)');
> const destFootagePath = path.join(path.dirname(dest), '(Footage)');
> 
> await fs.promises.symlink(srcFootagePath, destFootagePath, 'dir');
> ```

Did this work for you?

**Comment by pixelfactorydevelopmentteam** [comment]
@inlife @mahsanamin I am facing the same issue.I think it has 3 solutions.

A. Use .aep file as a shortcut for render (I have test this manually and it work for me) but i Don't know how to do it through nexrender.

B. Re-use location that was previously used (Most of our projects are uploaded from Mac computers) So WSL should be used.

C. As @mahsanamin is doing.

Can anyone help me which way will work, if there is any new way, please tell me:)
