### ISSUE TITLE
New Scene + n,out and Duration time

### ISSUE THREAD

**Issue by hasnhasan** [inlife/nexrender#486]
How can I make the following changes

1. in,out and Duration time change ?
2. New Scene add ?

<img width="712" alt="Ekran Resmi 2020-10-02 ÖS 9 04 38" src="https://user-images.githubusercontent.com/3776411/94955452-3c4a5300-04f3-11eb-82c2-8148320654af.png">

**Comment by inlife** [comment]
Hey @hasnhasan 

Probably the only way of doing that would be using custom jsx scripting. For the specifics, you would need to consult an official After Effects scripting API.

Cheers!

**Comment by hasnhasan** [comment]
Thanks I will investigate.
I have an audio file for each scene. I want to adjust the duration of the scene as much as this audio file length. Is there an example?

<img width="207" alt="Ekran Resmi 2020-10-03 ÖS 1 29 17" src="https://user-images.githubusercontent.com/3776411/94989314-74e23f00-057c-11eb-9ea4-b4560156190d.png">

**Comment by inlife** [comment]
There were a few solutions for this in issues from other people. For this I would suggest searching here, that should help.

**Comment by phlexib** [comment]
You’ll informations here [After Effects Scrimting guide. ](http://docs.aenhancers.com/) 

Look for AVItem.duration to get your audio file duration to start.

**Comment by hasnhasan** [comment]
I provided solution as below :)

```
for (var l in myLayers) {
    var myLayer = myLayers[l];
    var myComp = myLayer['template'];
    myComp = app.project.item(tempComps[myComp]);
    myComp = myComp.duplicate();
    myComp.name = 'Scene_' + l;

    if (!myLayer['text']) {
        myComp.layer(2).remove();
        myComp.layer(1).remove();
        myComp.layer('Text_BG').remove();
    }


    myComp = layerCollection.add(myComp);
    myComp.duration = myLayer['duration'];
    myComp.startTime = lastDur;
    lastDur = myComp.outPoint;



}
```
