### ISSUE TITLE
rendering rgb+a

### ISSUE THREAD

**Issue by dsrts** [inlife/nexrender#487]
This might be a silly question, but is it possible to render out a video with a transparent background? It looks like since Adobe CC 2017 nexrender needs to pass through a .mov or .avi state before rendering to any other file type, which if I have read things right can't do alpha channel rendering, so I am guessing not. But I'm wondering if I am missing something. I'm a bit of a novice here too, so it's possible I have missed something completely obvious, or am just lacking an understanding of how to parse the available documentation.

**Comment by inlife** [comment]
Hey @dsrts 

Technically you don't have to pass through .mov or .avi, it can be any format and encoding. It's just the thing that not many are supported within AE nowadays. However, I believe there was some format from the set of available ones that supported this kind of transparent rendering, can't say which one tho, you would probably need to research it.

After exporting, encode action could be used to convert it to a needed format. But again, check which formats and encodings support transparency.

Hope that helps.
Cheers!

**Comment by dsrts** [comment]
That gives me some hope, I'll see what I can come up with. I initially got the impression that nexrender would make a temporary .avi file before I could encode to a different format in post-render, but I don't understand the process very well yet.

Thank you!

**Comment by dsrts** [comment]
Found my own solution pretty quickly. AVI does do transparency, but only if you make sure it's lossless w/ alpha (which I did find here in another question earlier on). I was also misinterpresting the process. But if anyone is having the issue I was, this was how I solved it: 
```json
{ 
    "template": {
        "src": "file:///C:/.../AutoTemplate.aep",
        "composition": "Comp1",
        "outputModule": "Lossless with Alpha", 
        "outputExt": "avi" 
    }
    ,
    "actions":{
        "postrender": [
        
            {
                "module": "@nexrender/action-copy",
                "input": "result.avi",
                "output": "C:/.../lowerThirds.avi"
            }
        ]
    }

}   
```
