### ISSUE TITLE
Rendering multiple projects in the same job.

### ISSUE THREAD

**Issue by AgenteDog** [inlife/nexrender#490]
**Is your feature request related to a problem? Please describe.**
Rendering multiple projects in the same job.

**Describe the solution you'd like**
I actually got this to work in a nexrender-worker. Haven't tried it on the other version but I am sure it can be implemented similarly.

Basically, when the render is done the `job.state` is set to finished, but, I can actually do multiple things before this.

When doing the request to the server I pass 1 custom parameter.   `nextRenders`. This values are ignored by the worker, but, I can use them before the `job.state` is set to finished.

Here is some code I did for this:

```js
job = await render(job, settings);
//This executes after the render is done!
{
	//Check if the amount of renders or the amount of renders done has been set.
	//Set default values if not.

	const renders = typeof job.nextRenders != "undefined" ? job.nextRenders.length + 1 : 1;
	if (typeof job.renders == "undefined") job.renders = renders;
	if (typeof job.rendersDone == "undefined") job.rendersDone = 0;

	const rendersDone = job.rendersDone + 1;

	if (rendersDone < job.renders) {
		//Set up url/config for put request
		const url = `http://localhost:2323/api/v1/jobs/${job.uid}`;
		const config = {
			headers: {
				"nexrender-secret": secret
			}
		};

		//Make new data
		const nextRender = job.nextRenders[0];
		job.nextRenders.splice(0, 1);

		const nextJob = {
			...job,
			...nextRender,
			rendersDone,
			state: "queued"
		};

		//Do the request
		axios.put(url, nextJob, config);
	}

	console.log(`[${job.uid}] renders done: ${rendersDone}/${job.renders}`);

	//Once all renders are done do whatever it has to
	if (rendersDone == job.renders) {
		//Get renders folder path
		const folderPath = "D:/Trabajos/RenderWidgets/Advanced Demo/nexrender-server/output/";
		const rendersPath = folderPath + "renders/";

		let uploadFile;

		(async () => {
			//Zip all files
			//Only happens if there is more than just 1 render
			if (job.renders > 1) {
				console.log(`[${job.uid}] zipping files.`);
				const zipFile = folderPath + job.uid + ".zip";
				await zip(rendersPath, zipFile);

				//Delete files in the render directory
				console.log(`[${job.uid}] cleaning up files.`)
				fs.readdir(rendersPath, (err, files) => {
					for (let i = 0; i < files.length; i++) {
						fs.unlink(rendersPath + files[i], err => { if (err) throw err; })
					}
				})

				uploadFile = zipFile;
			}
			else uploadFile = job.actions.postrender[1].output;

			//Upload final file
			console.log(`This is where I upload ${uploadFile}`);

			//Delete the file for cleanup
			//console.log(`[${job.uid}] deleting uploaded file.`)
			//fs.unlink(uploadFile, err => { if (err) throw err; })

		})();
	}

	job.state == "finished";
}
```

This code could be optimized, and I will probably optimize it when I need to use it for production, but, for now it works.

**_The JSON_**

Setting up the json is also super easy. You just add the `nextRenders` value as an array. Inside that array you just pass all renders that you want to do. It's just an object that you would pass in any another job. this includes the template, assets, and actions. I am sure this could be optimized to make it easier, but, this is my first try at it. 

Example:
```json
{
	"template": [],
	"assets": [],
	"actions": [],
	"nextRenders": [
		{
			"template": [],
			"assets": [],
			"actions": []
		},
		{
			"template": [],
			"assets": [],
			"actions": []
		}
	]
}
```

**_Small explanations of the code_**

_1_
See how I set the `folderPath `and the `rendersPath`? This is important in my implementation. That can also (probably) be removed with a better implementation.  I basically have an action-copy on both of the renders that places them in the `rendersPath`.

_2_
When all the renders are done you can do a custom action. I, for example, just zip all files if there is more than 1 render and upload. After this you can delete the files for cleanup if you want. Since it's just code you can customize this pretty easily anyways.

Then, at the end, I just set the `job.state` to finished. If I don't set it to finished then it will be stuck doing the same render infinitely.

_3_

This is just a quick test I managed to do. I will probably fix this up in the near future to make it even better. I just wanted to show this since, maybe, it could become a feature.

_4_

As you can see, the way I manage to do this is by sending a put request to the current job. Just take the first item of the next renders, put it in a separate variable, and remove it from the job. Then, set what the next job is going to be. Spread the job, then the next render, and set the rendersDone to the amount of renders that have been complemented.  Finally, set the state to queued so that it "repeats" the render.

_**Stuff that could be fixed in this code:**_

_1_
Something that I will probably fix in the future is the zipping of the renders. As you can see in there I actually zip the whole folder. This is probably not a good Idea. What I will do instead is just pass an array with the location of all the renders completed in the axios request. Then, you can zip only this files and also delete only this files when cleaning up.

_2_
I could probably also not have to pass actions for every render. Instead, I can probably just render with the same name and add an extra number in the end. So if the output is coolRender then the second render would be coolRender2.  This could be made as an optional feature if it is not defined in the next render.

This would action-copy everything to the same directory without having to set it up twice.

_**Some other stuff**_

I am not the best at explaining things so if there are any questions about the code just ask :)

PD: I believe this could be a cool feature to implement. Still, it's just an idea.

**Describe alternatives you've considered**

**Additional context**

**Comment by inlife** [comment]
Hey @AgenteDog 

Quite a big issue description, I like it 👍 😄 

The first question I have is, why do you need to render multiple jobs within a single one? I can't seem to wrap my head around the reasons for that.

P.S. sorry for the long response time

**Comment by AgenteDog** [comment]
Well, personally I use it to render things that belong together in one job. Let's say I have 2 templates that are both related to football and 2 other to basketball. Instead of rendering `football1.aep` and `football2.aep` in separate jobs I can just render them on the same job, zip them, and upload them. That way I have something like Basketball.zip and Football.zip. 

Another case would be the keeping track of the rendering of multiple templates at the same time. As I explained `rendersDone` gets sent in the put request. If I want to know how many renders are left in total I can just check rendersDone and compare it to the total amount of renders that will happen (`renders`) and thats it.

I am sure this can be made so that those 2 parameters are added as soon as the server receives it to make it more convenient. (Because right now you know no renders have been completed because the `renders`/`rendersDone` value is missing.

For me specifically this is useful. And I have seen different issues regarding the same thing so I must not be the only one that would appreciate a feature like this one.

**Comment by inlife** [comment]
Ok, I guess I can see the reasoning behind the feature. However, what I do not understand the purpose of projects/jobs belonging together. It seems to be a kind of **meta-information** about the jobs themselves rather than a functionality need.

Would not you agree?

It seems to me that is something that would be better managed by an outside layer like a meta-data database/interface, or additional meta-information tools like project tagging, etc.

Also, looking from another point, funnily enough, it actually conflicts with a future feature of distributing a single project onto multiple jobs for the distributed rendering feature that is in planning since 2016 😄 
So technically a single `football1.aep` would possibly be rendered with a 1 parent and 4 children jobs.

**Comment by AgenteDog** [comment]
And yeah, it is about the metadata, but, also about the zipping. My goal is to be able to zip the render for both football1 and football2 in one and then upload that. That way someone can come and just download that one file to get all the renders. It is much easier than having to track all jobs and when they are done zip them and upload them.

Also, If I have one worker in the US and another one on Europe (and I don't shared storage) I would have to develop a way to upload both renders to 1 main place and them zip them/upload them.

As an alternative, maybe you could be able to send 1 request to the server with the same structure as I do now but instead of doing it in one job you could "link" different jobs. That way you can see general stats for the renders and then you also have the individual render ids to check their individual status. Still, It would not be as easy to zip all the renders.

I guess a simplified solution would be to zip all the renders when downloading and just upload the unzipped renders, but, In order to know when all the renders are done the solution I said above could work. It would be harder to implement though which is why I skipped the idea.

_Just for some background of why I need to have a zip:_
I'm trying to make it as easy as possible for someone to download the final product of multiple (or 1) renders. Also, zipping saves space and that would make it faster to download.

Also, that new feature sounds super cool! But I don't see how it conflicts. Imagine being able to render football1 and 2 with their respective "children jobs". That would be super cool!

**Comment by inlife** [comment]
I think our thinking is going in the right direction.

As an alternative way of achieving something you have suggested initially, and similar to your most recent thoughts, I came up with a concept of generalizing the parent-child relation to use not only for distribution purposes but also for grouping purposes.

So essentially there would be the main job, or let's call it meta-job. Depending on its nature it could be an instruction that would tell which jobs need to be rendered and how, and what to do with them after that. Additionally, it would describe preferences on which nodes should be responsible for that (maybe just the current one), how many nodes are needed, whether there should be distribution happening, etc.

Now the only thing I'm not sure about yet, what would be a good API and job interface for something like that. Or to put in different words, what would be the best way to create a meta job and set of child jobs?

**Comment by AgenteDog** [comment]
I think a modified version of my current method would be a good idea.

## What will we pass to the meta-job?

Before I explain, I want to clarify something. I am going to refer as "parent information" to the information that is at the top level of the information. 

As an example:
```json
{
  "parent_info": {
    "children_info": ""
  },
  "parent_info": {
    "children_info": ""
  },
}
```
I guess you get the general idea :)

### Actions
I was thinking that in order to be able to "render" one meta-job with multiple workers we have to tell it where to upload the renders. We can do that with actions in the meta-job.

As an example, I can have a folder called "football" in some s3 bucket. We tell the meta-job that this is where we want to upload all the renders and then the meta-job should tell each job that they should upload to that folder. That way everything gets uploaded to the same place easily.

We can achieve this by having an actions similarly to a normal job has. This actions could affect all jobs under it.

**New action**
We can also add a new action. We can optionally zip all uploaded render after the meta-job is done. It downloads all the renders from the s3 bucket, deletes them, zips all renders and finally uploads that. We can even make it so it uploads the zipped render in some other folder. In fact, we could even have the option to create automatic temp folders on aws instead of having to name them. This would be similar to the current thing that is done locally where a folder with a unique is done every time there is a new job.

### Jobs
This is where stuff gets interesting.

My idea was that jobs can look like this. _I have it as a js object in order to be able to add comments_

```js
const jobs = [
	{
		//This is a job with no children
		type: "single",
		template: [],
		assets: [],
		actions: []
	},
	{
		//This is a job with children jobs
		type: "has_children",
		template_src: "",
		jobs: [
			{
				composition: "",
				assets: []
			},
			{
				composition: "",
				assets: []
			}
		],
		actions: []
	}
];
```


You might notice I have 2 types of jobs here. Normal jobs and jobs with children. You might ask: Why do they look that different?

#### What the 2 jobs share in common
My idea is that both the jobs will not have an action copy, but, they can have an ``action-encode``. That way they can end up in whatever format you want them before uploading. (In my current method I use ``action-copy`` so I just want to clarify.)

Both of them will share the obvious. They will have the same ``action-upload`` because it was passed to the meta-job. 

They will also share a ``type`` to be able to know if its a job with children or not.

#### Normal jobs
Normals jobs (AKA Jobs with no children) are just... normal jobs. Can be passed like my current method.

#### Jobs with children
Setting up a good way to do this can be done in 2 different ways.

1. Each children job has it's own settings.
2. All children share the same settings.

I am going to explain option 2 since that is the one I most like and the one that seems easier to use.

As you said before, this jobs share the same project. The thing is, what if they share the same actions too? We can pass the ``template_src``, ``actions``, and a ``jobs`` array that contains the name of the composition and the assets.  This can be seen in the example json I provided.

This children jobs will also share the same action-upload as normal jobs.

### What else?
Nothing. We only have realistically pass this 2 main arguments!!!! I mean, what else do we have to pass? All the other information will be added by the meta-job automatically. That is what the next section is.

### How will it look in the end?
I'm thinking something like this.

```json
{
  "jobs": [
    {
      "type": "single",
      "template": [],
      "assets": [],
      "actions": []
    },
    {
      "type": "has_children",
      "template_src": "",
      "jobs": [
        {
          "composition": "",
          "assets": []
        },
        {
          "composition": "",
          "assets": []
        }
        ],
      "actions": []
    }
  ],
  
  "actions": {}
}
```

## What will the the meta-job give back?

For this, there is not much to explain. It should be able to provide all the ids of all the jobs, the amount of jobs to be done, and the amount of jobs done.

I am not 100% sure what the best way to pull it off would be but this is my idea.

```json
{
  "id": "",
  "jobs_amount": 2,
  "jobs_done": 0,
  "jobs": [
    {
      "type": "single",
      "template": [],
      "assets": [],
      "actions": [],
      "id": ""
    },
    {
      "id": "",
      "jobs_amount": 2,
      "jobs_done": 0,
      "type": "has_children",
      "template_src": "",
      "jobs": [
        {
          "id": "",
          "composition": "",
          "assets": []
        },
        {
          "id": "",
          "composition": "",
          "assets": []
        }
        ],
      "actions": []
    }
  ],
  
  "actions": {}
}
```
We can then access the progress for each job individually using this ids, and, we can know the the amount of renders to be done vs the amount of renders done from here.

## Conclusion
As you can see, my ideas are kind of general and can probably be though further, developed and changed. Still, like you said, I think we are going in the right direction. This could be something really cool.

Also, after thinking about it, this can probably be achieved without touching the workers. This can be done by changing the api pretty much, nothing else.

**Comment by inlife** [comment]
Ok, after reading carefully and some additional long thinking on this topic I want to say, I agree with almost everything here. For the last 3 years, I was thinking about this concept in the plane of linear jobs with relations between them. Now, however, it seems like I started changing my mind, and the option suggested by you with the nested jobs looks more appealing, and what's the most important much more simple for the end-user.

The only thing I would probably change is the naming. (mentioning this just below)

So taking an existing job model, and modifying it to make use of this new nested structure, would make it look something like this:
```js
const job = {
    /* this is a default usual nexrender job */
    "type": "container"
    "children": [
        {
            "template": {
                "src": "http://example.com/assets/myproject.aep",
                "composition": "main"
            },
            "actions":{
                "postrender": [
                    {
                        "module": "@nexrender/action-copy",
                        "output": "d:/mydocuments/results/part1.mov"
                    }
                ]
            }
        },
        {
            "template": {
                "src": "http://example.com/assets/myproject.aep",
                "composition": "main"
            },
            "actions":{
                "postrender": [
                    {
                        "module": "@nexrender/action-copy",
                        "output": "d:/mydocuments/results/part2.mov"
                    }
                ]
            }
        },
    ],
    "actions":{
        "postrender": [
            {
                "module": "@nexrender/action-merge",
                "input": [
                    "d:/mydocuments/results/part1.mov",
                    "d:/mydocuments/results/part2.mov"
                ]
                "output": "merged.mov"
            },
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "input": "merged.mov"
                "output": "encoded.mp4"
            },
            {
                "module": "@nexrender/action-upload",
                "input": "encoded.mp4",
                "output": "d:/mydocuments/results/myresult.mp4"
            }
        ]
    }
}
```

And then for the distributed job, sending a structure like this:
```js
const job = {
    /* define a automatically-distributed job */
    /* nexreder will internally create a bunch of jobs based on provided settings */
    /* and add required actions to upload/push rendered pieces, and the to download, merge them together and run post-render actions */
    "type": "distributed",
    "distribution": {
        "split": "even", // "static-slice"
        "split-time": "30s", // for "static-slice"
        "store": "network-stream", // "shared-folder", "cloud-folder"
        "store-params": {
            "bucket": "temp-data" // for "cloud-folder"
        },
    },
    "template": {
        "src": "http://example.com/assets/myproject.aep",
        "composition": "main"
    },
    "assets": [],
    "actions":{
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "encoded.mp4",
                "output": "d:/mydocuments/results/myresult.mp4"
            }
        ]
    }
},
```
Will they do all required automagical transformations on the API side to create a nested structure internally.

**A probably now, the main rule of this approach**: after a nested job gets picked up by a node, that node is now considered responsible for this job, and all nested children jobs become available for other nodes to pickup.

**Comment by AgenteDog** [comment]
Yup, that is exactly what I am thinking but with some fixed and additions. I like it!
