### ISSUE TITLE
database no longer mutable?

### ISSUE THREAD

**Issue by JamesBotterill** [inlife/nexrender#498]
I have a custom module which used to enable me to update custom objects the database.js

This functionality no longer seems to be working, I was wondering how I can get this working again as right now I'm having a nasty work around.

**Comment by inlife** [comment]
Hey @JamesBotterill 

Could you share more details?

**Comment by JamesBotterill** [comment]
I have a custom module which uploads to a web app I've developed and in the custom upload module if the upload is successful I'm storing the location of the render in the web app storage.  

I used to be able to extend the job json entry into the database to have a custom object (extra) when adding a job to the database which I would then update within the module using the the job.extra variable, this worked fine and without issues in previous versions but since updating to the latest server it no longer seems possible. 

Hope this makes sense

**Comment by inlife** [comment]
It should be still possible. The only major thing that changed however was adding a minimal "status" methods for jobs, to reduce the amount of network traffic going on each update check for very big job objects: https://github.com/inlife/nexrender/blob/master/packages/nexrender-server/src/index.js#L16-L18

Those methods are used internally to track job status/etc.

Other than that everything should be similar to what it was before
