### ISSUE TITLE
Show position in queue 

### ISSUE THREAD

**Issue by JamesBotterill** [inlife/nexrender#499]
Right now there's a scenario where I can have a number of jobs waiting to be processed, it would be good to return the position of a job when queued in the json response from the server.

**Comment by inlife** [comment]
How do you potentially see the interface for that API method? Could you give some examples?

**Comment by JamesBotterill** [comment]
I would see it as part of the v1/api/jobs/ response as an int. 

status : string
renderProgress : int 
queuePosition : int

As we know if the server oldest-first oldest-first or newest-first we can understand the position based number of items in queue and position based on pickup rule. 

only concern right now is if there's a large number of jobs in the queue every time a job is picked up it's a pretty big update and then race conditions if there's multiple workers.

**Comment by inlife** [comment]
That is a great suggestion! I'm not yet sure how it can be done yet, especially as you've mentioned because of possible race conditions and etc. But yea, I will definitely keep in mind for the next major update!
