### ISSUE TITLE
Alpha Channel Rendering

### ISSUE THREAD

**Issue by senthudms** [inlife/nexrender#500]
HI

Thanks for make Nexrender

My composition in Transparent Background,  I need to get the final video in alpha background, is that possible?

**Comment by phlexib** [comment]
You can create an output module preset in After Effects with whatever settings you want and pass it’s name to the “outputModule” property in the Job Template object in Nexrender
https://github.com/inlife/nexrender#details

**Comment by MHanutko** [comment]
Like phlexib mentioned:

`
"outputModule": "ProRes 422(HQ)",           //this has to be named like the preset inside Adobe After Effects
"outputExt": "mov"
    
`

**Comment by inlife** [comment]
Sorry for off-topic, but: it is so amazing that you guys are helping each other as well. I love our community!  🎉 😄

**Comment by jitendra-koodo** [comment]
> Like phlexib mentioned:
> 
> ```
> "outputModule": "ProRes 422(HQ)",           //this has to be named like the preset inside Adobe After Effects
> "outputExt": "mov"
> ```

Can you please share the full "actions" settings? 

I'm not able to get .mov, still giving me mp4 for some reason. My version:

	"actions": {
		"postrender": [
			{
				"module": "@nexrender/action-encode",
				"outputModule": "ProRes4444",
				"outputExt": "mov",
				"output": "encoded.mov"
			},
			{
				"module": "@nexrender/action-copy",
				"input": "encoded.mov",
				"output": "E:\\output.mov"
			}
		]
	}
