### ISSUE TITLE
Is there a way to render using AME?

### ISSUE THREAD

**Issue by atitkothari** [inlife/nexrender#502]
I know it is one of the features in the 2.0 release but is there a way I can use the AME to render using the current release? Maybe using a custom jsx script? 
Thanks!

**Comment by inlife** [comment]
Hey @atitkothari 

Yeah, technically there is!
https://github.com/inlife/nexrender/issues/83#issuecomment-580838407

Please try this out, and check if it does work for you :)
Cheers!
