### ISSUE TITLE
pre-render actions on images uploaded

### ISSUE THREAD

**Issue by JamesBotterill** [inlife/nexrender#503]
I'm trying to ensure that images meet a set of size requirements prior to them being rendered, I would want to write a small custom action that resizes the images if too large then use that image in leu of the one originally defines. 

Any ideas of how I would go about replacing the asset that's been defined with my new custom one as the documentation is a little light on this.

**Comment by MHanutko** [comment]
Hi James - you just want to resize the images to fit the Composition perfectly?

I have a workaround via expressions for that "issue".
You can use that expression directly inside After Effects or send it with every image via nexrender config.

`
Property:    "Scale",
Expression:  "if(thisLayer.width < thisLayer.height) { s=100*thisComp.width/thisLayer.width; [s,s]; } else { 
s=100*thisComp.height/thisLayer.height; [s,s]; }",
`

**Comment by inlife** [comment]
Hey @JamesBotterill 

The simplest action would look something like this:
```js
// mymodule.js
module.exports = async (job, settings, action, type) => {
    console.log('hello from my module: ' + action.module);
}
```
Job - contains current job object
Settings - the shared settings object for this node
Action - contains a specific action object that defines the action, example of that:
```json
            {
                "module": "@nexrender/action-copy",
                "output": "/home/videos/myvideo.mov"
            }
```
Type - contains either "prerender" or "postrender" strings signifying where this action was called

Simple example from nexrender itself: https://github.com/inlife/nexrender/tree/master/packages/nexrender-action-copy

**Comment by JamesBotterill** [comment]
@MHanutko Thanks for this, 

@inlife So as I understand if I define the output location in the module as and then reference that within the template to ensure that AE uses the generated output as the image used in the render. I assume also that "prerender" actions are completed prior the the assets being downloaded? 

Makes sense but would make messy in the long run as no way to delete as part of clean up, as wouldn't use the project file.

**Comment by morneluckybeard** [comment]
@JamesBotterill I believe prerender happens after the downloading of the assets.

I have a similar case where I had to install fonts before rendering, my prerender script checks the temporary directory for all the assets(fonts, images etc), I then run some node scripts to install the font and then return a resolved promise, that then continues with the rest of the actions. Once it completes the temporary directory is deleted.

**Comment by inlife** [comment]
Hey @JamesBotterill 

@monkeywithacupcake is right, prerender happens after download, you can check this snippet here to get the idea on how it works: https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/index.js#L105-L112

Not sure I understood your question about "output location" definition. Could you explain a bit more?

Cheers!

**Comment by JamesBotterill** [comment]
@inlife sure thing:

I have an image which at present needs to have a specific set of size requirements in my render. 

I want to check and resize this image prior to starting the render, I'm not sure how I would do this without defining the location of the resized output image in the template. 

As @monkeywithacupcake  said there's way to do this with expressions so will move forward with this option instead of writing a module.

**Comment by inlife** [comment]
@JamesBotterill you could put the resized version of the image to the same source (i.e. replacing the image)
Would that work for you?
