### ISSUE TITLE
Getting the hang up connection between nexrender-server and nexrender-worker if internet connection fails during communication 2 systems

### ISSUE THREAD

**Issue by pixelfactorydevelopmentteam** [inlife/nexrender#504]
Hi , 

I have running the nexrender server another system and worker another window server systems, Due to internet disconnection , I have getting the message :

{ FetchError: request to http://167.172.228.988:6006/api/v1/jobs/pickup failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to http://167.172.228.988:6006/api/v1/jobs/pickup failed, reason: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
 

The message is still going on if the internet connection back on the worker computer and unable work or render any job until , we restart the window system or restart the nexrender worker again ... due to these process  I am facing a lot of hectic issues during the render process so please suggest the best way for ignore the re-start the nexrender worker manually process

**Comment by inlife** [comment]
I'm assuming that is something that happens within the internals of nodejs itself. So that would probably mean it requires the whole executable to be restarted.

That seems like a serious problem, and a surface-level search that I just did seems to indicate that it indeed not only related to nexrender. Unfortunately, I don't think I have an idea for solving this issue at that time. Maybe you have some suggestions?

**Comment by Morreski** [comment]
Hi,
Sorry if i'm slightly off-topic but two things catched my attention here.

1. In the logs you provided: 167.172.228.988 is not a valid ipv4 adress. This **might** be related to your problem.
2. Your nexrender server at 167.172.228.228  on port 6001 is publicly accessible. You may want to shield it ;)
