### ISSUE TITLE
How to change the value of First Margin Property inside Path Options of a Text Layer using Nexrender

### ISSUE THREAD

**Issue by digitGrove89** [inlife/nexrender#507]
This may be a possible noob question. But couldn't able to find the solution myself.

I need to change the value of First Margin property which is present inside the Path Options of a Text Layer. 

I tried this code, 

 {
      "type": "data",
      "layerName": "main",
      "composition": "camera",
      "property": "First Margin",
      "value": "953"
    },

but i got this error message from nex render logs

Error: nexrender: Can't find a property sequence First Margin for key: First Margin

can you kindly guide me where i'm wrong. or is this not possible in nexrender ?

![image](https://user-images.githubusercontent.com/46499139/97847837-3b852680-1d16-11eb-91d4-8996f94c70c7.png)

**Comment by inlife** [comment]
Try accessing it via something like `Text.Path Options.First Margin`, or even better try to check out how it can be done via scripting. That should help, since nexrender just does a thin wrapper on top of that 👍
