### ISSUE TITLE
Allow repeated ffmpeg parameters for action-encode

### ISSUE THREAD

**Issue by blesner** [inlife/nexrender#508]
It would be nice to support repeated ffmpeg parameters for `action-encode`. In my use-case I would like to use multiple `-i` parameters to perform overlaying/watermarking on videos. 

The actual specification of parameters with a JSON object does not support repeated keys, one possibility is to allow arrays as parameters values to indicate a parameter repetition. For example 
```
"params": {
   "-i": ["input1", "input2", ...],
   "-filter_complex": "..."
}
```
The first input at index 0 being the built-in input given by the `input` key.

The changes are quite small, and I happen to already have implemented it ;) and can submit a pull request if this feature is deemed useful.

**Comment by inlife** [comment]
Oh, I did not actually know that ffmpeg supports that kind of input repetition. If you have it already implemented, a pull request would be amazing, @blesner 🎉

**Comment by blesner** [comment]
Done! This is PR #513.
