### ISSUE TITLE
Command line stuck at rendering progress 100%...

### ISSUE THREAD

**Issue by mariselli** [inlife/nexrender#510]
**Describe the bug**
Hi there,
I am at my first usage and I got the program stuck.
I've created a very simple project of 3.5 sec with a white square moving on a black screen.
When I launch this command: 
```
nexrender-cli --file myjob.json
```
I see the output going on until 
```
[OVsMVgXpF9hvTIrYEJWK2] rendering progress 100%...
```
From that point on, nothing else happen.
I figured out, looking at the processes with `top` command, that the 3 process named
* aerendercore
* aerender
* aerender

are still executing.
When I kill those process, the execution of my command goes until the end and I get my rendered file.

At times everything goes fine. So basically it happen causally.
I would say at least the 90% it get stuck.

**Information about environment**

* Which version of nexrender are you using?
```
❯ nexrender-cli -v
1.21.4
```
* What kind of the setup do you have? (server+worker or cli)
I am just testing the cli version but I have had the same issue using a node script with nexrende/core

* Are you using pre-built binaries or globally installed npm packages?
Global (but I also tried with the local npm module when I tried to use the script way)

* Which kind (and version) of operating system you are running it in?
<img width="259" alt="CleanShot 2020-11-05 at 22 52 48@2x" src="https://user-images.githubusercontent.com/1041289/98300499-a6a25780-1fb9-11eb-9488-a4dc26dd158b.png">

* Any additional information that might be helpful
File myjob.json
```
{
	"template": {
		"src": "file:///Users/___my_path___/tests/ae-render/test.aep",
		"composition": "main"
	},
	"actions": {
		"postrender": [
			{
				"module": "@nexrender/action-encode",
				"preset": "mp4",
				"output": "encoded.mp4"
			},
			{
				"module": "@nexrender/action-copy",
				"input": "encoded.mp4",
				"output": "/Users/___my_path___/tests/ae-render/test.mp4"
			}
		]
	}
}
```

**Expected behavior**
I would have liked to do not see the process endless stuck on the 100%.

**Screenshots**
<img width="1014" alt="CleanShot 2020-11-05 at 22 51 44@2x" src="https://user-images.githubusercontent.com/1041289/98300814-1c0e2800-1fba-11eb-9f99-a352ff2e10a8.png">
processes:
<img width="2221" alt="CleanShot 2020-11-05 at 22 51 59@2x" src="https://user-images.githubusercontent.com/1041289/98300834-22040900-1fba-11eb-9e93-3c7a35c5507e.png">

**Comment by inlife** [comment]
Hey @mariselli 

Have you tried using different versions of After Effects as well? This looks like an error happening somewhere deep within aerendercore itself.

Cheers!

**Comment by mariselli** [comment]
Hi @inlife,
thanks for reaching me back.
Actually not, I've installed AE via Adobe Creative Cloud, the Adobe After Effects 2020, I didn't thought that could have been a version issue. I will try use an older version (hopefully I can install it with Adobe Creative Cloud).
Any suggestion on the version to try? Or any other guess on what should I try?
I notice that when you run everything with sudo it just not work.

**Comment by inlife** [comment]
@mariselli can't say any specific version, I just remember people having similar issues (actually some of them even documented on github issues as well), so you could try searching for that.

Yeah, sudo sometimes might do more harm than good :D
Hope that helps 👍 

Cheers!
