### ISSUE TITLE
job update isint working http://localhost:3000/api/v1/jobs/9OtngLIEg0WLrkRth_TiA

### ISSUE THREAD

**Issue by ilhamzacky** [inlife/nexrender#511]
Describe your question, attach logs, images or anything that might help to better understand it.

hi all , 
post , get status , delete all are working fine

but when a job fails and when I send a put request with the id - "http://localhost:3000/api/v1/jobs/9OtngLIEg0WLrkRth_TiA"

No response, can someone help,
Am i doing something wrong

Thank you

**Comment by inlife** [comment]
Hey @ilhamzacky 

What is the response code for HTTP request? Or is there no response code, does it go into an infinite cycle and then times out? Could you provide some screenshots?

Cheers!

**Comment by ilhamzacky** [comment]
hi @inlife thanks for a quick replay, say me if I am wrong

I tried your post method it's working perfectly, I just want to know when a job gets failed I should retry it, so I did is I made some changes to the post method, I am testing it through postman

Post URL
http://localhost:3000/api/v1/jobs

This is my body

```
{
                "template": {
                    "src": "file:///C:/Users/Ilham/Documents/PRO/TEMP01.aep",
                    "composition": "temp1"
                },
                "assets": [
                  {
                    "type": "data",
                    "layerName": "text",
                    "property": "Text.Source Textsdfmdsd",
                    "value": "ilham"
                  }
                ],
                "actions": {
                  "postrender": [
                    {
                      "module": "@nexrender/action-encode",
                      "output": "output.mp4",
                      "preset": "mp4"
                    },
                    {
                      "module": "@nexrender/action-copy",
                      "input": "output.mp4",
                      "output": "../rendered/out.mp4"
                    }
                  ]
                }
        }
```
Response
```
{
    "uid": "LgfFLHuktfpTsdgZ9KA79",
    "type": "default",
    "state": "queued",
    "output": "",
    "template": {
        "src": "file:///C:/Users/Ilham/Documents/PRO/TEMP01.aep",
        "composition": "temp1"
    },
    "assets": [
        {
            "type": "data",
            "layerName": "text",
            "property": "Text.Source Textsdfmdsd",
            "value": "ilham"
        }
    ],
    "actions": {
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "output": "output.mp4",
                "preset": "mp4"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "output.mp4",
                "output": "../rendered/out.mp4"
            }
        ]
    }
}
```
in asset property I made some changes, instead of the Text.source text, I changed  "Text.Source Textsdfmdsd"

Error message on worker
```
Error: nexrender: Can't find a property sequence Source Textsdfmdsd for key: Source Textsdfmdsd
aerender ERROR: Runtime error in After Effects.

[LgfFLHuktfpTsdgZ9KA79] error occurred: Error: Couldn't find a result file: C:\Users\Ilham\AppData\Local\Temp\nexrender\LgfFLHuktfpTsdgZ9KA79\result.avi
    at ChildProcess.<anonymous> (G:\stage clip new\nexrender-worker\node_modules\@nexrender\core\src\tasks\render.js:171:31)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

so I did is get that UUID of my posted video

update PUT
http://localhost:3000/api/v1/jobs/LgfFLHuktfpTsdgZ9KA79
On-body I have added the corrected body this time 

my response on PUT Update
```
{
    "uid": "LgfFLHuktfpTsdgZ9KA79",
    "type": "default",
    "state": "error",
    "output": "",
    "template": {
        "src": "file:///C:/Users/Ilham/Documents/PRO/TEMP01.aep",
        "composition": "temp1"
    },
    "assets": [
        {
            "type": "data",
            "layerName": "text",
            "property": "Text.Source Text",
            "value": "ilham"
        }
    ],
    "actions": {
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "output": "output.mp4",
                "preset": "mp4"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "output.mp4",
                "output": "../rendered/out.mp4"
            }
        ]
    },
    "updatedAt": "2020-11-07T16:57:17.868Z",
    "renderProgress": 0,
    "error": {}
}
```
But when I check the status of that updated video

GET 
http://localhost:3000/api/v1/jobs/LgfFLHuktfpTsdgZ9KA79/status

Response
```
{
    "uid": "LgfFLHuktfpTsdgZ9KA79",
    "state": "error",
    "type": "default",
    "renderProgress": 0,
    "error": {}
}
```
no state change, renderProgress change, it won't retry the fail job, 
say me if I had done wrong,
plz help,
Thank you 
Hope this helps

**Comment by inlife** [comment]
Oh I see what you mean. Yes, an existing errored job will not be retried unless you manually change its state from error to queued.

**Comment by ilhamzacky** [comment]
@inlife thanks for your quick replay, will have a check, 
thank you very much

**Comment by ilhamzacky** [comment]
thanks, @inlife, great it worked,

**Comment by ilhamzacky** [comment]
@inlife sorry for intercepting you, I just have 2 more questions, say me if I am wrong
1 st question -
I have installed the next reader on the windows server and I am using s3 to download and upload videos, 

my question is once downloading a video from s3, can't I render it simultaneously ?
else first I have to download the video and then have to start rendering, two commands  ?

2 nd question - 

first, when I was testing the project on my local, I was able to render multiple videos at a time, I used a for loop and got some data and I was able to render multiple simultaneously.
but when it comes to live using network rendering, it works as a job basis, so it renders a video at a time 

my question is cant I render two videos at a time ??

sorry if i had asked anything wrong,
thank you ....

**Comment by Thiago-Dantas** [comment]
@ilhamzacky usually aws SDK only makes the file available after download is complete
for 2, you can start multiple workers on the same computer, each will try to fetch from server and start rendering. take care not to overload your server

**Comment by inlife** [comment]
1. @ilhamzacky, not all video containers allow you to preview/use them until all or at least the last pieces were downloaded, so that is something very specific and should be done manually and carefully

2. as @Thiago-Dantas mentioned correctly, you would just need to run as many nexrender-worker instances as you need multiple threads of rendering to happen, as simple as that 👍 

Cheers!

**Comment by ilhamzacky** [comment]
thanks, @Thiago-Dantas @inlife , would be a great help!
