### ISSUE TITLE
Pre-render action, returns an empty error object to API when rejecting the promise.

### ISSUE THREAD

**Issue by morneluckybeard** [inlife/nexrender#512]
@inlife Love the library and the modular approach.  

I wanted to ask if it is possible from a custom action(pre-render) in this case, to return an error to the api? At the moment if I use return Promise.reject('no reason') it throws the error on the worker console, but the api returns with an empty error object.

![image](https://user-images.githubusercontent.com/58560781/98373982-b4eb8480-2048-11eb-9693-a3b77da0c88f.png)

![image](https://user-images.githubusercontent.com/58560781/98373606-2c6ce400-2048-11eb-945c-e11f26dc62ef.png)

![image](https://user-images.githubusercontent.com/58560781/98373565-17905080-2048-11eb-8254-89e5802ee7e0.png)

Thanks!

**Comment by inlife** [comment]
Hey @morneluckybeard 

Thanks for the kind words! ;)

Yea, regarding the error handling, it should pass the error message, however seems like it does not. At least in your case.
Please check out this line in the worker: https://github.com/inlife/nexrender/blob/master/packages/nexrender-worker/src/index.js#L83

As you can see it assigns an error object to the job, however seems like JSON.stringify can't pick it up and encode it properly. 
Maybe you have some suggestions on how to better provide that error so it would be properly sent to the server?

P.S. Another thing came to my mind, have you tried returning an error within promise rejection?

**Comment by morneluckybeard** [comment]
@inlife Strange, I removed all my code and just returned a rejected promise, do you think that the job.error could be overwritten somewhere seeing that it's mutable?

I tried throwing a new Error('no reason') and it remains empty, unfortunately. My setup is the network configuration, using npm -g @nexrender/worker.

I like your approach! I'm not sure about the "behind the scenes" of the worker, but if there are multiple places that an error can occur, they might overwrite the previous error as it's mutable? But you think it might be that JSON.stringify can't encode it?

How would you structure the rejected promise?

**Comment by inlife** [comment]
It might be a bug on the nexrender internal side. Usually, the rejected promise having an error object within itself is the best way to go, and how it's done in the nexrender. So, something like that:

```js
module.exports = () => {
    return Promise.reject(new Error("An error within some super action"))
}
```

Should be the proper API for the error. IF that does not work, however, it means it's either getting overwritten as you've mentioned (which is bad), or not working at all (which is arguably even worse :D). Changing the "error" field to an array would be probably more beneficial in regards to "compound" errors use-cases however it would break compatibility people have with v1 codebase, so it's a change that can be made only for v2.

Do you have some ideas why it might be happening and how it can be fixed?

**Comment by morneluckybeard** [comment]
> It might be a bug on the nexrender internal side. Usually, the rejected promise having an error object within itself is the best way to go, and how it's done in the nexrender. So, something like that:
> 
> ```js
> module.exports = () => {
>     return Promise.reject(new Error("An error within some super action"))
> }
> ```
> 
> Should be the proper API for the error. IF that does not work, however, it means it's either getting overwritten as you've mentioned (which is bad), or not working at all (which is arguably even worse :D). Changing the "error" field to an array would be probably more beneficial in regards to "compound" errors use-cases however it would break compatibility people have with v1 codebase, so it's a change that can be made only for v2.
> 
> Do you have some ideas why it might be happening and how it can be fixed?

Ahh okay that makes sense! 
When I get some time on my hands I'll take a look and see what's up. Thanks again!
