### ISSUE TITLE
Nexrender is getting completed in ~17 sec but no output is getting produced

### ISSUE THREAD

**Issue by harman262** [inlife/nexrender#514]
Describe your question, attach logs, images or anything that might help to better understand it.
Hi @inlife ,
I see this issue https://github.com/inlife/nexrender/issues/288 which as per description is coming with --reuse flag

but at my machine it is coming without that

Here is my sample job.json 

{
    "template": {
        "src": "file:///Users/harmangill/Desktop/TI/VideoTemplates/First/Slideshow/Travel Memories Slideshow (converted).aep",
        "composition": "=Final Comp"
    }
}

Output is : 

$ nexrender-cli --file job.json
> starting nexrender-cli
using automatically determined directory of After Effects installation:
 - /Applications/Adobe After Effects 2020/aerender
checking After Effects command line renderer patch...
command line patch already is in place
[vkDX46bS4-lkKzo4ebzlk] setting up job...
[vkDX46bS4-lkKzo4ebzlk] working directory is: /var/folders/2m/2hgfkgbd61n5qvm3df6k3ljh0000gn/T/nexrender/vkDX46bS4-lkKzo4ebzlk
[vkDX46bS4-lkKzo4ebzlk] downloading assets...
[vkDX46bS4-lkKzo4ebzlk] applying prerender actions...
[vkDX46bS4-lkKzo4ebzlk] running script assemble...
[vkDX46bS4-lkKzo4ebzlk] rendering job...
[vkDX46bS4-lkKzo4ebzlk] rendering took ~17.745 sec.
[vkDX46bS4-lkKzo4ebzlk] writing aerender job log to: /var/folders/2m/2hgfkgbd61n5qvm3df6k3ljh0000gn/T/nexrender/aerender-vkDX46bS4-lkKzo4ebzlk.log
[vkDX46bS4-lkKzo4ebzlk] dumping aerender log:
Running Script: /var/folders/2m/2hgfkgbd61n5qvm3df6k3ljh0000gn/T/nexrender/vkDX46bS4-lkKzo4ebzlk/nexrender-vkDX46bS4-lkKzo4ebzlk-script.jsx
aerender version 17.5x40
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched

> job rendering failed
Error: Couldn't find a result file: /var/folders/2m/2hgfkgbd61n5qvm3df6k3ljh0000gn/T/nexrender/vkDX46bS4-lkKzo4ebzlk/result.mov
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@nexrender/cli/node_modules/@nexrender/core/src/tasks/render.js:171:31)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:311:20)
    at Pipe.<anonymous> (net.js:668:12)

I am using AE 2020 with aerender version: 17.5x40
Please help.

Thanks

**Comment by inlife** [comment]
Hey @harman262 

Could you also provide aerender logs as well?

**Comment by harman262** [comment]
Hi @inlife ,

Sorry the late reply , these are the aerender logs: 

Running Script: /var/folders/2m/2hgfkgbd61n5qvm3df6k3ljh0000gn/T/nexrender/ZEFx2CzYn58QhkwMptt1t/nexrender-ZEFx2CzYn58QhkwMptt1t-script.jsx
aerender version 16.1.3x5
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched


Is there any other logs that i need to check ?

**Comment by harman262** [comment]
Hi @inlife ,
I am very sorry , i was actually new to this After Effects,
So i tried rendering the same composition using aerender command line.
There it should me "Output file not mentioned" Error.

Issue is resolved, thank you so much for this amazing tool.

Thanks

**Comment by inlife** [comment]
Glad it worked out! 🎉

**Comment by jjairojr** [comment]
@harman262 how u do this ? i'm having the same problem
