### ISSUE TITLE
Provide example for the `createHandler` method

### ISSUE THREAD

**Issue by cdanyl** [inlife/nexrender#515]
The nexrender server provide the `createHandler` method as mentioned here https://github.com/inlife/nexrender/tree/master/packages/nexrender-server#usage-programmatic

I try to use this method inside an NestJS application and add custom logics for each nexrender server api routes, maybe like a middleware? or, nexrender-server wrapper?

_In NestJS we can create http adapter https://docs.nestjs.com/faq/http-adapter. Maybe I can write and share a custom adapter library to use in an NestJS app, with Typescript definitions for some nexrender packages :)_

Please help me to embed nexrender server to my own server, or, provide examples 👌

**Comment by inlife** [comment]
Hey @cdanyl 

This example shows how the nexrender server could be embedded in an existing nodejs HTTP server.
Essentially working already as a middleware. It already contains all URL routes for nexrender handed within.

Did my response help you? I did not fully understand your question, so in case it did not, could you try to rephrase it a bit? :)

Cheers
