### ISSUE TITLE
multiple colours in one text layer

### ISSUE THREAD

**Issue by jonnymangothinkjam** [inlife/nexrender#516]
hey, 

I dont suppose there is a way to have multiple text colours in one text layer is there?

See a below example:

![image](https://user-images.githubusercontent.com/25662069/98935741-e1395200-24db-11eb-82f0-ec0d904832dd.png)

If i use nexrender to change the text in this type of example, i lose the formatting of the colour, and it will all go white to match the start of the text layer. 

maybe it accepts a sort of rudimentary html like text <span style="color: blue">colour</span> and i'm just missing the way to tell the JSON?

hopefully that makes sense!

**Comment by inlife** [comment]
Hey @jonnymangothinkjam 

If there is a way to do it via JSX scripting (like defined in Adobe AE docs), then it will be exactly the same way for nexrender.
Hope that helps 👍 

Cheers!
