### ISSUE TITLE
Does Windows Server Requires VGA to run Nexrender

### ISSUE THREAD

**Issue by ilhamzacky** [inlife/nexrender#519]
Hi all,
Need a small help, 
I am using Network Rendering On Aws server - Windows 
Windows server doest have VGA, will this Effect the rendering, 

![Capture](https://user-images.githubusercontent.com/51988537/99151737-25d31200-26c3-11eb-8404-db79a01ea6c0.PNG)
![Capture1](https://user-images.githubusercontent.com/51988537/99151744-35eaf180-26c3-11eb-98ed-3653900fec8d.PNG)

Response GET on the video status
```
{
    "uid": "GV6PGT1dAwqxpLdsHlY6H",
    "state": "finished",
    "type": "default",
    "renderProgress": 0,
    "error": null
}
```
Generated text document
```
aerender version 17.1.1x34
Using DXGI: Device: "Microsoft Basic Render Driver" has dedicated video RAM (MB): 0
 has video RAM(MB): 0
Skipping DX support: Microsoft Basic Render Driver
Running Script: C:\Users\ADMINI~1\AppData\Local\Temp\2\nexrender\g1PM2zLSXqV3qqTq3Jjj2\nexrender-g1PM2zLSXqV3qqTq3Jjj2-script.jsx
PROGRESS: Adding specified comp to Render Queue
PROGRESS:  11/14/2020 10:21:37 AM: Starting composition temp1.


PROGRESS:  Render Settings: Best Settings
PROGRESS:  Quality: Best
PROGRESS:  Resolution: Full
PROGRESS:  Size: 1920 x 1080
PROGRESS:  Proxy Use: Use No Proxies
PROGRESS:  Effects: Current Settings
PROGRESS:  Disk Cache: Read Only
PROGRESS:  Color Depth: Current Settings
PROGRESS:  Frame Blending: On for Checked Layers
PROGRESS:  Field Render: Off
PROGRESS:  Pulldown: Off
PROGRESS:  Motion Blur: On for Checked Layers
PROGRESS:  Solos: Current Settings
PROGRESS:  Time Span: Work Area
PROGRESS:  Start: 0:00:00:00
PROGRESS:  End: 0:00:05:24
PROGRESS:  Duration: 0:00:06:00
PROGRESS:  Frame Rate: 25.00 (comp)
PROGRESS:  Guide Layers: All Off
PROGRESS:  Skip Existing Files: Off
PROGRESS:  
PROGRESS:  Output Module: Lossless
PROGRESS:  Output To: C:\Users\ADMINI~1\AppData\Local\Temp\2\nexrender\g1PM2zLSXqV3qqTq3Jjj2\result.avi
PROGRESS:  Format: AVI
PROGRESS:  Output Info: None
PROGRESS:  Include: Project Link
PROGRESS:  Output Audio: On (if comp has audio)
PROGRESS:  Channels: RGB
PROGRESS:  Depth: Millions of Colors
PROGRESS:  Color: Premultiplied
PROGRESS:  Resize: -
PROGRESS:  Crop: -
PROGRESS:  Final Size: 1920 x 1080
PROGRESS:  Profile: -
PROGRESS:  Post-Render Action: None
PROGRESS:  
PROGRESS:  11/14/2020 10:21:37 AM: Finished composition temp1.



PROGRESS:  Total Time Elapsed: 0 Seconds
WARNING:After Effects warning: logged one error  error: Unable to Render: File Not Found G:\stagemujeeb\stagemuj\nexrender-boilerplate\Assets\President_Barack_Obama.jpg
```
can some one help ?
Thank you

**Comment by inlife** [comment]
Calling to all experts rendering on AWS please help with a comment!
@ilhamzacky please feel free to mention any of the people from: https://github.com/inlife/nexrender/issues/467 :)

**Comment by derekstavis** [comment]
I have been using AE on an AWS EC2 Windows instance and it works flawlessly. This is because AfterEffects supports pure software rendering. Also, as far as I understand AE is more CPU-bound than it is GPU-bound (ofc that is depending on the effects you use). I have found that in certain scenarios (simple text, image and video-based 2D compositions) software rendering is much faster (10x) than hardware accelerated rendering.

**Comment by Thiago-Dantas** [comment]
im running on a "simple" m5.xlarge just fine without the elastic graphics thing
my composition is fairly simple and i only render a small part of it though
from my testings aerender hogs memory more than anything else
