### ISSUE TITLE
Code that changes paths to new images

### ISSUE THREAD

**Issue by matanregev** [inlife/nexrender#52]
Hi,

First of all thanks for this very cool project.

I added a breakpoint just before running the aerender process in AE, and I look at the project.aepx in the /temp dir that nexrender creates, and still see the paths to the old (default) images in the fileReference element.

But, it still works and it manages to render 3 different versions of the same video with the new images instead of the default ones.

I'm trying to understand how come it works and where is the code that replaces the paths. I found code that replaces the script/data paths, but not the images ones.

I'm using AE 2018.

Thanks!

**Comment by inlife** [comment]
Hello,

Pretty much it cheats. If you check those paths for images, on your rendering machine, they are invalid. That fact will trigger aerender to switch search for files from absolute path to relative path. And it will look for images in the aepx project folder.

That's however requires user to remove files from original absolute folder if he uses same machine for rendering the project.

That's it. In the new version I'm planning to do thought, I want to change the project file itself. Or better said, parse the project file into json structure, make necessary changes, and build needed adobe version project file for particular rendering machine.

**Comment by matanregev** [comment]
Thanks a lot for the quick answer!

Looking forward for the new version. sound like a good plan!

**Comment by inlife** [comment]
Well, still not sure how much time it will take to do it.
But thank you! )
