### ISSUE TITLE
After Effects showing blank Screen and is not working anymore

### ISSUE THREAD

**Issue by benjioh5** [inlife/nexrender#520]
**Describe the bug**
https://community.adobe.com/t5/after-effects/after-effects-showing-blank-screen-and-is-not-working-anymore/td-p/10777775?page=1

**Information about environment**
* Which version of nexrender are you using? Lastest (v1.22.0)
* What kind of the setup do you have? (server+worker or cli) Server + Worker
* Are you using pre-built binaries or globally installed npm packages? Prebuilt
* Which kind (and version) of operating system you are running it in? OSX + Windows Server 2012 + Ubuntu 18.02
* Any additional information that might be helpful

**Expected behavior**
ae_render_only_node.txt cause error. On every OS, `ae_render_only_node.txt` exists, AE 2019 doesn't work anymore.

**Screenshots**
<img width="878" alt="스크린샷 2020-11-16 오후 4 27 26" src="https://user-images.githubusercontent.com/4755202/99225069-cabc2f00-282a-11eb-8a79-df26d3aa6263.png">

**Comment by benjioh5** [comment]
nexrender sometimes doesn't delete `ae_render_only_node.txt` file after render. There sould be notification of `ae_render_only_node.txt` or manual delete mode

**Comment by inlife** [comment]
By default nexrender-cli/nexrender-core never creates a license file, unless an option is provided, and nexrender-worker always creates a license file unless an option is provided.

Hope that helps :)

Cheers

**Comment by benjioh5** [comment]
@inlife Thx, but I cannot find README.md file at nexrender-worker. Cloud you add or notify default options on worker?

**Comment by inlife** [comment]
Hey @benjioh5 
Added a worker readme in a5ed0b9 👍

**Comment by benjioh5** [comment]
Thanks a lot!
