### ISSUE TITLE
Rendering an image sequence with built-in aerender's multi-machine mode (coordination with filesystem)

### ISSUE THREAD

**Issue by underabrightsky** [inlife/nexrender#521]
Hello,

Thank you very much for Nexrender.

I'm looking for some guidance. I would like to share the rendering of a sequence of images between multiple instances of aerender on a single machine.

The idea is to use the built-in multi-machine mode of aerender but on a single machine. aerender processes are able to cooperate naturally using the filesystem for coordination. The algorithm used is described in [this post](https://creativecow.net/forums/thread/network-rendering-in-ae-with-cc/).

I think that this approach is used by a plugin like [BG Renderer MAX](https://aescripts.com/bg-renderer/) - unfortunately, it is not scriptable .

Ideally, I would like start to multiple Nexrender jobs that work in the same directory. I have seen that I could give 
each job the same `uid`. But I think that they will step on each other when downloading the template and the assets.

I could use one of the jobs for downloading the assets but I think that I can not prevent the download of the template
by each job.

**Comment by inlife** [comment]
Hey @underabrightsky 

Yea, the thing you are describing is what I've had in mind for the last couple of years, and still haven't added to the nexrender.
So unless you do it all manually with custom nexrender-worker implementation, I guess it won't be possible otherwise, at least for now.

Cheers!

**Comment by underabrightsky** [comment]
Hello @inlife ! Thank you 😉  Have a nice week-end !
