### ISSUE TITLE
prerender  with @nexrender/action-encode

### ISSUE THREAD

**Issue by lundeee** [inlife/nexrender#522]
Hi.

Is it possible to encode asset in prerender  with @nexrender/action-encode?

**Comment by lundeee** [comment]
Hi.

I solved it. I took @nexrender/action-encode and modified it. I also added some calls to api to save video info (extracted form ffmepeg output).

thank you for this, great work.

**Comment by inlife** [comment]
Hey @lundeee 

Glad you got it fixed and resolved. 👍 
In case you wish to introduce this as a feature to nexrender, please feel free to create a PR :)

Cheers!

**Comment by spenciefy** [comment]
@lundeee Hey! Is there any chance you'd be willing to share your modifications to encode assets in pre-render?
