### ISSUE TITLE
Install Render_Settings and Output_Module from CLI

### ISSUE THREAD

**Issue by FinnFrotscher** [inlife/nexrender#524]
This is not strictly speaking a nexrender question, but definitely related.
I have one `.ars` and one `.aom` file exported from after effects on my local machine containing the `render settings` and `output module` respectively. 
How can I install them on another machine, using only the CLI?

**Comment by inlife** [comment]
Good question, hard to do.

Option 1. via some scripting hacks, (iirc there is an API that allows modifying those settings from within JSX https://github.com/inlife/nexrender/issues/179)
Option 2. more hardcore one: working with the filesystem and binary formats for settings (I remember I found the folder either somewhere in appdata (for windows) or in documents, containing a bunch of .txt files and one of those was the output/render template module settings), if they (Adobe) haven't changed anything from 3 years ago when I was researching this, those files can be copied and pasted (not guaranteed to work tho, hehe)

@FinnFrotscher, I hope that helps you :)

Cheers!
