### ISSUE TITLE
how to replace the footage in pre-compose?

### ISSUE THREAD

**Issue by zhang852774731** [inlife/nexrender#529]
i want to replace a footage, but the footage in a pre-compose. How can i replace it with json config file? 
thank you very much!
![Snipaste_2020-11-24_19-17-45](https://user-images.githubusercontent.com/6835841/100087539-db535180-2e89-11eb-80d6-001eb68f8b3d.png)

the final com is the main com. the footage that i want to replace located in precompose HIGF_1
![Snipaste_2020-11-24_19-17-32](https://user-images.githubusercontent.com/6835841/100087743-1eadc000-2e8a-11eb-9c48-b9478e3bcdba.png)

**Comment by zhang852774731** [comment]
i found it in the doc

**Comment by joaoaugustogrobe** [comment]
@zhang852774731 could you please provide more details on your solution?
