### ISSUE TITLE
How add new project to api server?

### ISSUE THREAD

**Issue by Wzgbest** [inlife/nexrender#53]
Hello,
i have a question.How add new project to api server?

**Comment by inlife** [comment]
You can either use POST with json body, or use nexrender api from within nodejs as shown on the readme

**Comment by Wzgbest** [comment]
Thanks，
Can the motion scene made using a plug-in in AE can be rendered? How does it operate?

**Comment by inlife** [comment]
if your machine that you will be rendering at has the same plugin installed for AE, i guess it should be fine
never tested with plugins, so not sure really

**Comment by Wzgbest** [comment]
I tested it. After using plug-ins, the part of using plug-in will be lost. Of course, there is a corresponding plug-in on AE. I hope we can see why.

**Comment by Wzgbest** [comment]
The phenomenon of audio is broken and continued after rendering.Do you Know
this question?
