### ISSUE TITLE
unable to install windows version

### ISSUE THREAD

**Issue by avijit4all** [inlife/nexrender#530]
I have tried installing the application on windows 10 but it doesn't get installed. any suggestion on how to fix that. also when I download the file it says that the file can harm the computer and recommends not installing/downloading the file.

**Comment by inlife** [comment]
Hey @avijit4all,

That is not your windows per se, that is the built-in antivirus software seeing things where there are none. I would recommend adding the binary to the exclusion list and trying again.

Cheers!

**Comment by avijit4all** [comment]
Already done that, when I try to install one command prompt opens up for a brief period of time, and then nothing happens.

**Comment by inlife** [comment]
Ah, I see what the problem is. Please read the manual on the readme page more carefully. 👍 
This is not an installer, it is a ready-to-use binary with a CLI-only interface.

**Comment by avijit4all** [comment]
I tried looking for it in the manual. can you guide me on how to do it?

**Comment by inlife** [comment]
Try checking out this video as well: https://www.youtube.com/watch?v=E64dXZ_AReQ
It demonstrates a full cycle, starting from the binary download :)

**Comment by avijit4all** [comment]
Thanks! I will try that.
