### ISSUE TITLE
Every time it create a blank video.

### ISSUE THREAD

**Issue by amatyat** [inlife/nexrender#532]
Whenever I run the command it generate a blank video of 2KB. Please help.

`{
    "template": {
        "src": "file:///E:/nexRender/02-12-2020/testing/testing.aep",
        "composition": "Testing Video"
    },
    "assets": [
        {
            "src": "file:///E:/Pictures/Mobil-1-Racing-4T_10W-40_1L.png",
            "type": "image",
            "layerName": "Mobil-1-Racing-4T_10W-40_1L.png"
        }
    ],
    "actions":{
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4",
				"params": {"-vcodec": "libx264", "-r": 25}
            },
            {
                "module": "@nexrender/action-copy",
                "input": "encoded.mp4",
                "output": "E:/nexRender/myresult.mp4"
            }
        ]
    }
}`

**Comment by AtesDANIS** [comment]
yes it's same on my windows server but it works perfect on my mac. I think problem causing by encoders.
Is there anybody know that how can we solve it ?

**Comment by Thiago-Dantas** [comment]
try running with --debug flag and post output
