### ISSUE TITLE
Does nexrender supports target specified one nested compositions ?

### ISSUE THREAD

**Issue by biandh** [inlife/nexrender#533]
Here is the example minimal ae comp setting, 

maincomp > subcomp1 >  subcomp1.1 > TEXT 01
maincomp > subcomp2 > subcomp1.1 > TEXT 01
.....
maincomp > subcompN > subcomp1.1 > TEXT 01

Can i target maincomp.subcomp2.subcomp1.1 and get this specified layername of "TEXT 01" ?  how can i setting nexrender conifg json?   Looking forward to your answer ^_^

**Comment by rofthy** [comment]
had the same problem. worked out this way:
assets:
			"type":"data",
			"layerName":"layer"
			"composition“:“comp_name“
			"property":"Source Text",
			"value“:“text…“

**Comment by Thiago-Dantas** [comment]
you can either pass composition as above, or you can name your layer uniquely and nexrender will search in all compositions for the name
