### ISSUE TITLE
After effects holding onto file that can't be deleted during clean up causing error

### ISSUE THREAD

**Issue by limzykenneth** [inlife/nexrender#536]
**Describe the bug**
I'm running a render with `--reuse` to reuse the opened AE instance and a action-encode post render action. It doesn't seem to be a common occurence as I only came across it today but after the render and postrender completes, AE prevented a footage file from being deleted in the final cleanup step which caused a `EBUSY` erorr and the whole thing failed, despite actually finishing.

I have error handling code to handle general error cases which include this one which simply restarts the job, but it continues to error in the same way, making the job endless.

Another smaller and related problem is that the cleanup only removed the content of the folder containing the temporary project. 

**Information about environment**
* Which version of nexrender are you using? 1.23.0
* What kind of the setup do you have? Server and worker setup, running on the same machine, job added via nexrender-api
* Are you using pre-built binaries or globally installed npm packages? Both are imported into my script with a thin wrapper around them.
* Which kind (and version) of operating system you are running it in? Windows 10
* Any additional information that might be helpful - After Effects 2019

**Expected behavior**
I would expect the whole folder gets removed  during cleanup and in the case where it isn't able to do so, doesn't report it as an error since the render did succeed, just the cleanup isn't able to finish.

To fix this I think one thing to do is to replace the [`rmdirRecursively` function](https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/tasks/cleanup.js#L7) with [rimraf](https://www.npmjs.com/package/rimraf) which is written to do exactly what the function aims to do while also handling `EBUSY` error code elegantly. The functionality itself should probably also be asynchronous as no step after it depends on it finishing before it can continue, so it shouldn't block the execution thread.

In the case of the cleanup actually did fail or the EBUSY can't be completed even by `rimraf`, a warning can be issued instead of an error to indicate that the job did finish, just the cleanup isn't. The database entry in the server can be likewise indicate the actual status instead of showing up as an error.

**Comment by inlife** [comment]
Hey @limzykenneth 

That is actually a great suggestion. I will try to do exactly that!
