### ISSUE TITLE
Dynamic videos sequencing

### ISSUE THREAD

**Issue by ndamofli** [inlife/nexrender#54]
I am trying to create dynamic video sequences. Basically to put a number of videos one after another.
The idea is to start a video after its predecesor finishes.The videos have variable length.
I umderstand that this could be achieved with ae scripts. I tried adding some code on the assets/js file (i am using the boilerplate) but I really don’t know were to start. My js skills are good but I don’t have any experience with ae scripting api.
I named my videos: video1, video2, video3
Name of the comp: main
Any help is much appreciated.

**Comment by inlife** [comment]
Yes, please study those 2 issues
https://github.com/inlife/nexrender/issues/48
https://github.com/inlife/nexrender/issues/41
that is very similar to what you are asking

**Comment by ndamofli** [comment]
In my case, I am looking to create a single project with multiple sequenced videos. 
My question involves scripting the timeline, in such a way that I can control the time when a video strarts (moving its timeline) relatively to when the previous video ends.
Thank you so much though..

**Comment by inlife** [comment]
oh in that case, you should dig docs about after effects scripting
im not sure how, or even if, this is possible
