### ISSUE TITLE
Aerender "could not read from source" for .mov HEVC encoded video files

### ISSUE THREAD

**Issue by spenciefy** [inlife/nexrender#540]
First, thanks for the great work! I've been running Nexrender server and worker on AWS EC2 to render videos server side. 

I'm unable to render videos when trying to replace video footage layers with .mov videos that are HEVC h265 encoded (videos recorded on iPhone). It works perfectly with .mov h264 encoded files. The error I get is coming from aerender, and I'm wondering if anyone else has had similar issues: "Error: After Effects error: Could not read from source. Please check the settings and try again." I tried opening the .aep file on the machine and was able to successfully import the same HEVC .mov files in the GUI, so it seems like this is an aerender specific issue. 

I'm using After Effects CC 2020 v17.5.1 on Windows, and have tried with v17.0.4 and CC 2019 v16.1.3. I also downloaded VLC player to get the necessary codecs to open HEVC h265 videos on Windows Server 2019. 

I found a few Adobe support forums that mention similar issues, but importing HEVC h265 encoded videos should be fixed with the latest version of AE 17.5.1: 
- [https://community.adobe.com/t5/after-effects/unable-to-import-mp4-h-264-files-after-updating-to-after-effects-17-0-5/td-p/10997790?page=3](https://community.adobe.com/t5/after-effects/unable-to-import-mp4-h-264-files-after-updating-to-after-effects-17-0-5/td-p/10997790?page=3)
- [https://community.adobe.com/t5/after-effects/aerender-cannot-find-mov-files-hosted-on-the-server-windows-cc2019-amp-2020/td-p/10977993?page=1](https://community.adobe.com/t5/after-effects/aerender-cannot-find-mov-files-hosted-on-the-server-windows-cc2019-amp-2020/td-p/10977993?page=1)

Error log:
```
Using DXGI: Device: "Microsoft Basic Render Driver" has dedicated video RAM (MB): 0
 has video RAM(MB): 0
Skipping DX support: Microsoft Basic Render Driver
aerender version 17.0.4x59
Running Script: C:\Users\ADMINI~1\AppData\Local\Temp\2\nexrender\ilAgG_8DJqJbSQ5V8Xdk9\nexrender-ilAgG_8DJqJbSQ5V8Xdk9-script.jsx
aerender ERROR: Error executing script: C:\Users\ADMINI~1\AppData\Local\Temp\2\nexrender\ilAgG_8DJqJbSQ5V8Xdk9\nexrender-ilAgG_8DJqJbSQ5V8Xdk9-script.jsx
Error: After Effects error: Could not read from source. Please check the settings and try again.
aerender ERROR: Runtime error in After Effects.
aerender ERROR: After Effects can not render for aerender. Another instance of aerender, or another script, may be running; or, AE may be waiting for response from a modal dialog, or for a render to complete. Try running aerender without the -reuse flag to invoke a separate instance of After Effects
```
**Information about environment**
* Which version of nexrender are you using? nexrender-worker 1.23.0
* What kind of the setup do you have? Server + worker running on EC2 g4dn.4xlarge
* Are you using pre-built binaries or globally installed npm packages? NPM
* Which kind (and version) of operating system you are running it in? Windows Server 2019
* Any additional information that might be helpful 

**Expected behavior**
Expecting the video to import the footage properly and start rendering. 

**Screenshots**

**Comment by spenciefy** [comment]
Windows has trouble supporting HEVC H265 codecs, and while Windows 10 has a HEVC codec plugin available on the store, Windows Server 2019 doesn't support it. My solution was to transcode the asset video into mp4 in prerender.

**Comment by inlife** [comment]
Glad you got it resolved! 😄 🎉
