### ISSUE TITLE
Priority attributes for Jobs within the Nexrender-Server Queue  

### ISSUE THREAD

**Issue by rofthy** [inlife/nexrender#541]
It would be nice to be able to assign attributes of priority to each job (template) .

Example:
render priority : hight
render priority : middle
render priority : low

Nexrender Server might be able to prefer jobs with a higher priority status in the queue.

**Comment by inlife** [comment]
Thinking out loud: seems like nexrender server side has more and more queue-related requests. I wonder if that is a sing to rather choose a more reliable and tested queue-handling library for the internals.

Regarding your proposition, it is something I will definitely keep in mind! 👍

**Comment by andyglez96** [comment]
hello @inlife is this already implemented?

**Comment by inlife** [comment]
@andyglez96 it is not
