### ISSUE TITLE
aerender error

### ISSUE THREAD

**Issue by zhang852774731** [inlife/nexrender#542]
hi guys, have you ever got this error?

aerender ERROR: After Effects can not render for aerender. Another instance of aerender, or another script, may be running; or, AE may be waiting for response from a modal dialog, or for a render to complete. Try running aerender without the -reuse flag to invoke a separate instance of After Effects

**Comment by spenciefy** [comment]
From the discord:

![image](https://user-images.githubusercontent.com/3144112/103060595-8cb6d700-455d-11eb-8435-545ae0c403d9.png)

**Comment by Thiago-Dantas** [comment]
Are you running scripts and you have script menu calls in that script?
I've found that error happens in those calls

**Comment by zhang852774731** [comment]
i don't running scripts
