### ISSUE TITLE
is there any way to modify the duration of a composition with nexrender?

### ISSUE THREAD

**Issue by crisdeb** [inlife/nexrender#543]
is there any way to modify the duration of a composition with nexrender?

I've tried '_frameStart_' and '_frameEnd_' and they work correctly, but I have to intervene in the **middle**, since the duration of the composition is variable (it depends on the audio duration of the speaker that can be different) and the intro and ending are different from the body of the movie that can and must be shortened or lengthened.

**Comment by inlife** [comment]
Not sure, this question was raised multiple times tho, maybe someone already figured out a way to do that via scripting!

**Comment by JeanSassi** [comment]
@crisdeb @brassel 

#190 #199 

are you talking about the same subject?

I don't know how to apply the solution, could you instruct me more clearly?

**Comment by brassel** [comment]
Hi @JeanSassi, 

yes those tickets are somewhat related but more general. The nexrender extension we did there is a prerequisite to change anything which is not a ["AfterEffects Property"](https://ae-scripting.docsforadobe.dev/properties/property/). And this includes the change of durations. Thanks to that extension you can now set values for, e.g.,  [workAreaDuration](https://ae-scripting.docsforadobe.dev/items/compitem/?highlight=composition#compitem-workareaduration) of a composition. This might be what you need.

**Comment by JeanSassi** [comment]
Hi @brassel ,

excellent. I apologize in advance.

But how can I change these properties.

I didn't find anything in the documentation.
And some examples that I saw related to this seem to be a javascript code.

How to implement such a property using JSON?

Can you just give me an example or a link to study?

**Comment by brassel** [comment]
Hi @JeanSassi,

sorry for the late answer!
I am not an AfterEffects wizard myself, but I dug into the kind of manipulation which we have done in that direction.
Here is an example which sets the duration of the layer to correspond to the video we have exchanged via nexrender.

```javascript
{
  'composition': 'videos',
  'type': 'data',
  'layerName': 'Video1',
  'property': 'outPoint',
  'value': 'layer.source.duration',
}
```

The first step is to find out the relevant javascript attributes, e.g., on the page I linked in the last post. These include `inPoint`,  `outPoint`, `workingAreaDuration` and some more. If you know what you want manipulating the attributes is straight forward as above. But there are many pitfalls with regard to this, for example regarding frames vs. seconds. So, if you are looking for professional support with dynamic video content like this you could contact me directly.

**Comment by JeanSassi** [comment]
@brassel 
What is your email? thanks.

**Comment by brassel** [comment]
@JeanSassi I have updated my profile with my email and I have also added a link to our website. 
Here is the [section about dynamic content creation](https://www.recordbay.de/content-creation-hub) like videos, if you are interested. 

@inlife, if you would rather not have this kind of commercial comments in your repository, just let me know and I will delete it.

**Comment by JeanSassi** [comment]
@brassel I emailed you yesterday and also sent msg on instagram.

thx

**Comment by brassel** [comment]
Hi @JeanSassi, 

good that you were able to create your project with nexrender successfully!
After that you are now an expert of "composition and layer stitching" with nexrender and AE, right? :o)
Maybe you could answer this question here:

**Comment by brassel** [comment]
The "data" object is supposed to be one of the "assets".

**Comment by ish2015** [comment]
Hi @brassel thank you for your reply. Yeah it runs when i put it in under assets. But its not changing the comp time. its the same work area that rendered. I just added 10secs music clip for check, but its rendering the whole comp length in the template. 

 "assets": [
          {
              "src": "file:///z:/dance/Footage/background.jpg",
              "type": "image",
              "layerName": "background"
          },
          {
            "src": "file:///z:/dance/Footage/song.wav",
            "type": "audio",
            "layerName": "song"
          },
          {
			"composition": "dance",
			"type": "data",
			"layerName": "song",
			"property": "outPoint",
			"expression": "layer.source.duration"
		}
          	
Here's the script. could you tell me anyway to fix this?

**Comment by ish2015** [comment]
Hi @brassel sorry for the pinging you again, i was trying this all weekend. but still got no luck. could you let me know if its possible to set the comp to the selected layer duration.

**Comment by brassel** [comment]
Hi @ish2015,
I have had a look at your problem description, but, unfortunately, I do not have enough knowledge of AfterEffects itself to make something out of your problem description. What I helped you setting is the outpoint of the layer "song" such that it matches its source duration. Is this not happening? 
To check, maybe compare the description of outpoint here:
https://ae-scripting.docsforadobe.dev/layers/layer/?highlight=outpoint#layer-outpoint
Is the layer "song" the same that you have changed the src of? It is not easy to see, since the name of the composition is not given there.

> But its not changing the comp time. its the same work area that rendered.

So, maybe you also want to change the workAreaDuration?
https://ae-scripting.docsforadobe.dev/items/compitem/?highlight=workareaduration#compitem-workareaduration

**Comment by ish2015** [comment]
Hi @brassel Thank you again for the quick reply. 

> Is the layer "song" the same that you have changed the src of? It is not easy to see, since the name of the composition is not given there.

Its not quite clear for me what you've meant here. Should i put the whole script? 

And this is quite great

> So, maybe you also want to change the workAreaDuration?

If we can change the work area duration thats it, dont need to change the comp duration if we can change the work area with the "song" layer. 

can we change it like this

```
{
"composition": "dance",
"type": "data",
"layerName": "song",
"property": "workAreaDuration",
"expression": "layer.source.duration"
}
```

And im so sorry for bothering you like this. Im a video editor by profession but trying hard to understand coding stuffs.

**Comment by brassel** [comment]
> And im so sorry for bothering you like this. Im a video editor by profession but trying hard to understand coding stuffs.

No, problem, I would also like to help better. But you know how it is - like shouting from different shores of a river.
But I have asked our video editor to help and he was so kind as to make a tiny project for testing.
It seems what you need is this:
   ```
{
      "type": "data",
      "composition": "dance",
      "property": "containingComp.workAreaDuration",
      "layerName": "song",
      "expression": "layer.source.duration"
    }
```

Hope, this helps!

**Comment by ish2015** [comment]
Hi @brassel Thank you so much! will check this early tomorrow and will keep you posted! Thank you again for the support <3

**Comment by piscespieces** [comment]
I have followed this issue for couple days now and even though I get the render output, it doesn't modify the duration of the output video

```
{
  "template": {
      "src": "file:///Users/andresu/Desktop/songtest.aep",
      "composition": "Comp 1"
  },
  "assets": [
      {
          "type": "audio",
          "src": "file:///Users/andresu/Desktop/scalertest.mp3",
          "composition": "songprecomp",
          "layerName": "song",
          "property": "containingComp.workAreaDuration",
          "expression": "layer.source.duration"
      }
  ],
  "actions": {
      "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "encoded.mp4",
                "output": "/Users/andresu/Desktop/myresult.mp4"
            }
        ]
    }
}
```

@brassel

I would appreciate if you guys can point me in the right direction here

**Comment by brassel** [comment]
@piscespieces from what I see this looks correct. Are you at liberty to share your AE project and the `scalertest.mp3`? 
I cannot promise anything but maybe we can see what is the problem if the project is not too complicated.
(Simplifying to isolate the problem might also help both you and me, if it really is complicated...)
