### ISSUE TITLE
Couldn't find a result file

### ISSUE THREAD

**Issue by benwoodward** [inlife/nexrender#545]
I think this is maybe different to https://github.com/inlife/nexrender/issues/318 and https://github.com/inlife/nexrender/issues/342. There is actually a rendered file in the working directory, however, it's `result.mov` _not_ `result.avi`. Do I have a configuration issue, or is this a bug? 

```
> job rendering failed
Error: Couldn't find a result file: C:\Users\PAPERS~1\AppData\Local\Temp\nexrender\rSagb2UTCxjPjwg40KJrd\result.avi
    at ChildProcess.<anonymous> (C:\Users\Paperspace\scoop\persist\nodejs\bin\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\render.js:171:31)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
```

**Comment by phileastv** [comment]
Maybe you should try to add `"outputExt": 'mov',` in your json task, so Nexrender knows you're endoding a `.mov` file.

**Comment by Mindeliu** [comment]
Check if "composition" in .json matches your actual composition name in your project

**Comment by Gidde-Abhishek** [comment]
The issue is still there I am still getting the same error, though I worked around it by manually copying the .avi file from the location mentioned in the command line output, and then convert it to the desired format.

**Comment by inlife** [comment]
Could you provide the job definition you are using for this job?
