### ISSUE TITLE
Retrieve/resume job in Nexrender API

### ISSUE THREAD

**Issue by limzykenneth** [inlife/nexrender#549]
**Is your feature request related to a problem? Please describe.**
I have a nexrender-server instance running and an app using nexrender-api to add new jobs and keep track of current running jobs. One thing that I couldn't do now is restart the nexrender-api app while a render is ongoing because if I do so I will lose track of all currently running jobs and the associated event emitter that is returned from `addJob()`

**Describe the solution you'd like**
I've added a new function that is exported from [nexrender-api](https://github.com/inlife/nexrender/blob/master/packages/nexrender-api/src/job.js) that I'm calling `resumeJob()` that accepts an ID, then using the `withEventEmitter()` helper already there and making a request to the server's `GET /api/v1/jobs/:uid` route. It seems to work perfectly with no obvious problem that I see.

I'm happy to file a PR for this, just need to know what the best name for the exported function would be, `resumeJob` is just what I'm using it for so maybe there's a generic name like `retrieveJob` or something else that would be more appropriate.

**Comment by inlife** [comment]
Hey @limzykenneth 

This feature sounds very cool! Also, the name `resumeJob` seems fine as well. An alternative that crossed my mind was `continueJob`, however, it's a bit longer and hence probably not as nice as the former one. 

Looking forward to the PR! 👍 

Cheers!
