### ISSUE TITLE
Usage (Render network + node.js API wrapper)

### ISSUE THREAD

**Issue by Shivvyyy** [inlife/nexrender#55]
Can u please provide boilerplate of Usage (Render network + node.js API wrapper) also, like you provided for the single machine rendering or just please provide simple guide to implement this...

**Comment by inlife** [comment]
Yes, its quite simple actually
read this article to understand how to setup a network
https://medium.com/@inlife/guide-to-after-effects-automation-and-personalization-6039e9fa10d1

and then just use the api from your own project like shown there:
https://github.com/inlife/nexrender#usage-render-network--nodejs-api-wrapper

**Comment by Shivvyyy** [comment]
I request you to please tell me the process that you were about to explain in second part of your medium.com  article guide...https://medium.com/@inlife/guide-to-after-effects-automation-and-personalization-6039e9fa10d1...this would save my day.

**Comment by inlife** [comment]
Here is also a link to an example project
https://github.com/inlife/nexrender-boilerplate

If you combine everything together, you will definitely get what you need

**Comment by Shivvyyy** [comment]
I was able to make use of this API and get my work done on a single system but rendering on the multi-computer network is making trouble for me, I am little puzzled can you plz help me out with a proper guide to follow(My kind request). At least help me to make use of  (API (Render network + node.js API wrapper).
