### ISSUE TITLE
Return aerender from core render task

### ISSUE THREAD

**Issue by hdngr** [inlife/nexrender#550]
**Is your feature request related to a problem? Please describe.**
When developing new AE Templates and working on a local machine (Mac OS, AE 17.6) aerender does not exit.

**Describe the solution you'd like**
Return [`instance`](https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/tasks/render.js#L126) of spawned render process calling function so that instance can be message, extra event listeners can be attached, etc.

My use case is pretty simple, just want to force AE Render to shut down in some cases if render progress is 100%.

**Comment by inlife** [comment]
That is actually a great suggestion! Pushed as a commit 379d0f6
Will be included in the next release. 👍
