### ISSUE TITLE
similar template, same layers, same nexrender job, but error "Can't find a property sequence"

### ISSUE THREAD

**Issue by Fr4nZ82** [inlife/nexrender#552]
Please help me with this... i've some aep projects that uses same mechanism to change duration of each photo of a slide show based on the number of the photos... I used a Cursor to specify how mutch photos there are and expressions to change slide duration. This works for some aep files but fail in rendering step with others.

the error is "Error: nexrender: Can't find a property sequence numerofoto.Cursore for key: numerofoto"
note that this error is only for the "numerofoto" effect but not for colors effects that works the same way

NEXRENDER JOB that actually works:
```
NEXREDNER JOB: {
  type: 'default',
  template: {
    src: 'http://192.168.1.1:3000/aep/8f9da8383e45ceed84fa7abf7bc3ab7e08bfcca8',
    composition: 'immobiliare_o_bronze1#1'
  },
  assets: [
    {
      type: 'data',
      layerName: 'Control',
      property: 'Effetti.SFONDO.Colore',
      value: [Array]
    },
    {
      type: 'data',
      layerName: 'Control',
      property: 'Effetti.GRAFICA.Colore',
      value: [Array]
    },
    {
      type: 'data',
      layerName: 'Control',
      property: 'Effetti.TESTO 1.Colore',
      value: [Array]
    },
    {
      type: 'data',
      layerName: 'Control',
      property: 'Effetti.TESTO 2.Colore',
      value: [Array]
    },
    {
      type: 'data',
      layerName: 'Control',
      property: 'Effetti.numerofoto.Cursore',
      value: 5
    },
    {
      src: 'http://192.168.1.1:3000/aepAssets/immobiliare/immobiliare_o_bronze1/logo1.png',
      type: 'image',
      layerName: '@_logo'
    },
...
```
NEXRENDER JOB that actually fail:
```
NEXREDNER JOB: {
  type: 'default',
  template: {
    src: 'http://192.168.1.1:3000/aep/c4b2505162d7584fc471b793322cb99d56f0ec57',
    composition: 'ristoro_o_bronze1#1'
  },
  assets: [
    {
      type: 'data',
      layerName: 'Control',
      property: 'Effetti.GESSO.Colore',
      value: [Array]
    },
    {
      type: 'data',
      layerName: 'Control',
      property: 'Effetti.MENU.Colore',
      value: [Array]
    },
    {
      type: 'data',
      layerName: 'Control',
      property: 'Effetti.SOTTOTITOLI.Colore',
      value: [Array]
    },
    {
      type: 'data',
      layerName: 'Control',
      property: 'Effetti.numerofoto.Cursore',
      value: 4
    },
    {
      src: 'http://192.168.1.1:3000/aepAssets/ristorazione/ristoro_o_bronze1/Blackboard.jpg',
      type: 'image',
      layerName: 'Blackboard.jpg'
    },
...
```

error:
```
Running Script: C:\progetti\mydisplay-worker\temp\ZMAwTrIlr0D4yLcxC79bR\nexrender-ZMAwTrIlr0D4yLcxC79bR-script.jsx
aerender ERROR: Error executing script: C:\progetti\mydisplay-worker\temp\ZMAwTrIlr0D4yLcxC79bR\nexrender-ZMAwTrIlr0D4yLcxC79bR-script.jsx
Error: nexrender: Can't find a property sequence numerofoto.Cursore for key: numerofoto
aerender ERROR: Runtime error in After Effects.
```

pls tell me how to share aep files, i prefer to not share here aep projects

I tryed to log what happen inside nexrender.jsx script, but i've not found a way to log composition layers names and property sequences that the script effectively read from the aep.

**Comment by Fr4nZ82** [comment]
![image](https://user-images.githubusercontent.com/35651871/105352889-cfb4aa80-5bee-11eb-9d49-6e7db8f00151.png)
![image](https://user-images.githubusercontent.com/35651871/105353023-01c60c80-5bef-11eb-9aa6-78ab1fadb2c7.png)

**Comment by inlife** [comment]
My only idea/suggestion, for now, would be to try to debug the generated script within AE Extend Script toolkit to see what is actually happening with the instructions. Seems like it can't match something that it should, but not really understand why.

**Comment by crisdeb** [comment]
Hi I also need to make something similar.
If you want to send me an aep file, I can make some tests and see if I can do it.
oh i forgot, i'm italian too

**Comment by Fr4nZ82** [comment]
Ciao, ho trovato il problema finalmente... In pratica se il tipo di asset è
'data' allora bisogna specificare la composizione, altrimenti va a cercare
il nome livello su tutte le composizioni, e qui stava la differenza: alcuni
template avevano lo stesso lvl su tutte le comp e quindi non davano errore
e funzionavano... Inoltre lo stesso discorso non vale per gli assets di
tipo text e image.
Grazie comunque

Il gio 18 mar 2021, 12:43 crisdeb ***@***.***> ha scritto:

**Comment by crisdeb** [comment]
perfect
