### ISSUE TITLE
nexrender worker Heap memory allocationo failure on Windows

### ISSUE THREAD

**Issue by benjioh5** [inlife/nexrender#554]
**Describe the bug**
```

<--- Last few GCs --->

[7524:000001DDFD774B90]   565606 ms: Mark-sweep 31.3 (32.7) -> 30.6 (32.7) MB, 7.5 / 0.0 ms  (average mu = 1.000, current mu = 1.000) low memory notification GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory
 1: 00007FF60940968F
 2: 00007FF609383E66
 3: 00007FF609384DF6
 4: 00007FF609F0683E
 5: 00007FF609EE8281
 6: 00007FF609D3242C
 7: 00007FF609D3CDA1
 8: 00007FF609D2E383
 9: 00007FF609D2D584
10: 00007FF609EF99CF
11: 00007FF60942A358
12: 00007FF6092B165D
13: 00007FF6092AA0BC
14: 00007FF60944CBF3
15: 00007FF60946795C
16: 00007FF609467D54
17: 00007FF609336BC3
18: 00007FF6093B9A03
19: 00007FF6091C2671
20: 00007FF60A665C0C
21: 00007FFA5BB37974
22: 00007FFA5C6DA0B1
```

- Render video greater than 25GB.
- Render layers with more than 20 images.
- Then boom

**Information about environment**
* Which version of nexrender are you using? 1.26.0
* What kind of the setup do you have? (server+worker or cli) Server + Worker
* Are you using pre-built binaries or globally installed npm packages? npm & pre-build binaries
* Which kind (and version) of operating system you are running it in? Windows server 2019
* Any additional information that might be helpful.

**Expected behavior**
Just work well

**Screenshots**

**Comment by inlife** [comment]
Not sure I follow which part is responsible for the out-of-memory exception, since most of the heavy-work related to rendering happens on the aerender side. Is it a server or worker memory exception? It might be related to logging or the way the data is passed within nexrender. Is it data protocol based inject?

**Comment by Nazaroni** [comment]
I had the same error yesterday, my specs:

- render video ~13-15 min (120-150 GB)
- ~1500-2000 vector layers in general in the project
- Windows Server 2019
- Nexrender version: 1.19.2
- After Effects CC 2020 17.5

To fix this issue I have to change the configuration of the instance from 32 to 64 GB (RAM)... But this is not the solution... it's more trick to avoid the error... If I'll add a few scenes to the project - I should increase the RAM again to 128 GB and so on... :D
