### ISSUE TITLE
Multi-MachineRendering.

### ISSUE THREAD

**Issue by Shivvyyy** [inlife/nexrender#56]
I have successfully made it possible to render via multiple nodes and get the rendered files back to the api server but I need the IP of a particular render-node through which the particular frames has been rendered, so that I can fetch files from that node using that node IP. Is it possible to get that node IP on render finish?

**Comment by inlife** [comment]
Hey
It's a good question actually. Currently nexrender doesn't save the IPs of the render nodes.
Seems like the only way to get IP i see is possible, is slightly modify the code, so it would insert the IP of the machine that was rendering inside the project document.

**Comment by Shivvyyy** [comment]
Ok... then how to move files from render nodes to API server....As you suggested rsync for that in one of the network rend. issues  but it is not working on windows so Is there any other npm module to send file to api server after rendering get finished.

**Comment by Shivvyyy** [comment]
???? or atleast tell me any node js npm package which will help to move the rendered file to  api server ...and which will work fine on windows....or just help in getting ip address of rendering node on project finish

**Comment by Shivvyyy** [comment]
?????

**Comment by inlife** [comment]
you could try to split the original project onto few subprojects using startframe and endframe options for aerender and start them simultaneously

**Comment by Abukodonosor** [comment]
Tnx ... i have 1 more question

I start:
1st. nexrender --api-server --port =3000 
2nd. node api_call.js
3th. nexrender --renderer --host=localhost:3000 --aerender="C:\\bla bla"

Is thet right way ... because i think , i 1st need to start 1st. then 3th ... and after i need to run 2nd. multiple times ... but that dosenot work..

i have next issue is then i start nexrender api and after i start nexrender --renderer ...  he throw me error: request faild or no suitable project  find ... retrieing in 900000ms

**Comment by inlife** [comment]
i see that you are working mostly on localhost, maybe you would rather use simpler approach in that case?
https://github.com/inlife/nexrender-boilerplate

**Comment by Abukodonosor** [comment]
i am on widows virtual machine ..
i need to make sistem to send multiple AE templates .. on api server .. to cluster them ..(to make multi render farm, to speed up rendering proces) .. for that i use widows server R2012 ..

**Comment by Abukodonosor** [comment]
Can you specify me a steps which i need to follow to set up multi  multi project render enviroment?

I find in documentation those steps.
1st run nexrender --api-server --port ....

after i need to specify do i need to run nexrender --renderer or .. i need to make api_call ?
For me seems logic to call nexrenderer --reneder 1st .. and when i set this render node .. after i need to make api_call to send data to server and after he save it in temp file .. and nexrender need to start rendering ? Am i right?

I really need help .. i am trying to get it .. when i get it i will give my best to boost this lib XD

**Comment by Abukodonosor** [comment]
inlife ? are you there m8?

**Comment by inlife** [comment]
https://github.com/inlife/nexrender/wiki/Rendering-node
https://github.com/inlife/nexrender/wiki/API-server
https://github.com/inlife/nexrender/wiki/Project-model

**Comment by Abukodonosor** [comment]
OK i will put more focuse on studeing documentation .. after i will contact you ... tnx alot

**Comment by Abukodonosor** [comment]
Hi .. i studi it a bit .. and i understend how it works. XD

I have 2 questions for you.

-1st is how to run nexrender --renderer for specific project ? 
- 2nd is  "startframe and endframe options for aerender and start them simultaneously", i dont understend when i run mini subprojects whic chain start/end frame ... how to merge( fuse them)?

Can you provide me help for it ? Tnx alott :3333

**Comment by inlife** [comment]
>1st is how to run nexrender --renderer for specific project

there is no ability to do this right now, at least with the original renderer
you could try to write your own, using nexrender api, and renderer itself like has been demostrated in the issues

> 2nd is "startframe and endframe options for aerender and start them simultaneously", i dont understend when i run mini subprojects whic chain start/end frame ... how to merge( fuse them)?

there is no automatic way to merge them after, however you could use ffmpeg or something like that to do it, after both parts finished rendering
