### ISSUE TITLE
sometimes job rendering failed

### ISSUE THREAD

**Issue by fallcool** [inlife/nexrender#562]
sometimes when  i ran the nexrender-cli command, it gave error:"> job rendering failed Error: Couldn't find a result file:...". But if I ran the same command  again, no error. Anything I can do to help with this situation?

I am using Mac 10.14.6,  AE 2020 and nexrender-cli 1.26.1

**Comment by inlife** [comment]
Seems like aerender process exists before the actual rendering finishes, hence the error message. We don't have a clear solution for that yet, unfortunately :(

**Comment by rohanantao** [comment]
I seem to have a similar issue:
Running Script: /tmp/nexrender/hRUTCvNl6w83FK7Ml2OVP/nexrender-hRUTCvNl6w83FK7Ml2OVP-script.jsx
aerender ERROR: Error executing script: /tmp/nexrender/hRUTCvNl6w83FK7Ml2OVP/nexrender-hRUTCvNl6w83FK7Ml2OVP-script.jsx
Error: After Effects error: The source compression type is not supported.
aerender ERROR: Runtime error in After Effects.
aerender version 16.1.3x5
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched

> job rendering failed
Error: Couldn't find a result file: /tmp/nexrender/hRUTCvNl6w83FK7Ml2OVP/result.mp4
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@nexrender/cli/node_modules/@nexrender/core/src/tasks/render.js:174:31)

**Comment by inlife** [comment]
@rohanantao in your case you can see there is an error:
`Error: After Effects error: The source compression type is not supported.`

Try to fix that on inside of your project composition settings or something similar to that.

**Comment by rohanantao** [comment]
Hi there,

Thanks so much for that. I had two versions of after effects installed.
Removed one and updated the other to the latest version. That seemed to do
the trick.

With regards to the other issue, it related more to Mac permissions in the
/private/tmp folder. Updated the permissions with euro chmod -R 1777
/private/tmp and restarted.

Then using nexrender-cli —file main.json had it up and running to render it
successfully.

Step 1 done. Now into trying to figure out how to create batch processes
like templater pro. Not much documentation out there.

**Comment by inlife** [comment]
Hey @rohanantao 

Could you elaborate a bit more on what do you mean by batch processes?

**Comment by rohanantao** [comment]
Hi,

I've successfully rendered one video job with a single main.json file. Now, I've got data for multiple video jobs that need to be created using the same template. Just wondering what I need to do to set up a queue of jobs and render them.

**Comment by inlife** [comment]
To manage queues of jobs, you would probably need to use nexrender-server as well as nexrender-worker together.

**Comment by Ro-Ant** [comment]
Yup. Thats what I thought. Having a little difficulty setting it up. Would you know of any nexrender paid experts, you would recommend who'd be willing to help me with the network server and worker set up?

**Comment by shanicy** [comment]
Hi @inlife ,
Is there any news regarding aerender process exists before the actual rendering finishes?
It seems to happen in AE2020 and AE2021.
