### ISSUE TITLE
How To Trim A Composition

### ISSUE THREAD

**Issue by ilhamzacky** [inlife/nexrender#564]
Describe your question, attach logs, images or anything that might help to better understand it.
hi all, 
need a small help - I am rendering multiple videos - each video come with a different length -

I need to end up my composition by the end of the video

this is the JSON I am using 

```
{
  "type": "data",
  "layerName": "Part 3 (Video Message)",
  "property": "outPoint",
  "value": "13"
}
   
   ```
   
   it works fine but if the composition is set to 20 sec and if I pass a value of 13 sec it stops but in the remaining 7 sec it returns a black display - 
   
 Is there any way to stop the composition when the video is over ??
 
 Thank you

**Comment by rofthy** [comment]
"template":{
		"src":"String",
		"composition":"String",
		"frameStart":"Number",
		**"frameEnd":"Number",**
		....
frameStart and frameEnd determines the duration of composition

**Comment by ilhamzacky** [comment]
@rofthy thanks for your replay

It didn't work, return a 1-sec video

this is how I sent 

```
  "template": {
                     "src": "file:///C:/Users/Ilham/Documents/pro8/test/latest.aet",
                        "composition": "Post-Roll",
                           "frameStart": "2",
                        "frameEnd": "8"
                },
```

Also, one more thing, on this method is it possible to send multiple composition ??

Because I have a main composition  , inside it there are sub compositions - 

I need to send the "frameStart" "frameEnd" value to them ..

Thank you
