### ISSUE TITLE
Render worker stop on error despite not passed flag

### ISSUE THREAD

**Issue by limzykenneth** [inlife/nexrender#566]
**Describe the bug**
This only happens on very specific but not rare situation. I'm using nexrender-worker without the stop on error flag which means I expect the worker to keep running even when it come across an error. The problem is if the server the worker is polling is down while the worker finish rendering it will throw and stops.

It stems from [this line](https://github.com/inlife/nexrender/blob/master/packages/nexrender-worker/src/index.js#L88) in the `catch` block that is supposed to tell the server that the job has failed but since the scenario is that the server is down, it cannot do that which caused a uncaught rejected promise in the catch block and will halt the worker regardless.

**Information about environment**
* Which version of nexrender are you using? 1.23.0
* What kind of the setup do you have? server+worker
* Are you using pre-built binaries or globally installed npm packages? Locally installed npm packages, used programmatically
* Which kind (and version) of operating system you are running it in? macOS Big Sur
* Any additional information that might be helpful

**Expected behavior**
The worker should keep running despite the error unless passed the stop on error flag. The job won't be updated to have errored which may be a problem but in my case I have other logic to handle this to it's not a problem for me.

I can submit a PR that catches if the offending line failed if this fix is desired.

**Comment by inlife** [comment]
Great find @limzykenneth !
Seems like you are right, it attempts to send a request to the remote and fails.

How do you think, will removing `await` help? Or should we also add a `.catch(() => {})` with empty handler to make sure it wont trigger an exception?

A PR with a fix from your side would be greatly appreciated!

**Comment by limzykenneth** [comment]
Since it's only that one line that is expected to fail, for my fix I've added `.catch(() => {})` but for the handler I repeated the `if (settings.stopOnError) {` block to still stop on error if desired and provide error message otherwise. It's a bit redundant but I can't think of an elegant solution just yet.

If that's fine with you I'll put together a PR.

**Comment by inlife** [comment]
Oh, yeah, that additional condition inside that you've mentioned indeed makes sense. Did not think about such a case 👍 

> If that's fine with you I'll put together a PR.

Sure, that sounds amazing! Thank you!
