### ISSUE TITLE
Help me solve the problem

### ISSUE THREAD

**Issue by Butterf1ykisses** [inlife/nexrender#567]
Describe your question, attach logs, images or anything that might help to better understand it.
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'pkg-worker'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prepkg-worker', 'pkg-worker', 'postpkg-worker' ]
5 info lifecycle nexrender@1.0.0~prepkg-worker: nexrender@1.0.0
6 info lifecycle nexrender@1.0.0~pkg-worker: nexrender@1.0.0
7 verbose lifecycle nexrender@1.0.0~pkg-worker: unsafe-perm in lifecycle true
8 verbose lifecycle nexrender@1.0.0~pkg-worker: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\projectBackups\nexrender\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;dejs\;E:\下载的软件\git\Git\cmd;C:\Program Files\nodejs\node_modules;C:\Users\ttkshen\AppData\Roaming\npm;C:\Program Files\nodejs\;E:\下载的软件\tortoiseGit\bin;C:\nodejs\node_global;E:\下载的软件\VsCode\Microsoft VS Code\bin;C:\nodejs\node_global;C:\Program Files\nodejs\node_global
9 verbose lifecycle nexrender@1.0.0~pkg-worker: CWD: E:\projectBackups\nexrender
10 silly lifecycle nexrender@1.0.0~pkg-worker: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'cross-env NEXRENDER_REQUIRE_PLUGINS=1 pkg packages/nexrender-worker/package.json --out-path bin/'
10 silly lifecycle ]
11 silly lifecycle nexrender@1.0.0~pkg-worker: Returned: code: 1  signal: null
12 info lifecycle nexrender@1.0.0~pkg-worker: Failed to exec pkg-worker script
13 verbose stack Error: nexrender@1.0.0 pkg-worker: `cross-env NEXRENDER_REQUIRE_PLUGINS=1 pkg packages/nexrender-worker/package.json --out-path bin/`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid nexrender@1.0.0
15 verbose cwd E:\projectBackups\nexrender
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "pkg-worker"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error nexrender@1.0.0 pkg-worker: `cross-env NEXRENDER_REQUIRE_PLUGINS=1 pkg packages/nexrender-worker/package.json --out-path bin/`
22 error Exit status 1
23 error Failed at the nexrender@1.0.0 pkg-worker script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by inlife** [comment]
Could you elaborate on the problem? This log does not seem to tell me anything :(
