### ISSUE TITLE
how to run multiple jobs with one json file?

### ISSUE THREAD

**Issue by crisdeb** [inlife/nexrender#571]
I have to make a lot of video clips and I would like to optimize the time since a lot of time passes before After Effect initializes.

I've done some tests but they all give an error, I tried this one below but it only renders one video.

```
// myjob.json
{
    "template": {
        "src": "http://example.com/assets/**myproject_A.aep**",
        "composition": "main"
    },
    "assets": [
        {
            "src": "http://example.com/assets/myimage.png",
            "type": "image",
            "layerName": "background.png"
        }
    ],
    "actions":{
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "encoded.mp4",
                "output": "d:/mydocuments/results/**myresult_A.mp4**"
            }
        ]
    }
}
,
{
    "template": {
        "src": "http://example.com/assets/myproject_B.aep",
        "composition": "main"
    },
    "assets": [
        {
            "src": "http://example.com/assets/myimage.png",
            "type": "image",
            "layerName": "background.png"
        }
    ],
    "actions":{
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "encoded.mp4",
                "output": "d:/mydocuments/results/myresult_B.mp4"
            }
        ]
    }
}
```

How do I run multiple renders with one project?

**Comment by inlife** [comment]
You can speedup the proccess in 2 ways: 
* Run rendering in parallel starting multiple workers/cli 
* Or run AE before starting the render and provide the --reuse flag to tell nexrender to prefer existing running instance of AE

**Comment by crisdeb** [comment]
Thanks, I will try  **--reuse**

**Comment by Lkzeichner22** [comment]
Thank you very much for this amazing work @inlife !
It made my life a lot easier.

I am stuck on the same question as described by @crisdeb above tho.

When I put two jobs in one .json file, it only renders one video. I am unsure how this was solved?

Thank you for your time.

**Comment by inlife** [comment]
@Lkzeichner22 that is the expected behavior
single job = single run = single result video

if you need more videos, you would need to run it multiple times!
