### ISSUE TITLE
Repeat N times the same composition creating a single rendering

### ISSUE THREAD

**Issue by crisdeb** [inlife/nexrender#572]
I have a composition with text that changes each time creating a 'scene', each scene must be repeated N times updating the text (_example: **[strawberry],[apple],[lemon],[kiwi],...**_).

It is clear to me how to edit the text each time with the correct value:

```
{
  "type": "data",
  "layerName": "my text field",
  "property": "Source Text",
   "value": "strawberry"
},
```

But how do I **render the composition N times creating a single video file**?

Is there a way to do this with one job, or do you have to create each clip individually and merge everything together at the end?

**Comment by inlife** [comment]
Sounds to me like indeed a job that you would need to run N times providing different job definitions. And after those are rendered there can be an additional code from your side to merge all together via ffmpeg for example.

**Comment by crisdeb** [comment]
In fact, that's what I already do.
I was hoping there was a way to just use nexrender.
Thanks anyway

**Comment by sundayALLDAYa** [comment]
I've been doing this. but it keeps redownloading ffmpeg every time. after i do it 10 times that is 700 mb and 100 times 7 gigs. anyway for it to not have to keep downloading it
