### ISSUE TITLE
change resource already in the project

### ISSUE THREAD

**Issue by crisdeb** [inlife/nexrender#573]
How do I change a resource which is already present in the after effect project with another one?

I have a main composition '**MAIN**', where inside is present in a layer another composition "**TITLE_A**".

I want to exchange it with another composition "**TITLE_B**" but there is no external resource to call with '_src_' I just have to change the name of the composition

`"assets": [  { "composition": "TITLE_A" } ]`

How do you do it?
Thanks

**Comment by inlife** [comment]
Hey @crisdeb 

I don't think it is something that is possible with a pure nexrender job definition. Seems to me that for something like this you would need to write a custom jsx script.

Cheers!

**Comment by crisdeb** [comment]
Here is the solution to insert in a custom script jsx

```
var proj = app.project ; 
var newSource = proj.item(1); //  composition to be replaced [(1) is the index]
comp.layer(1).replaceSource(newSource, true); // replacement of internal resource
```
it would be nice to see it implemented in a module
