### ISSUE TITLE
Can I connect nexrender to a type form?

### ISSUE THREAD

**Issue by ReneVanV** [inlife/nexrender#576]
First of all, awesome tool Nexrender!!

I am working on a school project and I want to connect nexrender to a typeform/excel sheet. I want that if my excel sheet updates that my ae automatically renders. I saw this feature in a plugin called template for ae, but ofc that is way to expensive for a school project. Is this possible in nexrender?

**Comment by inlife** [comment]
Hey @ReneVanV 

That is something that is technically possible, but not yet implemented. If you would like to add a feature like this - that would be great!

Cheers!
