### ISSUE TITLE
Very long wait time from when it starts "rendering job..." to when it actually starts rendering

### ISSUE THREAD

**Issue by crisdeb** [inlife/nexrender#581]
Hi, I have a project that takes so much time when started.

Since it appears:

`[YKbQbiFgb_xkW3QxZC4OU] render job...`

To when it actually starts rendering:
```
[YKbQbiFgb_xkW3QxZC4OU] frame= 38 fps=0.0 q=0.0 size= 0kB time=00:00:00.00 bitrate=N/A speed= 0x
...
```

Almost **two minutes of waiting** time pass before the rendering actually starts.

The changes made in the After Effect project are very few, some text and some opacity but nothing excessive.

Does this happen to you too?

Is there any way to reduce the time?

What could be the cause of this excessive slowdown? Other projects I use have very few seconds between the start of the job and the start of rendering.

**Comment by inlife** [comment]
Hey @crisdeb 

This part is actually already the encoding (action-encode) in process, not rendering itself:
```
[YKbQbiFgb_xkW3QxZC4OU] frame= 38 fps=0.0 q=0.0 size= 0kB time=00:00:00.00 bitrate=N/A speed= 0x
```

Rendering was already finished at that point, the delay takes exactly that, the rendering on aerender side.

**Comment by crisdeb** [comment]
thanks
