### ISSUE TITLE
available properties

### ISSUE THREAD

**Issue by bblo-seso** [inlife/nexrender#590]
Hi all,

how can I find out which properties I can set with '"type": "data",'. E.g.: For a Text Layer, you can set 'Source Text'. That's clear so far, since 'Source Text' is listed in AEs properties. But (according to the readme), you can also set 'Source Text.font' and 'Source Text.size' - despite them not being listed in the AE properties. How are you supposed to find these hidden props?

concretely: How can I set the text color using nexrender

all the best,
Bert–

**Comment by teeveedee** [comment]
Properties can be found in the expressions menu. For your example, it's `Source Text.fillColor`

![Screenshot (4)](https://user-images.githubusercontent.com/62313013/116434939-7c1ab400-a810-11eb-87f0-0c39a744208e.png)

**Comment by benjioh5** [comment]
@teeveedee I think this should be added to documents
