### ISSUE TITLE
pause rendering and stay on frame whitout crash or having error

### ISSUE THREAD

**Issue by nazemi0101** [inlife/nexrender#592]
i using nexrender-cli-win64 on windows 64bit server without graphics card and cpu ryzen 5 3600 and 64 ram 
.some times rendering a project pause and not forwarding render to next frame and i check log rendering and see not error or crashing rendering just pause at a frame and not rendering another frame .
my render setting has avi format and postrender ffmpeg-b4.2.2 . i use and try on after effects 2019 and 2020 and 2021 

stay on frame 224 - if stop git bash and start again maybe rendering this project and not having problem. i say this bug not every time or have specific reason.maybe pause another frame in while rendering another project.not stability.
![image](https://user-images.githubusercontent.com/47674802/117151515-6a1bb100-adce-11eb-897a-6d714642d337.png)

**Comment by teeveedee** [comment]
Does the project render if you attempt it using aerender directly rather than invoking it through NexRender?

Try doing this (with the `--verbose` flag) and updating your issue with the log output provided.
