### ISSUE TITLE
What does the patch change?

### ISSUE THREAD

**Issue by MBrendel** [inlife/nexrender#596]
`@nexrender/core`applies a patch to  After Effects `commandLineRenderer.jsx` startup script.

What exactly does that patch change / add / patch?  
What problems does it solve?

Thanks!

**Comment by inlife** [comment]
Great question!

This patch adds an ability to inject and execute a jsx script before triggering the actual rendering flow, which how nexrender essentially makes everything work together. So in a way, this patch is essential for nexrender to work properly.

**Comment by MBrendel** [comment]
Thanks for your quick reply and big kudos for your work on this project.

So the original `commandLineRenderer.jsx` script is the same across all versions of AE? Nothing will get lost when it's overwritten?

**Comment by inlife** [comment]
From what I've seen it always has been the same. Can't be 100% sure for the future though.
