### ISSUE TITLE
log:  project failed, but video is created

### ISSUE THREAD

**Issue by kolyadin** [Inlife/nexrender#6]
Hi!
Running nexrender and having such error:

=========[RENDERNODE]=========

nexrender.renderer is starting

------------------------------
making request for projects...
looking for suitable projects...
[H1YhHOaw] setting up project...
[H1YhHOaw] downloading assets...
[H1YhHOaw] renaming assets...
[H1YhHOaw] filtering image assets...
[H1YhHOaw] patching project...
[H1YhHOaw] rendering project...
[H1YhHOaw] verifying project...
--------------------------
[H1YhHOaw] project failed
--------------------------

But output file is created and looks like correct.
Any suggestions?

**Comment by Inlife** [comment]
Hey!

Well, might be error with checking resulting filename.
nexrender looks for file named `H1YhHOaw_result.$EXT`

However, if final output **extension doesn't match** the one that have been provided in project template, there are might be errors.

Also it appears if you render sequence as **JPEG**s, there is currently no check for valid output.

If renderning is successfully finished, you can verify this by checking AE Logs dir inside `temp/H1YhHOaw` folder, **you can use** your rendered file without any concerns :)

If you want me to check this problem further you can provide you **json project** request and describe the **outputModule**. :)

Thanks.

**Comment by kolyadin** [comment]
Oh, it was my mistake.
You're absolutely right - extension naming issue.
I change extension from .mp4 to .mov and now output log is looking normal:

=========[RENDERNODE]=========

nexrender.renderer is starting

------------------------------
making request for projects...
looking for suitable projects...
[H1UkqupP] setting up project...
[H1UkqupP] downloading assets...
[H1UkqupP] renaming assets...
[H1UkqupP] filtering image assets...
[H1UkqupP] patching project...
[H1UkqupP] rendering project...
[H1UkqupP] verifying project...
[H1UkqupP] applying actions...
[H1UkqupP] cleaning up...
----------------------------
[H1UkqupP] project finished
----------------------------

thanks!
