### ISSUE TITLE
How can I modify a Gradient Fill property?

### ISSUE THREAD

**Issue by sjsaul1101** [inlife/nexrender#604]
I've been able to modify the nested properties several layers down from my file, but get this error:

`error: nexrender: Can't find a property sequence Gradient Fill 22.Opacity for key: Gradient Fill 22`

My project structure looks like this:
<img width="532" alt="Screen Shot 2021-05-25 at 6 31 22 PM" src="https://user-images.githubusercontent.com/12602667/119589328-6bb21680-bd87-11eb-8d85-06e8beec90b4.png">

And I'm passing this JSON into the assets array in the api:

```
{
    type: "data",
    layerName: "body 2",
    composition: 'koi_rig_steve',
    property: "Contents.Shape 1.Gradient Fill 22.Opacity",
    value: 0
}
```
Has anyone been able to modify gradient properties with nexrender?

**Comment by adanielyan** [comment]
Try 
```
{
  ...
  property: "Contents.Shape 1.Contents.Gradient Fill 22.Opacity",
  ...
}
```
