### ISSUE TITLE
All pipe instances are busy

### ISSUE THREAD

**Issue by robin-garnham** [inlife/nexrender#610]
Hi everyone, 

Great library, thank you for maintaining it. I'm having an issue with a composition process and hoping to get some help.

Full logs are below, but basically the job executes as I would expect and completes all steps, but then hangs for several minutes and then throws an error into the execution logs and successfully completes and continues in nexrender and executes my postrender functions.

It's a pain because my composition process completes in 34 seconds, but then hangs around for five mins before finishing. 

It's running on a virtual desktop environment running Windows 10 with the latest After Effects and `@nexrender/core ^1.28.0`

`aerender` version 18.2x37
Using DXGI: Device: "Microsoft Basic Render Driver" has dedicated video RAM (MB): 0
 has video RAM(MB): 0
2021-06-21 11:12:33:068 : INFO  Successfully Launched IPC Broker with medium Integrity Level
Skipping DX support: Microsoft Basic Render Driver
Qt: Untested Windows version 10.0 detected!
Running Script: D:\Users\robin\Desktop\render-service-master\src\workspace\DUOnOAHW6J4KSRTBE8qcg\nexrender-DUOnOAHW6J4KSRTBE8qcg-script.jsx
PROGRESS:  6/21/2021 11:12:39 AM: Starting composition LOWER THIRD logo.
PROGRESS:  Render Settings: Best Settings
PROGRESS:  Quality: Best
PROGRESS:  Resolution: Full
PROGRESS:  Size: 1920 x 1080
PROGRESS:  Proxy Use: Use No Proxies
PROGRESS:  Effects: Current Settings
PROGRESS:  Disk Cache: Read Only
PROGRESS:  Color Depth: Current Settings
PROGRESS:  Frame Blending: On for Checked Layers
PROGRESS:  Field Render: Off
PROGRESS:  Pulldown: Off
PROGRESS:  Motion Blur: On for Checked Layers
PROGRESS:  Solos: Current Settings
PROGRESS:  Time Span: Work Area
PROGRESS:  Start: 0:00:00:00
PROGRESS:  End: 0:00:05:23
PROGRESS:  Duration: 0:00:05:24
PROGRESS:  Frame Rate: 30.00 (comp)
PROGRESS:  Guide Layers: All Off
PROGRESS:  Skip Existing Files: Off
PROGRESS:  
PROGRESS:  Output Module: LFS
PROGRESS:  Output To: D:\Users\robin\Desktop\render-service-master\src\workspace\DUOnOAHW6J4KSRTBE8qcg\result_[#####].png
PROGRESS:  Format: PNG
PROGRESS:  Output Info: -
PROGRESS:  Start Frame: 0
PROGRESS:  Output Audio: -
PROGRESS:  Channels: RGB + Alpha
PROGRESS:  Depth: Millions of Colors+
PROGRESS:  Color: Straight
PROGRESS:  Resize: -
PROGRESS:  Crop: -
PROGRESS:  Final Size: 1920 x 1080
PROGRESS:  Profile: -
PROGRESS:  Post-Render Action: None
PROGRESS:  
PROGRESS:  0:00:00:00 (1): 0 Seconds
PROGRESS:  0:00:00:01 (2): 0 Seconds
...
PROGRESS:  0:00:05:22 (173): 1 Seconds
PROGRESS:  0:00:05:23 (174): 0 Seconds
PROGRESS:  6/21/2021 11:13:13 AM: Finished composition LOWER THIRD logo.
PROGRESS:  Total Time Elapsed: 34 Seconds
2021-06-21 11:14:57:311 : INFO  Successfully Launched IPC Broker with medium Integrity Level
2021-06-21 11:17:26:912 : ERROR vcfoundation::system::VCSysError: CreateFile('\\.\pipe\com.adobe.AdobeIPCBroker.ctrl-robin') failed <231: All pipe instances are busy.>
race:    1 00007FF80A630BDD
   2 00007FF80A62A940
   3 00007FF80A62A7F7
   4 00007FF80A62A81D
   5 00007FF80A62A00F
   6 00007FF80A621349
   7 00007FF80A622560
   8 00007FF80A62F9A1
   9 00007FF80A628484
  10 00007FF80A6282B7
  11 00007FF80A628274
  12 00007FF80A603436
  13 00007FF80A604CBA
  14 00007FF80A61B437
  15 00007FFFEB0385C3
  16 00007FFFEB02E224
  17 00007FFFEB0F76BA
  18 00007FFFEB0FE569
  19 00007FF82641FB80
  20 00007FF8289884D4
  21 00007FF829881821

2021-06-21 11:17:26:912 : INFO  Successfully Launched IPC Broker with medium Integrity Level`

**Comment by robin-garnham** [comment]
This issue seemed to just go away.

**Comment by inlife** [comment]
Interesting. Seems like its related to some After Effects internals, and possibly specifics of virtualized environments.

**Comment by robin-garnham** [comment]
This has come back

```
Adobe After Effects v18.2 Windows 64 render log for project "shootsta-lower-thirds.aepx"

Rendering started on 8/23/2021 at 1:50:07 AM

  8/23/2021 1:50:07 AM: Starting composition "LOWER THIRD logo".

  Render Settings: Best Settings  Quality: Best  Resolution: Full  Size: 1920 x 1080  Proxy Use: Use No Proxies  Effects: Current Settings  Disk Cache: Read Only  Color Depth: Current Settings  Frame Blending: On for Checked Layers  Field Render: Off  Pulldown: Off  Motion Blur: On for Checked Layers  Solos: Current Settings  Time Span: Work Area  Start: 0:00:00:00  End: 0:00:05:23  Duration: 0:00:05:24  Frame Rate: 30.00 (comp)  Guide Layers: All Off  Skip Existing Files: Off    Output Module: LFS  Output To: D:\Users\robin\Desktop\cloud-render-service\src\workspace\NntPLeKdCtT9Dwl9t_ITz\result_[#####].png  Format: PNG  Output Info: -  Start Frame: 0  Output Audio: -  Channels: RGB + Alpha  Depth: Millions of Colors+  Color: Straight  Resize: -  Crop: -  Final Size: 1920 x 1080  Profile: -  Post-Render Action: None    0:00:00:00 (1): 0 Seconds  0:00:00:01 (2): 0 Seconds  0:00:00:02 (3): 0 Seconds  0:00:00:03 (4): 0 Seconds  0:00:00:04 (5): 0 Seconds  0:00:00:05 (6): 1 Seconds  0:00:00:06 (7): 0 Seconds  0:00:00:07 (8): 0 Seconds  0:00:00:08 (9): 0 Seconds  0:00:00:09 (10): 0 Seconds  0:00:00:10 (11): 0 Seconds  0:00:00:11 (12): 0 Seconds  0:00:00:12 (13): 0 Seconds  0:00:00:13 (14): 1 Seconds  0:00:00:14 (15): 0 Seconds  0:00:00:15 (16): 0 Seconds  0:00:00:16 (17): 0 Seconds  0:00:00:17 (18): 0 Seconds  0:00:00:18 (19): 0 Seconds  0:00:00:19 (20): 0 Seconds  0:00:00:20 (21): 1 Seconds  0:00:00:21 (22): 0 Seconds  0:00:00:22 (23): 0 Seconds  0:00:00:23 (24): 0 Seconds  0:00:00:24 (25): 0 Seconds  0:00:00:25 (26): 0 Seconds  0:00:00:26 (27): 1 Seconds  0:00:00:27 (28): 0 Seconds  0:00:00:28 (29): 0 Seconds  0:00:00:29 (30): 0 Seconds  0:00:01:00 (31): 0 Seconds  0:00:01:01 (32): 0 Seconds  0:00:01:02 (33): 0 Seconds  0:00:01:03 (34): 1 Seconds  0:00:01:04 (35): 0 Seconds  0:00:01:05 (36): 0 Seconds  0:00:01:06 (37): 0 Seconds  0:00:01:07 (38): 1 Seconds  0:00:01:08 (39): 0 Seconds  0:00:01:09 (40): 0 Seconds  0:00:01:10 (41): 0 Seconds  0:00:01:11 (42): 1 Seconds  0:00:01:12 (43): 0 Seconds  0:00:01:13 (44): 0 Seconds  0:00:01:14 (45): 0 Seconds  0:00:01:15 (46): 1 Seconds  0:00:01:16 (47): 0 Seconds  0:00:01:17 (48): 0 Seconds  0:00:01:18 (49): 0 Seconds  0:00:01:19 (50): 0 Seconds  0:00:01:20 (51): 1 Seconds  0:00:01:21 (52): 0 Seconds  0:00:01:22 (53): 0 Seconds  0:00:01:23 (54): 0 Seconds  0:00:01:24 (55): 0 Seconds  0:00:01:25 (56): 0 Seconds  0:00:01:26 (57): 1 Seconds  0:00:01:27 (58): 0 Seconds  0:00:01:28 (59): 0 Seconds  0:00:01:29 (60): 0 Seconds  0:00:02:00 (61): 0 Seconds  0:00:02:01 (62): 0 Seconds  0:00:02:02 (63): 1 Seconds  0:00:02:03 (64): 0 Seconds  0:00:02:04 (65): 0 Seconds  0:00:02:05 (66): 0 Seconds  0:00:02:06 (67): 0 Seconds  0:00:02:07 (68): 0 Seconds  0:00:02:08 (69): 1 Seconds  0:00:02:09 (70): 0 Seconds  0:00:02:10 (71): 0 Seconds  0:00:02:11 (72): 0 Seconds  0:00:02:12 (73): 0 Seconds  0:00:02:13 (74): 0 Seconds  0:00:02:14 (75): 1 Seconds  0:00:02:15 (76): 0 Seconds  0:00:02:16 (77): 0 Seconds  0:00:02:17 (78): 0 Seconds  0:00:02:18 (79): 0 Seconds  0:00:02:19 (80): 1 Seconds  0:00:02:20 (81): 0 Seconds  0:00:02:21 (82): 0 Seconds  0:00:02:22 (83): 0 Seconds  0:00:02:23 (84): 0 Seconds  0:00:02:24 (85): 0 Seconds  0:00:02:25 (86): 1 Seconds  0:00:02:26 (87): 0 Seconds  0:00:02:27 (88): 0 Seconds  0:00:02:28 (89): 0 Seconds  0:00:02:29 (90): 0 Seconds  0:00:03:00 (91): 0 Seconds  0:00:03:01 (92): 1 Seconds  0:00:03:02 (93): 0 Seconds  0:00:03:03 (94): 0 Seconds  0:00:03:04 (95): 0 Seconds  0:00:03:05 (96): 0 Seconds  0:00:03:06 (97): 1 Seconds  0:00:03:07 (98): 0 Seconds  0:00:03:08 (99): 0 Seconds  0:00:03:09 (100): 0 Seconds  0:00:03:10 (101): 0 Seconds  0:00:03:11 (102): 0 Seconds  0:00:03:12 (103): 1 Seconds  0:00:03:13 (104): 0 Seconds  0:00:03:14 (105): 0 Seconds  0:00:03:15 (106): 0 Seconds  0:00:03:16 (107): 0 Seconds  0:00:03:17 (108): 0 Seconds  0:00:03:18 (109): 1 Seconds  0:00:03:19 (110): 0 Seconds  0:00:03:20 (111): 0 Seconds  0:00:03:21 (112): 0 Seconds  0:00:03:22 (113): 0 Seconds  0:00:03:23 (114): 0 Seconds  0:00:03:24 (115): 1 Seconds  0:00:03:25 (116): 0 Seconds  0:00:03:26 (117): 0 Seconds  0:00:03:27 (118): 0 Seconds  0:00:03:28 (119): 0 Seconds  0:00:03:29 (120): 0 Seconds  0:00:04:00 (121): 1 Seconds  0:00:04:01 (122): 0 Seconds  0:00:04:02 (123): 0 Seconds  0:00:04:03 (124): 0 Seconds  0:00:04:04 (125): 0 Seconds  0:00:04:05 (126): 1 Seconds  0:00:04:06 (127): 0 Seconds  0:00:04:07 (128): 0 Seconds  0:00:04:08 (129): 0 Seconds  0:00:04:09 (130): 0 Seconds  0:00:04:10 (131): 0 Seconds  0:00:04:11 (132): 1 Seconds  0:00:04:12 (133): 0 Seconds  0:00:04:13 (134): 0 Seconds  0:00:04:14 (135): 0 Seconds  0:00:04:15 (136): 0 Seconds  0:00:04:16 (137): 0 Seconds  0:00:04:17 (138): 1 Seconds  0:00:04:18 (139): 0 Seconds  0:00:04:19 (140): 0 Seconds  0:00:04:20 (141): 0 Seconds  0:00:04:21 (142): 0 Seconds  0:00:04:22 (143): 0 Seconds  0:00:04:23 (144): 1 Seconds  0:00:04:24 (145): 0 Seconds  0:00:04:25 (146): 0 Seconds  0:00:04:26 (147): 0 Seconds  0:00:04:27 (148): 0 Seconds  0:00:04:28 (149): 1 Seconds  0:00:04:29 (150): 0 Seconds  0:00:05:00 (151): 0 Seconds  0:00:05:01 (152): 0 Seconds  0:00:05:02 (153): 0 Seconds  0:00:05:03 (154): 0 Seconds  0:00:05:04 (155): 1 Seconds  0:00:05:05 (156): 0 Seconds  0:00:05:06 (157): 0 Seconds  0:00:05:07 (158): 0 Seconds  0:00:05:08 (159): 0 Seconds  0:00:05:09 (160): 1 Seconds  0:00:05:10 (161): 0 Seconds  0:00:05:11 (162): 0 Seconds  0:00:05:12 (163): 0 Seconds  0:00:05:13 (164): 1 Seconds  0:00:05:14 (165): 0 Seconds  0:00:05:15 (166): 0 Seconds  0:00:05:16 (167): 1 Seconds  0:00:05:17 (168): 0 Seconds  0:00:05:18 (169): 0 Seconds  0:00:05:19 (170): 0 Seconds  0:00:05:20 (171): 1 Seconds  0:00:05:21 (172): 0 Seconds  0:00:05:22 (173): 0 Seconds  0:00:05:23 (174): 0 Seconds  8/23/2021 1:50:38 AM: Finished composition "LOWER THIRD logo".


  Total Time Elapsed: 31 Seconds
Log closed on 8/23/2021 at 1:50:38 AM
```

**Comment by robin-garnham** [comment]
I can't see any reason that it's doing this, and it seemed to go away for a while.
The composition is rendered and everything is generated, but the next step doesn't occur for about 5 mins, and then it does and all works correctly.
It seems to work fine on Mac, but the Windows virtual environment I'm using is where the issue exists. It's also strange that it went away and then came back again after I re-licensed After Effects (re-logging in via the UI to confirm I still own the license)

**Comment by inlife** [comment]
Hey,

I did more research, and seems like that is indeed related to Win32 API used within the After Effects software:
https://stackoverflow.com/questions/31700018/win32-api-named-pipe-all-pipe-instances-are-busy
https://microsoft.public.vc.mfc.narkive.com/6w1K1vSy/error-pipe-busy-all-pipe-instances-are-busy

That also corresponds with a tracelogged function call `CreateFile` you've posted above: `2021-06-21 11:17:26:912 : ERROR vcfoundation::system::VCSysError: CreateFile('\.\pipe\com.adobe.AdobeIPCBroker.ctrl-robin') failed <231: All pipe instances are busy.>`

As per explanation by msdn:
> If there is at least one active pipe instance but there are no available listener pipes on the server, which means all pipe instances are currently connected, CreateFile fails with ERROR_PIPE_BUSY.

My questions to you:
1. How many AE instances do you run in the VM?
2. How many VM instances do you run on your OS at the same time?

**Comment by kevin-chaplin** [comment]
Hiya, thanks again for looking into this, in answer to your questions we are running only 1 AE instance and 1 VM.

**Comment by inlife** [comment]
That \*might\* be related to the usage of the VM itself, but can't say exactly. That definitely something that happens in the native (c++) part of the AE binary, not sure how that can be fixed other than by Adobe themselves.
