### ISSUE TITLE
Limit number of aerender to be processed

### ISSUE THREAD

**Issue by benghan104** [inlife/nexrender#62]
Hello!

I'm not very good in managing and limiting the number of aerender.exe allowed to be operated. I faced an issue as below: 

> WARNING:After Effects warning: logged one error  error: Rendering error while writing to file ...\result.mov. An output module failed. The file may be damaged or corrupted.

When I search through the web, it says most probably because that I'm using QuickTime for H.264 codec with a large number of threads. Here's the URL: https://forums.adobe.com/thread/1252092 

However, I don't know how to limit the amount of thread for aerender.exe . I tried 12 threads on aerender.exe and all crash at the same time. Have anyone experienced on this issue too?

**Comment by inlife** [comment]
are all of the threads writing into the same file ?

**Comment by inlife** [comment]
that is unusual than. And i dont have an idea how i can help you :(
