### ISSUE TITLE
Getting job workpath in jsx script

### ISSUE THREAD

**Issue by adanielyan** [inlife/nexrender#629]
Hi, I am running the nexrender-cli on Mac. I am running a jsx that is defined in job's assets. In that jsx I need to manipulate the template file before it is rendered. In order to open it I need to get the current job's workpath (including the randomly generated folder name) in my jsx script. For some reason providing a relative path in the script doesn't work. For example if I try to open `./project.aep` or `project.aep` the file path is converted to `/template.aep` which is obviously not correct. 

I tried using `File($.fileName).path`, however it returns `/Applications/Adobe%20After%20Effects%202021/Scripts/Startup` instead of something lile `~/Projects/temp/5ArUtUeOp9b8KPTTIMDM8`. I searched through the documentation and code, but couldn't find a way to get the jobs absolute workpath in jsx. Please help.

**Comment by adanielyan** [comment]
OK, after some more thinking I found an easy way to get the workpath in jsx:

```js
var projectFile = app.project.file;
if (projectFile.exists) {
  var workpath = projectFile.path
}
```

**Comment by inlife** [comment]
That is a very nice finding! Hopefully, other people will agree with me! 😄

**Comment by adanielyan** [comment]
My finding may be obvious for someone who has more experience with jsx, but I'm very new to it :)
