### ISSUE TITLE
mp4 rendering XD?

### ISSUE THREAD

**Issue by Abukodonosor** [inlife/nexrender#63]
settings:
   { outputModule: 'h264',
     startFrame: 0,
     endFrame: 600,
     outputExt: 'mp4' },

And result i receive is 

[ryoVw_YRf] project failed
--------------------------

Error message: ENOENT: no such file or directory, stat 'C:\Users\Abu\Desktop\for_zip\temp\ryoVw_YRf\result.mp4'
{ Error: ENOENT: no such file or directory, stat 'C:\Users\Abu\Desktop\for_zip\temp\ryoVw_YRf\result.mp4'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\Abu\\Desktop\\for_zip\\temp\\ryoVw_YRf\\result.mp4' }

Can you tell me what i miss to render video at mp4 format,.. btw avi format works well ... I am on windows 10...

tnx for answer XD

**Comment by inlife** [comment]
make sure your version of after effects supports h264 encoding and mp4 output format
did you set up your output module properly ?

**Comment by Abukodonosor** [comment]
now i am looking documentation ... how to  add this encode .. if you know how to make it fast .. send me link ...btw i use AE CC 2015


I more question .. do you maybe know how to adjust this template to your nexRender ....
part which i have trouble is  color, text and etc.. how to set them?
do you maeby know the way?


{
  aep: 'C:\\prj\\AeTemplate\\Dynamic\\Simple_Promo\\Fade_Up\\11',
  target: 'Final Comp',
  id: 176113,
  'render-status': 'ready',
  totalcomp: 18,
  output: 'betareevio_4857_176113_18',
  'bg_image1.1': 
 'http://195.201.21.189:3008/videos/trim_videos/flxebd0c33f033a70e64b332a947ed03c671526324953090.mp4',
  'duration1.1': 
 'http://195.201.21.189:3008/videos/trim_videos/ebd0c33f033a70e64b332a947ed03c671526324953090.mp4',
   'text1.2': 'Svolge azione caustica',
   'color1.2': '000000',
   'text1.3': 'che provoca l\'essiccamento di qualsiasi parte vegetale a contatto con il prodotto',
   'color1.3': '000000',
   'text1.1': 'BIOSEC',
   'color1.1': 'ffffff',
   'background_color1.1': '364737'
 }

**Comment by inlife** [comment]
please read all the information there:
https://github.com/inlife/nexrender/wiki

and search in issues (opened/closed) for similar answered questions
