### ISSUE TITLE
How to to delete layer from Template.

### ISSUE THREAD

**Issue by sitestrokes** [inlife/nexrender#635]
Hello,

I have AE template which contain 5 slides with different different layers.

I have successfully changed background image layer , text layer and audio layer also.

Suppose i want render video with only 2 slides layers instead of 5 slides .

Is it possible to delete layers from AE template or render video without some layers.

Thanks.

**Comment by shahabbasi** [comment]
I'm not exactly sure what you're talking about, but take a look at [this](https://github.com/inlife/nexrender#details). I think using properties `frameStart` and `frameEnd` might help.

**Comment by sitestrokes** [comment]
Hello,

I have a template that contains 5 text layers n 5 BackgroundImage Layer.

suppose I have to change layer 1 and layer 3 text layer data as well as background Image layer data and render template using nexrender then the final video contains my changed data as well as default layer data.

I want final video with only changed data, not any default layer data.

is that possible with using nexrender?

Thanks.

**Comment by inlife** [comment]
I think it is! At least if I'm correctly getting the idea of what are you describing.

**Comment by sitestrokes** [comment]
Hello,

Thanks for your response.

As I explained before, I need the ability to delete and change few layers and need final output with changed layers only, without layers that have been deleted already.

Let’s say I have 5 slides in my template, changed only 2 of them. The final output video should contain only 2 slides that I have changed.

To achieve this, Do I need to change any settings in aftereffects, or is it possible directly with Nexrender commands?

Kindly guide me, how can I achieve it with Nexrender commands, if possible.
If there is any other way than this, please let me know

Thanks.

**Comment by inlife** [comment]
Hey @sitestrokes 

I think that is something that for sure can be done with JSX scripting

Here are a few resources to help you get started:
* https://ae-scripting.docsforadobe.dev/
* https://github.com/ExtendScript/wiki/wiki

**Comment by sitestrokes** [comment]
Hello,

can I change 'workpath' to any cloud location (Google Cloud or S3)?

Thanks.
