### ISSUE TITLE
Converting assests

### ISSUE THREAD

**Issue by Abukodonosor** [inlife/nexrender#64]
Hello , can you give me advice how to adjust  those parametars .. to make them look like 

'text1.2': 'Svolge azione caustica',
'color1.2': '000000',

   { "name": `text1.2`,  "src": `http://localhost:${port}/assets/text1.2.txt` },

or
   { "name": `text1.2`,  "src": `Svolge azione caustica` },

?

**Comment by inlife** [comment]
which parameters ?
are you talking about parametrizing a composition elements ?

in that case please refer https://github.com/inlife/nexrender-boilerplate for the examples

**Comment by Abukodonosor** [comment]
I have different input types... I am working on some project and we need to switch from old rendering mechanisam to this... now i am trying to convert old templates parametars to new one...

Our templates have dinamic text, colors, and etc... thing what i need is how to inject color and other parametars to your  project.assets[]

**Comment by Abukodonosor** [comment]
{	
	"uid" : "pls_work",
        "template": "11.aepx",
        "composition": "main",
        "type": "default",
        "settings": {
            // dont forget to setup the right output module; info:
            // The default outputModule for Windows users is "Lossless"h264 & the default outputExt is "avi"
            // You can create custom modules from Edit -> Templates -> Output Modules but the name and outputExt have to be in sync
            // Go to Composition -> Add Output Module to create customModule names
            // https://helpx.adobe.com/after-effects/using/basics-rendering-exporting.html#output_modules_and_output_module_settings
            "outputModule": "Lossless",
            "startFrame": 0,
            "endFrame": duration,
            "outputExt": "avi"
        },
        "assets": [
            { "type": "project", "name": "11.aepx",    "src": `http://localhost:${port}/assets/11.aepx`}, 
  		{"name":'bg_image1.1', "src" : 'http://localhost:${port}/mats/bg_image1.1.mp4'},
  		{"name":'duration1.1', "src": 'http://localhost:${port}/mats/duration1.1.mp4'},
  		{"name":'text1.2', "src": 'http://localhost:${port}/mats/text.1.2.txt'},
  		{"name":'color1.2', "src": 'http://localhost:${port}/mats/color1.2.txt'},
  		{"name":'text1.3', "src": 'http://localhost:${port}/mats/text1.3.txt'},
  		{"name":'color1.3', "src": 'http://localhost:${port}/mats/color1.3.txt'},
  		{"name":'text1.1', "src": 'http://localhost:${port}/mats/text1.1.txt'},
  		{"name":'color1.1', "src": 'http://localhost:${port}/mats/color1.1.txt'},
  		{"name":'background_color1.1', "src": 'http://localhost:${port}/mats/background_color1.1.txt'}
        ]
    }


i make Project to look like this, and error what i am getting is 


Error message: connect ECONNREFUSED 127.0.0.1:80
{ RequestError: connect ECONNREFUSED 127.0.0.1:80
    at ClientRequest.req.once.err (C:\Users\Abu\Desktop\for_zip\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ECONNREFUSED',
  message: 'connect ECONNREFUSED 127.0.0.1:80',
  host: 'localhost',
  hostname: 'localhost',
  method: 'GET',
  path: '/:$%7Bport%7D/mats/text1.1.txt',
  bufferedData: <Buffer > }

**Comment by Abukodonosor** [comment]
I test it on boiler plate already ...  issue i faceing with is how to import  text color and other things... i know how to work with other models...

Can you write me part of code that i need .. this is a 3 lines of code .. because its obvious we dont understend eachother ... or i am getting it wrong...

**Comment by inlife** [comment]
yes, sure, its already there, in boilerplate project

![image](https://user-images.githubusercontent.com/2182108/40117523-dc9a8d0c-591f-11e8-8ca1-3ba5aa3d5eee.png)

also there is an issue with same stuff
https://github.com/inlife/nexrender/issues/7#issue-167478273

**Comment by inlife** [comment]
Yes, thats exactly what you need to do, this is how dynamic data works in nexrender. I assumed you knew it, considering the fact it was mentioned multiple times in the documentation.

**Comment by Abukodonosor** [comment]
Now i will spent some time to learn how to fatch compositions .. how to set value of determined composition, layer ... and etc 

Am i going in right direction ?

if you wish .. it will help me alot.. to upload you template .. to help me a bit ?

**Comment by inlife** [comment]
you can download an example template provided in nexrender boilerplate 😉 
the rest is up to you, you need to look for help on adobe AE scripting forums

**Comment by Abukodonosor** [comment]
Inlife XD Can nexrender render template if tempalte have  compostion who is compiled from sub-compositions? .. because template is organised that way?

And can you explain me how your JS code know how to target artist layer?
