### ISSUE TITLE
How to use nexrender-action-cache

### ISSUE THREAD

**Issue by JamesBotterill** [inlife/nexrender#640]
Forgive my ignorance but the documentation for nexrender-action-cache is very light.

how do I write a cache file, is it json and do I reference the file and location? 

Improved documentation and an example cache file would be appreciated

**Comment by inlife** [comment]
Hey @JamesBotterill 

Maybe this pull request would help shine a bit more light on the use case: https://github.com/inlife/nexrender/pull/616 ?

Cheers
