### ISSUE TITLE
image with blending mode

### ISSUE THREAD

**Issue by adirzoari** [inlife/nexrender#646]
in AE program I have 2 images. 1 image with a blending mode (stroke-png.png), the second image gets the effect and mask into.
as you can see here
![image](https://user-images.githubusercontent.com/20258998/138611488-49cc6199-f106-4c2a-a1df-c4f22f123366.png)
![image](https://user-images.githubusercontent.com/20258998/138611555-8ba8a101-422b-445b-a0ee-d6c7cdc48656.png)

when I edit the JSON I want to change the photo dynamically so I change it
```
   {
        "src": "https://images.unsplash.com/photo-1501901609772-df0848060b33?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=809",
        "type": "image",
        "layerName": "Change this Photo"
      },
```
I get the photo without the effect of blending mode into
![image](https://user-images.githubusercontent.com/20258998/138611537-b0e5e7d0-2986-4fce-b397-9894cb5a5e07.png)

**Comment by inlife** [comment]
No, but docs should be of great help here! :)
