### ISSUE TITLE
 ContentType on Action Upload Provider-S3

### ISSUE THREAD

**Issue by bukanalie** [inlife/nexrender#648]
**Describe the bug**
On postrender. I use @nexrender/action-upload with S3 Provider to upload output file.
But when i check on S3, Content-Type header is shown application/octet-stream instead of video/mp4 

**Information about environment**
* Which version of nexrender are you using? @nexrender/core ^1.31.0
* What kind of the setup do you have? @nexrender/core (Programmatic)
* Are you using pre-built binaries or globally installed npm packages? Both
* Which kind (and version) of operating system you are running it in? Windows 10
* Any additional information that might be helpful

**Expected behavior**
Content-Type header on S3 is video/mp4 or same as input extension

**Screenshots**
![image](https://user-images.githubusercontent.com/3202529/139783903-4f284b7a-09d9-44cf-85eb-3cb3dd248c3e.png)

![image](https://user-images.githubusercontent.com/3202529/139783926-79a4fab5-8298-49e8-a252-e408789ff268.png)

**Comment by bukanalie** [comment]
i try to added this line on .\node_modules\@nexrender\provider-s3\src\index.js

![image](https://user-images.githubusercontent.com/3202529/139790189-01fcc468-46a8-435b-a01a-72a944414e1b.png)


and working fine

**Comment by inlife** [comment]
Would you like to create a Pull Request for this improvement?

**Comment by bukanalie** [comment]
Sure, Pull Request was created
