### ISSUE TITLE
target layer

### ISSUE THREAD

**Issue by Abukodonosor** [inlife/nexrender#65]
Inlife XD Can nexrender render template if tempalte have compostion who is compiled from sub-compositions? .. because template is organised that way?

And can you explain me how your JS code know how to target artist layer?

**Comment by Abukodonosor** [comment]
The main issue was .. i didnt get how your layer know which fucntion need to triger .... and this is in actionScript ,.. actionScript set connection like standard mvc ( javaFX, C#)  action on specific element.


Can you give me some advice? how to search connections for images or videos ?
Do i need to loop true layers to ask for names or ?

**Comment by inlife** [comment]
you can check that by opening the aepx template file alongside the boilerplate
it is set right from inside the project

**Comment by Abukodonosor** [comment]
Morning Inlife ,  do you maybe know how to add connections to image or video.

Can he give connection to that type ... because on text obviously work.. and its easy to set.

To say guys who make templates to take care on that...  ?

where can we type that connection line?


prnt.sc/jj2tey

**Comment by inlife** [comment]
you mean, changing video or image based on expressions ?
unfortunately as far as i know its impossible, you can only change positions/time
also you can try using an "asset substitution" technique described in readme and in docs
hope that helps

**Comment by Abukodonosor** [comment]
Can i import  ExtendScript as data.js ? to have control on layers?

**Comment by inlife** [comment]
not sure

**Comment by Abukodonosor** [comment]
Can i iterate over layers ?  in my data.js file .. can you show me example... cuz i need to change value of some colorLayer... i have just name of it .. and layer miss connection thing (ActionScript  hook ) .. can i make it happend?

**Comment by inlife** [comment]
i dont think so, not with expressions

**Comment by inlife** [comment]
for that you would need the after effects scripting

**Comment by Abukodonosor** [comment]
I need to  make somehow .. to loop through the layers and to find layers with

**Comment by inlife** [comment]
i cannot help you with that

**Comment by Abukodonosor** [comment]
Is that thing doable? 

I am aiming to do?

**Comment by inlife** [comment]
i dont think so

**Comment by inlife** [comment]
@Abukodonosor glad to announce that targeting layer is doable now in the new pre-release version
