### ISSUE TITLE
Follow-up: And Unresolved "The structure has changed" #161

### ISSUE THREAD

**Issue by alancoote** [inlife/nexrender#650]
AERender displays this message if the structure of an imported asset via Nexrender changes. This can easily happen when using JSON as an asset. 

As AERender is spawned by nexrender the only control could be via JSX file to automatically click OK when this dialog box appears. 

Our workaround to date has been to open each project in AfterEffects then resave the project. And make sure the JSON doesn't change.

However, AfterEffects 2022 seems more sensitive to any JSON changes which means Nexrender and AE 2022 is no longer a viable solution for dynamic content. 

It could be argued that this isn't a NexRender issue, But I think the solution should be one fixed by NexRender - unless anyone knows more?

**Comment by inlife** [comment]
Do you have suggestions on how that could be fixed on the nexrender side?
