### ISSUE TITLE
commandLineRenderer.jsx has changed in Adobe After Effects 2022

### ISSUE THREAD

**Issue by chrisapplegate** [inlife/nexrender#653]
**Describe the bug**
The unpatched `commandLineRenderer.jsx` supplied with Adobe After Effects v22 has changed from previous versions. As per the [official documentation](https://helpx.adobe.com/after-effects/using/automated-rendering-network-rendering.html) there are now additional options:

* `-OMtemplate` & `-RStemplate` for Output Module & Render Settings
* `-mfr` as a replacement for `-mp` for multi-frame rendering.

The patched `commandLineRenderer.jsx` supplied with nexrender _mostly_ works with AE 2022 after being applied, but it doesn't allow the above options, which is a shame as I'd like to try out the new multi-frame rendering and also see if it is compatible with M1-native beta of After Effects.

**Information about environment**
* Which version of nexrender are you using? 1.32.0
* What kind of the setup do you have? (server+worker or cli) Custom worker that requires the nexrender core library
* Are you using pre-built binaries or globally installed npm packages? npm packages
* Which kind (and version) of operating system you are running it in? MacOS 10.15 (Catalina) & 11 (Big Sur)

**Expected behavior**

In an ideal world, the patched `commandLineRenderer.jsx` would offer the same options as AE 2022's unpatched version. I've used nexrender enough that I'm happy to write such a patch and submit it as a PR.

But I also see a backwards-compatibility problem: a patched version of the v22.0 script won't then work with After Effects v18.x. So I guess you will also need version detection on the patcher, and different versions of the patched `commandLineRenderer.jsx` in `assets` to apply. But I'm not quite confident to dive into that without discussing here first...

An alternative thought was if there is any other way of patching the renderer that is futureproof and version-agnostic, but I don't know enough about AE's internals to say for sure.

**Comment by chrisapplegate** [comment]
Update: I have now added a PR for this: #656

**Comment by inlife** [comment]
@chrisapplegate thank you for the PR
it's indeed hard to find a way for that to work for both versions

i might need some time to think about it as well

**Comment by oreporan** [comment]
Assuming this can be closed?

**Comment by limzykenneth** [comment]
The latest patch for this does not work with After Effects Beta which doesn't include a year label that's expected.
