### ISSUE TITLE
nexrender-server send job status to external service on job update

### ISSUE THREAD

**Issue by Elladan81** [inlife/nexrender#655]
Hi here!

We are testing a Django app that sends renderings to a Nexrender server. 
When workers update (via PUT / jobs / uid) the status of a Job, I would like the server to notify me of the status change directly, without having to loop requests from Django app (some of our renderings can take several hours , hence an unnecessary number of requests).

Obviously, I could make a modification in nexrender-server: /src/routes/jobs-update.js and get the status of the object when an update takes place, and send a request to my Django app.
But on the off chance, is there a package that allows this?
Is there a method that would allow me not to touch the code of nexrender-server?
thank you in advance for your help

**Comment by inlife** [comment]
You could use a post-render action that triggers a webhook and sends a request to the target machine. Other than that there is no way of doing that without modifications.

**Comment by gijspouwels** [comment]
> You could use a post-render action that triggers a webhook and sends a request to the target machine. Other than that there is no way of doing that without modifications.

I'm also looking for this option, but I can't seem to find out if it's already implemented or not. Could you show me an example of how I could make a HTTP-request with a post-render action?
