### ISSUE TITLE
unable to change exported file name

### ISSUE THREAD

**Issue by ggepenyan** [inlife/nexrender#66]
There is no way to change exported file name. It's always `result`. 
Please add something like this at render.js
```
let fileName = project.settings.name;
project.resultname = fileName + '.' + outext;
```

**Comment by ggepenyan** [comment]
Files are appearing in Temps only for me, and inside Temps folder, all folder names are like `BkCN5s60f`. So I think this have to be fixed also.

**Comment by inlife** [comment]
sure, exported filenames will be added as a feature in the next version

Temps is a folder for temporary projects, where each project has a unique autogenerated name, which is how it's supposed to be

**Comment by ggepenyan** [comment]
Thanks for response. Yes I got that(about temp folder). I meant it would be great not to see folder names as  `BkCN5s60f`. It would be great to see folder names like `project-name-v1..v2` or `project-name1..2`

**Comment by ggepenyan** [comment]
I dont see any changes in results folder

**Comment by inlife** [comment]
temp folder is temporary, its not supposed to be viewed by users, just needs to have a unique name, to prevent collisions in case if you have lets say 4000 simultaneous projects

there were no any changes, the new version will be out in a few months, probably

**Comment by ggepenyan** [comment]
I understood. Thanks for detailing. But one more question. Is it correct that no changes appear in results folder? Nothing happens in that folder. But in temps folder I can see my video rendered

**Comment by inlife** [comment]
does it report about any errors occurred?
most likely it fails on the validation step
