### ISSUE TITLE
How to render mp4 video in VR/360_Video in Nexrender

### ISSUE THREAD

**Issue by vega6dev** [inlife/nexrender#662]
Hi, I would like to know if it is possible to render a normal mp4 video in VR_360Degrees using nexrender. And if yes, then could you please share some details on 'how'.

**Comment by limzykenneth** [comment]
If it can be rendered by After Effects, it can be rendered using nexrender. There's no extra stuff going on here. If you need information about how to render 360 videos with AE you should be able to look up this information online somewhere.
