### ISSUE TITLE
font replace issue

### ISSUE THREAD

**Issue by Fredalter** [inlife/nexrender#669]
Hi,

nexrender-cli-win64-1-33-0 and after effets 2022

Still sticked with my fonts issue, after lot of tests and changes, it's seems not to be an issue with nexrender.
My projects is based on a webservice (on windows) who launch the nexrender cli, when an expression change fonts in a layer, i think aerender executed from IIS can't access font folder and raplace all fonts of the aep by a dafault one.
Does anyone have an idea to fix this ? probably permission issue but i try many things without succes

Frédéric

**Comment by limzykenneth** [comment]
I find that I need to install the font via right click > install font for all users, before it can be accessed. I'm not changing fonts via expressions though so not sure if it affects anything in that case.
