### ISSUE TITLE
Structure of Template

### ISSUE THREAD

**Issue by Abukodonosor** [inlife/nexrender#67]
Do template structure need to be in one compostiion?

like boiler_plate he have all in one compostition ...
Now i have templatse like this : http://prntscr.com/jl2mj5

And template whic i need to render is Final Comp ..
(http://prntscr.com/jl2mul)

**Comment by Abukodonosor** [comment]
and Controller composition have ... all $.eval (hooks)
http://prntscr.com/jl2n6g

Is that possible ?

**Comment by Abukodonosor** [comment]
Do template structure need to be in one compostiion? ( cuz nexrender renders only 1 composition at the time)
Can aerender render multiple compositions (or nested compostiions) and how to do that?

**Comment by inlife** [comment]
no, nexrender can render only 1 composition per "nexrender project"
multiple compositions only via rendering as different projects

**Comment by Abukodonosor** [comment]
Do i need to use xml.parser and to open file... to replace file from where i want to read variables ...?

**Comment by inlife** [comment]
yea

**Comment by Abukodonosor** [comment]
Can i replace image , and video paths in that xml?

**Comment by inlife** [comment]
have you tried opening it and doing that ?

**Comment by Abukodonosor** [comment]
Do you know.. can i write some part of code .. to make auto reference to missing footage in template?

**Comment by Abukodonosor** [comment]
It works.. you can change footage items via xml.

Do you know can i change image  inside of layer ?

**Comment by Abukodonosor** [comment]
If template have :

backgorund_image.jpg , can i put .mp4
video on that place ?

Or i need to make different compostion which support mp4 for background , instead of
 jpg ?
