### ISSUE TITLE
Server concurrency causing duplicate renders

### ISSUE THREAD

**Issue by limzykenneth** [inlife/nexrender#670]
**Describe the bug**
This is essentially the same thing as reported back in #109. The way the server is written currently means that it is possible for two (or more) workers picking up a new job from the server to receive the same job if they both do it within the window of picking up a job and updating its status to "picked". This results in situation where the job is rendered twice or more and is problematic for what I'm doing.

I see that the fix introduced in #113 was removed in https://github.com/inlife/nexrender/commit/1f526865d368be8f3fa013bdd3bb98e127a48c1f but I cannot tell why as mentioned in the commit message would that check be redundant, nowhere else in the code I looked at addresses this problem.

**Information about environment**
* Which version of nexrender are you using? 1.31.0
* What kind of the setup do you have? server+worker
* Are you using pre-built binaries or globally installed npm packages? API
* Which kind (and version) of operating system you are running it in? Windows Server
* Any additional information that might be helpful

**Expected behavior**
Each job should only be rendered once.

**Comment by inlife** [comment]
Ah, it might have been a mistake from my side. We could revert the commit if that helps!

**Comment by limzykenneth** [comment]
I found simply reverting it causes the whole thing to break possibly because the timestamp is updated in more than one places. I still can't find a good simple solution to this yet but it may need to be making sure the database itself is atomic.

**Comment by limzykenneth** [comment]
Some basic tests I made seems to show that using a mutex lock could possibly solve this problem. I'll test it on my system first to determine any potential issue before proposing it as a solution.

**Comment by limzykenneth** [comment]
I've tested using [async-mutex](https://www.npmjs.com/package/async-mutex) on my system and it seems to work well and I'm not seeing duplicate renders anymore. The mutex lock only applies in the pickup route as except for unconventional use of the API there shouldn't be an issue here but if desired we can wrap all database editing routes in mutex locks, but it may affect performance a bit especially on slow file systems.

@inlife If that all sounds good to you I can put together a PR for this.

**Comment by inlife** [comment]
That sounds great! A PR would be amazing!
