### ISSUE TITLE
Enable defining actions bu providing actions programmatically

### ISSUE THREAD

**Issue by limzykenneth** [inlife/nexrender#671]
**Is your feature request related to a problem? Please describe.**
This is a bit of an edge case but I would like to use custom actions (prerender, postrender, etc) without having to split them out into separate installable package. The reason is that I'm using nexrender-worker programmatically and it would be nice to clearly define an action in the code starting the worker instead of having to rely on installed packages.

**Describe the solution you'd like**
I have a patch that addresses this that basically adds an `actions` field to the settings passed to the `start` function of nexrender-worker which can then be used to associate a particular name with an action function. The way its implemented is also backwards compatible, it will check in the `actions` object if provided first then if not exist proceed to check the installed packages as usual (including global packages).

Happy to file a PR for this if you think it's good to include, although it will only be useful to whoever is using nexrender-worker programmatically (which is undocumented).

**Comment by inlife** [comment]
Hey @limzykenneth 

Could you show me how does it look like? I don't seem to understand exactly right now, but I think the example will help! :)

Cheers

**Comment by limzykenneth** [comment]
Sure. In the code starting a worker:
```js
const {start} = require("@nexrender/worker");

const myCustomAction = (job, settings, {input, params}, type) => {
  // Whatever the action needs to do
};

start(process.env.NEXRENDER_HOST, process.env.NEXRENDER_SECRET, {
  workpath: projectsPath,
  actions: {
    "custom-action": myCustomAction
  }
});
```

This way I don't have to have `myCustomAction` as a separate package but just include it as a simple function alongside the code I start the worker with.

**Comment by inlife** [comment]
Oh, that looks awesome! Supporting the idea 150%!

**Comment by limzykenneth** [comment]
No big hurry on this but I see 1.34.0 is released on GitHub but I'm not seeing it on NPM yet. Both for core and worker

**Comment by inlife** [comment]
Pushed out an npm update as well (had to mark it 1.34.1 instead).
