### ISSUE TITLE
Add ESLint with some simple rules

### ISSUE THREAD

**Issue by nihey** [inlife/nexrender#677]
**Is your feature request related to a problem? Please describe.**
Nexrender is a great project, I use it internally in my company and sometimes we make some changes and adaptations to our needs.

One thing that makes it harder to contribute back to it is that we use it with a ESLint with some basic rules (like not using semicolons), and pass the code through a CI that enforce all of those rules. This leads to massive conflicts when we want to merge Nexrender code or if we wish to contribute something back.

Adding a basic ESLinting for the project and enforcing some of those rules could help us keep the same code standard as the original project and minimize these conflicts.

**Describe the solution you'd like**
We could agree in some basic rules under the usage (or not) of semicolon, build a `.eslintrc` file and add a CI that ensures these rules are being followed through the project.

One thing that the project would also benefit from is that it could lint the code for problems.

**Comment by inlife** [comment]
Hey @nihey 

Actually, I do not see reasons why not. Would you be able to create a PR with needed changes, if that is not too much to ask?

Cheers!

**Comment by nihey** [comment]
No problems! I'll submit a PR soon.

**Comment by inlife** [comment]
Thank you @nihey :)
