### ISSUE TITLE
Will this allow Google Sheets to submit JSON data to the Nexrender API?

### ISSUE THREAD

**Issue by rstrblstr** [inlife/nexrender#678]
I realize this is not currently a feature, but I came across this tutorial to connect Google Sheets to a Node.js application https://sheetdb.io/use-cases/google-spreadsheet-data-with-node-js

**Does anyone know whether this process would potentially work with the Nexrender API?**

I have a friend that would love to have a Google Sheets button that submits data to the renderer, or a Node.js application that contacts it and then submits to the API, but I'm still a novice when it comes to this stuff. I'd gladly pay someone to consult briefly and teach me how to achieve this.

**Comment by fabform** [comment]
Handy to locate google sheet id
[find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by inlife** [comment]
Most likely something like that could be achieved with Google Spreadsheets scripting via Apps Script:

https://developers.google.com/apps-script/guides/sheets
https://stackoverflow.com/questions/14742350/google-apps-script-make-http-post

**Comment by rstrblstr** [comment]
These look like great suggestions. Many thanks!
