### ISSUE TITLE
Running into Dependencies Issues When Installing With npm

### ISSUE THREAD

**Issue by nhicksdesign** [inlife/nexrender#682]
I'm guessing I installed this incorrectly, but whenever I try to install using npm i -g @nexrender/cli @nexrender/action-copy @nexrender/action-encode, I get this list:

npm WARN @nexrender/core@1.35.0 requires a peer of @nexrender/action-upload@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nexrender/core@1.35.0 requires a peer of @nexrender/provider-ftp@^1.17.2 but none is installed. You must install peer dependencies yourself.
npm WARN @nexrender/core@1.35.0 requires a peer of @nexrender/provider-gs@^1.21.3 but none is installed. You must install peer dependencies yourself.
npm WARN @nexrender/core@1.35.0 requires a peer of @nexrender/provider-s3@^1.21.4 but none is installed. You must install peer dependencies yourself.

+ @nexrender/cli@1.35.0
+ @nexrender/action-encode@1.28.2
+ @nexrender/action-copy@1.24.2
updated 3 packages in 4.657s

I've gone and manually tried to install those specific versions with npm as well, but to no avail. A nexrender folder was definitely created in my node_modules folder, but so far any nexrender commands I enter are not found.

**Comment by inlife** [comment]
Hey,

Which error do you actually get when you attempt to run `nexrender-cli` ?

**Comment by nhicksdesign** [comment]
Hey!
I just got a simple nexrender-cli: command not found

**Comment by nhicksdesign** [comment]
And then when I go to try installing again with npm i -g @nexrender/cli @nexrender/action-copy @nexrender/action-encode, I get this:

npm WARN @nexrender/core@1.35.0 requires a peer of @nexrender/action-upload@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nexrender/core@1.35.0 requires a peer of @nexrender/provider-ftp@^1.17.2 but none is installed. You must install peer dependencies yourself.
npm WARN @nexrender/core@1.35.0 requires a peer of @nexrender/provider-gs@^1.21.3 but none is installed. You must install peer dependencies yourself.
npm WARN @nexrender/core@1.35.0 requires a peer of @nexrender/provider-s3@^1.21.4 but none is installed. You must install peer dependencies yourself.

+ @nexrender/action-copy@1.24.2
+ @nexrender/cli@1.35.0
+ @nexrender/action-encode@1.28.2
updated 3 packages in 7.99s

**Comment by nhicksdesign** [comment]
Not sure why, since it looks like nexrender has indeed been installed. I have not tried manually installing the binaries though. I'm still a bit of a Terminal beginner, so I'm not 100% on how to install that way. I assumed npm would work just fine.
