### ISSUE TITLE
EXR sequence?

### ISSUE THREAD

**Issue by imgntn** [inlife/nexrender#683]
Hi!

I have a project with 1 EXR sequence  of 240 frames that is used on 3 different layers.

Layer 1
Layer 2
Layer 3

I'd love to swap that EXR sequence for another EXR sequence and render a PNG sequence out.

In After Effects I would choose Replace Footage -> File -> and then choose the first EXR and make sure 'import as sequence is clicked'.

I've used nexrender before but I'm having trouble getting this workflow to work.  Is it supported?

Any tips on how to set up the job?

Thanks in advance for your time and your help!  And of course for the awesome library to start with!!

**Comment by inlife** [comment]
Hey there @imgntn 

Unfortunately, this kind of import and asset delivery is not possible with nexrender at the moment.

The import itself seems like a doable task, with this script as an example: https://aenhancers.com/viewtopic.php?t=2479

But more complex question for now is how to build a networked delivery of those assets.

Oh and sorry for such a long response time! 😅
