### ISSUE TITLE
Spaces/special chars in linked assets

### ISSUE THREAD

**Issue by anthonyharrison44** [inlife/nexrender#687]
**Describe the bug**
We are using nexrender to download and insert images and/or videos assets into the AEP with the http/https protocol. We encounter issues when the linked file has a space and/or special character in the URL file name. Eg. https://assets.seen.io/static/landingpages/testing/crystal%203.png

The asset downloads as "crystal%203.png" rather than "crystal 3.png" as seen in screenshot below.

AE errors before the render begins.

**Information about environment**
* Which version of nexrender are you using? 1.37.0
* What kind of the setup do you have? (server+worker or cli) server+worker
* Are you using pre-built binaries or globally installed npm packages? npm packages
* Which kind (and version) of operating system you are running it in? Windows 10 / AE2022 (Also tested on 21 and 20)
* Any additional information that might be helpful

**Expected behavior**
Spaces and special encoded characters in URL file names are converted back to space or character.

**Screenshots**
<img width="640" alt="Screen Shot 2022-01-10 at 19 27 37" src="https://user-images.githubusercontent.com/59919458/149996087-639e1902-aeb5-47d5-8d18-3110d717dd3c.png">

**Comment by inlife** [comment]
Should be resolved in `v.1.37.1`

**Comment by anthonyharrison44** [comment]
Issue still occurring with v1.37.1

**Comment by anthonyharrison44** [comment]
@inlife bump

**Comment by inlife** [comment]
@anthonyharrison44 please check out if the new `v1.37.3` resolves the issue for you!

**Comment by anthonyharrison44** [comment]
Getting an error after update:

`C:\Users\AErender>C:\Users\AERender\AppData\Roaming\npm\nexrender-worker  --host=http://127.0.0.1:3050 --multi-frames
internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\@nexrender\core\node_modules\node-fetch\src\index.js
require() of ES modules is not supported.
require() of C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\@nexrender\core\node_modules\node-fetch\src\index.js from C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\@nexrender\core\src\tasks\download.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\@nexrender\core\node_modules\node-fetch\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\@nexrender\core\src\tasks\download.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'ERR_REQUIRE_ESM'
}`

**Comment by anthonyharrison44** [comment]
@inlife still getting the same error on 1.37.4

**Comment by anthonyharrison44** [comment]
@inlife 

C:\Users\AErender>C:\Users\AERender\AppData\Roaming\npm\nexrender-worker  --host=http://127.0.0.1:3050 --multi-frames
C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\@nexrender\core\src\tasks\download.js:4
const fetch    = require('node-fetch')
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\node-fetch\src\index.js from C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\@nexrender\core\src\tasks\download.js not supported.
Instead change the require of index.js in C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\@nexrender\core\src\tasks\download.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\@nexrender\core\src\tasks\download.js:4:18)
    at Object.<anonymous> (C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\@nexrender\core\src\index.js:16:22)
    at Object.<anonymous> (C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\worker\src\bin.js:5:18) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by inlife** [comment]
Hey @anthonyharrison44 

Published version v1.37.5. It has a downgraded version of node-fetch, that solved issues on my end. 

Could you please also check to see if that helped with the issue on your end?

Thank you!

**Comment by anthonyharrison44** [comment]
@inlife 

npm ERR! code EBUSY
npm ERR! syscall rename
npm ERR! path C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\@nexrender\core\src\tasks
npm ERR! dest C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\.worker-7GXTvjxn\node_modules\@nexrender\core\src\tasks
npm ERR! errno -4082
npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\worker\node_modules\@nexrender\core\src\tasks' -> 'C:\Users\AErender\AppData\Roaming\npm\node_modules\@nexrender\.worker-7GXTvjxn\node_modules\@nexrender\core\src\tasks'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AErender\AppData\Local\npm-cache\_logs\2022-02-03T06_11_09_828Z-debug-0.log

[2022-02-03T06_11_09_828Z-debug-0.log](https://github.com/inlife/nexrender/files/7992215/2022-02-03T06_11_09_828Z-debug-0.log)

Folders are not named correctly anymore in the node modules:
<img width="558" alt="Screen Shot 2022-02-03 at 07 19 24" src="https://user-images.githubusercontent.com/59919458/152291638-b425686a-974c-49f7-a344-c7fd4b897b73.png">

**Comment by anthonyharrison44** [comment]
Had a separate issue but now tested and working
