### ISSUE TITLE
How to set priority of a job?

### ISSUE THREAD

**Issue by DigitalTwelfthMan** [inlife/nexrender#690]
From the server documentation there's seemingly a way to set the priority of a job on the server and then the server be able to send the highest priority job to the worker. 

The documentation is incomplete on this and should be more comprehensive. 

- How do we set priority in the json payload we send to the nexrender server
- What's the ordering for priority (1 is highest or lowest priority?)

Any help  you can provide in filling these gap would be great.

**Comment by JamesBotterill** [comment]
bump

**Comment by hannesfant** [comment]
> How do we set priority in the json payload we send to the nexrender server
 You just pass it as another field

> What's the ordering for priority (1 is highest or lowest priority?)
The higher the number the higher the priority, in case of a tie the older job is chosen
