### ISSUE TITLE
An unexpected error occurred while exporting a composition.

### ISSUE THREAD

**Issue by anthonyharrison44** [inlife/nexrender#692]
**Describe the bug**
Included a 4 aerender logs from different composition renders. Renders are failing as you can see from the logs. This happens at random. The biggest issue however is that a valid file (.mov ProRes 422) is still created but is cut short from where the render crashed. This is problematic as it's then very difficult to know that a render has failed especially when working with an automated workflow.

**Crash logs:**
[aerender-A7Gmo7C4Y1Qy90CgPYzzN.log](https://github.com/inlife/nexrender/files/7983254/aerender-A7Gmo7C4Y1Qy90CgPYzzN.log)
[aerender-ejnngv8rpueXd8ki7z67s.log](https://github.com/inlife/nexrender/files/7983255/aerender-ejnngv8rpueXd8ki7z67s.log)
[aerender-KCjZ5F-7nF9n0g2zUSOQ8.log](https://github.com/inlife/nexrender/files/7983256/aerender-KCjZ5F-7nF9n0g2zUSOQ8.log)
[aerender-Faoatljuiyl1fFZ8xGP_W-ahlsell-crash.log](https://github.com/inlife/nexrender/files/7983258/aerender-Faoatljuiyl1fFZ8xGP_W-ahlsell-crash.log)

**Information about environment**
* Which version of nexrender are you using? 1.37.0
* What kind of the setup do you have? (server+worker or cli) Server + worker
* Are you using pre-built binaries or globally installed npm packages? npm
* Which kind (and version) of operating system you are running it in? Windows 10
* Any additional information that might be helpful - aerender version 22.0x111

**Expected behavior**
Is there a way that nexrender could detect when an error is thrown within aerender and fail the render thus it can be retried?

Any help here is appreciated.

**Comment by inlife** [comment]
Hey @anthonyharrison44 

I've found a similar question from the community on AE forums: https://community.adobe.com/t5/after-effects-discussions/after-effects-error-rendering-plug-in-instance-verification-failed-26-400/td-p/12057819

Is that something that is applicable to your case?

**Comment by anthonyharrison44** [comment]
Already set to classic 3D
