### ISSUE TITLE
Rendering fails with -reuse flag on aerender

### ISSUE THREAD

**Issue by sumukhavadhani** [inlife/nexrender#699]
Hi,

I am using nexrender with the latest version of After Effects `aerender version 22.2x120` on Mac M1. 
On passing the `reuse` flag, I get the following error:

```
aerender version 22.2x120
PROGRESS: Launching After Effects...
aerender SYNTAX ERROR: Illegal argument flag: -reuse
```

Things tried so far:
1. Forced reinstall of the patch
2. Updated AE to latest version

Any help with this is greatly appreciated. Also, would it help to switch to a Windows machine with the latest AE version?

**Comment by oreporan** [comment]
why was this closed?

**Comment by pochenok** [comment]
I'm having the same issue
mac os, after effects 23.1 (the only installed)
with --reuse flag it fails saying something about "illegal flag". (tried --reuse / --reuse=true)
without it - works just fine

**Comment by pochenok** [comment]
aerender SYNTAX ERROR: Illegal argument flag: -reuse
aerender version 23.1x83
PROGRESS: Launching After Effects...
