### ISSUE TITLE
nexrender-worker stuck at 'rendering job' 

### ISSUE THREAD

**Issue by gijspouwels** [inlife/nexrender#700]
First of all, thanks a lot for this amazing project, which is exactly what I was looking for!

I managed to get a job rendering locally with _nexrender-cli_, then I setup  _nexrender-server_ on a remote server to receive and distribute jobs, and run _nexrender-worker_ on my local machine to retreive jobs. However, the worker seems to get stuck at rendering the job:

```
[qBG2psD-0KhbpZmQCqqwV] setting up job...
[qBG2psD-0KhbpZmQCqqwV] working directory is: /var/folders/6f/wyjqt5_d0_d2pp17k8ntz0nr0000gn/T/nexrender/qBG2psD-0KhbpZmQCqqwV
[qBG2psD-0KhbpZmQCqqwV] applying predownload actions...
[qBG2psD-0KhbpZmQCqqwV] downloading assets...
[qBG2psD-0KhbpZmQCqqwV] applying postdownload actions...
[qBG2psD-0KhbpZmQCqqwV] applying prerender actions...
[qBG2psD-0KhbpZmQCqqwV] running script assemble...
[qBG2psD-0KhbpZmQCqqwV] rendering job...
```

After a while, the scripts breaks with the following error:

```
[qBG2psD-0KhbpZmQCqqwV] rendering took ~251.97 sec.
[qBG2psD-0KhbpZmQCqqwV] writing aerender job log to: /var/folders/6f/wyjqt5_d0_d2pp17k8ntz0nr0000gn/T/nexrender/aerender-qBG2psD-0KhbpZmQCqqwV.log
[qBG2psD-0KhbpZmQCqqwV] dumping aerender log:
aerender version 18.4.1x4
PROGRESS: Launching After Effects...
aerender ERROR -1712: AESend failed to send apple event at line 909

[qBG2psD-0KhbpZmQCqqwV] error occurred: Error: Couldn't find a result file: /var/folders/6f/wyjqt5_d0_d2pp17k8ntz0nr0000gn/T/nexrender/qBG2psD-0KhbpZmQCqqwV/result.mov
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@nexrender/worker/node_modules/@nexrender/core/src/tasks/render.js:205:31)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
```

There is indeed no _result.mov_, so it seems like nothing has been rendered at all. The log file:

```
aerender version 18.4.1x4
PROGRESS: Launching After Effects...
aerender ERROR -1712: AESend failed to send apple event at line 909
```

Now, when I try the same job locally with _nexrender-cli_, it will also freeze at the same point until I delete the _ae_render_only_node.txt_ files that the worker created in my documents folder (my local machine is running macOS 10.12). When I delete those files and try again with _nexrender-cli_, it renders the job perfectly again, taking about 22 seconds.

Has anyone experienced this?

**Comment by crisdeb** [comment]
I also get stuck on:

`[Dga5eXBEpOUCjXAeXTdQm] rendering job...`

But in my case the script remains blocked forever. Without error message or end of operation.

I use Windows 10 and nexrender-cli-win64.exe version 1.38.0

The strange thing is that sometimes the same json script executes the renderin sometimes not, yet the files and resources are always the same.

What can it depend on?

**Comment by gijspouwels** [comment]
Have you already tried deleting the _ae_render_only_node.txt_ file in both _C:\Users\Public\Documents\Adobe_ and _C:\Users\(username)\Documents_? For the CLI version (not the worker) this did the trick for me. Eventually, I also got the worker to render by the way. Although I would have to look into it to to remember what exactly made it work.

**Comment by crisdeb** [comment]
Hi thanks, 
the problem is the encoding of the file.

if I use **Unicode UTF8 (without BOM)** everything works correctly
