### ISSUE TITLE
notarget No matching version found for @nexrender/provider-sftp@^1.37.10.

### ISSUE THREAD

**Issue by benjioh5** [inlife/nexrender#707]
**Describe the bug**
```
npm WARN   peer @nexrender/action-upload@"^1.0.0" from @nexrender/core@1.37.10
npm WARN   node_modules/@nexrender/core
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nexrender/provider-sftp@^1.37.10.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2022-03-01T11_54_04_709Z-debug-0.log
```
https://github.com/inlife/nexrender/blob/d3b634511e9b74a4d3d59d75a11e3749eb764795/packages/nexrender-provider-sftp/package.json#L3

https://github.com/inlife/nexrender/commit/04c9c8c4dab982d7f4270a61ed9755f5192a1f3c#r67704969

**Information about environment**

window server

**Expected behavior**
Install well. change dependency 1.37.10 to 1.37.9

**Screenshots**

**Comment by limzykenneth** [comment]
Getting this error currently as well and cannot install nexrender as a result.

**Comment by benjioh5** [comment]
Solved this problem by merging #708
@limzykenneth

**Comment by limzykenneth** [comment]
Still need a new release to fix the current broken one on NPM.

**Comment by limzykenneth** [comment]
@inlife Can a new release be pushed to NPM ASAP? Not being able to install Nexrender is starting to block my workflow. Thanks!

**Comment by formikaro** [comment]
> Solved this problem by merging #708 @limzykenneth

This problem seems to persist on my machine, see attatched screenshot+log

[](url
[2022-03-07T10_21_34_876Z-debug-0.log](https://github.com/inlife/nexrender/files/8196900/2022-03-07T10_21_34_876Z-debug-0.log)
![Screenshot 2022-03-07 112940](https://user-images.githubusercontent.com/76885552/157014371-04643b44-9a15-4f6c-8a2b-ebe155dd7b74.jpg)
)

**Comment by benjioh5** [comment]
@formikaro Patch is not yes distributed.

**Comment by formikaro** [comment]
I see, then please distribute it :)

**Comment by benjioh5** [comment]
LTGM
