### ISSUE TITLE
Improve nexrender-server pickup implementaion

### ISSUE THREAD

**Issue by ivansenic** [inlife/nexrender#711]
**Is your feature request related to a problem? Please describe.**
Running `nexrender-server` with thousands of jobs, makes the `pickup` endpoint go through all the entries in order to find the next job for pickup. 

This might work fine with the disk database, but that can not be scaled to multiple server instances. At least for us on GCP as it does not support `ReadWriteMany` with persistent disks.

Running with the Redis support, makes it even worst as Redis needs to load all keys that are currently in the cache. Yes then scaling is easy, but then the op takes really long once you have thousands of jobs. But regardless of Redis, the problem would exist if you try to implement any backing database, loading all jobs just to pick one seems wrong, especially as the amount of `queued` jobs could be small.

**Describe the solution you'd like**
Not sure. I was thinking simplest thing would be add `fetchByState` method to the database interface. However, this would expose the issue when there are bunch of the queued jobs. Maybe a more direct `pickQueued` makes sense, but this would break things like `priority` and the implementation needs to understand if oldest or newest jobs should be returned first.

The Redis would still suffer, but support with Redis JSON or MongoDB would be able to pick up jobs easily.

**Comment by limzykenneth** [comment]
Unless a lock is implemented on the storage side, wouldn't running multiple instances of the server accessing the same data source cause race conditions?

**Comment by ivansenic** [comment]
Yes I am not talking about the disk database approach here. I am talking about possibility to have a backing database that would make the instance of the `nexrender-server` stateless. 

Running multiple instances, so you can avoid having single point of failure. Those can be placed in different zones and/or regions.
