### ISSUE TITLE
Script Asset regex parsing not picking up parameter names

### ISSUE THREAD

**Issue by rafravago** [inlife/nexrender#716]
When running a job, I get the following error : 

```
[qcVyjSzTHZq75OMIQl4z3]  -- W A R N I N G --
        The following parameters used in the script were NOT found on the JSON "parameters" object of your script asset <myscriptname>.jsx

            t, t, t, t, t

        Please set defaults in your JSX script (see documentation) or copy the following placeholder JSON code snippet and replace the values with your own:

            "parameters" : [

                {
                    "key" : "t",
                    "value" : null
                }
```
Tracing it down to nexrender-core/src/tasks/script.js >  EnhancedScript.prototype.findMissingMatchesInJSX, the following line : 
```
// Parse all occurrences of the usage of NX on the provided script.        
const nxMatches = matchAll(script, this.getRegex("searchUsageByMethod")("get", "gm")).toArray();
```

returns :  `nxMatches [ 'get', 'get', 'get', 'get', 'get' ]`

my script header contains: 

```
(function() {
	
	var count = NX.get('count');
	var indices = NX.get('indices');
	var subs = NX.get('subs');
	var parts = NX.get('parts');
	var colors = NX.get('colors');
		
	var composition = NX.get('composition');
```

So it should return  `nxMatches [ 'count', 'indices', 'subs', 'parts', 'colors' ]` right.

The final output in the resulting JSX looks like this.

'''
// Parameter injection from job configuration
NX.set('composition', "main");
NX.set('indices', [...);
NX.set('subs', [...]);
NX.set('parts', [...]);
NX.set('colors', [...]);
NX.set('count', 30);
NX.set('t', null);
NX.set('t', null);
NX.set('t', null);
NX.set('t', null);
NX.set('t', null);
NX.set('t', null);
'''

Something wrong with the regex perhaps?

**Comment by ralphschuler** [comment]
Hey im facing the same issue.

Im using 
    "@nexrender/core": "^1.39.0"
    
The output when i try to render is as follows:

[pRRXg9zpwTgN8YEr6jb7N]  -- W A R N I N G --
        The following parameters used in the script were NOT found on the JSON "parameters" object of your script asset https://afterfx-api.main-test.inhausai-infra.services/static/scripts/addLayer.jsx

            t, t, t, t

        Please set defaults in your JSX script (see documentation) or copy the following placeholder JSON code snippet and replace the values with your own:

        
            "parameters" : [
                
                {
                    "key" : "t",
                    "value" : null
                }

        

                {
                    "key" : "t",
                    "value" : null
                }

        

                {
                    "key" : "t",
                    "value" : null
                }

        

                {
                    "key" : "t",
                    "value" : null
                }

        
            ]

**Comment by ralphschuler** [comment]
@rafravago 

i found the issue in my script.

the NX.get function should be atop the file and outside of the directly invocted function

```
var count = NX.get('count');
var indices = NX.get('indices');
var subs = NX.get('subs');
var parts = NX.get('parts');
var colors = NX.get('colors');
		
var composition = NX.get('composition');

(function() {
 <use the variables here>
})
```

**Comment by ralphschuler** [comment]
> @rafravago
> 
> i found the issue in my script.
> 
> the NX.get function should be atop the file and outside of the directly invocted function
> 
> ```
> var count = NX.get('count');
> var indices = NX.get('indices');
> var subs = NX.get('subs');
> var parts = NX.get('parts');
> var colors = NX.get('colors');
> 		
> var composition = NX.get('composition');
> 
> (function() {
>  <use the variables here>
> })
> ```

Never mind,

it just worked a second and then broke again
will further investigate.

**Comment by sh0shinsha** [comment]
Hey, facing the same issue.  Any updates?

**Comment by ralphschuler** [comment]
Hey,

i didnt found out why this message occurs.
but what i found is it still works.

however something is super weird with the regex, 

1. when i use a custom script with a parameter `location` which holds a path like this `C:\videos\73e292538b15cc97930b6-VID_20210803_161417.mp4` the core lib will corrupt the script files and crash.
i then escaped the slashes into this `C://videos//73e292538b15cc97930b6-VID_20210803_161417.mp4`
which will result in the script running but still crashing because my first custom script will get executed twice even if its only defined once.

**Comment by JamesBotterill** [comment]
I've found this issue, it looks like when I view the script it's injected a rouge NX.set('t', null);

**Comment by inlife** [comment]
What would be a way to fix that?

**Comment by JamesBotterill** [comment]
I don't think it's an issue, it just throws up a warning which can be confusing. 

Not getting a warning would be helpful though ;)

**Comment by smukkejohan** [comment]
Seems on https://github.com/inlife/nexrender/blob/9a768597dd943d147780eb1f8b6c6d2ca40ac9a0/packages/nexrender-core/src/tasks/script.js#L276  

function is exprecting the result from matchAll to contain a nested array with  the capture groups, however it does not and the match[2] keyword is the t in the string "get". 

If I use the native string.matchAll the remaining code works correctly. 

I'l make a PR for it.
