### ISSUE TITLE
Unhandled Promise rejection

### ISSUE THREAD

**Issue by Elijahdanie** [inlife/nexrender#725]
This error comes up once cleaning up.. shows

(node:10912) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: rimraf: missing path
    at rimraf (C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\node_modules\rimraf\rimraf.js:54:3)
    at C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\tasks\cleanup.js
    at new Promise (<anonymous>)
    at C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\tasks\cleanup.js
    at C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\helpers\state.js
    at C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\index.js
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async start (C:\snapshot\nexrender\packages\nexrender-worker\src\index.js)
(node:10912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10912) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10912) UnhandledPromiseRejectionWarning: Error: Couldn't find module @nexrender/provider-c, Unknown protocol provided.
    at download (C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\tasks\download.js)
    at C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\tasks\download.js
    at C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\helpers\state.js
    at C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\index.js
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async start (C:\snapshot\nexrender\packages\nexrender-worker\src\index.js)
(node:10912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
PS C:\Users\elijahdanie\Downloads\NexRender Engine>

**Comment by nicohery** [comment]
I had the same error and I just tried to log "job.workpath" in /usr/local/lib/node_modules/@nexrender/worker/node_modules/@nexrender/core/src/tasks/cleanup.js
This property was undefined. When I change "job.workpath" with "settings.workpath" it works fine but this patch is not permanent.

**Comment by Elijahdanie** [comment]
i made this modifications and it worked also, that was the issue, so when would it be live?
