### ISSUE TITLE
Debugging S3 Action Upload?

### ISSUE THREAD

**Issue by joeystevens00** [inlife/nexrender#726]
Is there logging information around s3 action upload? I don't see anything about an error in the work directory log file or worker output and don't see my file uploaded to s3. I've already run aws configure and confirmed I can access s3 using the aws cli tool.

The relevant output in the worker

```
[O2Tihv8lATpxgKPB2fCBi] starting action-upload action
[O2Tihv8lATpxgKPB2fCBi] action-upload: input file /var/folders/t_/154wlzzn5f554gnfyp69_27h0000gn/T/nexrender/O2Tihv8lATpxgKPB2fCBi/result.mp4
[O2Tihv8lATpxgKPB2fCBi] action-upload: output file https://s3-us-east-1.amazonaws.com/nexrender-assets/poc_example.mp4
[O2Tihv8lATpxgKPB2fCBi] cleaning up...
```

input
```
   "actions": {
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "result.mp4"
            },
            {
                "module": "@nexrender/action-upload",
                "input": "result.mp4",
                "provider": "s3",
                "params": {
                    "region": "us-east-1",
                    "bucket": "nexrender-assets",
                    "key": "poc_example.mp4",
                    "contentType": "video/mp4",
                    "acl": "private"
                }
            }
        ]
    }
```

**Comment by Pilskalns** [comment]
For a short time-debug solution you could find an S3 provider file in `node_modules` and enable AWS SDK debugging to the console.

Here's the file I mean:
https://github.com/inlife/nexrender/blob/master/packages/nexrender-provider-s3/src/index.js#L5

And here's a rabbit hole to AWS docs:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/logging-sdk-calls.html

Happy debugging 🙂
