### ISSUE TITLE
How to change Text layer text to bold and italic

### ISSUE THREAD

**Issue by sitestrokes** [inlife/nexrender#727]
Hello,

I am able to change the font family and font size,

Here is the e.g. : 
 { "type": "data", "layerName": "service B", "property": "Source Text", "value": "Hello" },
 { "type": "data", "layerName": "service B", "property": "Source Text.font", "value": "Poppins" },

How to make that font bold and italic,
I have checked the font properties and get some properties like: 

1) FauxBold(value) -> bold
2) FauxItalic(value) -> Italic

I have tried but not getting output 
Let me help how to set properties

Thanks in advance

**Comment by olekristensen** [comment]
Hi there,
For this i think you have to use the PostScript name of the font and variant, e.g:
`{ "type": "data", "layerName": "service B", "property": "Source Text.font", "value": "Poppins-Bold" },`
