### ISSUE TITLE
Worker stops after a while

### ISSUE THREAD

**Issue by schwampf** [inlife/nexrender#732]
HI there,

I am working on a project using nexrender server and worker. Both are running on an external Windows Server 2019.
For testing purposes i set up a large queue with about 50 jobs.
The worker does what it should do, picking up job by job. But after a while the worker stops working and hangs. Most of the time after about 30 Minutes, sometimes after 2-3 hours. 
The strange thing is, this problem has never occurred while I was still connected to the server via remote desktop.

When I reconnect via RDP, I see the worker stops. In Task Manager, After Effects has still a running process, taking Memory and about 10% of the CPU.

Has Anyone ever had such an issue?

I would appreciate some help as I'm the project for a client and I'm running out of time.

**Comment by anthonyharrison44** [comment]
I believe I'm having this same issue, have you made any progress?

**Comment by schwampf** [comment]
I wouldn't call it a pregress, but before I launched the projekt, I did a last Update on After Effects and Nexrender. Since then, the Server and worker is running and the customer is rendering about one video a day. So far the worker didn't stop. But I didn't run a large render queue since the launch. Maybe the problem only occurs when the worker does many jobs in a row?

**Comment by anthonyharrison44** [comment]
You might be right, I've submitted a similar issue here - https://github.com/inlife/nexrender/issues/733

Can I ask which versions of AE and nexrender you are currently running?

**Comment by schwampf** [comment]
> You might be right, I've submitted a similar issue here - #733
> 
> Can I ask which versions of AE and nexrender you are currently running?

nexrender-version: 1.39.1
After Effects: 22.4

**Comment by hetarth18** [comment]
can we mark it as fresh? facing the same issue.

**Comment by inlife** [comment]
https://github.com/inlife/nexrender/issues/733#issuecomment-1223886260

**Comment by angelch94** [comment]
For those of you using command prompt in Windows, maybe this could be useful:
https://stackoverflow.com/questions/70773392/node-js-executable-hangs-up-unexpectedly
