### ISSUE TITLE
Is `applyPreset` not supported on the command line？

### ISSUE THREAD

**Issue by jinzhan** [inlife/nexrender#734]
I wanna add some effects with the `.ffx` preset file, and it works well when using After Effect application on my MacBook. But it won't work when I use nexrender. Here is the code.

```js
   function findCompByName(CompItemName) {
        var project = app.project;
        var numItems = project.numItems;

        for (var i = 1; i <= numItems; i++) {
            var item = project.item(i);
            if (item instanceof CompItem && item.name === CompItemName) {
                return item;
            }
        }
    }            

  var curItem = findCompByName('Text1');
  var textLayer = curItem.layers[1];
  var file = new File('/Applications/Adobe After Effects 2022/Presets/Text/Rotation/flower.ffx');

  app.beginUndoGroup('apply preset');
  textLayer.selected = true;
  alert(textLayer.name);
  
  // The next line of code doesn't work, and even throw an error in Windows system
  textLayer.applyPreset(file);
  textLayer.selected = false;
  app.endUndoGroup();
```

I would greatly appreciate your help.

**Comment by njho** [comment]
Hey was there any result from this? We're experiencing the same issue. Thanks @jinzhan

**Comment by inlife** [comment]
Actually, could it be that alert prevents any further execution on CLI environment?
Also, I know its quite late but @jinzhan do you by accident have that error that is being thrown by windows?

**Comment by inlife** [comment]
Another question, what are you trying to achieve with a preset? @njho 
Maybe same behaviour can be replicated without using presets?

**Comment by njho** [comment]
Yeah I made sure to remove any alerts in the code that wouldn't be supported by CLI.

After finding out this was an issue we rewrote some expressions and manually set the effects to avoid requiring the preset.

So now we have a CLI version and UI version of a plugin
