### ISSUE TITLE
Active Job Cleanup Exemption

### ISSUE THREAD

**Issue by evantayloryates** [inlife/nexrender#745]
Currently, the cleanup command (`nexrender-cli -c` or `nexrender-cli --cleanup`) will clean up the artifacts from _all_ past jobs, including jobs that are **actively running**. Cleaning up active job files often results in unexpected behavior or errors. 

Ideally, this command would only remove files for completed jobs. A purely additive alternative would be to support a `--soft-cleanup` CLI option.

Note: I didn't label this as a bug since I wouldn't necessarily say the existing cleanup behavior is wrong

**Comment by inlife** [comment]
Good point there, @evantayloryates!

Do you have suggestions on how something like that could be achieved?
