### ISSUE TITLE
Trying to get NEXrender to work

### ISSUE THREAD

**Issue by jalmar2000** [inlife/nexrender#747]
Dear creator's/ users of nexrender,

I've been trying to get nexrender to work but as I have very little knowledge of working with the MacOS terminal or any other code I've been having a hard time getting nexrender to work for me and I was hoping if someone would be able to get me any further as i would love to learn how I can use nexrender. 

**Final goal to use nexrender for**
I have to make a lot of lowerthirds where the names change all the time. We have a template with two text fields which I would like to be populated from a CSV. 

**What I've done so far**
I have made a first .json file following the tutorial mentioned in the github file. I've downloaded the CLI and given it it's own folder where i also store the .json and the assets folder. Then the next step is where it all comes to a hold. I navigated to the nexrender folder in the terminal and ran the command: 
`jalmarverbraak@Jalmars-MacBook-Pro ~ % nexrender-cli-macos --file main.json --binary="/Applications/Adobe After Effects 2022/aerender"

zsh: command not found: nexrender-cli-macos

jalmarverbraak@Jalmars-MacBook-Pro ~ % `
which resulted in getting a zsh error.
I've checked that zsh is working with a basic command like netstat.
Also I've been searching online but from what I've seen the command seems to be right. 

If someone knows how to fix this problem that would be amazing. Thanks in advance!!

**Comment by inlife** [comment]
Hey,

Please refer to the documentation on how to run CLI apps for macOS. Alternatively, take a look at this answer: https://stackoverflow.com/questions/15080835/running-an-executable-in-mac-terminal#15080940

Cheers!

**Comment by jalmar2000** [comment]
Dear Inlife,

This was exactly the information I needed. After a lot of trial and error with the right src paths in my .json and the some other difficulties I managed to get my first test render out of nexrender. I am looking forward to playing around with this even more.

**Comment by jalmar2000** [comment]
maybe another question that I have is how to encode in proress 4444 with alpha.
I've tried a lot of params at the action-encode and I've also added an outputModule and OutputExt in the template section but it either works but gives me a H.264 video in .mov(which doesn't have the transparent layer) or it gives me an error when I try to use -vcodec prores-ks.

**Comment by anthonyharrison44** [comment]
Your output from AE is Prores 4444 with alpha? What are you trying to encode it to? What’s the goal? H.264 doesn’t support an alpha channel (https://www.digitalrebellion.com/blog/posts/list_of_video_formats_supporting_alpha_channels.html)

**Comment by jalmar2000** [comment]
the outputModule is indeed a preset a made with Proress 4444 channels RGB + Alpha. I would like to encode it to an .mov as indeed h.264 doesn't support the alpha channel but I can't seem to get an .mov file with alpha in a proress 4444 codec. I have gotten a .mov video out of nexrender but when I check the codec information with VLC it displays as a h.264 codec.

**Comment by anthonyharrison44** [comment]
Nexrender actually outputs the default AE output module into a temp folder before running the post render actions. I'm not exactly sure where this temp folder is on a Mac but I'd look inside the nexrender cli folder to start. For your post render actions you have two options:
1. Use the copy module and do not encode the output file. Not sure if this will work as I've never tried that specifically. 
2. Use copy video and audio in the encode module, you'll have to look this up but you're basically just re encoding the same file with the same settings. 

It's important to note that a codec is different to a container. Eg .mov can house various codecs, hence why you've been able to output a .mov with h.264.
