### ISSUE TITLE
Related with the rendering AEP templates.

### ISSUE THREAD

**Issue by kishanPrajapat-Forcebolt** [inlife/nexrender#753]
@inlife 
@inlife 

Can you guide me. What can I do ?
First of all, We can use this library for rendering the AEP templates files and automate the project. 
For rendering AEP template, we need aerender executable file and also we need adobe software for rendering it. But My question is that like how can we render the AEP template on the server.  Like, is it possible to run After Effects on a server to render videos or you can say  running aerender on the server.

Can anyone give me solution for this or you can guide me for the same ?

**Comment by limzykenneth** [comment]
As long as After Effects is installed on a server, it can run nexrender. You may want to look into the `nexrender-server` and `nexrender-worker` for effective remote rendering. You don't need to activate the After Effects installation on the server as well.

**Comment by kishanPrajapat-Forcebolt** [comment]
But is it will work. Like it needs aerender which is in adobe after effects software.

**Comment by limzykenneth** [comment]
Yes, it will need after effects to be installed. Nexrender does not work without after effects.

**Comment by kishanPrajapat-Forcebolt** [comment]
@limzykenneth Thank you so much.
One question, Can we run adobe after effects on server. If adobe after effects runs on server then it can render any templates on server. Like we don't need to installed adobe on our local and we renders any templates dynamically.
It is possible or not?

**Comment by limzykenneth** [comment]
As long as the server you have is running Windows or macOS and thus can install After Effects, they will work. You will need to set up Nexrender, make all assets available to the server, and expose the server to the internet but if you can do those as well you can render on a remote server and there's no need to install after effects locally.

**Comment by kishanPrajapat-Forcebolt** [comment]
ok got it. 
@limzykenneth thanks.

**Comment by limzykenneth** [comment]
That depends on where you are getting your server. I'm using Azure VM with Windows Server 2016 and RDP in to install After Effects and setting up Nexrender worker then the rest I can run on any other server (including Linux). Installing After Effects on Windows Server is the same as how you would do it for a local desktop, install Creative Cloud then install the trial version of After Effects, no need to activate it with a license.

**Comment by kishanPrajapat-Forcebolt** [comment]
Thanks you so much @limzykenneth.
Talking about the nexrender worker, 
![image](https://user-images.githubusercontent.com/96729877/184823213-5fce4a5a-d034-4e28-9ae9-dd7484b2bb24.png)
In this image, like we need the server hosted URL and secret key of the windows server.
Then it takes WorkPath and binary path of nexrender/aerender from the deployed windows server.

**Comment by kishanPrajapat-Forcebolt** [comment]
Thanks @limzykenneth
Let me check with this.
