### ISSUE TITLE
Related with After Effects Error: File Not Found: 

### ISSUE THREAD

**Issue by kishanPrajapat-Forcebolt** [inlife/nexrender#755]
Hi @inlife @inlife 
I have some AEP templates. When I made changes in them and save it. It takes the absolute path of the saving destination and for all the assets in AEP folder. When I going to render AEP video template using Nexrender in mine device where I've made changes, it is rendering fine but the main problem comes into the picture is that when I send the AEP folder to different device means when I render the AEP file into different devices. It gives me the error of file not found (either assets file attach with AEP project file or any other assets) means it takes the absolute path of mine system where I've have made changes first. 

Can you give me solution for this and guide me for the same.
Thanks

**Comment by kishanPrajapat-Forcebolt** [comment]
@inlife 
@inlife 
can anyone tell me about this or can you guide me what can I do?

**Comment by limzykenneth** [comment]
I had dealt with this in 3 different ways before:

1. Define all the required assets [through Nexrender](https://github.com/inlife/nexrender#footage-items) (this is what I'm doing now)
2. Open up the project in After Effects, resolve the missing footage warnings, and re-save the project on the server
3. Save the project as .aepx (XML file) and programmatically change the root paths to match the server's path (I have done this before but may not be possible in newer version of After Effects)

**Comment by kishanPrajapat-Forcebolt** [comment]
Thanks for replying @limzykenneth 
1. Yes, I have done with defining all assets but what happened if there are more footage assets with AEP file. Like, 50 or more than.  Then also we have to define the assets.

2. You are saying that resolve the missing footage and save it on the server. Means, suppose I have windows server on azure or something there I have to save it in adobe after effect.

3. Let me for this one in newer version. because I'm using newer version.

**Comment by limzykenneth** [comment]
> Yes, I have done with defining all assets but what happened if there are more footage assets with AEP file. Like, 50 or more than. Then also we have to define the assets.

That's the trade for with this solution. For me I'm handling it all programmatically because my use case makes it possible, so it's not a problem for me.

> You are saying that resolve the missing footage and save it on the server. Means, suppose I have windows server on azure or something there I have to save it in adobe after effect.

Yes, you'll RDP into the remote server, open the AE file, resolve the missing footage, then save.

**Comment by kishanPrajapat-Forcebolt** [comment]
> That's the trade for with this solution. For me I'm handling it all programmatically because my use case makes it possible, so it's not a problem for me.
Like I'm replacing my own assets for the different-different Comp layers but is it feasible to define all the assets which is always be with AEP template. Like, some video of burn effect , flare effect, So for these also any user have to have these types of assets to render videos. 

If there are some assets that is always render with AEP without defining them because adobe aerender takes absolute path for them. After running the same AEP in different devices, it doesn't takes those one. For those assets files we have define it. Am I right?

You are saying that you are handling it programmatically. But could you please explain me like how do you do it?
Because when I'm going to start rendering, there is one script file generated for rendering. So we have to make changes in that script after generation or we have to make other script file and use it in our job assets.

Thanks

**Comment by johkon** [comment]
@kishanPrajapat-Forcebolt have you tried using action-unzip? If you collect all files in after effects and zip them, AE will look for the missing files in the (Footage) folder.

**Comment by limzykenneth** [comment]
For how I'm defining the assets programmatically, it is as described in the README [here](https://github.com/inlife/nexrender#template-rendering). Assets that form their own layers is easily replaced with footage items. More complex assets can be handled with static or data assets. Even more complex use case can use the script assets which can take care of everything (if for some reason it cannot, there is no way to do it via aerender).

You can also use the [collect files feature](https://austinnewell.net/blog/how-to-package-adobe-after-effects-project/) which may work as well, I haven't tried it as I don't really need it.

**Comment by kishanPrajapat-Forcebolt** [comment]
> For how I'm defining the assets programmatically, it is as described in the README [here](https://github.com/inlife/nexrender#template-rendering). Assets that form their own layers is easily replaced with footage items. More complex assets can be handled with static or data assets. Even more complex use case can use the script assets which can take care of everything (if for some reason it cannot, there is no way to do it via aerender).

Yeah, I get you point. I'm defining same as yours but you are saying that programmatically. So I was little bit confused. That's why I were asking. 
Thanks @limzykenneth  for helping me out.

**Comment by kishanPrajapat-Forcebolt** [comment]
> have you tried using action-unzip? If you collect all files in after effects and zip them, AE will look for the missing files in the (Footage) folder.


@johkon 
Yes I have tried this type of functionality. Like I'm collecting all the files of AEP template from adobe. and some new folder is generated for the project. and I have make zip file of this folder. And upload onto the s3. After uploading, I download the zip file and unzip it and use the AEP src in the job JSON. 

But the problem is that, when I'm collecting files of a AE project than also it is saved first then collect the files and make a folder, so it is again taking the absolute path for that folder. 

If I'm using that zip file in another device then also it is not rendering. It gives the "after effect error: file not found ". It takes the path of that folder which I saved before in another device.

Could you explain me how can I use this action unzip in another way? or mine way is also same I think. 

Thanks

**Comment by limzykenneth** [comment]
> As much as I understand that you are saying that those assets whose layers are present in aep template can be replaced with another. But in my template, there are some video layers and image layers that is attached with aep template in footage folder. If I'm not defining it in job json, the video was rendering fine because of absolute path. It is automatically taking those assets by own without defining. And using the AEP file in different device then it is not rendering because those assets which I haven't defined is giving error of not found due to absolute path of previous saved folder.

Sorry I don't quite understand the difference you are pointing out here. If an asset is added to the composition as a layer, regardless of where the asset is originally, it can be replaced by something else by defining it in the nexrender `assets` field we have been talking about; if said asset is not replaced by nexrender, it will continue to try to use whatever path is set in the aep file.

**Comment by kishanPrajapat-Forcebolt** [comment]
> Sorry I don't quite understand the difference you are pointing out here. If an asset is added to the composition as a layer, regardless of where the asset is originally, it can be replaced by something else by defining it in the nexrender assets field we have been talking about; if said asset is not replaced by nexrender, it will continue to try to use whatever path is set in the aep file.


Yeah, you are right. that's what I'm saying. 
but Why the saved folder gives error in another device. If we render this AEP file in another system. It is showing that file not found.

**Comment by johkon** [comment]
> And upload onto the s3. After uploading, I download the zip file and unzip it and use the AEP src in the job JSON.

So you use this prerender-action for downloading and unzipping? https://github.com/dylangarcia/nexrender-action-unzip

The path to your footage will still be wrong, but the footage will be in availible the temporary render folder. Normaly, After Effects will check in the folder (Footage), next to the .aep file, for missing files. This worked for me, when i had issues with absolute paths.

**Comment by kishanPrajapat-Forcebolt** [comment]
> Normally After Effects will check in the folder (Footage), next to the .aep file, for missing files.

@johkon 
It checks but using absolute path. Like you have worked on some aep template than save it, zip it and use it in different pc or system. Then it gives the error of file not found. because in that case also it takes the absolute path of previous saved footage files.

**Comment by johkon** [comment]
Ah sorry, zip the AEP and all the footage in the same folder. That's how I did it.

I was wrong about AE checking the (Footage) folder, it has to be all the same folder. Then it will work ob any PC, without absolute paths.

**Comment by kishanPrajapat-Forcebolt** [comment]
Yes, I have zipped the aep with all the assets in footage folder.

> it has to be all the same folder

you are saying, aep with assets. or all assets in footage folder.

Could you please share me your zip file that you are saying it can work in any pc. I can test it.

Thanks @johkon

**Comment by johkon** [comment]
I can't get an original zip-file right now, sorry. But you have do it like this:
![Untitled-1](https://user-images.githubusercontent.com/57528885/186609417-ff04e5fa-45eb-451b-8675-6b45e22dde04.jpg)
All the footage has to be in the same folder as the AEP-file. Then zip the files without any folders and use prerender action-unzip.

I now have a setup, where the paths are all equal on my renderworkers (mounted network storage). But I used this solution before and I'm pretty sure it still works😅

**Comment by kishanPrajapat-Forcebolt** [comment]
> I now have a setup, where the paths are all equal on my renderworkers (mounted network storage). But I used this solution before and I'm pretty sure it still works😅

Ok, Got it. Let me try with above way.
@johkon

**Comment by kishanPrajapat-Forcebolt** [comment]
@johkon
Thanks. It is working now👍👍

**Comment by kishanPrajapat-Forcebolt** [comment]
@johkon
I have one question that I have use the nexrender action-upload. And I have upload any file using it. It is successfully uploaded. But I want that URL after rendering. Because, I need to send the URL somewhere else. 
Any Idea?

**Comment by kishanPrajapat-Forcebolt** [comment]
@johkon @limzykenneth 
![image](https://user-images.githubusercontent.com/96729877/187428184-6fd0cbca-f3cb-4db3-887b-ed1ce713849a.png)

In this, It gives the error of source compression type is not supported. I don't know for what reason it gives error. 
I have recorded a video from webcam and then I have use this recorded video in rendering.
Could you tell me about this?

**Comment by kishanPrajapat-Forcebolt** [comment]
Hi @limzykenneth @johkon 
I have one question, Like I have rendered AEP file. In that file, I have replaced all the assets. In case of images, After rendering,  scale and resolution of image is small and reduced in rendered video. But in my aep file the image is in perfect form. So how do I do this.
Could you tell me? What's the problem.

**Comment by kishanprajapat2564788** [comment]
@inlife @limzykenneth @johkon Hi all,
Can you please help me out with the above error of source compression after adding webcam-recorded video to the Job JSON?

> In this, It gives the error of source compression type is not supported. I don't know for what reason it gives error.
I have recorded a video from webcam and then I have use this recorded video in rendering.

Thanks in advance!

**Comment by njho** [comment]
I bumped into this issue and realized that @nexrender/core copies the template .aep file separate of its footage into the working directory.

After modifying such that it pulls the .aep and all of its files in its folder, it works correctly
