### ISSUE TITLE
Upgrade ffmpeg-static to b5.0.1 to support M1 Macs (darwin-arm64)

### ISSUE THREAD

**Issue by danielgwilson** [inlife/nexrender#758]
**Is your feature request related to a problem? Please describe.**
Currently, `action-encode` does not function correctly on M1 Macs. This results in an `Unsupported architecture.` error when attempting to run `action-encode` as a post-render action.

**Describe the solution you'd like**
Since `ffmpeg-static` supports M1 Macs, it would be nice to update the version of `ffmpeg-static` installed upon running `action-encode`.

**Describe alternatives you've considered**
I've attempted to define the binary manually using environment variables, but it's being a bit of a pain (not picking up the `env` value)—I figured I'd add an issue here in the meantime.

**Additional context**
_N/A_

**Comment by danielgwilson** [comment]
_Temporary resolution for those interested—_

_`package.json`_
```json
  ...
  "overrides": {
    "@nexrender/action-encode": {
      "ffmpeg-static": "^5.0.2"
    }
  },
  ...
```

**Comment by inlife** [comment]
Thanks for the issue! Added a commit https://github.com/inlife/nexrender/commit/5193b73b2e950decb3c7073dc9b418a390ad2533 that should help with that
