### ISSUE TITLE
Proper Formatting to API Server

### ISSUE THREAD

**Issue by KiwiVFX** [inlife/nexrender#76]
Hello!
Thank you a ton for providing the following code! Can't explain in words how much frustration it saved.
I'm using AE for years as Motion Graphics designer. I've managed to run boiler template render successfully. Renderer and Server are running under same console. Got Appserv running for HTTP, for assets and simple form which sends post command which should trigger render.
What I'm trying to achieve is: You go on a page, Insert/select desired values/options/files and it will send it in json format to API which will shoot it to the render node so the rendering will be triggered.

I'm familiar with basic coding but not as much with java nor json files, I'm trying for over a day to send a proper request (in many forms) from form to the console, sadly without success - it won't convert properly.
Hopefully you can point out where i went wrong.

index test:
[index.txt](https://github.com/inlife/nexrender/files/2472108/index.txt)

Receiving: 
![screenshot_99](https://user-images.githubusercontent.com/44083421/46855298-f084d780-ce0b-11e8-9ce0-d1d818724435.png)

Template looks like that:
```json
{
    "template": "Simple-1.aepx",
    "composition": "Comp1",
    "settings": {
        "outputModule": "JPEG Sequence",
        "outputExt": "jpg",
        "startFrame": 0,
        "endFrame": 20
    },
    "assets": [
        {
            "type": "project",
            "src": "http://127.0.0.1/Simple-1/assets/Simple-1.aepx",
            "name": "Simple-1.aepx"
        }, {
            "type": "image",
            "src": "http://127.0.0.1/Simple-1/assets/BG.jpg",
            "name": "BG.jpg",
            "filters": [{
                "name": "cover",
                "params": [1920, 1080]
            }]
        }, {
            "type": "audio",
            "src": "http://127.0.0.1/Simple-1/assets/Audio.mp3",
            "name": "Audio.mp3"
        }, {
            "type": "script",
            "src": "http://127.0.0.1/Simple-1/assets/data.js",
            "name": "data.js"
        }
    ]
}
```

**Comment by inlife** [comment]
Hello @KiwiVFX 

First of all thank you for your kind words!

I took your html and slightly changed it into a standalone form. It should work without need of any external server, just double click the html and press submit.

**Note:** just make sure to properly setup url to the api, which might be running on a different port in your case.

![image](https://user-images.githubusercontent.com/2182108/46858304-adc6fd80-ce13-11e8-83d1-abd4d08dd262.png)

Here is the html file:
[nexrender.html.zip](https://github.com/inlife/nexrender/files/2472287/nexrender.html.zip)

Have a nice day!

**Comment by KiwiVFX** [comment]
Thanks a ton, That looks way better than mine!
After changing ports of appserv to 3000 - it doesn't seem to work, console isn't receiving anything - i'll try a fresh start and will play with it a bit, might work this out.
Keep up the great work.

All the best!
