### ISSUE TITLE
aerender ERROR An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by oncul** [inlife/nexrender#769]
I am getting error after a while on worker. I have valid adobe licences. I get the error after 10-20 render jobs. I disabled multiframe.

```
aerender ERROR An existing connection was forcibly closed by the remote host.

: Unable to receive at line 463
```

<img width="938" alt="Ekran Resmi 2022-09-07 14 31 08" src="https://user-images.githubusercontent.com/370796/188868521-71b3abdf-5d13-4184-9c0c-9a2ac91aa8c3.png">

<img width="557" alt="Ekran Resmi 2022-09-07 14 31 23" src="https://user-images.githubusercontent.com/370796/188868567-126f8dd8-41f5-4515-b78b-52b03694a18b.png">

Windows 2019 Server
After Effects v22

**Comment by limzykenneth** [comment]
Reported before in #314. I would suggest trying to isolate the error as much as possible and provide more information about your setup (eg. any remote resources, what kind of hardware, how long/big are the videos, how Nexrender is setup and run, etc).

**Comment by SimeJah** [comment]
I am still having this issue. Out of nowere it seems... And interestingly only when I am using the RE:Vision FX DE:Noise plugin. (now updated to 3.6.1)
Using AE 23.6.6 and Deadline 10.3.5.15 (Cant seem to update the repo... I get 'An error'.
Windows 11 Home 10.0.22631 Build 22631
If anyone knows how I can resolve this issue I would be very grateful!
