### ISSUE TITLE
substitute image in sub-composition

### ISSUE THREAD

**Issue by eeandrew** [inlife/nexrender#77]
It seems we can only substitute image in the main composition. Is it possible to substitute image in sub-composition?
For example, the main composition is composed by two other compositions(sub composition). I want to substitute images in the sub compositions. Is this operation possible?

**Comment by inlife** [comment]
Hello @eeandrew 
That is a good question, i've never worked with subcompositions
However, don't they (footage items) exist in project itself, and work the same way for any comp?

The thing is, the way how image replacement works, is by invalidating original absolute asset path and replacing it with the new relative one. So if AE cannot find the original file pointing to the asset via absolute path, it will try to pick up the asset with the same name, nearby the aep/aepx file.

Just seems to me that everything should work fine, at least in theory. What do you think?

**Comment by eeandrew** [comment]
@inlife  my mistake, substitute image in sub-composition works. I'll do more test and let you know the results. You can close this issue. Thanks a lot :-)
