### ISSUE TITLE
Can run job to a specific worker

### ISSUE THREAD

**Issue by mohali-id** [inlife/nexrender#770]
**Is your feature request related to a problem? Please describe.**
I want to run job to a specific worker(s) by defining worker name(s) on job meta data

**Describe the solution you'd like**
1. The worker can have an identifier such as id or name
2. Once we create a job to the server, we can add an additional job meta data to specify worker (by identifier) to execute the job

Thank You

**Comment by inlife** [comment]
Hey @mohali-id 

It is a great idea!

I do not think we still have such a system implemented for identifying the workers. But it definitely would be great to have something like that. Possibly even a simple tagging system would do.

```
$ nexrender-server --tags=primary,plugins
$ nexrender-server --tags=small
```

Actually, would you be interested in adding something like that to the tool?

**Comment by mohali-id** [comment]
Yes @inlife, it need a tagging system.
I think it would be nice if the worker has a tagging system too.
