### ISSUE TITLE
Change font-size based on available space

### ISSUE THREAD

**Issue by ehaeusler** [inlife/nexrender#772]
I have a project where the font size of some text elements is scaled based on it's available space. This is done with an expression. If I render the project normally, everything gets scaled correctly. But if I change the text property dynamically and render it via nexrender, it doesn't work as expected and the the text is way too large.

Has anyone had a similar use case or a possible solution?

**Comment by anthonyharrison44** [comment]
I see with went stale however I can confirm text scaling works with nexrender. I use the following formula to scale:
`maxW = thisComp.width * 0.9;
maxH = thisComp.height * 0.25;
r = sourceRectAtTime(time);
w = r.width;
h = r.height;
s = w/h > maxW/maxH ? maxW/w : maxH/h;
[100,100]*s`

**Comment by sops21** [comment]
> maxW = thisComp.width * 0.9; maxH = thisComp.height * 0.25; r = sourceRectAtTime(time); w = r.width; h = r.height; s = w/h > maxW/maxH ? maxW/w : maxH/h; [100,100]*s

Where did you enter this formula at? I'm running into the same issue.

**Comment by inlife** [comment]
looks like an Transform.Scale expression within a given layer
