### ISSUE TITLE
Regarding Export Video Quality

### ISSUE THREAD

**Issue by kishanPrajapat-Forcebolt** [inlife/nexrender#773]
@inlife 
I'm rendering AEP template. But I want to export the video or get the rendered video in less resolution. Like, using action encode in postrender module. But how can I define the export quality to 720p. 
![image](https://user-images.githubusercontent.com/96729877/193533707-bb3c6f3c-7e76-46e4-aeba-24a2c0282c1e.png)
In this image, I have set the scale but it is not working.
My question is that how can we reduce the scale(resolution) of video using postrender.
could you help me out?

**Comment by anthonyharrison44** [comment]
I believe this should be: 
`-vf scale=-1:720`

Alternatively if you want to spend up the entire workflow/render you can change the comp size of the render comp to 1280x720 and AE will output this resolution directly.

**Comment by kishanPrajapat-Forcebolt** [comment]
As you said, I have to define the export settings for all the templates that I'm going to use. Like in the render queue in adobe. Export high quality!! or something like this.

Can we make any global changes for export quality? For all the templates, the export quality will always be 720. We don't have to set for each template.

**Comment by kishanPrajapat-Forcebolt** [comment]
![image](https://user-images.githubusercontent.com/96729877/193781901-e0881037-920b-4107-81d2-59cd5f2bba1b.png)
as you said use this method 

> I believe this should be:
-vf scale=1280:-1

but it is giving this error!

can you please tell me what I'm supposed to do?

**Comment by youzhajun** [comment]
@kishanPrajapat-Forcebolt hello， It should be possible. There are output module settings in AE. You can set the format you want as the default.

**Comment by kishanprajapat2564788** [comment]
@youzhajun thanks for answering

**Comment by kishanprajapat2564788** [comment]
@inlife @youzhajun @limzykenneth 
![image](https://user-images.githubusercontent.com/47397967/203535287-4d52a3ee-2532-447b-a377-1c9fa4b3745b.png)

In this, It gives the error of the source compression type is not supported. I don't know for what reason it gives an error.
I recorded a video from a webcam and then I have use this recorded video in rendering.
Could you tell me about this?

**Comment by limzykenneth** [comment]
@kishanPrajapat-Forcebolt There's not enough info for me to tell what the issue is, from the error message it may be that the video recorded is not in a format readable by after effects. A better way to make sure things work is to actually run After Effects and try to render the video manually from After Effects first before trying to do it through Nexrender as you'll be able to debug easier that way.

**Comment by kishanprajapat2564788** [comment]
Thanks, @limzykenneth let me check on my end. If It can be solved through AE.

**Comment by kishanprajapat2564788** [comment]
Hi @limzykenneth @johkon
I have one question I have rendered AEP file. In that file, I have replaced all the assets. In the case of images, After rendering, the scale and resolution of the image are small and reduced in the rendered video. But in my aep file, the image is in perfect form. So how do I do this? Can we do scaling or we can say autofit to that layer using Nexrender ?
Could you tell me? What's the problem?

**Comment by youzhajun** [comment]
> 
@kishanprajapat2564788 
You need to check the scaling attribute of the layer on the template and the attribute value of the position z axis. They will affect the display size of the picture. If you want to achieve 100% filling without changing any attribute, the new material must be exactly the same as the actual size of the old material. I am also studying how to make the replacement materials 100% filled. Can you tell me if you have a good plan?

**Comment by kishanprajapat2564788** [comment]
@youzhajun Till now, I haven't found any perfect solution for this. But for now, I have tried to give an expression for each layer. Like this, 
{
    type: "data",
    layerName: "ph_layer.jpg",
    property: "Scale",
    expression: "cw = thisComp.width; ch = thisComp.height; lw = thisLayer.width; lh = thisLayer.height; r = Math.max(cw/lw*100, ch/lh*100); [r, r];"   
}

In this way, the image got auto-fit in the comp. But sometimes it is not perfect.
