### ISSUE TITLE
asset type 'video'?

### ISSUE THREAD

**Issue by dzg** [inlife/nexrender#78]
This is very (n)exciting! But what if I want to replace a video asset?
I don't see 'video' as a type at https://github.com/inlife/nexrender/wiki/Project-model#assettype

**Comment by inlife** [comment]
i hope that helped!

**Comment by dzg** [comment]
Yes, I will give it a shot, thanks!

One more question: how exactly to I "POST project data to api server"?

Thanks again for your time.

**Comment by inlife** [comment]
well you can use curl or postman, or any other http client for that
or you could use the nexrender api for that

**Comment by dzg** [comment]
So ... create a Project Model JSON file (like https://github.com/Inlife/nexrender/wiki/Project-model) and then something like 
`curl -d "@data.json" -X POST http://localhost:3000`
?

**Comment by dzg** [comment]
So ... create a JSON file (like https://github.com/Inlife/nexrender/wiki/Project-model) and then did
`curl -d "@project.json" -X POST http://localhost:3000`
But I got parsing errors ... I think that is not really JSON?
Do I have to actually run some js to post the 'model'?
Sorry, confused.

**Comment by inlife** [comment]
no, you should not run anything for that
just make sure you are sending valid json as raw body in POST message

**Comment by dzg** [comment]
Like this?

```
$ curl -X POST -d "{template: 'template1.aepx',composition: 'composition1',settings: {outputModule: 'h264',outputExt: 'mp4',startFrame: 0,endFrame: 542}}" localhost:3000
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /</pre>
</body>
</html>
```

**Comment by inlife** [comment]
oh, i see the issue
even a few now

first of all, its not a valid json, you can use any available online tools to help you fix that (or form a valid one)

second, the url which you are trying to post request to is wrong, it should be
`http://localhost:3000/api/projects`

Also, there is a similar issue: https://github.com/inlife/nexrender/issues/36
And also, a bonus, there is a web form recently used for similar stuff: https://github.com/inlife/nexrender/issues/76#issuecomment-429251013

The latest one, doesnt require you running webserver for that form, just open it in browser, and done. :)
