### ISSUE TITLE
show the Rendering Progress Value

### ISSUE THREAD

**Issue by turgutreis** [inlife/nexrender#783]
how can I display the percentage value from the rendering process? I want to display it in the frontend? I have created a nodejs server and want to display the encoding progress on the client.

**Comment by limzykenneth** [comment]
The progress is technically available in the job object under the `renderProgress` key but one caveat is that it only relates to the progress of After Effects rendering and does not include the postrender encode action (if you are using it) or any other actions.

**Comment by turgutreis** [comment]
The onRenderProgress function does not work there is no output. Do you know why it does not work?

<img width="481" alt="nex" src="https://user-images.githubusercontent.com/5589984/208098357-3abeed3e-4ff8-4b7e-9a3d-6f88e4525052.png">

**Comment by limzykenneth** [comment]
`onRenderProgress` is not meant for consumption of render progress by the client but rather it runs alongside the render next to AE. `client.on("progress")` that you are using the in the screenshot there should be giving you what you expected no?

**Comment by turgutreis** [comment]
Oh, okay, then I must have misunderstood something. It works as it should. I have another question. How can I use the custom-action exactly and how can I call it then? 
<img width="419" alt="costum" src="https://user-images.githubusercontent.com/5589984/208110474-27e5a118-2142-418d-9216-863d8f69e88a.png">

**Comment by inlife** [comment]
One of the great additions by @limzykenneth by the way! 😉 🎉

**Comment by turgutreis** [comment]
> If you are planning to use the core directly as shown on your screenshot, there are two things you are defining in there: 1. the job config, 2. the settings config. The settings config is where you define custom actions as shown in the screenshot there. To use the custom action, you need to ask for it to be used in the job config ie. the JSON config or the first argument to render function here, and it should be under one of the available hooks (predownload, prerender, ...).

thanks for your help
