### ISSUE TITLE
How to get my video to export to the specified path?

### ISSUE THREAD

**Issue by keatonphillips** [inlife/nexrender#786]
I'm new to nexrender and still figuring everything out - so I could be missing something. 

I was able to figure out how to successfully render a job using a json file thanks to the videos online and one of the posts that mentioned to use the method [here](https://stackoverflow.com/questions/15080835/running-an-executable-in-mac-terminal#15080940) to get terminal to be able to complete the job. (using `./nexrender-cli-macos --file myjob.json`

my issue is the encoded video is not actually exported to the specified path in the json. It exports to folders within the private folder in the sequence below - and each export seems to make a separate random folder in this similar format. 

`/private/var/folders/0r/zqg_yk4s50v7pk687jqrcw5m0000gn/T/nexrender/9HL5ksYJ9a_vJHSio_rp7/encoded.mp4`

What can I do to get the video to actually export to the specified export path in the json file?

**Comment by limzykenneth** [comment]
You will need to use the copy [action](https://github.com/inlife/nexrender#actions) to copy the rendered file to your desired location.

**Comment by keatonphillips** [comment]
Thank you for your response - I was using the copy action based on the instructions on that link.

I seem to have been able to have gotten it to work. I changed the format from `"output": "d:/mydocuments/results/myresult.mp4"` to just `"output": "d:/mydocuments/results` and it is outputting the correct folder now, where it did not before.

Glad to get it working, but is that the intended format / behavior? Just curious. Thanks for your time!

**Comment by limzykenneth** [comment]
How did it not work with `"output": "d:/mydocuments/results/myresult.mp4"`? Did it error? Did it not copy anything? Did it do something else unexpected?
