### ISSUE TITLE
ReferenceError: callback is not defined

### ISSUE THREAD

**Issue by harryttd** [inlife/nexrender#79]
See line here: https://github.com/inlife/nexrender/blob/master/renderer/tasks/actions.js#L35

The code should not be `return callback(err)` but rather it should be `reject(err)` as it is wrapped in a Promise and `callback` is not defined anywhere.

**Comment by inlife** [comment]
indeed, seems like an oversight, thank you @harryttd !
not sure when i'll be able to fix it, issue gonna stay opened

**Comment by inlife** [comment]
closing issue, since older version is now deprecated
