### ISSUE TITLE
How to get Woker progress in real time？

### ISSUE THREAD

**Issue by youzhajun** [inlife/nexrender#794]
I call woker through the server to create a production task, and then call the server api through polling to query the task status. However, frequent http requests consume a lot of resources, and there is no way to get the execution progress. Is there a more perfect solution to get both the task status and the task execution progress. thanks!

**Comment by inlife** [comment]
Not at the moment. And considering the nature of the API, it should not involve that many resources. Unless you are making very frequent requests. What is your delay between requests?

**Comment by youzhajun** [comment]
3 second，Is there a way to get the execution progress of the rendering?

**Comment by inlife** [comment]
Usually, the data about render progress is reported back to the nexrender server: https://github.com/inlife/nexrender/blob/master/packages/nexrender-worker/src/index.js#L66-L80

And from there, it can be read by any HTTP client about any job.
