### ISSUE TITLE
Multi-image render is failing

### ISSUE THREAD

**Issue by adrinmir** [inlife/nexrender#796]
When I use more than 1 image source, render fails.
Image URLs work and there is no issue, but when I add more than 1 image to AE template, render fails.

"assets": [
                    {
                        "type" : "data",
                        "layerName" : "BASLIK",
                        "property" : "Source Text",
                        "value": BASLIK
                    },
                    {
                        "src": IMAGEURL2,
                        "type": "image",
                        "layerName": "IMAGE1"
                    },
                    {
                        "src": IMAGEURL3,
                        "type": "image",
                        "layerName": "IMAGE2"
                    }
                ],

**Comment by adrinmir** [comment]
I found the problem, AE 2023 latest version fails with NexRender. I am using 2022 version and it works now.

**Comment by zalom** [comment]
> I found the problem, AE 2023 latest version fails with NexRender. I am using 2022 version and it works now.

Wait, are you saying that only AE 2022 works with Nexrender (the latest release)? Can you specify which version are you using?

@inlife, can you shed any light on this?

**Comment by inlife** [comment]
According to the latest release, this bug should be fixed: https://github.com/inlife/nexrender/pull/831

**Comment by zalom** [comment]
> According to the latest release, this bug should be fixed: #831

OK, I will give it a go right now.

**Comment by zalom** [comment]
Hm, I think I should open a new issue. ->

```shell
checking After Effects command line renderer patch...
command line patch already is in place
[omitted] setting up job...
[omitted] working directory is: C:\Users\ADMINI~1\AppData\Local\Temp\2\nexrender\omitted
[omitted] applying predownload actions...
[omitted] downloading assets...
[omitted] skipping the clean up...
(node:8132) UnhandledPromiseRejectionWarning: #<Object>
(node:8132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:8132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am sending a payload to the server. I noticed something while downloading assets (locally). One of the images returns HTTP 403 from some CloudFront URL. Could it be that this is the exception the worker is throwing?

But, in any case, this should not kill the worker, it should be an error that is handled.

**Comment by zalom** [comment]
I can verify that the latest release works with AE 2023. Just rendered one video.
