### ISSUE TITLE
Regarding the Fit to comp or image does not fit to its comp size 

### ISSUE THREAD

**Issue by kishanprajapat2564788** [inlife/nexrender#801]
@inlife @limzykenneth @Mrzy
Thanks for your support.

I have one question.
`{
           "type": "data",
            "layerName": "1.jpg",
            "property": "Scale",
            "expression": "cw = thisComp.width; ch = thisComp.height; lw = thisLayer.width; lh = thisLayer.height; r =Math.max(cw/lw*100, ch/lh*100); [r, r];"   
}`
In issue #235, I have put expression for the image fit to comp in my project JSON. It works or is rendered well. But when I upload a vertical or square image (like 6:19 and 1:1) then fit comp doesn't work. Images got spread or cut or small.
Could you tell me how can we do this to solve the fit-to-comp issue?

**Comment by limzykenneth** [comment]
Have you tried out the expression in AE itself directly? In general if your question is more to do with AE and not Nexrender you should probably ask them on a more AE focused forum instead.
