### ISSUE TITLE
Rendering process hangs when there is a single quote "'" in the template.src and/or template.composition

### ISSUE THREAD

**Issue by Tillaert** [inlife/nexrender#806]
**Describe the bug**
Rendering process hangs when there is a single quote "'" in the template.src and/or template.composition.

**Information about environment**
Nexrender 1.40.0
@nexrender/core

Windows 11 / Adobe After Effects 23.0

**Expected behavior**
Rendering continues or process fails.

``` Javascript
const { render } = require('@nexrender/core')

const main = async () => {
    const result = await render(
        {template: 
            {src: "file:///c:/Users/User/templates/Filename'.aep",
             composition: "composi'tion"}}, {
        skipCleanup: true,
        addLicense: false,
        debug: true,
        actions: {
            "custom-action": (job, settings, {input, params}, type) => {
                // Custom action code
            }
        },
    })
}

main().catch(console.error);
```

**Comment by limzykenneth** [comment]
I think you'll need to manually escape the single quotes as the value defined in the string is passed directly to the command line and so with single quote having special meaning in the command line it probably confuses things.
