### ISSUE TITLE
The size of the replaced picture in the video

### ISSUE THREAD

**Issue by youzhajun** [inlife/nexrender#808]
I have an ae template, which contains an image of 100 * 100px. The layer is scaled by 30%, which means that the actual display effect is 70 * 70. When the size of the material I replace is less than 70 * 70, it will be displayed in an equal proportion. Is there a solution? thank you

**Comment by limzykenneth** [comment]
You can dynamically change the scale value of the layer to fit your input image provided you are using Nexrender programmatically. Otherwise doing the scaling with AE expression is also another option.
