### ISSUE TITLE
Nexrender in docker container

### ISSUE THREAD

**Issue by pkarpovich** [inlife/nexrender#81]
Hey everyone!

Maybe someone was a success with a run this library in docker container?

**Comment by positlabs** [comment]
Until Adobe releases a linux version of AE, you won't be able to run this within Docker.

**Comment by positlabs** [comment]
I think you might be able to with windows containers, but I just now discovered them. https://www.docker.com/products/windows-containers

**Comment by oreporan** [comment]
@pkarpovich any luck running nexrender on docker ?
