### ISSUE TITLE
After using the nexrender program to render the video, it was found that the UI of adobe ae on Windows was changed, and all functions on ae were unavailable.

### ISSUE THREAD

**Issue by youzhajun** [inlife/nexrender#812]
After using the nexrender program to render the video, it was found that the UI of adobe ae on Windows was changed, and all functions on ae were unavailable. As shown in the figure, I wonder if you have encountered this kind of problem? We would be grateful if you could provide some solutions!

<img width="1098" alt="1671525324503" src="https://user-images.githubusercontent.com/84554002/208623355-624f9132-5c17-4b28-9b84-550dce98f737.png">

**Comment by inlife** [comment]
Duplicate https://github.com/inlife/nexrender/issues/220
