### ISSUE TITLE
log error message

### ISSUE THREAD

**Issue by youzhajun** [inlife/nexrender#813]
When I use a program to render a video, the log information shows that the file information cannot be found, but this is not the Windows folder of my rendering server and cannot exist. What is the reason?

**logFile:**
![e2cf995826295410f7312245a816790](https://user-images.githubusercontent.com/84554002/208857913-156b30fd-09ba-4ea5-bb70-6722948a4dcd.jpg)

**window dir list**
![1dec165a07470b230fb7a0be64d62ed](https://user-images.githubusercontent.com/84554002/208857939-e551acda-23db-4d3a-a787-72fb2d0ea58f.jpg)

**Comment by limzykenneth** [comment]
It probably is what the file path is saved as in the AE file when it is being put together. After Effects tends to save absolute links to assets on the computer where the AE file is saved and when moving the project to another compute these paths will still stay the same.
