### ISSUE TITLE
Error: Couldn't find module @nexrender/provider-c, Unknown protocol provided.

### ISSUE THREAD

**Issue by xiaoyaogaobin** [inlife/nexrender#819]
C:\phpstudy_pro\nest>nexrender-cli-win64.exe --file main.json --binary="C:/Program Files/Adobe/Adobe After Effects CC/Support Files/aerender.exe"
> starting nexrender-cli
checking After Effects command line renderer patch...
command line patch already is in place
[5bAte86761PQG1VHH9H96] setting up job...
[5bAte86761PQG1VHH9H96] working directory is: C:\Users\Administrator\AppData\Local\Temp\nexrender\5bAte86761PQG1VHH9H96
[5bAte86761PQG1VHH9H96] applying predownload actions...
[5bAte86761PQG1VHH9H96] downloading assets...
[undefined] cleaning up...
> job rendering failed
Error: Couldn't find module @nexrender/provider-c, Unknown protocol provided.
    at download (C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\download.js)
    at C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\download.js
    at C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\helpers\state.js
    at C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\index.js
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1376:13)
    at internal/main/run_main_module.js:18:47
[undefined] Temporary AfterEffects project deleted. If you want to inspect it for debugging, use "--skip-cleanup"

**Comment by limzykenneth** [comment]
Hi, can you provide a bit more info about your problem? There's not much I can tell from just the error log here. Especially the contents of `main.json` would be very helpful along with what you're trying to do.

**Comment by APZmedia** [comment]
We have installed nexrender/cli nexrender/action-copy and nexrender/encode in a Windows machine with npm installed globally, with the following error: 
`
> starting nexrender-cli                                                                                                                                                                                                                                                       
using automatically determined directory of After Effects installation:                                                                                                                                                             - C:\Program Files\Adobe\Adobe After Effects 2023\Support Files\aerender.exe                                                                                                                                            checking After Effects command line renderer patch...                                                                                                                                                                         command line patch already is in place                                                                                                                                                                                                [ndHiarkvovE1FSxw1fbCb] setting up job...                                                                                                                                                                                     [ndHiarkvovE1FSxw1fbCb] working directory is: C:\Users\APZRYZ~1\AppData\Local\Temp\nexrender\ndHiarkvovE1FSxw1fbCb                                                                                                            [ndHiarkvovE1FSxw1fbCb] applying predownload actions...                                                                                                                                                                       [ndHiarkvovE1FSxw1fbCb] downloading assets...                                                                                                                                                                                 [ndHiarkvovE1FSxw1fbCb] skipping the clean up...                                                                                                                                                                                    > job rendering failed          
                                                                                                                                                                                
Error: Couldn't find module @nexrender/provider-c, Unknown protocol provided.                                                        
at download (C:\nodejs\nvm\v14.21.2\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\download.js:147:43)                                                                                                      at module.exports (C:\nodejs\nvm\v14.21.2\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\download.js:164:9)                                                                                                at module.exports (C:\nodejs\nvm\v14.21.2\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\helpers\state.js:8:12)                                                                                                  at C:\nodejs\nvm\v14.21.2\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\index.js:118:22                                                                                                                         at processTicksAndRejections (internal/process/task_queues.js:95:5)  
`

and installing it with npm i -g @nexrender/provider-c 

`
npm ERR! code E404                                                                                                                                                                                                            npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nexrender%2fprovider-c - Not found                                                                                                                                   npm ERR! 404                                                                                                                                                                                                                  npm ERR! 404  '@nexrender/provider-c@latest' is not in the npm registry.                                                                                                                                                      npm ERR! 404 You should bug the author to publish it (or use the name yourself!)                                                                                                                                              npm ERR! 404                                                                                                                                                                                                                  npm ERR! 404 Note that you can also install from a                                                                                                                                                                            npm ERR! 404 tarball, folder, http url, or git url. 
`

**Comment by limzykenneth** [comment]
@APZmedia We'll still need more info, especially the contents of `main.json` or we can't tell what's wrong here.

**Comment by APZmedia** [comment]
Here is the example.json, the first arg of render function in @nexrender/core module.

`
    "template": {
        "src": "...",
        "composition": "TestNexrender"
    },
    "actions":{
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mov",
                "output": "result.mov"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "result.mov",
                "output": "..."
            }
        ]
    }
`

**Comment by limzykenneth** [comment]
What is the value of the `template.src`? I think if my guess is correct it would be something like `C:\Users\username\Documents\template.aep`?

If that is the case then you are missing the `file://` protocol at the beginning of the string, ie. it should be `file://C:/Users/username/Documents/template.aep`. Have a look at the examples [here](https://github.com/inlife/nexrender#examples-1).

**Comment by APZmedia** [comment]
It actually was file:/// with three instead of two slashes.
In any case, now, it gives me this error 
```
aerender version 23.2.1x3
PROGRESS: Launching After Effects...
aerender SYNTAX ERROR: Illegal argument flag: -r

```

**Comment by inlife** [comment]
@APZmedia it means your nexrender patch was not properly installed for the AE version that is being used for nexrender

**Comment by APZmedia** [comment]
I forced patched it programatically, but it didn't change. Is there a way to force the patch with the cli? I can't find documentation for this.

**Comment by inlife** [comment]
@APZmedia, there is a setting for that: `forceCommandLinePatch`, it should be set to true

More details: https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/helpers/patch.js#L63
