### ISSUE TITLE
nexrender not using the sended project

### ISSUE THREAD

**Issue by rafadess** [inlife/nexrender#82]
Hi!

Nice job with nexrender. It's really useful. Congratulation.

I'm having an issue with sending project to the server. I'm sending a project object with POST method. The server is receiving the POST message but it seems that the server is ignoring the project that I'm sending. The rendernode always render the template project instead of using the project that I sent.

This is how I'm sending the project object:
`var xhr = new XMLHttpRequest();`
`xhr.open("POST", 'http://localhost:3000/api/projects/');`
`var obj = { template: "mwbv1811_01.aep", composition: "mwbv1811_01", assets: []};`
`xhr.send(obj);`

It's a just a test, but instead using this project, it is using the one defined on /api/models/project.js that I think it's the default.

Any help will be very appreciated.

Rafael

**Comment by inlife** [comment]
oh, just make sure to change "template" to the same name as the sent file
in the past that had "feature" more meaning, now it just becomes a bit annoying\
