### ISSUE TITLE
Dynamic headers for API client

### ISSUE THREAD

**Issue by limzykenneth** [inlife/nexrender#821]
**Is your feature request related to a problem? Please describe.**
I'm working on a custom re-implementation of Nexrender server and as part of this re-implementation I would like to use alternative method of authorization using the Authorization header.

**Describe the solution you'd like**
It would be great to be able to pass a header object on API client creation (that will be sent on every request to the server) and also be able to modify this header object throughout the lifetime of the client object as well. This may also be used by downstream packages such as Nexrender workers.

**Describe alternatives you've considered**
The internal implementation of [`createClient`](https://github.com/inlife/nexrender/blob/master/packages/nexrender-api/src/index.js#L3) may need to be reworked but it very likely can be done in a fully backwards compatible way. I may start work on this in the near future.

**Additional context**
The [re-implementation](https://github.com/limzykenneth/nexrender-serverless) of Nexrender server I'm talking about.

**Comment by inlife** [comment]
That sounds like a good idea!

Also, I very much support the serverless use case, I think at some point, I even modified the existing server to work on vercel to some extent.

**Comment by limzykenneth** [comment]
I'm just kinda obsessed with Cloudflare workers recently :stuck_out_tongue: 

I'll have a look at adding dynamic headers when I get a bit of time.
