### ISSUE TITLE
Retrieve assets list action from a .aep file

### ISSUE THREAD

**Issue by DeAngelisMarco** [inlife/nexrender#838]
Hi, is it possible to create a new action (like @nexrender/action-list) to retrieve the list of all the assets objects into a project file (.aep)? Something like this:

```
{
    "template":{
        "src": "file:///W:/example.aep",
        "composition": "Comp HDTV 1080 25 - full"
    },
    "actions": {
        "prerender": [
            {
                "module": "@nexrender/action-list",
                "output": "list.txt",
            }
        ]
    }
}
```

Thanks and regards!

**Comment by JamesBotterill** [comment]
I don't quite understand, do you want to retrieve all assets from the aep? 

What would you expect to be in the txt?

**Comment by DeAngelisMarco** [comment]
Exactly: the ideal would be a file (json or xml would be better than txt) with the list of compositions present in the project (whether the composition is not specified) with the list of all the assets inside each one. This way, I could decide which assets to edit for rendering if I didn't know the After Effects project content

**Comment by JamesBotterill** [comment]
I don't think this would be possible as all pre-rendering actions take place before the aerender command line tool runs, I've been thinking about a nexrender plugin for ae which would enable you to generate a json template project. 

But my knowledge of AE plugin development is very very limited.

**Comment by DeAngelisMarco** [comment]
Maybe with a script file .jsx? I could create a script to enumerate all the compositions and the assets objects and dump them into a json file... what do you think about it?
