### ISSUE TITLE
Compilation error since adding the cache

### ISSUE THREAD

**Issue by benoitRodde** [inlife/nexrender#845]
Since adding the cache I can't launch my worker, the error : 

Error: Cannot find module 'fs/promises'
Require stack:
- /snapshot/nexrender/packages/nexrender-core/node_modules/cacache/lib/entry-index.js
- /snapshot/nexrender/packages/nexrender-core/node_modules/cacache/lib/get.js
- /snapshot/nexrender/packages/nexrender-core/node_modules/cacache/lib/index.js
- /snapshot/nexrender/packages/nexrender-core/node_modules/make-fetch-happen/lib/cache/entry.js
- /snapshot/nexrender/packages/nexrender-core/node_modules/make-fetch-happen/lib/cache/index.js
- /snapshot/nexrender/packages/nexrender-core/node_modules/make-fetch-happen/lib/fetch.js
- /snapshot/nexrender/packages/nexrender-core/node_modules/make-fetch-happen/lib/index.js
- /snapshot/nexrender/packages/nexrender-core/src/tasks/download.js
- /snapshot/nexrender/packages/nexrender-core/src/index.js
- /snapshot/nexrender/packages/nexrender-worker/src/bin.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/snapshot/nexrender/packages/nexrender-core/node_modules/cacache/lib/entry-index.js:11:5)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/nexrender/packages/nexrender-core/node_modules/cacache/lib/entry-index.js',
    '/snapshot/nexrender/packages/nexrender-core/node_modules/cacache/lib/get.js',
    '/snapshot/nexrender/packages/nexrender-core/node_modules/cacache/lib/index.js',
    '/snapshot/nexrender/packages/nexrender-core/node_modules/make-fetch-happen/lib/cache/entry.js',
    '/snapshot/nexrender/packages/nexrender-core/node_modules/make-fetch-happen/lib/cache/index.js',
    '/snapshot/nexrender/packages/nexrender-core/node_modules/make-fetch-happen/lib/fetch.js',
    '/snapshot/nexrender/packages/nexrender-core/node_modules/make-fetch-happen/lib/index.js',
    '/snapshot/nexrender/packages/nexrender-core/src/tasks/download.js',
    '/snapshot/nexrender/packages/nexrender-core/src/index.js',
    '/snapshot/nexrender/packages/nexrender-worker/src/bin.js'
  ],
  pkg: true
}

I try to restart npm run i

npm run install-child

npm run pkg

**Comment by benoitRodde** [comment]
make-fetch-happen use cacache who  use fs/promises => then error 

I try to clear npm cache without results

**Comment by inlife** [comment]
What node version are you using?

**Comment by benoitRodde** [comment]
v18.7.0

**Comment by limzykenneth** [comment]
@benoitRodde Can you provide a bit more info about your setup? Have you confirmed that both the server and worker are running on node 18.7.0?
