### ISSUE TITLE
Missing module after updating worker 

### ISSUE THREAD

**Issue by natoshiro40** [inlife/nexrender#849]
Hi, I just downloaded the binaries for the latest version of nexrender worker and server and I am struggling to get it to run. 

IDK how to explain it a better way ^^', I just use the same command as before. 

![image_2023-02-13_093148196](https://user-images.githubusercontent.com/51412972/218408456-6f436e61-90ec-428d-ae81-78b9e86307fd.png)

* Which version of nexrender are you using? latest release (1.42.2)
* What kind of the setup do you have? server+worker 
* Are you using pre-built binaries or globally installed npm packages? Binaries
* Which kind (and version) of operating system you are running it in? Windows 11 
 after effects version 23.2

**Comment by benoitRodde** [comment]
Hi ! I have exactly same error as you since the push of http cache

**Comment by natoshiro40** [comment]
OK, the 1.41.1 seems to be working well. And the 1.42.0 is causing the bug.

**Comment by inlife** [comment]
Ah, that would make sense. I will try to focus on updating the embedded binary version of node in next updates

**Comment by inlife** [comment]
Published v1.42.3, try testing it out: https://github.com/inlife/nexrender/releases/tag/v1.42.3

**Comment by natoshiro40** [comment]
Okay I'll try, thanks

**Comment by natoshiro40** [comment]
It seems to work properly, I'm closing the Issue. thank you.
