### ISSUE TITLE
Problem with font

### ISSUE THREAD

**Issue by andyglez96** [inlife/nexrender#852]
Hey guys, I'm having some problem when using a font from Adobe (Router-Bold), basically it doesn't render with that font at all, this is how I sent the param to the job: 

` {
      type: 'data',
      layerName: 'Jump',
      property: 'Source Text.font',
      value: 'Router-Bold'
    }`
    I have checked and the font is activated in my Adobe account

**Comment by andyglez96** [comment]
should be a problem with Adobe fonts, as I need to send them in another way?

**Comment by andyglez96** [comment]
@inlife is there a way to send the font style also in the parameters?

**Comment by JamesBotterill** [comment]
@andyglez96 is the font already downloaded and installed on the machine which performs the render? I'm pretty sure aerender app will not fetch and install any fonts which aren't already present on the machine

**Comment by andyglez96** [comment]
Yes I'm pretty sure it's installed, I have checked i the Adobe Creative Cloud app and is activated and also checked the Fonts panel of the OS and are installed

Even if I don't send the Router-Bold font in the parameters, it's grabbing a random font(the text layer has Router-Bold in the AE project)

**Comment by JamesBotterill** [comment]
I've just tested this font activated on Adobe CC and using the cli with my test project and it's fine,

This was on osx. 

Maybe an issue activating the font? looks like it might be an AE issue

**Comment by andyglez96** [comment]
no luck on my side, I even updated the AE version and nothing, same behavior.
it makes no sense, because when I open it in my local computer it works, but send it to render grabs a random one :(

**Comment by JamesBotterill** [comment]
Ahh are you rendering on an EC2 instance running Adobe CC and After Effects?

**Comment by andyglez96** [comment]
in this case After effect is in a render-mode only, so no need to have it open, and yes Adobe CC open and logged in

**Comment by andyglez96** [comment]
but yes, EC2 instance

**Comment by JamesBotterill** [comment]
I've not worked on setting up an EC2 instance I'm afraid, I'm sure some users on here do. 

If you attempt to use the CLI on the EC2 instance does the issue still occur?

**Comment by andyglez96** [comment]
actually I'm using the cli on the instance, command line using the binary from nexrender

**Comment by hamboomger** [comment]
@andyglez96 have you figured out a way to make the fonts issue disappear? I'm having a similar issue, EC2 + nexrender, but with Roboto font

**Comment by ivansenic** [comment]
We at Plainly Videos experienced a lot of different edge cases with fonts. Actually it's one of the things we still fight the most and something that we managed to finally overcome for our users. But here are the situations I can confirm can lead to bugs:

* of course font not being installed on the system
* font is installed, but you are missing the correct type script name (for example you have `Roboto.otf` file, but the typescript name is `Not-Roboto`)
   * good place for confirmation is https://fontdrop.info
* then you change both font and the text value of the layer, where order of actions is important (font should be changed last)
* you set a text with characters that is not supported by the font, AE uses the default font
