### ISSUE TITLE
Save .AEP project after running script file (after replacing elements)

### ISSUE THREAD

**Issue by pochenok** [inlife/nexrender#854]
Is it possible to save .AEP project after running nexrender-generated .jsx file (for replacing elements)?
I would like to generate project-folders (variations of the video) and then use these folders to render in adobe media encoder. Unfortunately AME cannot run that script before rendering project.

**Comment by JamesBotterill** [comment]
If you use the flag `--skip-cleanup` you should be able to get the nexrender generated aep from the temp folder the render was created from. 

Worth a try

**Comment by pochenok** [comment]
I tried (--skip-cleanup and --skip-render) and .aepx file in tmp folder has default assets in place (basically It is an original project file) instead of a new ones that I'm passing via nexrender

**Comment by JamesBotterill** [comment]
I've just looked and you're correct that what happens is it creates a copy of the original aep and then runs a jsx script to replace the layers. 

You can run custom scripts by using the script asset I believe, what you should be able to do is right a small script that saves your project. This should (hypothetically) mean the aepx file is now the updated on and not the default on used for rendering. 

https://ae-scripting.docsforadobe.dev/general/project.html#project-save


 (I'm still learning this myself, willing to be correct by wiser heads)
