### ISSUE TITLE
How to connect Smart Resize Plugin with Nexrender ?

### ISSUE THREAD

**Issue by shaileshsitestrokes** [inlife/nexrender#858]
Hello,

I have an AEP file that used a smart resize plugin to render resizable video.

I want to Render this AEP File using Nexrender like 3 different resizable videos verticle, panorama, and square.

Is there any solution that I can pass from JSON or any other setting which I can apply?

Thanks.

**Comment by JamesBotterill** [comment]
from my attempts to manipulate the comp settings from a script, this isn't possible as the script file being added works as a layer within the project and doesn't have access to app.project.activeItem which is needed at a script level to adjust these settings. 

Happy to be shown how to do this though.
