### ISSUE TITLE
can it run on Cloud server？

### ISSUE THREAD

**Issue by lamberfox** [inlife/nexrender#86]
Is it possible to run on the server? Because you need to install AE, but the server does not have enough hardware to support the installation of AE.

**Comment by inlife** [comment]
Hello

you can run nexrender api server on pretty much any operating system
however, for render node, you need to run it on system that has After Effects installed

also you can try to make use of amazon, or google platforms to install or run nexrender there

**Comment by xanpj** [comment]
Keep in mind that for cloud servers you can only run it on Windows Server OS because Mac OS is not supported on the big cloud platforms. I am using it on Windows Server 2012 and it works fine. Of course, it needs to have enough hardware support to install AE, although you will be only using aerender.exe and not AE itself.

**Comment by lamberfox** [comment]
@inlife Thank you for your reply. I'll try to install AE in Windows server. In addition, the AE version required for your nexrender-boilerplate project does not seem to be too high, as other issues mentioned.
So if i want to run your demo, which AE version do I need to install best?

`Error message: ENOENT: no such file or directory, stat 'D:\__Project-nodejs\nexrender-boilerplate-master\nexrender-boilerplate-master\temp\JDf_9jniY\result.mp4'
{ [Error: ENOENT: no such file or directory, stat 'D:\__Project-nodejs\nexrender-boilerplate-master\nexrender-boilerplate-master\temp\JDf_9jniY\result.mp4']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path:`

**Comment by lamberfox** [comment]
@xanpj OK! Thank you for your reminder

**Comment by inlife** [comment]
while i was developing it, i was using AE 2015, maybe even 2016
they still had support for mp4 export built in
hence the usage of mp4 as outputExt, and validation error that you've provided
(in thast case you should probably switch to avi)

**Comment by lamberfox** [comment]
@inlife  I've tried many versions of AE and output format, and always the same error prompt. Must the template AE file end with aepx, because I now have an AEP file. I want to replace the underlying images to generate new videos.

**Comment by inlife** [comment]
you can save and export your aep file to aepx with menu directly from interface of After Effects
