### ISSUE TITLE
Template HTTP download causes crash, where same asset as FILE works

### ISSUE THREAD

**Issue by backbeatmedia** [inlife/nexrender#864]
**Description**
Using the latest release of Nexrender, I have a job which requires http download of the AEP template. This causes a crash. Manually downloading the AEP and adding it as a file in the same job json solves the issue and renders OK.

**Environment**
* Nexrender 1.42.3
* Using win64 CLI in a testing environment
* I have tried this on both the downloaded binary from "Releases", and one I compiled myself.
* Running on Windows Server 2022 datacenter (this is an EC2 instance)

**Expected behavior**
I expected the job to render with a downloaded file, and the cli process to exit normally

**Screenshots**
This job json did not render:
![image](https://user-images.githubusercontent.com/78971664/222766859-51a47969-2e9c-4a30-aaf1-502c6cf5cb44.png)

Here is the crash report:
![image](https://user-images.githubusercontent.com/78971664/222767123-acea6268-4235-43e8-abc3-e420fc179ab3.png)

This job json rendered
![image](https://user-images.githubusercontent.com/78971664/222766706-ee635ed0-49e1-449c-bef6-646711b7eda0.png)

Here is the cli output
![image](https://user-images.githubusercontent.com/78971664/222767494-a49bb10c-be5b-453e-80f1-ef197646e608.png)

**Comment by benoitRodde** [comment]
I have the same error, I am still looking for the solution

**Comment by benoitRodde** [comment]
If you don't use cache comment this part of code works (in download.js) : 
 /*
    const cachePath = settings.cache === true ?
        path.join(settings.workpath, "http-cache") :
        settings.cache;

    if(!asset.params) asset.params = {};
    // Asset's own `params.cachePath` takes precedence (including falsy values)
    asset.params.cachePath = Object.hasOwn(asset.params, 'cachePath') ?
        asset.params.cachePath :
        cachePath;
    */

**Comment by backbeatmedia** [comment]
Thank you for the suggested workaround.

**Comment by limzykenneth** [comment]
@backbeatmedia Can you share the JSON as a text file so I can try and replicate this on my end?

**Comment by backbeatmedia** [comment]
Sure - here it is
[job.zip](https://github.com/inlife/nexrender/files/10899584/job.zip)

**Comment by limzykenneth** [comment]
This is only happening with the prebuilt binaries, npm installed version works fine. 

@inlife In the implementation I used `Object.hasOwn` which is not available in node 14 but available in node 16, we can either refactor that out or futher upgrade the bundled node version to node 16 (node 14 EOL is this April anyway so I'd prefer the upgrade).

**Comment by inlife** [comment]
Got it, upgrade it is, will work on that soon.

**Comment by inlife** [comment]
Published new version https://github.com/inlife/nexrender/releases/tag/v1.42.4
Upgraded to node18

**Comment by backbeatmedia** [comment]
Hello thank you for the update to node18. Now my issue is that the app will not build. It reports

`> Error! No available node version satisfies 'node18'`

However when I look in the `~/.pkg-cache` folder I see node18 binaries right there.

**Comment by backbeatmedia** [comment]
Hello - thank you the new version has successfully downloaded http assets. Issue closed.
