### ISSUE TITLE
Non-Nexrender external modules are not packaged into binaries

### ISSUE THREAD

**Issue by backbeatmedia** [inlife/nexrender#867]
**Description**
Additional modules are not packaged into windows worker binaries. To replicate the problem:

* Start with the latest Nexrender
* Use npm to install a non-Nexrender module in `@nexrender-core` e.g. `nexrender-install-font-crossplatform`
* Add the module to the dependencies in `@nexrender-core/package.json`
* Add the module as a `require` statement in `@nexrender-core/src/index.js`
* Package binaries using `npm run pkg`
* Run an instance of the Server, and create a job that requires that module
* Run the worker binary, pointing at that server

**Information about environment**
* Nexrender v1.42.4
* Vanilla worker, and a server reverse engineered into Lambda functions
* Worker is packaged from my fork of Nexrender - more or less identical to the master version, with a couple of tweaks including the addition of these modules
* Windows Server 2022, EC2 instance

**Expected behavior**
I expected the chosen modules to be packaged into the executable and be available to the code when running on the production machine

**Screenshots**
This is the crash report on my worker instance
![image](https://user-images.githubusercontent.com/78971664/223480793-848b35c7-863e-49d7-b575-7d9d274ff002.png)

This is my `package.json`
![image](https://user-images.githubusercontent.com/78971664/223481130-8fed1b32-cb3c-4764-9ef3-93fd4d5ad6fe.png)

This is the section of `index.js`
![image](https://user-images.githubusercontent.com/78971664/223481541-b07cdb1a-d914-4070-a24e-592c1affc0f2.png)

**Comment by inlife** [comment]
Does this also happen if the dependencies are provided as "peerDependencies"?

**Comment by backbeatmedia** [comment]
Hello - thank you very much for replying. If the dependencies are provided as "peerDependencies" in `@nexrender-core/package.json` then the `npm run pkg` process fails with a warning that a dependency related file could not be found. I seem to recall it happens during the prelink phase. Unfortunately I am away from my dev machine today and tomorrow, otherwise I would be able to post a screenshot.

**Comment by backbeatmedia** [comment]
Hello - here is a screenshot of the error

![image](https://user-images.githubusercontent.com/78971664/224279898-04ad2f23-ce8e-4983-a269-f8e48000dc6c.png)

**Comment by inlife** [comment]
Ah, I see. It attempts to connect it as if it was a local dependency. And the problem is somewhere else. The "dependency" way should also have worked properly. Furthermore, in your case, I would even say that would be the correct way of using this. But for some reason, one of two things happened:

1. The library was not properly bundled to the binary (probably unlikely)
2. Requireg fails to load the library from internal linked storage and attempts to load a globally installed lib on the system, skipping the bundled binary (probably more likely)

At this moment, I do not have a solution for this. :(

**Comment by backbeatmedia** [comment]
Hello - I have found a workaround which is to have each new EC2 instance install the dependencies globally during initialisation. I have added commands to the userdata powershell script to achieve this. It works, although it slows down the instance getting ready to render.
