### ISSUE TITLE
Custom UID

### ISSUE THREAD

**Issue by KonkenBonken** [inlife/nexrender#874]
I there any way to use a custom `uid` for a render?
A custom directory for the rendering to take place. Now you get to specify a `workpath` and then `nexrender` creates a random subdirectory in there, but is there any way to specify a name for this, so it can be worked with easier
Now I have to await `onInstanceSpawn` and then grab it from the `job.uid` there

**Comment by inlife** [comment]
Hey @KonkenBonken 

Providing uid manually in the job definition should do the trick. :)

**Comment by KonkenBonken** [comment]
Where do I put that? @inlife 
This don't work:
```ts
 render(json, {
            workpath: 'rendering/renders',
            uid: 'customID'
        });
```

**Comment by inlife** [comment]
Well, settings are conceptually something relates to the instance that does rendering, while uid is purely related to a specific job. Does that make sense? :)
