### ISSUE TITLE
Regarding using the google photos base URL as a image or videos src asset in JSON

### ISSUE THREAD

**Issue by kishanPrajapat-Forcebolt** [inlife/nexrender#881]
Hi @inlife @limzykenneth @K-JBoon 
I'm using this library for the last 1 year and I found this library so good.
And I found some issues with my rendering. When I do rendering with the image src of google photos base URL then it is showing an error.

![image](https://user-images.githubusercontent.com/96729877/230375925-5d275c24-306e-4ff2-aca2-290878237968.png)

This is my google photos base url: 
`https://lh3.googleusercontent.com/lr/AHRh2pY0F3H2RK7tvw4H_OfZUpYRnwDQLMbuDoPs-h9LE52UdDZ6gvMZuOR03OAEByLOZZXRwOXvx4nWsjMuZkjGO6k1GUpehiNwlbCENKiEDqpPYaxF_mkKPF9hJqGo4iJz_kq9JRuJGUNkfv_G0OGACkJ1pQMMn0BKSIreim8XQG_7fHb_KlHfcwpFkUQpzUuWIPls09I9P3bb6qIG_1NX2ecZTtXBE3_0oytXYFanu7-fbuLdr7LVKK9rusYk66OnbRGRhO62xMLXaV2hIYlu-tLMjd_befzgcH1PajNoMVIPbKtBX9TQdIZLZiBYi7aD3xAlJHBr8KSh8Vetf9SkA6pB05eXxE4gtCxn3g-NZLJXWPHrjVNmLmqoScLKaebMmeWVR5rjJa15RrnbCnY52kZq1I05FB_fGIi8Db-X967mLe_sSbh8dRApv5XtA8VkQC0fjBPmQip2fdzWTfvVt_Bp0c-atY9g_nu8hvf7YnJ0WWWKtI5K2axEUwQ9feAqRFjMXsWhNSTrizXWHkk2kJFWdLuybCVO9FZbBjjKQPwTqsSE8fIM5_7MbTweGNE9x1jbob34i-VF9w0M3zNJBUp05xuL0zsXsBsqDntEJYCXU1y39L8vNvjGUHXbQc_GPBZzfZwtCqIQY307vuBL9wtKiX9a0WAWJeZ2fWSzwZz49s-b6Ltc4ma4tvasSmT_E1gndTf8bHEs0E5lwz2_ZA-IxH4GssVBpFYKcKYoTRdvfa36qAkrrRGCAuNbgBQHXcz-DaUx4jw-5_ecEQeIssOTLSxj-0UH5r_cVHwysJ20xeOjV7cdHK3ZqbHFDjv3VA7X-uqHiejTQPZqeM1IyaCEGtxI60P9m_eR8jzvt8jE9Xly6XYsleFusAF8dqqJBJ7bELilxS_5giNT5pfxDVO8uSHTU5lt3RkQL6YeewpXAinhRfxnHvUnhVjjTSMlCyFhm8cO2dv6ry8Dj-AVEsNG79QMse4fkRROiisWkWSQzOfVisjT_25Ne-sNyONEAGRGhLhP=w2048-h1024`

Could you please guide me on how I do this?

**Comment by limzykenneth** [comment]
That photo or at least that URL does not seem to be publicly available, I only get a 403 when visiting it

**Comment by kishanPrajapat-Forcebolt** [comment]
https://lh3.googleusercontent.com/lr/AHRh2paaUntGWR7pvcWehEJyyZfVEfJWOgpKtfEVGmhxyhPo-tmlK-n0kVlmXi_56EEiSO9TVXTtfkpbqtmijVou8hiFH2EFFgJZslHqF7inwntC8gOklArY5Ly6cGzbSEp7I_JdTJTateWXe9wBKy8yaR0KhXY5nKSUcZZeUOkCk4BnQHHas-tFstbWuXbdM6waL_8tJ-kJJqhKpFlV6q9Nm-TOe91gPTiUyDAaTopxJBGJTFiA3OPf6TrdeMhURtCb5OyjMe3u5Ug2bZr0OJ6wK7IGH5gKvshtsQWdcRogNKw1xXdy4mbExeemd4t-kE49T3VMiocKrAeCwdyCh9YdzDM-Wq07Xv_RyL2EcAXnE8gt6zO57DJbxDH5zp_fZrpNNp1bFg6UUtzbm35AgvZEAFjZFytBmD2vPA4dr1ouLg_ANjUKezQFwHmORUQTKZexioM6b_q1pojbSD3LScgk7idLTD7BP7NidCH7DSGSfl2PnD0FqM6DrmWavndVwXIlD9yEFLU_nmYIO0MKtN1sv2JSc2Hb9YBx8e1i9Tp6F0xLm7ARjwRnzC3t6XASxeDYgJmE-Dbx_2DQMoCxv2jaahu4u3HgLz53WVv4MRisjOyuK2v2Lvgeh_UILDAwuNfDqwcFCqzocDeH0rAhAX_9IqX0kJmOlCO-oSVqAhUmXmVl-FjZFScZhLardQvKMoFunPVrOnJihNQvF_v7zqLoIPylnW2uFD46U-8fgGy1TeH0Sq41NfRSoB0_19xQuxkwwPOVpc4XWLNO3AehX6HGmivcniezFdJ2WjR4gLLqL62jge8Y71S9z3QTDtp8HIxgiSn1NaQT_3OzSBzwz_eSvwdjaswygO0XetYSwZ8m7Jmoiq9k4W-hVudNKiRWp7U-CV_2pMH-Yse3f9VLoACWQw2uHD6t-jIHLgFTODAJE9O_0VG4IGVKniJNNAq41NVQmulhciVG9m2VoTl_7fPb9eMReg1HYkxCFa_TRK4YvgxerbKX7H3JV5s8OmMAbg7Vw064N2T2CDFZIg

Here is the updated URL. Can you tell me why this URL not working in rendering?

**Comment by K-JBoon** [comment]
Hey @kishanPrajapat-Forcebolt , it looks like the provided source asset is not publicly available as pointed out by @limzykenneth 

It's important to note that while the URL may work in your browser, the requests made by Nexrender to download the URL do not have any of your browser's session or cookie data, so it can't actually access the asset.

For content that's supposed to require an authentication/authorization step I'd recommend writing your own implementation to download the assets to the local filesystem, and then refer to them in the jobs by path.

For content that can be public make sure the URLs are publicly accessible, for example by uploading them to a public image hosting service, or as public objects in a cloud object store. You can easily check if they're publicly accessible by trying to open the URL in an incognito browser window.

**Comment by kishanPrajapat-Forcebolt** [comment]
Ok let me check from my end.

**Comment by kishanPrajapat-Forcebolt** [comment]
I'm getting the above URL from google photos auth. I think the issue is from there only.

**Comment by kishanPrajapat-Forcebolt** [comment]
Hi @K-JBoon @limzykenneth 
I have solved the above issue thanks for your support.

Currently, I'm struggling with some doubt about whether can we shuffle the layers through the JSON Job. Like, I have 10 image layers 1 to 10 with some names. I have made the JSON job in sequence order. So If I'm writing the JSON in some shuffle way then the layers got shuffled or not?
