### ISSUE TITLE
Sometimes render function hangs up

### ISSUE THREAD

**Issue by vishnushelar** [inlife/nexrender#883]
Sometimes render function hangs up and keep processing in waiting state for infinite time.

**Comment by inlife** [comment]
It is indeed the case, once about every 40-50 renders that happens in my case. 
I will investigate a potential to abort the job after a stale is detected for more than a given time period.

**Comment by dhavalyours** [comment]
i agree with inlife,  we are facing  the same issue every 40 50 renders

**Comment by inlife** [comment]
I implemented a new algo for aborting the job if the aerender is not responding for a while In the most recent version of nexrender.
