### ISSUE TITLE
stop a job when state is rendering job (nexrender-worker-nexrender-server)

### ISSUE THREAD

**Issue by nazemi0101** [inlife/nexrender#885]
hi ,
we use this verisions
nexrender-server-win64.exe v1.43.0 
nexrender-worker-win64.exe v1.43.0
i add jobs with send request to nexrender-server with method POST /api/v1/jobs after nexrender-server send jobs to a worker and worker do rendering 

we want to stop (kill rendering to stop process) jobs with request to nexrender-server with 
method PUT /api/v1/jobs/:uid   or  method  DELETE /api/v1/jobs/:uid or everyway  to do this

even not way to do this . i think can do workaround with delete job and stopped and when get error or rendering stop command cmd and run automatically new worker  cmd to continue rendering and do another jobs... (add this feature to cancel jobs)

we try to delete jobs to stopped or canceled workaround . process is stopped and worker stopped but get a error 
please help to find a way to do delete or stopped without error with nexrender-server ,worker or cli or programmer ... 

this is my worker when delete jobs on rendering

[-_rx8niUVA_iOD2bgDL89] rendering progress 0%...
[-_rx8niUVA_iOD2bgDL89] rendering progress 12%...
node:internal/process/task_queues:95
    runMicrotasks();
    ^

Error: AssertionError [ERR_ASSERTION]: job must have template object defined
    at validate (C:\snapshot\packages\nexrender-types\job.js)
    at C:\snapshot\packages\nexrender-server\src\routes\jobs-update.js
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at wrappedFetch (C:\snapshot\nexrender\packages\nexrender-api\src\index.js)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.updateJob (C:\snapshot\nexrender\packages\nexrender-api\src\job.js)

Node.js v18.5.0

**Comment by limzykenneth** [comment]
There isn't a way to do this just yet with existing API, I would be interested in having the ability to abort a rendering task, although halting and cleaning up AE after halting it like this may be a bit tricky.
