### ISSUE TITLE
How to cancel a rendering job 

### ISSUE THREAD

**Issue by RezaRamezanisani** [inlife/nexrender#886]
i use from 
 nexrender-server.exe (1.43.0)
 nexrender-worker-exe (1.43.0)
my question:
Is it possible to stop a job while rendering by sending a request (now with any delete or put method) to the nexrender server with API and then be ready to receive subsequent requests to add a new job. If possible, please tell me what I should do

**Comment by inlife** [comment]
Hey,

Unfortunately this functionality does not exist, so not possible to do at the moment.
