### ISSUE TITLE
Unable to generate video : Object of type AVLayer found where a Number, Array, or Property is needed

### ISSUE THREAD

**Issue by VidyBack** [inlife/nexrender#896]
**Describe the bug**
Unable to generate video 
I am getting this error : Error: Object of type AVLayer found where a Number, Array, or Property is needed
                                     aerender ERROR: Runtime error in After Effects.

**Information about environment**
v1.43.2
cli
npm packages
Window11
After Effect 2023

**Expected behavior**
when i named layer "storeName" its not rendering but after renaming it works

**Comment by inlife** [comment]
Hey @VidyBack 

Does this bug also happen when you are using an older version of nexrender?
v1.43.0 for example

THanks!

**Comment by VidyBack** [comment]
after debugging i found out that text layername And composition name both had the same name ,after i changed the composition name from storename to something else its worked

**Comment by inlife** [comment]
Ok, so to sum up so far:

### NEVER NAME COMPOSITION AND LAYER THE SAME NAME

**Comment by inlife** [comment]
I'll see if there is something we can do on the script side to prevent that, but for now, this recommendation should be helpful, it seems.

**Comment by PaajaE** [comment]
@inlife 
This was a lifesaver for me - exactly same problem. Nevertheless, there is also a bug in nexrender or more precisely JSX script file:

Inside changeValueForKeyPath the throw error clause is triggering a crash in AE. It's just a matter of replacing `layer` with `layer.name` at the end of the message and everything will work

**Comment by inlife** [comment]
Oh, thanks @PaajaE 
Will fix this in the next release!

**Comment by inlife** [comment]
Should alredy be fixed in the latest release
