### ISSUE TITLE
video does not render using nexrender

### ISSUE THREAD

**Issue by raomanish07** [inlife/nexrender#90]
I am using nexrender-boilerplate project for dynamic video render (https://github.com/inlife/nexrender-boilerplate).but i am getting error.
![nexrender](https://user-images.githubusercontent.com/10682113/52088292-7bfbc180-25d1-11e9-98da-0d5045fb81f8.png)

I am uploaded the error screen shot.
Please help me to resolve the issue.

**Comment by inlife** [comment]
most likely you are using a newer version of After Effects which doesn't support mp4 output, please change the configuration option to avi for windows

**Comment by raomanish07** [comment]
Thanks for quick reply.sure i will change the configuration format mp4 to AVI.

Thanks

**Comment by raomanish07** [comment]
change the configuration avi but no luck. getting the same error with result.avi not found in temp/.../result.avi..

Thanks

**Comment by inlife** [comment]
is there a rendered video tho ?

**Comment by raomanish07** [comment]
No any video file rendered.

**Comment by inlife** [comment]
there is probably some error while rendering the video
try launching rendering with a AE_LOG env var before the command
```$ AE_LOG=D:/test/ae.log COMMAND```
this should trigger aerender to create a log for this job, and you might see more details there

**Comment by inlife** [comment]
@raomanish07 was there any progress ?
