### ISSUE TITLE
Move a composition in the timeline/change its duration?

### ISSUE THREAD

**Issue by ATroschke** [inlife/nexrender#900]
Hey,

I am trying to automatically combine .mp4 files in varying length, but can't seem to understand how I would make this possible using nexrender. I am relatively new to AE as well, so I am not comfortable using ExtendScript, but I do have programming knowledge.

Can anyone guide me to an example project using such an approach that is capable of combining 3+ mp4 files of varying length?

Thanks!

**Comment by limzykenneth** [comment]
When you say "combine", do you mean concat (ie. one video after another) or having more complex layout with the different videos? If it is just concat I would not recommend AE and nexrender for this as something like FFMPEG can do that relatively easily. If it is more complex layout, you will need to create that composition in AE first and the actual method depends on what the layout actually is.

**Comment by ATroschke** [comment]
I have a rather complex data-driven Layout. I am (for the lack of figuring
out data assets in nexrender currently) also using mamoworldJSON to fill in
data.

The Individual sections depend on each other and share the data passed into
the .aep.

I have, however, a single "repeatable" comp that is currently filled with a
1-hour long asset as a placeholder (assets injected through nexrender are
at most 4-5 minutes).

I have seen some talk about changing start and end times of a layer but
haven't quite figured out how I would manage that.

Also since I am replacing the asset in the repeatable comp, would I have to
add placeholder compositions (repeat 1...repeat n)? Since changing the
asset in the repeatable comp would probably change it for all instances.

Kenneth Lim ***@***.***> schrieb am Fr., 9. Juni 2023, 12:37:

**Comment by limzykenneth** [comment]
I might be misunderstanding but is what you are trying to do is to replace a 1 hour long footage asset in a composition with a single shorter footage that loops? You can do that with standard [asset replacement](https://github.com/inlife/nexrender#footage-items) and set the layer in AE itself to loop. I'm not too familiar with the last part so you may need to look up how to loop a footage layer in AE (layer settings or expressions).

The more you can set up and working in AE, the easier it is to work with a nexrender pipeline, I often find.
