### ISSUE TITLE
Rendering is very slow

### ISSUE THREAD

**Issue by ab192130** [inlife/nexrender#903]
Hi **nexrender** community. I'm trying to render a video with nexrender.
The length of the video I'm trying to render is: 20 sec.
But render takes about 11 minutes. 

I've tried enabling "**multiFrames**" option. But it didn't help. Rendering time was the same.
 
"**maxMemoryPercent**" and "**multiFramesCPU**" options are set to default values.

I've tried both binary and programmatical ways. PM2 load-balancing also have been tried.

Current system specs are: 
- Core i7 i5-9300HF (8 CPUs), ~2.4GHz
- Memory: 16Gb RAM
- GPU: NVIDIA Geforce GTX 1650

How can I increase my rendering time? I'll appreciate any help. Thank you

**Comment by inlife** [comment]
Hey @ab192130! 

Did you measure what time it takes to render precisely the same composition and set of settings within After Effects directly (without nexrender)?

**Comment by JamesBotterill** [comment]
How long does it take when rendering by the AErender cli without nexrender?

**Comment by turgutreis** [comment]
how can I halve the render settings?

**Comment by inlife** [comment]
@turgutreis please elaborate what do you mean?
