### ISSUE TITLE
Could not require module '@nexrender/action-encode' with v1.44.1 binary

### ISSUE THREAD

**Issue by meza** [inlife/nexrender#905]
Hi, I'm getting the following and I'm not sure where to go from here.

I'm using the v1.44.1 MacOS Binary from the releases. I've even installed @nexrender/action-encode as a global package just to be safe but that doesn't help.

```
error occurred: NestedError: Could not require module '@nexrender/action-encode'
    at requireg (/snapshot/nexrender/packages/nexrender-core/node_modules/requireg/lib/requireg.js:14:11)
    at /snapshot/nexrender/packages/nexrender-core/src/tasks/actions.js
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Caused By: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
```

**Information about environment**

* Which version of nexrender are you using?
 v1.44.1

* What kind of the setup do you have? (server+worker or cli)
 server + worker

* Are you using pre-built binaries or globally installed npm packages?
 binaries

* Which kind (and version) of operating system you are running it in?
 server: ubuntu 22.10
 worker: MacOS 13.4

* Any additional information that might be helpful

**Expected behavior**
I'd expect the encoding to work

**Screenshots**
![image](https://github.com/inlife/nexrender/assets/211977/4baabd74-08c2-461e-a2ab-9b9dd84b210c)

**Comment by meza** [comment]
I downgraded to 1.43.3 and it works there.

**Comment by inlife** [comment]
Hey @meza 

I see, thanks. I will investigate.

**Comment by inlife** [comment]
Uploaded new fixed binaries to the same release https://github.com/inlife/nexrender/releases/tag/v1.44.1
Please take a look to see if it works for you now.

(they got significantly bigger, seems like during packaging some packages were not properly linked)

**Comment by meza** [comment]
Works now, thanks!
