### ISSUE TITLE
Incorrect reference to `fetch` instead of `wrappedFetch`

### ISSUE THREAD

**Issue by limzykenneth** [inlife/nexrender#913]
**Describe the bug**
On [this line](https://github.com/inlife/nexrender/blob/master/packages/nexrender-api/src/job.js#L23C53-L23C58) the reference to `fetch` was not changed to `wrappedFetch` and so will still be referencing the environment's fetch.

**Comment by inlife** [comment]
Oh, good catch @limzykenneth 
I'll fix this in the upcoming update

**Comment by inlife** [comment]
Should be fixed in https://github.com/inlife/nexrender/releases/tag/v1.45.3
