### ISSUE TITLE
Can't find a property sequence

### ISSUE THREAD

**Issue by arthuraltino** [inlife/nexrender#920]
**Describe the bug**
I'm trying to set the value of Text.Animator_1.Range_Selector_1.End, but nexrender cli always return this error: ` rendering reached an error: nexrender: Can't find a property sequence Animator_1.Range_Selector_1.End for key: Animator_1within layer: lyrics`
I've already tried all possible solutions given in other issues.

**Information about environment**
* Which version of nexrender are you using? Nexrender 1.45.4 - Win x64
* What kind of the setup do you have? CLI
* Are you using pre-built binaries or globally installed npm packages? Pre-built binary
* Which kind (and version) of operating system you are running it in? Windows 11
* After Effects 2023

**Screenshots**
![image](https://github.com/inlife/nexrender/assets/36716544/b920b0ff-e4e3-4b77-92da-5478d81ae0f3)

**Comment by inlife** [comment]
I would suggest trying to open ExtendScript toolkit, connect it to your AE instance, and try to manually figure out how to access this property.

nexrender is trying to do something like this: `layer.property('Text').property('Animator_1').property('Range_Selector_1').property('End')`
And this does not work, so maybe some other approach needs to be taken for this specific case.

**Comment by arthuraltino** [comment]
> I would suggest trying to open ExtendScript toolkit, connect it to your AE instance, and try to manually figure out how to access this property.
> 
> nexrender is trying to do something like this: `layer.property('Text').property('Animator_1').property('Range_Selector_1').property('End')` And this does not work, so maybe some other approach needs to be taken for this specific case.

Thanks for the quick answer. ExtendScript toolkit helped me finding the right property sequence (`Text.Animators.Animator_1.Selectors.Range_Selector_1.End`), but now i'm facing another error, that comes from After Effects itself:
`Error: After Effects error: Can not "set value" with this property, because the property or a parent property is hidden.
aerender ERROR: Runtime error in After Effects.`
