### ISSUE TITLE
AfterFX.exe crashing with dialog

### ISSUE THREAD

**Issue by erlendp** [inlife/nexrender#921]
We've encountered several situations where the `AfterFX.exe` process crashes with a dialog that prevents the process from terminating, and subsequently hangs the nexrender worker until the render timeout elapses. This is obviously problematic, especially when the workers are running as background services, and took us a while determine the cause.

Does anyone know if there's a way to avoid displaying this dialog in the event of a crash? Apparently checking 'Don't show again' doesn't help!

Alternatively, it'd be good if nexrender could detect this situation, and automatically terminate the process.

**Comment by inlife** [comment]
Any information what is the cause of the crash within the dialog box as reported by AfterFX?

**Comment by erlendp** [comment]
Not that I can see, although there is a process dump provided.

<img width="1101" alt="image" src="https://github.com/inlife/nexrender/assets/34012855/5f3e5994-4b9a-4f34-b525-0d6dbbd8b403">

**Comment by inlife** [comment]
I experienced this hangs myself. They are indeed a rare occurrence, happening once per 100 renders or so.
However, I was never able to understand the root cause.

**Comment by erlendp** [comment]
I'm fairly sure there are some AEP files that consistently crash with `aerender`, but I'm sure the converse is also true.

Do you think there would be anything we could put into place to detect this crash, and kill the process early?

**Comment by dougclift** [comment]
This happened to me twice in the past week.  Here is the windows event log.  I also saved the dmp file from the after effects crash window if that might help.

[AE Error.txt](https://github.com/inlife/nexrender/files/13088626/AE.Error.txt)

**Comment by inlife** [comment]
I noticed `RADAR_PRE_LEAK_64` in the log, which points me to this: https://answers.microsoft.com/en-us/windows/forum/all/radarpreleak64/a534e186-65ab-42c9-97e2-b654a713f0db

Could be that there is some bug in AE that causes extensive memory leak, which then in turn causes OS to terminate the process, or something along those lines.
