### ISSUE TITLE
You should provide a proper path to After Effects' "aerender" binary

### ISSUE THREAD

**Issue by Hardik4296** [inlife/nexrender#927]
Can you please help me to solve this.
You should provide a proper path to After Effects' "aerender" binary
![image](https://github.com/inlife/nexrender/assets/66513550/f963ebec-47a2-4a12-b06b-f0e44c3349d3)

here is my json :
{
    "template": {
        "src": "XXXXXX/T.aep",
        "composition": "MAIN"
    }
}

**Comment by JamesBotterill** [comment]
What version of after effects do you have installed?

**Comment by Hardik4296** [comment]
i do not have installed yet. does it mandatory?

**Comment by JamesBotterill** [comment]
Yes After Effect is mandatory as it handles the rendering

**Comment by Hardik4296** [comment]
Okay thanks
