### ISSUE TITLE
you need to run application with admin priviledges once to install Adobe After Effects commandLineRenderer.jsx patch

### ISSUE THREAD

**Issue by Hardik4296** [inlife/nexrender#928]
Please suggest me what am i doing wrong here.
![image](https://github.com/inlife/nexrender/assets/66513550/018db3be-714f-4804-b46c-0e55aaa6d27b)

{
    "template": {
        "src": "https://xxx/xxx/temp1/T.aep",
        "composition": "main"
    }
}

**Comment by JamesBotterill** [comment]
Open command prompt as administrator, normally on windows I think you can right click on Command Prompt and select open as administrator

**Comment by Hardik4296** [comment]
Ohk I got it. Thanks
