### ISSUE TITLE
can i use without installing adobe after effect.

### ISSUE THREAD

**Issue by Hardik4296** [inlife/nexrender#929]
Hello can i use nexrender without installing adobe after effect software.

**Comment by pernydev** [comment]
No. You cannot render a job/use a worker/use the CLI without After Effects on the worker/cli machine. You can use nexrender-server but that will not allow you to render without workers.
![image](https://github.com/inlife/nexrender/assets/83672513/7f8bdbdd-1ee6-404f-87e9-57be13db0fe6)

**Comment by pernydev** [comment]
I even made this!
![image](https://github.com/inlife/nexrender/assets/83672513/d645454a-1ba9-4929-aefe-279b08df755d)

**Comment by inlife** [comment]
nice one @pernydev! 😂😂 😂
