### ISSUE TITLE
How to change text layer color and shape layer background color with json?

### ISSUE THREAD

**Issue by vimaloneuser** [inlife/nexrender#930]
![image](https://github.com/inlife/nexrender/assets/75586053/2c4aebbc-412b-4f4c-b51b-e7d26adbc2a4)
![image](https://github.com/inlife/nexrender/assets/75586053/9f70d9e2-6ead-4e48-bd44-cde30bb2aa9e)

I want to change the font color of THE WEDDING and I want to change the background color of Shape Layer 4 so I have tried with the below type of JSON but none of these are working.

1.
"assets": [
  {
    "type": "data",
    "layerName": "THE WEDDING",
    "property": "Color",
   "value": [1.0, 0.5, 0, 0]
  }
  {
    "type": "data",
    "layerName": "Shape Layer 4",
    "property": "Color",
   "value": [1.0, 0.5, 0, 0]
  }
]
Error: Error: nexrender: Can't find a property sequence Color for key: Colorwithin layer: Shape Layer 4

2.
"assets": [
  {
    "type": "data",
    "layerName": "THE WEDDING",
    "property": "Effects.Skin_Color.Color",
    "value": [1, 0, 0]
  }
  {
    "type": "data",
    "layerName": "Shape Layer 4",
    "property": "Effects.Skin_Color.Color",
    "value": [1, 0, 0]
  }
]
Error: Error: Error: nexrender: Can't find a property sequence Color for key: Effects.Skin_Color.Color layer: Shape Layer 4

Can anyone help here?

**Comment by benrohel** [comment]
For the shape Layer, you need to provide the path of the property, it should be something like :
`Contents.Rectangle 1.Fill.Color` assuming your shape is a Rectangle.

For the text, the color is not accessible with a simple property.
I see two options, First you replace the value in your JSON with an expression to set the text style:
`{
            "type": "data",
            "layerName": "THE WEDDING",
            "property": "Text.Source Text",
            "expression": "let style = text.sourceText.style..setFillColor([1,0,0]);"
        },`

Option 2 : you add a Color Control and use an expression on the Text to set the color using the Color Control, and in your JSON, you set Color Control itself.

expression on text : `let style = text.sourceText.style;
let color = effect("Color Control")("Color");
style.setFillColor(color);
`
JSON 
`{
"type": "data",
"layerName": "THE WEDDING",
"property": "Color Control..Color",
"value": [1, 0, 0]
}`

<img width="1846" alt="Screenshot 2023-11-06 at 6 16 00 AM" src="https://github.com/inlife/nexrender/assets/73726219/ab420056-26a6-42f5-95a5-d38fff2c6f40">

**Comment by viratsharma56** [comment]
Can you help me in how to target the source text?
