### ISSUE TITLE
Error: nexrender: Can't find a property sequence Color for key: Colorwithin layer

### ISSUE THREAD

**Issue by vimaloneuser** [inlife/nexrender#931]
![Screenshot 2023-11-02 at 12 46 23 AM](https://github.com/inlife/nexrender/assets/75586053/011ae4e5-45b8-4129-8876-769c5faf46c4)
![Screenshot 2023-11-02 at 12 46 40 AM](https://github.com/inlife/nexrender/assets/75586053/b8ef641a-b624-4f04-920e-47edcb3f6436)

I want to change the font color of THE WEDDING and I want to change the background color of Shape Layer 4 so I have tried with the below type of JSON but none of these are working.

1.
"assets": [
  {
    "type": "data",
    "layerName": "THE WEDDING",
    "property": "Color",
   "value": [1.0, 0.5, 0, 0]
  }
  {
    "type": "data",
    "layerName": "Shape Layer 4",
    "property": "Color",
   "value": [1.0, 0.5, 0, 0]
  }
]
Error: Error: nexrender: Can't find a property sequence Color for key: Colorwithin layer: Shape Layer 4

2.
"assets": [
  {
    "type": "data",
    "layerName": "THE WEDDING",
    "property": "Effects.Skin_Color.Color",
    "value": [1, 0, 0]
  }
  {
    "type": "data",
    "layerName": "Shape Layer 4",
    "property": "Effects.Skin_Color.Color",
    "value": [1, 0, 0]
  }
]
Error: Error: Error: nexrender: Can't find a property sequence Color for key: Effects.Skin_Color.Color layer: Shape Layer 4

Can anyone help here ?

**Comment by sharukhmohammed** [comment]
I have experienced the same issue and root cause of this issue for me is that, two compositions named with exact same, and have different layers/properties. `aerender` takes the first match only, always.
