### ISSUE TITLE
Typo in the job init() Method.

### ISSUE THREAD

**Issue by phlexib** [inlife/nexrender#938]
**Describe the bug**
there's a typo in the job init Method at line 64. 
`addicense` instead of `addLicense`

**Expected behavior**
Object.assign should correctly assign `addLicense`

**Screenshots**
<img width="540" alt="Screenshot 2023-11-06 at 7 11 24 AM" src="https://github.com/inlife/nexrender/assets/7967308/c6ad824d-fe88-4291-ba41-a543eb2ea8ed">

**Comment by inlife** [comment]
Good catch, going to push a fix!

**Comment by inlife** [comment]
Actually, where did you find this? Current master has it set up correctly: https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/index.js#L76

**Comment by phlexib** [comment]
Updated to **1.46.5** and it is indeed fixed.
