### ISSUE TITLE
quote values in `type=data` assets

### ISSUE THREAD

**Issue by egradman** [inlife/nexrender#94]
I'm generating my `job.json` using python, and the json is generated with double quotes.  That means I might have unescaped single quotes in the output.

```
 {
   "type": "data",
   "layerName": "content_title",
   "composition": "Title",
   "property": "Source Text",
   "value": "Something with a ' character"
}
```

This generates a syntax error when running the JSX file, because the code generator isn't escaping the single quote.

I think the `wrapData` function in `tasks/script.js` should sanitize this string, but I'm not _exactly_ sure if that's the right place (I just started playing with this package yesterday) so I'm not providing a pull request.

**Comment by inlife** [comment]
oh yes, single quotes in this case always should be escaped
that applies for all of those values: `layerName`, `composition`, `property`, `value`, `expression`

**Comment by inlife** [comment]
added a simple escaping algo for singular quotes: https://github.com/inlife/nexrender/commit/d60db436ad7721c1210bf35c41273b235675e06a
