### ISSUE TITLE
How to target the Source Text

### ISSUE THREAD

**Issue by viratsharma56** [inlife/nexrender#941]
I am trying to edit the text for aep video. I am using this JSON for the purpose:
`const myJobJson = {
    "template": {
        "src": "file:///Users/virat/Downloads/sample/After Effect/Switch To Text Box Titles-2.aep",
        "composition": "01 Scene",
        "outputModule": "H.264 - Match Render Settings - 15 Mbps",
        "outputExt": "mp4",
        "settingsTemplate": "Best Settings"
    },
    "assets": [
        {
            "type": "data",
            "layerName": "01_01 Text",
            "composition": "01 Scene",
            "property": "Source Text",
            "value": "hello"
        }
    ]
}`

The layer structure of AEP looks like:
<img width="351" alt="image" src="https://github.com/inlife/nexrender/assets/63762280/adb6ad79-b5b5-4fc2-80ea-65812da3306c">

Getting this error: `Can't find a property sequence Source Text for key: Source Textwithin layer: 01_01 Text`

Can someone help me with this?

**Comment by JamesBotterill** [comment]
remove this from the asset "composition": "01 Scene"

You just need to reference the layer name, also the layer within the pre-comp 10_01 Text

**Comment by viratsharma56** [comment]
Hey James, thanks for helping out. But I have tried with this assets:
`"assets": [
        {
            "type": "data",
            "layerName": "01_01 Text",
            "property": "Source Text",
            "value": "hello"
        }
    ]`

But it shows the same error: `Can't find a property sequence Source Text for key: Source Textwithin layer: 01_01 Text`

**Comment by viratsharma56** [comment]
@JamesBotterill can you help here?

**Comment by JamesBotterill** [comment]
apologies, the text seems to be within a "01_01 Text" pre-comp and not "01 Scene" as stated in your json object, this means it was looking in the wrong place. 

I see that your pre-comp being the same name as the text layer this could be the issue as when the script is matching to an object in the project it finds the pre-comp layer first and not the text layer within it. I would try to rename of of the layers maybe the pre-comp to "01_01 Text Comp" and try again.

**Comment by viratsharma56** [comment]
Yupp, it works now. Thanks
