### ISSUE TITLE
Error: Couldn't find module @nexrender/provider-e, Unknown protocol provided.

### ISSUE THREAD

**Issue by JoeyKentin** [inlife/nexrender#942]
I'm getting this error any idea what i might be doing wrong?

Error: Couldn't find module @nexrender/provider-e, Unknown protocol provided.
    at download (C:\snapshot\nexrender\packages\nexrender-core\src\tasks\download.js)
    at C:\snapshot\nexrender\packages\nexrender-core\src\tasks\download.js
    at C:\snapshot\nexrender\packages\nexrender-core\src\helpers\state.js
    at C:\snapshot\nexrender\packages\nexrender-core\src\index.js
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:64:3)
    at Function.runMain (pkg/prelude/bootstrap.js:1980:13)
    at node:internal/main/run_main_module:17:47

This is my code
{
    "template": {
        "src": "E:/School/23-24/ExpertLab/6-WebVideoAutomation/project.aep",
        "composition": "Main"
    },
    "assets": [
        {
            "type": "data",
            "layerName": "name",
            "property": "Source Text",
            "value": "Joey"
        },
        {
            "src":"E:/School/23-24/ExpertLab/6-WebVideoAutomation/Assets/Background/background_001.jpg",
            "type": "image",
            "layerName": "background.png"
        },
        {
            "src": "E:/School/23-24/ExpertLab/6-WebVideoAutomation/Assets/Audio/audio_001.mp3",
            "type": "audio",
            "layerName": "audio.mp3"
        }
    ],
    "actions": {
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "encoded.mp4",
                "output": "E:/School/23-24/ExpertLab/6-WebVideoAutomation/Export/prototype_001.mp4"
            }
        ]
    }
}

**Comment by inlife** [comment]
Please update the asset and template "src" attributes to look like the following: `file:///e/School/...`
