### ISSUE TITLE
How do I configure multiple nexrender-workers on one nexrender-server?

### ISSUE THREAD

**Issue by DongJu-Na** [inlife/nexrender#946]
The final program architecture I want to construct is React <-> Java <-> nexrender-server <-> nexrender-worker.
I would like to have multiple nexrender-workers here.

After uploading a file through Java Rest API, I want to combine the uploaded file path and various data to pass the final json to nexrender-server.

This situation requires rendering to create multiple videos at the same time. Accordingly, multiple workers are needed. Can you help me

**Comment by JamesBotterill** [comment]
Looks at tagging, you can connect multiple workers each with its own tag, then when submitting a video you can add the tag for the corresponding worker.

It's pretty easy just follow the documentation

**Comment by DongJu-Na** [comment]
thank you :)
