### ISSUE TITLE
Post render action (action-encode) seems to be failing.

### ISSUE THREAD

**Issue by solanki21** [inlife/nexrender#948]
**Describe the bug**
Job gets stuck on "rendering.." message and does not show any % progress. I see that the mp4 file is begin created in the temp folder (named result.mp4) but it is not being encoded nor copied at specified destination.

My Nexrender script part for post render action:

  "actions" : {
    "postrender" : [
      {
        "module": "@nexrender/action-encode",
        "output": "encoded.mp4",
        "preset": "mp4",
        "params": {"-vcodec": "libx264", "-r": 25}
      },
      {
        "module" : "@nexrender\/action-copy",
        "input" : "encoded.mp4",
        "output" : "C:\\result.mp4"
      }
    ]
  }

Log:
[KzogcoVYqvGnTqYZk3qUS] working directory is: C:\Users\ContainerAdministrator\AppData\Local\Temp\nexrender\KzogcoVYqvGnT
qYZk3qUS
[KzogcoVYqvGnTqYZk3qUS] applying predownload actions...
[KzogcoVYqvGnTqYZk3qUS] downloading assets...
[KzogcoVYqvGnTqYZk3qUS] applying postdownload actions...
[KzogcoVYqvGnTqYZk3qUS] applying prerender actions...
[KzogcoVYqvGnTqYZk3qUS] running script assemble...
[KzogcoVYqvGnTqYZk3qUS] rendering job...

**Information about environment**
* Which version of nexrender are you using?
Latest win-64 binary.

* What kind of the setup do you have? (server+worker or cli)
Only worker.

* Are you using pre-built binaries or globally installed npm packages?
pre-built binary.

* Which kind (and version) of operating system you are running it in?
Windows 2019 Server.

* Any additional information that might be helpful

**Expected behavior**
Should present % rendering progress and copy resulting video file to specified location.

**Comment by inlife** [comment]
Hey

Could you share your after effects rendering log?

**Comment by solanki21** [comment]
I am not sure if this is the correct log file as it contains little information. Here is my screen grab:

 Directory of C:\Users\ContainerAdministrator\AppData\Local\Temp\nexrender\XWoC9-TIlhAWClzPG1SRd

12/20/2023  08:28 AM    <DIR>          .
12/20/2023  08:28 AM    <DIR>          ..
12/20/2023  08:27 AM        11,200,613 AEProject.aep
12/20/2023  08:27 AM    <DIR>          AEProject.aep Logs
12/20/2023  08:27 AM             2,436 FilePathReplacer.jsx
12/20/2023  08:27 AM         3,450,671 music.mp3
12/20/2023  08:27 AM            25,022 nexrender-XWoC9-TIlhAWClzPG1SRd-script.jsx
12/20/2023  08:27 AM           534,512 photo-1.jpg
12/20/2023  08:27 AM           501,326 photo-10.jpg
12/20/2023  08:27 AM           577,754 photo-2.jpg
12/20/2023  08:27 AM           577,611 photo-3.jpg
12/20/2023  08:27 AM           566,647 photo-4.jpg
12/20/2023  08:27 AM           568,395 photo-5.jpg
12/20/2023  08:27 AM           558,113 photo-6.jpg
12/20/2023  08:27 AM           581,123 photo-7.jpg
12/20/2023  08:27 AM           581,780 photo-8.jpg
12/20/2023  08:27 AM           574,566 photo-9.jpg
12/20/2023  08:28 AM         9,303,438 result.mp4
              15 File(s)     29,604,007 bytes
               3 Dir(s)  20,708,474,880 bytes free

C:\Users\ContainerAdministrator\AppData\Local\Temp\nexrender\XWoC9-TIlhAWClzPG1SRd>cd "AEProject.aep Logs"

C:\Users\ContainerAdministrator\AppData\Local\Temp\nexrender\XWoC9-TIlhAWClzPG1SRd\AEProject.aep Logs>dir
 Volume in drive C has no label.
 Volume Serial Number is CE15-4C82

 Directory of C:\Users\ContainerAdministrator\AppData\Local\Temp\nexrender\XWoC9-TIlhAWClzPG1SRd\AEProject.aep Logs

12/20/2023  08:27 AM    <DIR>          .
12/20/2023  08:27 AM    <DIR>          ..
12/20/2023  08:28 AM             5,652 AE 12-20-2023 8-27-49 AM.txt
               1 File(s)          5,652 bytes
               2 Dir(s)  20,708,474,880 bytes free

C:\Users\ContainerAdministrator\AppData\Local\Temp\nexrender\XWoC9-TIlhAWClzPG1SRd\AEProject.aep Logs>type "AE 12-20-202
3 8-27-49 AM.txt"
Adobe After Effects v23.1 Windows 64 render log for project â€œAEProject.aepâ€

Rendering started on 12/20/2023 at 8:27:49 AM

  12/20/2023 8:27:50 AM: Starting composition â€œScene 01â€.

  12/20/2023 8:28:51 AM: Finished composition â€œScene 01â€.mp\nexrender\XWoC9-TIlhAWClzPG1SRd\result.mp4


  Total Time Elapsed: 1 Min, 1 Sec
Log closed on 12/20/2023 at 8:28:51 AM

**Comment by inlife** [comment]
nexrender usually says the path of the ae render log file when rendering is happening
try to look in these folders:
* C:\Users\ContainerAdministrator\AppData\Local\Temp\nexrender\
* C:\Users\ContainerAdministrator\AppData\Local\Temp\nexrender\XWoC9-TIlhAWClzPG1SRd\

**Comment by solanki21** [comment]
Yes I looked into that folder. There is file called `AE 12-20-2023 8-27-49 AM.txt` inside
`C:\Users\ContainerAdministrator\AppData\Local\Temp\nexrender\XWoC9-TIlhAWClzPG1SRd\AEProject.aep Logs` folder.
I didn't find anything else.

**Comment by huangmengasd** [comment]
> **Describe the bug** Job gets stuck on "rendering.." message and does not show any % progress. I see that the mp4 file is begin created in the temp folder (named result.mp4) but it is not being encoded nor copied at specified destination.
> 
> My Nexrender script part for post render action:
> 
> "actions" : { "postrender" : [ { "module": "@nexrender/action-encode", "output": "encoded.mp4", "preset": "mp4", "params": {"-vcodec": "libx264", "-r": 25} }, { "module" : "@nexrender/action-copy", "input" : "encoded.mp4", "output" : "C:\result.mp4" } ] }
> 
> Log: [KzogcoVYqvGnTqYZk3qUS] working directory is: C:\Users\ContainerAdministrator\AppData\Local\Temp\nexrender\KzogcoVYqvGnT qYZk3qUS [KzogcoVYqvGnTqYZk3qUS] applying predownload actions... [KzogcoVYqvGnTqYZk3qUS] downloading assets... [KzogcoVYqvGnTqYZk3qUS] applying postdownload actions... [KzogcoVYqvGnTqYZk3qUS] applying prerender actions... [KzogcoVYqvGnTqYZk3qUS] running script assemble... [KzogcoVYqvGnTqYZk3qUS] rendering job...
> 
> **Information about environment**
> 
> * Which version of nexrender are you using?
>   Latest win-64 binary.
> * What kind of the setup do you have? (server+worker or cli)
>   Only worker.
> * Are you using pre-built binaries or globally installed npm packages?
>   pre-built binary.
> * Which kind (and version) of operating system you are running it in?
>   Windows 2019 Server.
> * Any additional information that might be helpful
> 
> **Expected behavior** Should present % rendering progress and copy resulting video file to specified location.

Hello, have you resolved the above issue? In my case, it can render normally, but the code "result.on('progress', (job, percents) => console.log('project is at: ' + percents + '%'))" will only be executed after the rendering is finished, and finally display 100%.

**Comment by inlife** [comment]
I believe this issue is related to the language used within after effects rendering logs. I have a theory they might've changed the logs language from always English to local languages, as seen in this issue: https://github.com/inlife/nexrender/issues/945

**Comment by huangmengasd** [comment]
It is like this. I tried switching to English, and it was successfully executed. It seems that I have not fully understood this great project yet. Thank you for your response.

**Comment by inlife** [comment]
Could you share which language you had before, and how the after-effects rendering log looked like before?

**Comment by inlife** [comment]
I want to understand what potential modifications need to be made to support other languages out of the box

**Comment by huangmengasd** [comment]
I previously used Chinese. In the workpath, the Chinese parts in logs like "aerender-XXX.log" are garbled.
![1](https://github.com/inlife/nexrender/assets/29702229/5ef4fa79-aa2e-4f00-a661-850c24e086c2)
