### ISSUE TITLE
Rendering progress will only be returned when the ’outputModule‘ is set to ’H.264'.

### ISSUE THREAD

**Issue by huangmengasd** [inlife/nexrender#964]
When I try to replace `H.264 - Match Render Settings - 15 Mbps` or `H.264 - Match Render Settings - 40 Mbps` with `Lossless` or other output modules, the progress is not returned, and there are only three lines of information in the log: 

> Adobe After Effects v23.0 Windows 64 render log for project “test.aep”
> Rendering started on 2024/1/25 at 13:58:30
> 
> 
> Log closed on 2024/1/25 at 13:58:52

My version of AE is 2023. If I use `aerender.exe` directly for rendering, the output information is normal. I am not sure what could be causing this issue and hope to receive your answer.

**Comment by inlife** [comment]
I noticed similar things with ae23, not sure what could be the case. Something wrong is going on there.

Would be happy to get more insights from people in the community.

**Comment by huangmengasd** [comment]
I wrote a small program to test it, and found that I can retrieve the response information. I hope this can be helpful.
```
const { execFile } = require('child_process');

const aerenderPath = 'D:/Software/AE2023/Adobe After Effects 2023/Support Files/aerender.exe';
const projectPath = 'test.aep';
const outputPath = 'output.avi';

execFile(aerenderPath, ['-project', projectPath, 
                        '-comp', 'main',
                        '-RStemplate', 'Best Settings',
                        '-OMtemplate','Lossless',
                        '-output', outputPath
                        ], (error, stdout, stderr) => {
    if (error) 
        console.log(`error: ${error.message}`);

    if (stdout)
        console.log(`stdout: ${stdout}`);

    if(stderr)
        console.log(`stderr: ${stderr}`);
});
```
