### ISSUE TITLE
PNG sequence support

### ISSUE THREAD

**Issue by Tillaert** [inlife/nexrender#969]
Support for rendering templates with a PNG sequence.

When a template uses a PNG Sequence, this error occurs:

```
aerender ERROR: Error executing script: C:\Users\Tillaert\AppData\Local\Temp\nexrender\J5acLOrighu718keNwOOJ\nexrender-J5acLOrighu718keNwOOJ-script.jsx
Error: nexrender: Trying to create a file replacement for an unknown file: C:/Users/Tillaert/AppData/Local/Temp/videofier-AhbAb3/image-300x[25000-25036].png
```

An alternative would be to use PRORes 4444 as intermediate format.

PNG is prefered due to portability and alpha channel support.

**Comment by inlife** [comment]
Could you also show how your job definition looks like?

**Comment by inlife** [comment]
I added an experimental support for importing image sequences.

To mark an asset as a sequence, it must have "sequence": "true" defined on the json.
