### ISSUE TITLE
Error: After Effects error: File myPlaceholder is not a valid file type for import.

### ISSUE THREAD

**Issue by lincolnlemos** [inlife/nexrender#97]
I got this error message "Error: After Effects error: File myPlaceholder is not a valid file type for import." 

After some debug, I realized that the error was coming because I was using a layerName (myPlaceholder) without the file extension.

If you get the same error, just use a extension on your layerName like "myPlaceholder.mp4"

Should we add something warning about this on wiki? Like "If you are using layerName, you should have a file extension on the layerName".

**Comment by inlife** [comment]
good point, i think that best place for it would be near `layerName` definition in the readme

**Comment by inlife** [comment]
fixed in https://github.com/inlife/nexrender/commit/0c4e945150074e0e5f5163c0dca17ed515ff898c, closing the issue
