### ISSUE TITLE
AERender Options When Using --file Argument

### ISSUE THREAD

**Issue by antoinne85** [inlife/nexrender#975]
Hello and thanks in advance for any guidance you might be able to provide.

We're rendering by invoking the CLI on Windows and passing in the `--file` parameter to a job file. I've spent some time reading over the documentation and it's not clear to me how (or if) we can adjust some of the settings like enabling multi-frame rendering or controlling CPU/Memory limits when using the CLI.

Is it just something I'm overlooking in the documentation? If so, please feel free to tell me to RTFM (but a link to the portion of the manual that I've missed would be _really_ appreciated). Thanks again!

**Comment by inlife** [comment]
Hey @antoinne85 

The CLI documentation is a bit lacking in that regard. I would suggest taking a look at similar performance parameters for Worker. They will be identical for CLI: https://github.com/inlife/nexrender/tree/master/packages/nexrender-worker#information

Please do let me know if that helps!
