### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by andyglez96** [inlife/nexrender#981]
Hello guys,

Suddenly(since last Saturday) I started receiving this error in the middle of the render process. It happens randomly, not every time. Any idea on what could this be? Thank you in advance.
![image](https://github.com/inlife/nexrender/assets/88163491/918c07af-41be-44ff-a60b-d5b43d0c89a5)

**Comment by inlife** [comment]
Could you please specify which version of nexrender are you using?

**Comment by andyglez96** [comment]
sure

[v1.45.7](https://github.com/inlife/nexrender/releases/tag/v1.45.7)

**Comment by andyglez96** [comment]
I have updated to v1.50.0 and having the same behaviour

**Comment by inlife** [comment]
Are you using any proxy before your nexrender server, like nginx or something of sorts?

**Comment by andyglez96** [comment]
@inlife sorry, the problem is on my side. The ALB throwing that 502. Thank you
