### ISSUE TITLE
Windows process AfterFX.exe is not killed when no logging is reported for 60 seconds.

### ISSUE THREAD

**Issue by Tillaert** [inlife/nexrender#982]
**Describe the bug**
Windows process AfterFX.exe is not killed when no logging is reported for 60 seconds. Node process exits.

**Information about environment**
Windows Server 2019. 
Remaining process: 
```

Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
AfterFX.com                   2560 Services                   1  4,764,060 K

```

**Expected behavior**
The AfterFX.exe is killed.

**Additional info**

**Comment by Tillaert** [comment]
I have no idea. The way we run is, that we have one runner per environment, but that environment doesn't finish, because a process is still running. 

I can kill the environment, after a timeout, however, NexRender's logging timeout cannot be disabled (I now set it to Number.MAX_SAFE_INTEGER). If that timeout kicks in, it returns a value (through an exception) which stops the external time-out mechanism.

Due to the nature of AfterEffects, this problem might not be solvable. It would help if the `maxUpdateTimeout` can be set to zero, disabling the timer (similar to `maxRenderTimeout` )

**Comment by inlife** [comment]
Thanks for the info. I'll think of possible solutions.

I wonder, what is the way you separate the environments? This approach sounds very interesting.

**Comment by Tillaert** [comment]
I run aftereffects in a VM, using nexrender to configure the job, and when all the processes are done, the VM is destroyed. The dangling process causes the VM not to finish. I could investigate killing the VM from the host, once NexRender has finished.

**Comment by igalness** [comment]
Maybe on Windows we can use something like https://github.com/inlife/nexrender/pull/996
To kill aerender and all related to aerender child process (like AfterFX.com )

**Comment by igalness** [comment]
After running some tests on _**Windows 11 + Node 20 LTS + AE 2023**_ , it looks like  `instance.kill('SIGINT')` only terminates the `aerender.exe` process and leaves `AfterFX.exe` process spawned by it, still running

**Comment by mario1in** [comment]
@Tillaert Using VM sounds like an interesting solution, especially for more reliable concurrent processing. Could you please provide a detailed of your solution? Very appreciate!!
