### ISSUE TITLE
aerender error an existing connection was forced closed by the remote host. : unable to receive at line 502

### ISSUE THREAD

**Issue by 477174** [inlife/nexrender#983]
When I try to render with the -reuse option set to true and with an open instance of After Effects, the render completes successfully, but when I try to render in the background with aerender.exe, I get:

Running Script: C:\my\absolute\path\nexrender-T7hx2ykRnouJJzsphfb-3-script.jsx                                                                                    [0] aerender ERROR An existing connection was forced closed by the remote host. : Unable to receive at line 500.

I tried disabling the firewall and nothing changed, I also tested running my script manually in After Effects and it worked normally.

**Comment by inlife** [comment]
Hey @477174 

Did you figure out the problem?

**Comment by 477174** [comment]
@inlife 

Yes, the problem was in these two lines of my script:

`var presetFile = new File('C:\\Users\\Windows 10\\Documents\\bot-video\\after\\presets\\Imagem Ajust Comp.ffx');
 newLayer.applyPreset(presetFile);` 
 
 When running render with an open instance of After Effects with "-reuse" as true, the preset was being imported without any problems and the rendering ran fine until the end, but when I was trying to render in the background this import apparently blocked the effects later.
 
But when I was trying to render in the background, importing this preset was apparently crashing aerender.exe.

**Comment by inlife** [comment]
Oh I see, very interesting. Thanks for sharing!
