### ISSUE TITLE
How to just change image path only in comp layer of After effects?

### ISSUE THREAD

**Issue by naitik30** [inlife/nexrender#986]
I am quite new in After effects. I want to replace image which used multiple layers of after effect. but when I use following json to replace the image in after effect, it replace the image but it remove the effect which mention on layer. How to just replace the image not remove effect.
`{
          src: "file:///Users/napatel/Documents/dev/temp/Social5/Images/img-2-600x400.jpg",
          type: "image",
          layerName: "image-1_1",
          composition: "image-1_1",
        },
        {
          src: "file:///Users/napatel/Documents/dev/temp/Social5/Images/img-2-600x400.jpg",
          type: "image",
          layerName: "image-1_2",
          composition: "image-1_2",
        },`

**Comment by JamesBotterill** [comment]
Try pre-comping the image and then add the effects to the pre-comp.

Also I'd have a separate name for the composition from asset
