### ISSUE TITLE
Rendering Failure with aerender.exe on Windows Server on Google Comptue engine

### ISSUE THREAD

**Issue by kostia3507** [inlife/nexrender#987]
**Describe the bug**
While using nexrender on a Windows Server, the rendering process starts successfully but fails with an error from `aerender.exe` stating it failed to render the output due to an unknown reason. This issue occurs after following the regular rendering steps and is accompanied by a deprecation warning regarding the default log path.

**To Reproduce**
1. Execute the nexrender command via CLI:
   ```bash
   python execute_render_comand.py
   ```
2. Observe the STDOUT messages indicating the steps being processed.
3. Encounter an error at the rendering step.

**Expected behavior**
The job should render successfully without errors and produce the expected output file.

**Information about environment**
- Nexrender version: latest
- Setup type: CLI
- Installation method: Using pre-built binaries
- Operating system: Windows Server (on Google Compute Engine)
- Adobe After Effects version: 2020

**Additional context**
The error occurs during the rendering stage, and the logs indicate a failure in `aerender.exe` to render the output. There's also a deprecation notice about changing the default log path for `aerender` in future releases.

**Logs**
The error message received is:
```
> job rendering failed
Error: aerender.exe failed to render the output into the file due to an unknown reason
    at ChildProcess.<anonymous> (C:\snapshot\nexrender\packages\nexrender-core\src\tasks\render.js)
    at ChildProcess.emit (node:events:537:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:537:28)
    at Pipe.<anonymous> (node:net:747:14)
```

![image](https://github.com/inlife/nexrender/assets/166399202/0ebfe7e0-42f9-4d8b-8897-b9136c64d0ba)
![image](https://github.com/inlife/nexrender/assets/166399202/6c018e03-9cb6-4050-98c1-294e5e4654d3)

here is JSON file:
![image](https://github.com/inlife/nexrender/assets/166399202/84619c5f-efe3-4a83-9bb5-23ebcd8da95b)

**Comment by kostia3507** [comment]
update: I downloaded Node.js and I'm getting this error now
![image](https://github.com/inlife/nexrender/assets/166399202/93426520-8f04-4f8f-9a8f-4cb135b2da6f)

**Comment by inlife** [comment]
Hey @kostia3507 

Could you also provide logs coming from the aerender? They should be in the workpath near the temporary project folders.

**Comment by kostia3507** [comment]
Problem is fixed, If anybody would have simillar problem, you should install C++ from 2008 to 2015
