### ISSUE TITLE
RemoveJob is not working

### ISSUE THREAD

**Issue by andyglez96** [inlife/nexrender#988]
**Describe the bug**
When trying to remove a job which is currently rendering I got an error (see the attachment)

**Information about environment**
* Binaries v1.50.6
* Server + worker
* Windows 11

**Screenshots**
![image](https://github.com/inlife/nexrender/assets/88163491/2bb1db46-da0d-4839-9d0b-f6400e71584f)
![image](https://github.com/inlife/nexrender/assets/88163491/a2fae35e-a4d6-4728-bb2b-96958fb5da06)

**Comment by andyglez96** [comment]
@inlife is this a known problem?

**Comment by inlife** [comment]
Seems like it's related to the fact that the worker attempts to update the job even though it was removed already.

**Comment by andyglez96** [comment]
exactly

**Comment by andyglez96** [comment]
got it, in the meantime, I will find some workaround. Looking forward to this functionality. Thanks @inlife!!!
