### ISSUE TITLE
Can we submit job to deadline using nexrender?

### ISSUE THREAD

**Issue by naitik30** [inlife/nexrender#990]
I'm fairly new to the renderer and Nexrender environments. I can locally render a brief video. Additionally, I can set up network rendering locally with Nexrender. We want to render thousands of 30-second videos per day, however once all the videos are finished, we don't want to continue running workers. Is it feasible to set up a system similar to this one, where the server may start workers as needed? After further investigation, it appears that AWS Thinkbox Deadline uses cloud rendering via spot instances, allowing workers to start as needed. Can we use Nexrender to submit the job by the deadline to Thinkbox?

**Comment by JamesBotterill** [comment]
I'm sure it would be possible but you would need to fork and extend the server to trigger the creation and provisioning of a server on a new job created.

There's nothing out the box to do this presently but sounds like a cool project

**Comment by inlife** [comment]
Yeah, this functionality does not exist, but looks interesting. I think we are all are very open to any such contribution!! 🎉
