### ISSUE TITLE
too slow rendering since update After Effect to 24

### ISSUE THREAD

**Issue by dailyled** [inlife/nexrender#992]
Hello to all the community
We have a problem with too slow rendering since we update after effects from version 22 to 24 (on MACOS & ae_render_only_node without interface). Renderings can take up to 1500 seconds whereas before it took 30 seconds on version 22.
Then we noticed that the output module returned us an .mp4 file by default whereas before it was a .mov. Has anyone had the same problem as me and if so have you found a solution to revert to the QuickTime .mov format by default?
I saw in the documentation that you can modify output Module directly in the json (in template option) but I can't put it like in version 22 where my generation was still very fast..
Please help me..
Thanks !

**Comment by dailyled** [comment]
I just discovered the reason for this slowdown. this came from a thickening of the "fontbold" font, once removed the generation becomes as fast as before.
That's it, if this helps anyone.
Bye!

**Comment by inlife** [comment]
That feels like the most AE thing that could've happened :)

**Comment by dailyled** [comment]
Yes ;) and it took me a few weeks to find..:(

**Comment by inlife** [comment]
I can only say, I understand your pain! And I'm still amazed by the fact that you were able to even find this :)

**Comment by dailyled** [comment]
Thank you very much, I hope I was able to help the community as much as they were able to help me !
