### ISSUE TITLE
mac 14.5 permission errors

### ISSUE THREAD

**Issue by sundayALLDAYa** [inlife/nexrender#997]
having a problem in mac sonoma 14.5

```
bob@dan-MacBook-Air automation % sudo ./render_jobs.sh
Password:
> starting nexrender-cli
using automatically determined directory of After Effects installation:
 - /Applications/Adobe After Effects 2024/aerender
checking After Effects command line renderer patch...
command line patch already is in place
[sNONt7zpy6owdqI_S-K3H] setting up job...
[sNONt7zpy6owdqI_S-K3H] working directory is: /tmp/nexrender/sNONt7zpy6owdqI_S-K3H
[sNONt7zpy6owdqI_S-K3H] applying predownload actions...
[sNONt7zpy6owdqI_S-K3H] downloading assets...
[sNONt7zpy6owdqI_S-K3H] applying postdownload actions...
[sNONt7zpy6owdqI_S-K3H] applying prerender actions...
[sNONt7zpy6owdqI_S-K3H] running script assemble...
[sNONt7zpy6owdqI_S-K3H] rendering job...
[sNONt7zpy6owdqI_S-K3H] -- D E P R E C A T I O N: --

nexrender is changing the default aerender log path to the project folder.
This is done to streamline the log management and enable efficient log cleanup.

If you want to keep the old behavior and mute this message, please set the environment variable NEXRENDER_ENABLE_AELOG_LEGACY_TEMP_FOLDER to true.
If you want to switch to the new behavior, please set the environment variable NEXRENDER_ENABLE_AELOG_PROJECT_FOLDER to true.

Right now, the old behavior is still the default, but this will change in the next minor releases.
Estimated date of change to the new behavior: 2023-06-01.

[sNONt7zpy6owdqI_S-K3H] rendering reached an error: After Effects error: Error in output for render queue item 1, output module 1. Can not create a file in directory /tmp/nexrender/sNONt7zpy6owdqI_S-K3H. Try checking write permissions.

[sNONt7zpy6owdqI_S-K3H] rendering took ~13.116 sec.
[sNONt7zpy6owdqI_S-K3H] writing aerender job log to: /tmp/nexrender/aerender-sNONt7zpy6owdqI_S-K3H.log
[sNONt7zpy6owdqI_S-K3H] dumping aerender log:
WARNING:After Effects warning: Project has missing fonts.

WARNING:After Effects warning: File “this-or-that.aep” is locked. You can’t save any changes to this file.
Running Script: /tmp/nexrender/sNONt7zpy6owdqI_S-K3H/nexrender-sNONt7zpy6owdqI_S-K3H-script.jsx
PROGRESS: Adding specified comp to Render Queue
aerender Error: After Effects error: Error in output for render queue item 1, output module 1. Can not create a file in directory /tmp/nexrender/sNONt7zpy6owdqI_S-K3H. Try checking write permissions.
aerender version 24.4.1x2
PROGRESS: Launching After Effects...

catching the error internally
[sNONt7zpy6owdqI_S-K3H] cleaning up...
> job rendering failed
Error: Couldn't find a result file: /tmp/nexrender/sNONt7zpy6owdqI_S-K3H/result.mov
    at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/@nexrender/cli/node_modules/@nexrender/core/src/tasks/render.js:318:31)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:337:12)
```

i installed through node.js

here is the log:
```
WARNING:After Effects warning: Project has missing fonts.

WARNING:After Effects warning: File “this-or-that.aep” is locked. You can’t save any changes to this file.
Running Script: /tmp/nexrender/sNONt7zpy6owdqI_S-K3H/nexrender-sNONt7zpy6owdqI_S-K3H-script.jsx
PROGRESS: Adding specified comp to Render Queue
aerender Error: After Effects error: Error in output for render queue item 1, output module 1. Can not create a file in directory /tmp/nexrender/sNONt7zpy6owdqI_S-K3H. Try checking write permissions.
aerender version 24.4.1x2
PROGRESS: Launching After Effects...
```

that's it

i tried sudo chmod 777 for the temp folder and ae file

**Comment by abdulghanitech** [comment]
> having a problem in mac sonoma 14.5
> 
> ```
> bob@dan-MacBook-Air automation % sudo ./render_jobs.sh
> Password:
> > starting nexrender-cli
> using automatically determined directory of After Effects installation:
>  - /Applications/Adobe After Effects 2024/aerender
> checking After Effects command line renderer patch...
> command line patch already is in place
> [sNONt7zpy6owdqI_S-K3H] setting up job...
> [sNONt7zpy6owdqI_S-K3H] working directory is: /tmp/nexrender/sNONt7zpy6owdqI_S-K3H
> [sNONt7zpy6owdqI_S-K3H] applying predownload actions...
> [sNONt7zpy6owdqI_S-K3H] downloading assets...
> [sNONt7zpy6owdqI_S-K3H] applying postdownload actions...
> [sNONt7zpy6owdqI_S-K3H] applying prerender actions...
> [sNONt7zpy6owdqI_S-K3H] running script assemble...
> [sNONt7zpy6owdqI_S-K3H] rendering job...
> [sNONt7zpy6owdqI_S-K3H] -- D E P R E C A T I O N: --
> 
> nexrender is changing the default aerender log path to the project folder.
> This is done to streamline the log management and enable efficient log cleanup.
> 
> If you want to keep the old behavior and mute this message, please set the environment variable NEXRENDER_ENABLE_AELOG_LEGACY_TEMP_FOLDER to true.
> If you want to switch to the new behavior, please set the environment variable NEXRENDER_ENABLE_AELOG_PROJECT_FOLDER to true.
> 
> Right now, the old behavior is still the default, but this will change in the next minor releases.
> Estimated date of change to the new behavior: 2023-06-01.
> 
> [sNONt7zpy6owdqI_S-K3H] rendering reached an error: After Effects error: Error in output for render queue item 1, output module 1. Can not create a file in directory /tmp/nexrender/sNONt7zpy6owdqI_S-K3H. Try checking write permissions.
> 
> [sNONt7zpy6owdqI_S-K3H] rendering took ~13.116 sec.
> [sNONt7zpy6owdqI_S-K3H] writing aerender job log to: /tmp/nexrender/aerender-sNONt7zpy6owdqI_S-K3H.log
> [sNONt7zpy6owdqI_S-K3H] dumping aerender log:
> WARNING:After Effects warning: Project has missing fonts.
> 
> WARNING:After Effects warning: File “this-or-that.aep” is locked. You can’t save any changes to this file.
> Running Script: /tmp/nexrender/sNONt7zpy6owdqI_S-K3H/nexrender-sNONt7zpy6owdqI_S-K3H-script.jsx
> PROGRESS: Adding specified comp to Render Queue
> aerender Error: After Effects error: Error in output for render queue item 1, output module 1. Can not create a file in directory /tmp/nexrender/sNONt7zpy6owdqI_S-K3H. Try checking write permissions.
> aerender version 24.4.1x2
> PROGRESS: Launching After Effects...
> 
> catching the error internally
> [sNONt7zpy6owdqI_S-K3H] cleaning up...
> > job rendering failed
> Error: Couldn't find a result file: /tmp/nexrender/sNONt7zpy6owdqI_S-K3H/result.mov
>     at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/@nexrender/cli/node_modules/@nexrender/core/src/tasks/render.js:318:31)
>     at ChildProcess.emit (node:events:519:28)
>     at maybeClose (node:internal/child_process:1105:16)
>     at Socket.<anonymous> (node:internal/child_process:457:11)
>     at Socket.emit (node:events:519:28)
>     at Pipe.<anonymous> (node:net:337:12)
> ```
> 
> i installed through node.js
> 
> here is the log:
> 
> ```
> WARNING:After Effects warning: Project has missing fonts.
> 
> WARNING:After Effects warning: File “this-or-that.aep” is locked. You can’t save any changes to this file.
> Running Script: /tmp/nexrender/sNONt7zpy6owdqI_S-K3H/nexrender-sNONt7zpy6owdqI_S-K3H-script.jsx
> PROGRESS: Adding specified comp to Render Queue
> aerender Error: After Effects error: Error in output for render queue item 1, output module 1. Can not create a file in directory /tmp/nexrender/sNONt7zpy6owdqI_S-K3H. Try checking write permissions.
> aerender version 24.4.1x2
> PROGRESS: Launching After Effects...
> ```
> 
> that's it
> 
> i tried sudo chmod 777 for the temp folder and ae file

Did you found any work around for this issue?

**Comment by inlife** [comment]
The best strategy is not to run nexrender with sudo for day-to-day use. It seems like that is related to the permission issue.
