### ISSUE TITLE
Composition is not found when converting AE project

### ISSUE THREAD

**Issue by danielshorten** [inlife/nexrender#999]
**Describe the bug**
When using an old project file with a new version of After Effects, nexrender fails to resolve the composition.

**Information about environment**
* nexrender version: 1.49.3
* Setup: server + worker
* Pre-built binaries
* Windows Server 2019

**Expected behavior**
Normally my script runs fine and locates the `cent` layer in my `_CENT_VT_6s` composition.

**Additional information**
If I open and resave the After Effects project in the new version of After Effects, I don't have any errors.

After Effects log messages with old project file:
```
aerender version 24.2.1x2
--
PROGRESS: Launching After Effects...
INFO:After Effects: this project must be converted from version 23.1 (Macintosh 64). The original file will be unchanged.
Running Script: \nexrender\UOmtDHI7NLDp9Fb9ib0mQ\nexrender-UOmtDHI7NLDp9Fb9ib0mQ-script.jsx
aerender ERROR: Error executing script: \nexrender\UOmtDHI7NLDp9Fb9ib0mQ\nexrender-UOmtDHI7NLDp9Fb9ib0mQ-script.jsx
Error: nexrender: Couldn't find any layers by provided name (cent) inside a composition: *
aerender ERROR: Runtime error in After Effects.
catching the error internally
```
Relevant portion of the nexrender job: 
```
{
    "template": {
        "src": "s3://retriever-qa.s3.amazonaws.com/media/themes/video/temp_themes/204/theme.aep",
        "composition": "_CENT_VT_6s"
    },
    "assets": [
        {
            "type": "data",
            "value": "99",
            "property": "Source Text",
            "layerName": "cent",
        }
   ]
}
```

**Comment by inlife** [comment]
Could you try opening that project in the AE that nexrnender uses, manually running that Script that is generated in the folder and then making a screenshot of layers of that composition with `cent` being visible on the screen

**Comment by danielshorten** [comment]
Thanks for your response, and for suggesting a closer look at what's happening on our renderer.  It turned out the error was on our side, and the incorrect AE template file was getting downloaded for the render job.

🙏
